---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: &x-project applications
  namespace: argocd
  labels:
    fr.karlsen: *x-project
spec:
  sources:
    - {repoURL: https://github.com/sebastka/homelab.git, path: k8s/applications, targetRevision: HEAD}
  destination: {name: in-cluster, namespace: argocd}
  project: app-of-apps
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
      enabled: true
