---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure
  namespace: argocd
  labels:
    fr.karlsen: infrastructure
spec:
  sources:
    - {repoURL: https://github.com/sebastka/homelab.git, path: k8s/infrastructure, targetRevision: HEAD}
  destination: {name: in-cluster, namespace: argocd}
  project: app-of-apps
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
      enabled: true
