---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: &x-project infrastructure
  namespace: argocd
  labels:
    karlsen.fr/project: *x-project
spec:
  sources:
    - {repoURL: https://github.com/sebastka/homelab.git, path: k8s/infrastructure, targetRevision: HEAD}
  destination: {namespace: argocd, name: in-cluster}
  project: app-of-apps
  syncPolicy:
    automated: {allowEmpty: false, enabled: true, prune: true, selfHeal: true}
    # managedNamespaceMetadata:
    retry: {backoff: {duration: 5s, factor: 2, maxDuration: 3m}, limit: 5, refresh: true}
    syncOptions: [ServerSideApply=true]
