# yaml-language-server: $schema=
# https://artifacthub.io/packages/helm/intel/intel-device-plugins-gpu?modal=values
---

name: igpu
sharedDevNum: 1  # Number of containers that can share the same GPU device
