# yaml-language-server: $schema=
# https://artifacthub.io/packages/helm/bitnami-labs/sealed-secrets?modal=values
---
namespace: sealed-secrets
keyrenewperiod: 8766h  # ~ 1 year

resources:
  requests: {memory: 32Mi}
  limits: {memory: 64Mi}

containerSecurityContext:
  allowPrivilegeEscalation: false
  seccompProfile: {type: RuntimeDefault}
