---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: valkey
  namespace: envoy-gateway-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: valkey
  namespace: envoy-gateway-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: valkey
  template:
    metadata:
      namespace: envoy-gateway-system
      labels:
        app.kubernetes.io/name: valkey
    spec:
      serviceAccount: valkey
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: {type: RuntimeDefault}
      containers:
        - name: valkey
          # Dockerfile: https://github.com/valkey-io/valkey-container/blob/mainline/9.0/alpine/Dockerfile
          image: index.docker.io/valkey/valkey:9.0.3-alpine3.23
          args: [--save, ""]
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: {drop: [ALL]}
          resources:
            requests: {memory: 64Mi}
            limits: {memory: 64Mi}
          # env:
          #   - {name: VALKEY_EXTRA_FLAGS, value: '--save 60 1 --loglevel warning'}
---
apiVersion: v1
kind: Service
metadata:
  name: valkey
  namespace: envoy-gateway-system
  labels:
    app.kubernetes.io/name: valkey
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: valkey
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379
