---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-rmwebhooks-egress
  namespace: kyverno
spec:
  endpointSelector: {matchLabels: {job-name: kyverno-rm-webhooks}}
  egress:
    - {toEntities: [kube-apiserver]}
