---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-cleanup-ingress
  namespace: kyverno
spec:
  endpointSelector: {matchLabels: {app.kubernetes.io/name: kyverno-cleanup-controller}}
  ingress:
    - {fromEntities: [host], toPorts: [ports: [{port: '9443', protocol: TCP}]]}  # Host probes
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-cleanup-egress
  namespace: kyverno
spec:
  endpointSelector: {matchLabels: {app.kubernetes.io/name: kyverno-cleanup-controller}}
  egress:
    - {toEntities: [kube-apiserver]}
