---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-intra-namespace
  namespace: kyverno
spec:
  endpointSelector: {}
  ingress: 
    - {fromEndpoints: [matchLabels: {k8s:io.kubernetes.pod.namespace: kyverno}]}     
  egress:
    - {toEndpoints: [matchLabels: {k8s:io.kubernetes.pod.namespace: kyverno}]}
