---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-scaletozero-egress
  namespace: kyverno
spec:
  endpointSelector: {matchLabels: {job-name: kyverno-scale-to-zero}}
  egress:
    - {toEntities: [kube-apiserver]}
