---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-privilege-escalation
spec:
  background: true
  rules:
    - name: deny-privileged-and-escalation
      match: {any: [resources: {kinds: [Pod]}]}
      exclude: {any: [resources: {namespaceSelector: {matchExpressions: [{key: kubernetes.io/metadata.name, operator: In, values: [kube-system, kube-node-lease, kube-public, kyverno, envoy-gateway-system, cilium-spire, cilium-secrets]}]}}]}
      validate:
        failureAction: Audit
        message: "Container '{{ element.name }}' must not run as privileged or allow privilege escalation."
        foreach:
          - list: "request.object.spec.[containers, initContainers][]"
            deny:
              conditions:
                any:
                  - {key: "{{ element.securityContext.privileged }}", operator: Equals, value: true}
                  - {key: "{{ element.securityContext.allowPrivilegeEscalation }}", operator: Equals, value: true}
