---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: verify-image-signatures-custom
spec:
  background: false
  rules:
    - name: verify-sebastka-images
      match: {any: [resources: {kinds: [Pod]}]}
      verifyImages:
        - imageReferences: ['ghcr.io/sebastka/*']
          failureAction: Audit  # Enforce
          mutateDigest: false
          verifyDigest: false
          attestors:
            - count: 1
              entries:
                - keyless:
                    subject: 'https://github.com/sebastka/containers/.github/workflows/*'
                    issuer: https://token.actions.githubusercontent.com
                    rekor: {url: https://rekor.sigstore.dev}
