---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-probes
  annotations:
    policies.kyverno.io/title: Require Liveness and Readiness Probes
    policies.kyverno.io/description: Require all containers in Deployments, StatefulSets, and DaemonSets to define liveness and readiness probes so Kubernetes can properly manage container lifecycle.
spec:
  background: true
  rules:
    - name: require-liveness-readiness-probes
      match: {any: [resources: {kinds: [Deployment, StatefulSet, DaemonSet]}]}
      exclude: {any: [resources: {namespaceSelector: {matchExpressions: [{key: kubernetes.io/metadata.name, operator: In, values: [kube-system, kube-node-lease, kube-public, falco]}]}}]}
      validate:
        failureAction: Audit
        message: "All containers must define liveness and readiness probes."
        foreach:
          - list: request.object.spec.template.spec.containers
            preconditions:
              all:
                - {key: "{{ element.name }}", operator: NotEquals, value: headlamp-plugin}
            pattern:
              livenessProbe: {periodSeconds: '>0'}
              readinessProbe: {periodSeconds: '>0'}
