---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kyverno

# Wave 0: CRDs + Operator
# Wave 1: CiliumNetworkPolicies
# Wave 2: ClusterPolicies
patches:
  - target: {kind: CiliumNetworkPolicy}
    patch: |
      - {op: add, path: /metadata/annotations, value: {argocd.argoproj.io/sync-wave: '1'}}
  - target: {kind: ClusterPolicy}
    patch: |
      - {op: add, path: /metadata/annotations, value: {argocd.argoproj.io/sync-wave: '2'}}

resources:
  - Namespace.yaml
  - ClusterPolicy.spread-pods.yaml
  - ClusterPolicy.require-securitycontext.yaml
  - ClusterPolicy.disallow-latest-tag.yaml
  - ClusterPolicy.require-requests-limits.yaml
  - ClusterPolicy.require-labels.yaml
  - ClusterPolicy.require-probes.yaml
  - ClusterPolicy.restrict-image-registries.yaml
  - ClusterPolicy.verify-image-signatures-custom.yaml
  - ClusterPolicy.verify-image-signatures-third-party.yaml
  - CiliumNetworkPolicy.namespace.yaml
  - CiliumNetworkPolicy.migrate-resources.yaml
  - CiliumNetworkPolicy.rm-webhooks.yaml
  - CiliumNetworkPolicy.scale-to-zero.yaml
  - CiliumNetworkPolicy.admission.yaml
  - CiliumNetworkPolicy.background.yaml
  - CiliumNetworkPolicy.cleanup.yaml
  - CiliumNetworkPolicy.reports.yaml

helmCharts:
  - name: kyverno
    repo: https://kyverno.github.io/kyverno/
    version: 3.8.1  # renovate: datasource=github-releases depName=kyverno/kyverno
    releaseName: kyverno
    namespace: kyverno
    includeCRDs: true
    valuesFile: values.yaml
