---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kyverno

# Wave 0: CRDs + Operator
# Wave 1: CiliumNetworkPolicies
# Wave 2: ClusterPolicies
patches:
  - target: {kind: CiliumNetworkPolicy}
    patch: |
      - {op: add, path: /metadata/annotations, value: {argocd.argoproj.io/sync-wave: '1'}}
  - target: {kind: ClusterPolicy}
    patch: |
      - {op: add, path: /metadata/annotations, value: {argocd.argoproj.io/sync-wave: '2'}}

images:
  - {name: ghcr.io/kyverno/readiness-checker, newTag: latest, digest: sha256:f6b71ec78ce69172ae9b0161f72c978909355e94bed8e260cdc4de282a5ec41b}

resources:
  - Namespace.yaml
  - ClusterPolicy.spread-pods.yaml
  - ClusterPolicy.trivy-node-collector-fix-proxy-bins.yaml
  - ClusterPolicy.require-securitycontext.yaml
  - ClusterPolicy.disallow-latest-tag.yaml
  - ClusterPolicy.require-requests-limits.yaml
  - ClusterPolicy.require-labels.yaml
  - ClusterPolicy.require-probes.yaml
  - ClusterPolicy.restrict-image-registries.yaml
  - ClusterPolicy.verify-image-signatures.yaml
  - CiliumNetworkPolicy.namespace.yaml
  - CiliumNetworkPolicy.migrate-resources.yaml
  - CiliumNetworkPolicy.rm-webhooks.yaml
  - CiliumNetworkPolicy.scale-to-zero.yaml
  - CiliumNetworkPolicy.admission.yaml
  - CiliumNetworkPolicy.background.yaml
  - CiliumNetworkPolicy.cleanup.yaml
  - CiliumNetworkPolicy.reports.yaml

helmCharts:
  - name: kyverno
    repo: oci://ghcr.io/kyverno/charts
    version: 3.8.1  # renovate: datasource=helm registryUrl=oci://ghcr.io/kyverno/charts depName=kyverno
    releaseName: kyverno
    namespace: kyverno
    includeCRDs: true
    valuesFile: values.yaml
