---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slink-app-pvc
  namespace: slink
spec:
  accessModes: [ReadWriteOncePod]
  resources: {requests: {storage: 1Gi}}
  storageClassName: longhorn-static
  volumeName: slink-app-pv
