---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slink-app-pvc
  namespace: slink
  labels:
    app.kubernetes.io/name: slink
    recurring-job.longhorn.io/source: enabled
    recurring-job-group.longhorn.io/group1: enabled
spec:
  accessModes: [ReadWriteOncePod]
  resources: {requests: {storage: 1Gi}}
  storageClassName: longhorn-encrypted
  volumeName: slink-app-pv
