---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-intra-namespace
  namespace: longhorn-system
spec:
  endpointSelector: {}
  ingress:
    - {fromEndpoints: [{matchLabels: {k8s:io.kubernetes.pod.namespace: longhorn-system}}]}
  egress:
    - {toEndpoints: [{matchLabels: {k8s:io.kubernetes.pod.namespace: longhorn-system}}]}
    - {toEntities: [kube-apiserver]}
    - {toFQDNs: [{matchName: file01.hera.home.karlsen.fr}], toPorts: [ports: [{port: '2049', protocol: TCP}]]}  # NFS backup/restore target (file01)
    - {toCIDR: [192.168.1.20/32], toPorts: [ports: [{port: '2049', protocol: TCP}]]}  # NFS backup/restore target (file01)
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-longhorn-manager
  namespace: longhorn-system
spec:
  endpointSelector: {matchLabels: {app: longhorn-manager}}
  ingress:
    - {fromEntities: [host], toPorts: [ports: [{port: '9502', protocol: TCP}]]}  # Readiness probe
    - {fromEntities: [kube-apiserver], toPorts: [ports: [{port: '9502', protocol: TCP}, {port: '9503', protocol: TCP}]]}  # Admission webhook, recovery backend
  # egress: []
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-longhorn-ui
  namespace: longhorn-system
spec:
  endpointSelector: {matchLabels: {app: longhorn-ui}}
  ingress:
    - {fromEndpoints: [{matchLabels: {k8s:io.kubernetes.pod.namespace: envoy-gateway-system}}], toPorts: [ports: [{port: '8000', protocol: TCP}]]}
  # egress: []
