# yaml-language-server: $schema=
# https://github.com/longhorn/charts/blob/v1.11.x/charts/longhorn/values.yaml
# https://github.com/longhorn/longhorn/tree/master/chart
# https://joshrnoll.com/installing-longhorn-on-talos-with-helm/
# https://www.johanneskueber.com/posts/longhorn_uservolumes_talos/
---

defaultSettings:
  defaultReplicaCount: 2
  defaultDataLocality: best-effort
  defaultDataPath: /var/mnt/longhorn-data
  allowCollectingLonghornUsageMetrics: false
  upgradeChecker: false
  replicaAutoBalance: best-effort
  systemManagedCSIComponentsResourceLimits: '{"csi-attacher":{"requests":{"memory":"128Mi"},"limits":{"memory":"512Mi"}},"csi-provisioner":{"requests":{"memory":"64Mi"},"limits":{"memory":"512Mi"}},"csi-resizer":{"requests":{"memory":"128Mi"},"limits":{"memory":"512Mi"}},"csi-snapshotter":{"requests":{"memory":"64Mi"},"limits":{"memory":"512Mi"}},"longhorn-csi-plugin":{"requests":{"memory":"512Mi"},"limits":{"memory":"4096Mi"}},"node-driver-registrar":{"requests":{"memory":"64Mi"},"limits":{"memory":"128Mi"}},"longhorn-liveness-probe":{"requests":{"memory":"64Mi"},"limits":{"memory":"128Mi"}}}'
  freezeFilesystemForSnapshot: true
  snapshotDataIntegrity: enabled
  # snapshotDataIntegrityCronjob: '0 0 */7 * *'  # Default
  snapshotDataIntegrityCronjob: '0 0 * * 0'  # Sunday 00:00 UTC / 02:00 CEST
  snapshotDataIntegrityImmediateCheckAfterSnapshotCreation: false
  backupCompressionMethod: gzip
  allowRecurringJobWhileVolumeDetached: true
  recurringSuccessfulJobsHistoryLimit: 3
  recurringFailedJobsHistoryLimit: 3

defaultBackupStore:
  backupTarget: nfs://file01.hera.home.karlsen.fr:/mnt/nfs/homelab/longhorn-backup?nfsOptions=soft,timeo=330,retrans=3
  pollInterval: 300

longhornManager:
  resources:
    requests: {memory: 2048Mi}
    limits: {memory: 4096Mi}
  updateStrategy:
    rollingUpdate:
      maxUnavailable: '35%'  # 1/3 node: serial upgrade of longhorn-manager pods

persistence:
  reclaimPolicy: Retain
  defaultClassReplicaCount: 2
  defaultDataLocality: best-effort

# # https://github.com/longhorn/longhorn/issues/8707
# preUpgradeChecker:
#   jobEnabled: false
#   # upgradeVersionCheck: false
