---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-intra-namespace
  namespace: falco
spec:
  endpointSelector: {}
  ingress:
    - {fromEndpoints: [matchLabels: {k8s:io.kubernetes.pod.namespace: falco}]}
  egress:
    - {toEndpoints: [matchLabels: {k8s:io.kubernetes.pod.namespace: falco}]}
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-falco
  namespace: falco
spec:
  endpointSelector: {matchLabels: {app.kubernetes.io/name: falco}}
  ingress:
    - {fromEntities: [host], toPorts: [ports: [{port: '8081', protocol: TCP}]]}  # Host probes
  egress:
    - {toEntities: [kube-apiserver]}
    - {toEntities: [world], toPorts: [ports: [{port: '443', protocol: TCP}]]}  # falcoctl rule updates
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-falcosidekick
  namespace: falco
spec:
  endpointSelector: {matchLabels: {app.kubernetes.io/name: falcosidekick}}
  ingress:
    - {fromEntities: [host], toPorts: [ports: [{port: '2801', protocol: TCP}]]}  # Host probes
  egress:
    - {toEndpoints: [{matchLabels: {k8s:io.kubernetes.pod.namespace: victoria-logs, app.kubernetes.io/name: victoria-logs-single}}], toPorts: [ports: [{port: '9428', protocol: TCP}]]}  # Loki-compatible log push
    - {toEndpoints: [{matchLabels: {k8s:io.kubernetes.pod.namespace: ntfy, app.kubernetes.io/name: ntfy}}], toPorts: [ports: [{port: '8080', protocol: TCP}]]}  # Webhook output
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-falcosidekickui
  namespace: falco
spec:
  endpointSelector: {matchLabels: {app.kubernetes.io/name: falcosidekick, app.kubernetes.io/component: ui}}
  ingress:
    - {fromEntities: [host], toPorts: [ports: [{port: '2802', protocol: TCP}]]}  # Host probes
    - {fromEndpoints: [matchLabels: {k8s:io.kubernetes.pod.namespace: envoy-gateway-system}], toPorts: [ports: [{port: '2802', protocol: TCP}]]}  # Envoy Gateway
  # egress: []
