---

extends: default

ignore: |
  **/charts
  Secret.*.yaml
  *.enc.yaml
  values.default.yaml
  values.*.default.yaml
  k8s/infrastructure/auth/authelia/assets/configuration.yaml

rules:
  line-length: disable
  comments-indentation: disable
