---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-zabbix-frontend-ingress
  namespace: zabbix
spec:
  endpointSelector: {matchLabels: {app.kubernetes.io/name: frontend}}
  ingress:
    - {fromEntities: [host], toPorts: [ports: [{port: '8080', protocol: TCP}]]}  # Host probes
    - {fromEndpoints: [matchLabels: {k8s:io.kubernetes.pod.namespace: envoy-gateway-system}], toPorts: [ports: [{port: '8080', protocol: TCP}]]}  # Envoy Gateway
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-zabbix-frontend-egress
  namespace: zabbix
spec:
  endpointSelector: {matchLabels: {app.kubernetes.io/name: frontend}}
  egress:
    - {toCIDR: [192.168.2.12/32], toPorts: [ports: [{port: '10051', protocol: TCP}]]}  # Zabbix server API
    - {toFQDNs: [matchName: db02.hera.home.karlsen.fr], toPorts: [ports: [{port: '5432', protocol: TCP}]]}
