---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: zabbix-db-credentials
  namespace: cnpg-database
spec:
  encryptedData:
    password: AgBV6/iHer9JZnMlE1iRCBBNfEUQHtoRKGhr7HZw85vACEIa52EdLWgfZ9ZdTdw5YjsYbm9eTwpX8klJuE38enHnGpEEykT32dNqmKrvSjc+1xV3WOvD/XridxCYolpjJgmaahr7iId00q8EYkr12xJFJFmMuu5u/tPoAKdSEqvmk2bozFqOMHPjeIfc4AzBX+WJE9gsRHUGJ784Opnd1Wjk6WshmsqW6IOr77WvZCu2IRGVAsiM6tzPOm4lp7tV9hfe9ifEcKka36YyE4sR4znv4sWP7xtAxNTB+RtbtxtwFOLE+fz9Ld+QKcuUUAn5bvV27M3A7Q80+a9NO+AGXfleROH+c9tJv10OO+/nWR5PbjTOw0KjGb5KwK+xND3LUbAjMQEfF7LUgl/yL2HmZ+u4UmB21eDB3HmgW1e4DFDXsJ38W5RBHZ0TBE7dJOa6zmoYCJk1jKgW1ew4z3HyMbRtXMDRvR3zieH+bm9p51pnzvWt15eu8QcnhssvCqwTcf79cghj8mFSnJNEb8BjcngOKTjGPcp8Jwor7COF2AOocvG5T99Y8O5nIfiOQGmpzpWdOaTCAs1+hm5NjLDP7ozgqf0dsHOR/dXzhbBaLBcfllRLqFGT5i7FMU6KpeExqG+eUwg7U1bVY44yeGZkF37bOu2JjvtZd1Qn9SlDt9TDDC/kC+mEntzfErDlk4MFcR80DbLkq9pvXAoCvS15mOKWD0V9KxujnB4+UK+l2YT5Eb545sIIKQE/Osz8tcaOL44=
    username: AgARZl8d2GS610kdLRggUcfA9M8nmqcfGp17+9s12wgHwiQZ093JV66Mwj5pNHDePDzkusS06ht1hZAuPhOjaHQ4znFVhT5IiSuCHDVhqNv5a09IKP/aCfAwTTJhdvy2Vkqtr0vFWhw3lHA7Mhx/cCFdX96V1dP8hppMlbJzQUgDJSMR2yWcPLlgVPf/uJLyEtk6WUhGvt2X9phUmjgD2ATPC38j1Qr3ezvdQRUMfyXp+ctn58z6cV5NTrwiUG3qpOpDdDleJLxa7dOdH7kCjOmttEBR3EtcpyFQibvamDATDEqTisZosYhaTddLDS2/KOndOYHHEHRq5/GQ/OsthKd9QrwprTHeB4uCRm6OsR9sY580NXTYdG9qxbcKeMveiqSJgO3mMrzQ0i53MY5KLbz7nc37r028b2aL0VfVwAmAS3PbL/Ss77pNjIxXv1IBbAyp0cFHRoB8GaD/9j0QEKrqRC+mVc/RzhvEwoPzUOOFL1DgpA5yft/ehar6qwp3zmN7nRvsrxfu4yuF91Fl6uiOEGipKTF7R3npALLFfS+h1MSnPp77a8On+/jQC+Jk4V80lDgAvRFwFrKbQbvTNfJJ0oYiFAC4jnJtBzceunxprW8V/OxrkmmQc83umcLUYAowAc9TGYMdFCKLJJtqDNNgwvS9fgHUgCO/AJDe/Ze/iKLRFO24dPsgjh/ONW7PbaBkmboUJgs=
  template:
    metadata:
      annotations:
        kustomize.config.k8s.io/behavior: replace
      name: zabbix-db-credentials
      namespace: cnpg-database
    type: kubernetes.io/basic-auth
