---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
  namespace: zabbix
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  namespace: zabbix
automountServiceAccountToken: false
