---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace: light-ldap

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - {namespace: light-ldap, name: lldap-config, files: [lldap_config.toml=assets/lldap_config.toml]}
  - {namespace: light-ldap, name: lldap-env, envs: [assets/lldap.env]}
  - {namespace: light-ldap, name: bootstrap-env, envs: [assets/bootstrap.env]}
  - namespace: light-ldap
    name: bootstrap-schemas
    files:
      - group-schemas.json=assets/group-schemas.json
      - groups.json=assets/groups.json
      - user-schemas.json=assets/user-schemas.json
      - users.jq=assets/users.jq

resources:
  - Namespace.yaml
  - SealedSecret.lldap-secrets.yaml
  - SealedSecret.lldap-db-credentials.yaml
  - SealedSecret.bootstrap-secrets.yaml
  - Cluster.lldap-db.yaml
  - ServiceAccount.yaml
  - Job.bootstrap.yaml
  - Deployment.yaml
  - Service.yaml
  - HTTPRoute.yaml
  - TCPRoute.yaml
