---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: lldap-db-credentials
  namespace: cnpg-database
spec:
  encryptedData:
    password: AgAggWiU6gAUQD1F4vdZOoMBxg0lVKNpvwzoehxaC6hSl8v/zKjqyuf8b24A4Q7UpO3wqCbFbMEB5Eq7WBsvTGU54OO7SEpqXGaH0oCPumpeXeRAIR93cjoq287kjM+rrTUD7iNF08VTMGuvPC5h9SE5kfjwwF86TOKo65Cc//pILxDDEHVsbmdvEtNJt167cmRCa0XPiTCdu/sAdewW0wruMtaySfuxpQZ/s4dV1MlTR/EWWqdup7yik1eE0uYDLyKtzzLbeUqlT7tF689HV7ypt+oZfzDoAC9c0uSoxhyLgk30W5psxv7f6v7qU5QG0SCHn70kIziesz/dpp2pa+i/yxRt25JAyendM74uMqVNBUGEgLGoEsZReqTF3njuDXMUAEbWEoDdExDQdzhmzn0nifFWT/5CB3KUOjduzFC+dXWR2acpeqL0BPHXazM3zeuQeaaYV/iFJy9AK92LvHMQuYaq9X3sRjDkzY9Gt8rweWZQmV2xzuni7Umn9xYHwpxTrCooUZlRK7TK0OdhKukzlGFmJaWocHqYSXjLUt1T9gv1qtBiwnhQxxHsAgkcKTgZKSZ52R9hpJdmE2eCxaDxt/Ti1sIqUPnwLBlQZ7xvbk1nmf3NZPZFT8OtA+kMiJSIRsR1A9UAwqtzeLxQMeXn1ovnbFWPpuBdBZGDapXrEg5lYZqK6q4q726gS8TWAdLcH7Ekx9pE0BGKzcc8Khckn3SW1hU04cOGgL1km7SrYFhG7gzS70wI3/VvLPRDyzk=
    username: AgCC1VDBUy4cMCduXXYzJ7m/nkwGnoyAXQnRZrZcxGu/CZPJUAz/jqf6/i2VvKkyNz3376c/vddsvVyQLh7hwJlZvOXAp+OMFhtxmq5Ctg5ZCGAk8bsd4K4YyLHso9LQ1ub5tP+Q5C3haVB34nY2XNOypYK+cxfdgq/3w5PLV8/zyca1ukt+GDF0vhmKrfmzqu/zhjVMOHN/GeXxae6WkmrKdsI380/lB0qP2cVEVgEWCuHjt5CSyIKyjmrSPeWO8UNgxggRa3nVo5SmENbXemx+gcJK82Y/dJRZZZVhzJL9uMVirlnxXNqZ46UCrq/Ae/ykYIlx6gbaWlLc+w5zBs7D6mJI5GwAjIeRTYiVa3WIOdy3EYZt4P0/65odAKmA7Tg01Cp9o4C9coO0G4Xgib8L67MHE2k83M9vkwjd7y1JkQ3Tj9cTdm8Wca5z9HAu5WvVnKp19SCohGDTILPUqVBK/mHU+gGroKYc0mDiIqg9n/NAA2uzp/KH4xESfefUM/PpQ8kND4phhi+G8zx/xfxuXqkB3ce/9g8R+WAFCictBXSPwZgr2jNEDc+7O5rCnWOjJRFFQZGVrNhzv4j7hdHBmZGdb8a25q906wuj7OD+BGuz3KBlHS4z7itglv2z68jWVwT/x3v/LhL4QurZgth7ODNToITUSxPA15vCb2t45sZTxPdA9h9jVpqQBkV+/3+DOcCVcA==
  template:
    metadata:
      annotations:
        kustomize.config.k8s.io/behavior: replace
      name: lldap-db-credentials
      namespace: cnpg-database
    type: kubernetes.io/basic-auth
