---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: light-ldap
  namespace: light-ldap
spec:
  parentRefs:
    - {namespace: gateway, name: default, sectionName: ldap}
    - {namespace: gateway, name: default, sectionName: ldaps}
  rules:
    - backendRefs: [{name: lldap, kind: Service, port: 389}]
