# Talos permission workaround:
# - https://github.com/longhorn/longhorn/issues/6114
# - https://github.com/xrs444/flux/commit/2c0c7f69c9f878e59938d46a0dd081060a1ff458
# -> Insecure flag on the export fixed the issue.
---
apiVersion: longhorn.io/v1beta2
kind: BackupTarget
metadata:
  name: nfs-backup-target
  namespace: longhorn-system
spec:
  backupTargetURL: nfs://file01.hera.home.karlsen.fr:/homelab-longhorn-backup?nfsOptions=soft,timeo=330,retrans=3
  pollInterval: 5m0s
