---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-longhorn-ui-ingress
  namespace: longhorn-system
spec:
  endpointSelector: {matchLabels: {app: longhorn-ui}}
  ingress:
    - {fromEndpoints: [{matchLabels: {k8s:io.kubernetes.pod.namespace: envoy-gateway-system}}], toPorts: [ports: [{port: '8000', protocol: TCP}]]}
