# [FEATURE] Backup to multiple BackupTargets: https://github.com/longhorn/longhorn/issues/10625
# [FEATURE] Allow specifying the backup target for recurring backups: https://github.com/longhorn/longhorn/issues/11421
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: backup-group1-recurring-job
  namespace: longhorn-system
spec:
  name: backup-group1-recurring-job
  task: backup
  retain: 7
  concurrency: 1
  cron: 00 3 * * *  # 03:00 UTC / 05:00 CEST
  # parameters:
  #   full-backup-interval: '7'
  groups: [group1]
  # labels:
  #   backup-schedule: daily
  #   retention-policy: weekly
