---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: backup-group1-recurring-job
  namespace: longhorn-system
spec:
  name: backup-group1-recurring-job
  task: backup
  cron: 00 5 * * *
  concurrency: 1
  retain: 7
  groups:
    - group1
  labels:
    backup-schedule: daily
    retention-policy: weekly
  # backupTargetName: nfs-backup-target  # Should be available in Longhorn 1.13
