---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: longhorn-crypto
  namespace: longhorn-system
spec:
  encryptedData:
    CRYPTO_KEY_PROVIDER: AgCdKdfsh+liAP7doIjn8mytYcBGoAm0eZOh6OQj4Ojdu3X4lq7Q31jBuu0VvHn3otUJDWIlZ8NmRzL4wut8yTiJBjF/B4kJPZSknIu27Fv5qLgU4kn75gp8x3PT/EycRZjE+EWb0Ve7TyTIAwcoky1fgiWC1LFIr8I8cZYSZtLmeW80FwwSTvwaBzBP6O0bfF8SGVMHlCcgXR+tro9x862MBrcp2pKPH0E8gU5FMVE4a8e4bSX+0O5ZtOWY14DWBDcm8yDM5BClpFtXIvVTJdHocX9t+m7hbjUN1+pubyO9X0tgz6TSfACk2VCAa7Z5JjwHTcBE2A5rcVXYHMwe7R9sNTZTtXANk9b8dM6nuhkjeK1rB5DXf6rNR+ZvraSXCJ39U5ZtNG8rJjzaQz8saxubh7Mp3NGuPyPKsBc/G2BnrpsAs0WY3g+DjSlQDYpsiW0oed36BxobtOXzt1EpQ+C3bvQwdzdxo7KpVe/ikxCovBKQKqwIL5ZdWQXu1HlBZkmGdvgiChiukbaOq6Q1mOf84ZOJArvSaNM5X6766pw/cuOiax76bXL9mrrrtCO5v8kZmb+pNzKr45KG8OQrOeqpkwI3cmc1qlTIplt5jA8AJmvSjBMkr96aQSeAqABnoWqV0uYMtji4wyQM3HlGgnrhdIeFq+opb7+lwJ3u8Y6+o4KRwFrNBs8gn+oLKtCsLo28M7kZ48U=
    CRYPTO_KEY_VALUE: AgCpY3GQmoElwDbK9dChUnQKNg40M86UO0fKLpBnsqIzaWZaSUcqMqA44Rdg4KPyS4NB9r88YEvCgVWTajO+lbN3SIzBdD/gxwWOUoKQt4EbJHQpJUbhjPjobrcBwZLWHWSAcJh9dAEiM4Ph17T3yCz3ggUaIPjW9EApvwACGl+5hqh833C0E33WhZEoHALCQG2tHkWjwqZrE3A3/ETONSMmt+k0+7QZcD8VwbwXJJPspKEjFW1iHI+2dg8t1rsNHD1eDG+TQwHl4hGb98uSQJCbQObaDnZ8uvuKGsqvSTt+R71br1fAUjihO5mhy5hbGj9dd7pULtYgRuZDcZohiKPWeN11UkdZqN+25ChOJVncl6QocGhA9MXdCs1EfqXPTI8s7VlSRod1OEFu44knfH7ebyJxPRnn1cC61pEa3/0w4ier+yttFwwctiQ19sgyGSnJsYuyy1+cY/tHMbwVKEXHZf2FxNiRpDb1eXgTXGgx/4bd7RuPLeRlVQHNI3k2f/fqC7/mxAccM0kMl4QiZZK0KtMZlycEep4l7r9AWNn6II7u/ghOoqGaHYhSPCZKsnDfQkt/DHyGrWTlHUESYoNO/7qQl9dASoCJ832DdeejBx140aFFS/pvck1kXLGA29pZzforW+jGQeDFshnoCZoLV7y4Q6uKvigTMAIT7VxTsnZi+oS8pN8DZ5F90LudP1gVj6jWHqwrL2MTcgIkPhYp3h+7cRHVjN3gTNXGlUkXM2HcSndncFNqeYjCGU4D8wA=
  template:
    metadata:
      annotations:
        kustomize.config.k8s.io/behavior: replace
      name: longhorn-crypto
      namespace: longhorn-system
