# yaml-language-server: $schema=
# https://github.com/longhorn/charts/blob/v1.11.x/charts/longhorn/values.yaml
# https://github.com/longhorn/longhorn/tree/master/chart
# https://joshrnoll.com/installing-longhorn-on-talos-with-helm/
# https://www.johanneskueber.com/posts/longhorn_uservolumes_talos/
---

networkPolicies:
  enabled: true

defaultSettings:
  defaultReplicaCount: 2
  defaultDataLocality: best-effort
  defaultDataPath: /var/mnt/longhorn-data
  allowCollectingLonghornUsageMetrics: false
  replicaAutoBalance: best-effort
  systemManagedCSIComponentsResourceLimits: '{"csi-attacher":{"requests":{"memory":"512Mi"},"limits":{"memory":"512Mi"}},"csi-provisioner":{"requests":{"memory":"512Mi"},"limits":{"memory":"512Mi"}},"csi-resizer":{"requests":{"memory":"512Mi"},"limits":{"memory":"512Mi"}},"csi-snapshotter":{"requests":{"memory":"512Mi"},"limits":{"memory":"512Mi"}},"longhorn-csi-plugin":{"requests":{"memory":"4096Mi"},"limits":{"memory":"4096Mi"}},"node-driver-registrar":{"requests":{"memory":"512Mi"},"limits":{"memory":"512Mi"}},"longhorn-liveness-probe":{"requests":{"memory":"64Mi"},"limits":{"memory":"64Mi"}}}'
  freezeFilesystemForSnapshot: true
  snapshotDataIntegrity: enabled
  snapshotDataIntegrityCronjob: '0 3 * * *'  # Default: '0 0 */7 * *'
  snapshotDataIntegrityImmediateCheckAfterSnapshotCreation: true
  backupCompressionMethod: gzip
  allowRecurringJobWhileVolumeDetached: true

defaultBackupStore:
  backupTarget: nfs://file01.hera.home.karlsen.fr:/mnt/nfs/homelab/longhorn-backup?nfsOptions=soft,timeo=330,retrans=3
  pollInterval: 60s

longhornManager:
  resources:
    requests: {memory: 2Gi}
    limits: {memory: 2Gi}

persistence:
  reclaimPolicy: Retain
  defaultClassReplicaCount: 2
  defaultDataLocality: best-effort

# https://github.com/longhorn/longhorn/issues/8707
preUpgradeChecker:
  jobEnabled: false
  # upgradeVersionCheck: false
