# yaml-language-server: $schema=
# https://github.com/longhorn/charts/blob/v1.11.x/charts/longhorn/values.yaml
# https://joshrnoll.com/installing-longhorn-on-talos-with-helm/
# https://www.johanneskueber.com/posts/longhorn_uservolumes_talos/
---
# values.yaml
defaultSettings:
  defaultReplicaCount: 2
  defaultDataLocality: best-effort
  defaultDataPath: /var/mnt/longhorn-data
  allowCollectingLonghornUsageMetrics: false
  upgradeChecker: false
  replicaAutoBalance: best-effort
  systemManagedCSIComponentsResourceLimits:
    csi-attacher:
      requests:
        # cpu: 100m
        memory: 128Mi
      limits:
        # cpu: 500m
        memory: 128Mi
    csi-provisioner:
      requests:
        # cpu: 100m
        memory: 128Mi
      limits:
        # cpu: 500m
        memory: 128Mi
    csi-resizer:
      resources:
        requests:
          # cpu: 100m
          memory: 128Mi
        limits:
          # cpu: 500m
          memory: 128Mi
    csi-snapshotter:
      resources:
        requests:
          # cpu: 100m
          memory: 128Mi
        limits:
          # cpu: 500m
          memory: 128Mi
    longhorn-csi-plugin:
      resources:
        requests:
          # cpu: 100m
          memory: 128Mi
        limits:
          # cpu: 500m
          memory: 128Mi
    node-driver-registrar:
      resources:
        requests:
          # cpu: 100m
          memory: 128Mi
        limits:
          # cpu: 500m
          memory: 128Mi
    longhorn-liveness-probe:
      resources:
        requests:
          # cpu: 100m
          memory: 128Mi
        limits:
          # cpu: 500m
          memory: 128Mi

longhornManager:
  resources:
    requests:
      # cpu: 100m
      memory: 1024Mi
    limits:
      # cpu: 500m
      memory: 1024Mi

persistence:
  reclaimPolicy: Retain
  defaultClassReplicaCount: 2
  defaultDataLocality: best-effort

# https://github.com/longhorn/longhorn/issues/8707
preUpgradeChecker:
  jobEnabled: false
  # upgradeVersionCheck: false
