# yaml-language-server: $schema=
# https://github.com/longhorn/charts/blob/v1.11.x/charts/longhorn/values.yaml
# https://github.com/longhorn/longhorn/tree/master/chart
# https://joshrnoll.com/installing-longhorn-on-talos-with-helm/
# https://www.johanneskueber.com/posts/longhorn_uservolumes_talos/
---
# values.yaml
defaultSettings:
  defaultReplicaCount: 2
  defaultDataLocality: best-effort
  defaultDataPath: /var/mnt/longhorn-data
  allowCollectingLonghornUsageMetrics: false
  replicaAutoBalance: best-effort
  systemManagedCSIComponentsResourceLimits: '{"csi-attacher":{"requests":{"memory":"512Mi"},"limits":{"memory":"512Mi"}},"csi-provisioner":{"requests":{"memory":"512Mi"},"limits":{"memory":"512Mi"}},"csi-resizer":{"requests":{"memory":"512Mi"},"limits":{"memory":"512Mi"}},"csi-snapshotter":{"requests":{"memory":"1Gi"},"limits":{"memory":"1Gi"}},"longhorn-csi-plugin":{"requests":{"memory":"8i"},"limits":{"memory":"8Gi"}},"node-driver-registrar":{"requests":{"memory":"512Mi"},"limits":{"memory":"512Mi"}},"longhorn-liveness-probe":{"requests":{"memory":"512Mi"},"limits":{"memory":"512Mi"}}}'
  freezeFilesystemForSnapshot: true
  snapshotDataIntegrity: enabled
  snapshotDataIntegrityCronjob: '0 3 * * *'  # Default: '0 0 */7 * *'
  snapshotDataIntegrityImmediateCheckAfterSnapshotCreation: true
  backupCompressionMethod: gzip

longhornManager:
  resources:
    requests: {memory: 1Gi}
    limits: {memory: 1Gi}

persistence:
  reclaimPolicy: Retain
  defaultClassReplicaCount: 2
  defaultDataLocality: best-effort

# https://github.com/longhorn/longhorn/issues/8707
preUpgradeChecker:
  jobEnabled: false
  # upgradeVersionCheck: false
