---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - HTTPRoute.yaml
  - GrafanaDashboard.hubble.yaml
  - GrafanaDashboard.hubble-dns-namespace.yaml
  - GrafanaDashboard.hubble-l7-http-metrics.yaml
  - GrafanaDashboard.hubble-network-overview.yaml
