---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: glance
  namespace: glance
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  strategy: {type: Recreate}
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: glance
      app.kubernetes.io/version: stable
      app.kubernetes.io/component: server
      app.kubernetes.io/part-of: glance
      # app.kubernetes.io/managed-by: kustomize
  template:
    metadata:
      namespace: glance
      labels:
        app.kubernetes.io/name: glance
        app.kubernetes.io/version: stable
        app.kubernetes.io/component: server
        app.kubernetes.io/part-of: glance
        # app.kubernetes.io/managed-by: kustomize
    spec:
      serviceAccountName: glance
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
        fsGroup: 65532
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: {type: RuntimeDefault}
      containers:
        - name: glance
          # Dockerfile: https://github.com/glanceapp/glance/blob/main/Dockerfile
          image: docker.io/glanceapp/glance:v0.8.4@sha256:6df86a7e8868d1eda21f35205134b1962c422957e42a0c44d4717c8e8f741b1a
          command: [/app/glance]
          args: ['--config', '/glance.yaml']
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: {drop: [ALL]}
          resources:
            requests: {memory: 48Mi}
            limits: {memory: 128Mi}
          ports:
            - {name: http, containerPort: 8080}
          startupProbe: {httpGet: {port: 8080, path: /}, initialDelaySeconds: 2, periodSeconds: 10, failureThreshold: 3}
          livenessProbe: {httpGet: {port: 8080, path: /}, initialDelaySeconds: 10, periodSeconds: 120}
          readinessProbe: {httpGet: {port: 8080, path: /}, initialDelaySeconds: 10, periodSeconds: 120}
          volumeMounts:
            - {name: glance-config-volume, mountPath: /glance.yaml, subPath: 'glance.yaml', readOnly: true}
      volumes:
        - {name: glance-config-volume, configMap: {name: glance-config}}
