---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oidc
  namespace: glance
spec:
  template:
    type: Opaque
    metadata:
      name: oidc
      namespace: glance
      annotations:
        kustomize.config.k8s.io/behavior: replace
  encryptedData:
    client-id: AgA7wI0a3P/JV/ExO7GLzOugcdow0OuVZ9WhZ3zKxSQIl65gQS2V77CL1DimsHjLz2fb1fIQStKFPMLNc42P9P33wm5kyWcQeI3QZJ0k8E2LAt9PtDGVQAR3h4E5vzGRvLCuf4v6HSqnn5BXR2j+phPu7Xs5Oh75gcdzBAdgqUbM+WqK1pQi1+OgU5IueWY3QN9tSBucTA39YY1jdTDHO04byU1bk3dDi5ZXx/W7SYCgG4QGbCAVlobwtxnj6CYVoRU7x3fGCZy7Hu9gta1mto+iVbiU4Um14hrMz3AEfC1g/SjKXCSgQ+hLSr1dgSMB16PekQ4ohJ7oJwijmO8T4wQfMBmnQxUTH2N4kOLaJPNT2hMPfnFdrlyIq8+2sZeQxGtAZwQYYgdQqZILyKLAcaY2jKjGAa32vwcSnSXRORWpYaufkC1xUhbp71k1glWDWglPpUw2MlH817TLuy090PvalLvsGu834qNsOgzZscgKhip2IEzsNjciVvtztbJ2bVWN1JYebrZp5fEh6ta/9Q3XmHkIubbea3kyQhw0fLme7XlMROdF5JkAbYNHhHoaeLyOad/ej098kO8orIbXNQ0wh+nDJYFX33gyfcE008Ilp7CTTy7vxiDq0h9FR/WWIzQD/zcHotsC9XRewLFtw1y5ps0+2dE2nc2pL9xYszOddawLh+yX8e5eIFiAlzseLp4HCL4ttK8eQjuKgZUqjd9G9Co=
    client-secret: AgAZc0VHjVbDhQlhNRBlA4m9tY7FN2sO7nrJkjPxB0p+sf9Bv0WEtQzfk4ucvqLWdpSwHsrVO9q0XnQHLbuAFarLk1lq1sDHBGglUc0i3FDZVMudhhHBHChDFiitXm3OM3MYS5cn4lLz6FUq6Pkd7O7Fhm5bQw8WvFPvBLSGr6rrDoAie2VCAv59Au8UqFwp/aLcrKdTLKyZFfJQEjZ+oZySfaJ9gnxSjTpT5vEJj6IrBYuNc9Wq0ine+unMZigmsvpPVEAViJ5POcXI90bEkrvqnech2oLLhtjFOsOh+/Y7xtXNH2PHhnb8Y5IdSx0HSutce6c7dlaZvL92yQ3kBW3becwmPZq8KwMExx7kKRGDPT/A91IrngZdEDNj7q2zFTOULDhM+b4Q3CCDw7riDnSOQNeLL0ZGxfUWvbyshwmnWt+i7Lp3Fup+074AatXOQJS7Gp0yNjUWm6irWZ2HDaDEfymAs14JgnJRt2/vcx298k8pV9udYKEn4DAnpbKsfxsmvpKkUakl1DOQxn3LWSEWdncEDeFmQ9o3G+zdYCOM3kgs3VM3O1Xb5MWBYVTW022Q/R2itIhuMHH6GnHQ7EEiB1yqSfTpf8hPcg8SSSqjA/7UfSsnj4GUXCfgulc/CQe3c1N/qK25uD66Z7IOXfrG01/ZLIN/EZI6Ggc834LjuW3QVBwxbH03aYTzF+HCKId04KGTEcCwNuVJxr5od9FIutr9Z5wNh8Iw0ShogTOJDe0zx6yYBtcxmo8EvQZcF4wJm9+eJwKuNQcLRzT/tA1+
