---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: media
  namespace: argocd
spec:
  sourceRepos:
    - https://github.com/sebastka/homelab.git
  destinations:
    - namespace: argocd
      server: '*'
    - namespace: jellyfin
      server: '*'
    - namespace: opentogethertube
      server: '*'
    - namespace: metube
      server: '*'
    - namespace: vert
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
