---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: media
  namespace: argocd
spec:
  sourceRepos: [https://github.com/sebastka/homelab.git]
  destinations:
    - {namespace: argocd, server: 'https://kubernetes.default.svc'}
    - {namespace: jellyfin, server: 'https://kubernetes.default.svc'}
    - {namespace: metube, server: 'https://kubernetes.default.svc'}
    - {namespace: opentogethertube, server: 'https://kubernetes.default.svc'}
    - {namespace: vert, server: 'https://kubernetes.default.svc'}
  clusterResourceWhitelist:
    - {group: '', kind: Namespace}
