---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oidc
  namespace: headlamp
spec:
  encryptedData:
    OIDC_CLIENT_SECRET: AgAjIkRcXFy9CS4UeE7Noq56xtTSbfhCcoN63ssiJFlum3uI7mQxREZJ0iFvwaoQq10lac9VtU0jMBwX7zN5hKlg3rrZQw1thAGwkgBtsAZg0Ee059BJFnt9c2MrToDxEckWQ+1x0VO283DWUH460Lj5ffuSc0zn638Ol1iaK242FMDlzsSe6nX0bxfz6OK+woDqUeN2hNCzPDv/FwOltV/kW1CfG69zOsaRp+cSjjhSzBWA+mBIu5VUn7d8tjQz6xaMx0mCQ3r6RvVIaq4d3tTFh2VRBXvfTDaKKvC+nQtu5TmW/FUDCo7OvrbeKvIECeZwrbBU/bbVEC0FbUVc8W/BOFPaCqsWO0/GL4gbaGxmw6WSsWhruYdmfdw0SuoRki5dStp9WtiHFRkWDqbjYJ1JdJ+DuFcNY20yMIC1YgVAJg/mkYRMbohY4wO8WtnK/IAwwZHPIrfeNGSWEPxloseu818wKw04e1ScniNUCiJS18rq4gcGvzEc4j01UmnHTfniT4XNZlPl6NFUO4/Lg+p/z06nGSYEQfk4svJ51se4OADQesmrq2z6uskNSdGZ0MTnsYFR7bBbMb7iZc/HFZcs1rDc4wPV8cfB9/+Njn/8MosxBUnOmDl3FgBF48WtW/KVr/G3lpMCAjzNDaQJRMqcuGfGZkRPeB9MdgLtXO6g43G1hOaDFSxha2DyqOUH7ooj8K8upfY/zCg3b0WVNjZ0Br+Iq2d20vEM3xeHFy93wvcOMyegJMR6icXSmlTK/N/CyFXfNSnHZO3oWwcDF3kxBzPRHmsuOt0=
  template:
    metadata:
      annotations:
        kustomize.config.k8s.io/behavior: replace
      name: oidc
      namespace: headlamp
    type: Opaque
