# yaml-language-server: $schema=https://raw.githubusercontent.com/kubernetes-sigs/headlamp/refs/heads/main/charts/headlamp/values.schema.json
# https://artifacthub.io/packages/helm/headlamp/headlamp?modal=values
---

config:
  oidc:
    secret: {create: false}
    clientID: kube_login
    issuerURL: https://auth.karlsen.fr
    scopes: openid profile email groups
    # callbackURL:
    validatorClientID: kube_login
    validatorIssuerURL: https://auth.karlsen.fr
    # useAccessToken:
    usePKCE: true
    # useCookie:
    # meUserInfoURL:

  # pluginsDir: "/headlamp/plugins"
  # enableHelm: false
  # watchPlugins: false
  # # tlsCertPath: "/headlamp-cert/headlamp-ca.crt"
  # # tlsKeyPath: "/headlamp-cert/headlamp-tls.key"
  # # Extra arguments that can be given to the container. See charts/headlamp/README.md for more information.
  # extraArgs: []

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 100
  runAsGroup: 101
  fsGroup: 101
  fsGroupChangePolicy: OnRootMismatch
  seccompProfile: {type: RuntimeDefault}

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities: {drop: [ALL]}

httproute:
  enabled: false

resources:
  requests: {memory: 64Mi}
  limits: {memory: 64Mi}

pluginsManager:
  enabled: false
  resources:
    requests: {memory: 512Mi}
    limits: {memory: 512Mi}
  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities: {drop: [ALL]}
