# yaml-language-server: $schema=https://raw.githubusercontent.com/kubernetes-sigs/headlamp/refs/heads/main/charts/headlamp/values.schema.json
# https://artifacthub.io/packages/helm/headlamp/headlamp?modal=values
---

config:
  oidc:
    secret: {create: false}
    externalSecret: {enabled: true, name: oidc}  # OIDC_CLIENT_SECRET
    clientID: headlamp
    issuerURL: https://auth.karlsen.fr
    scopes: openid profile email groups
    # callbackURL:
    validatorClientID: headlamp
    validatorIssuerURL: https://auth.karlsen.fr
    # useAccessToken:
    usePKCE: true
    # useCookie:
    # meUserInfoURL:

  # pluginsDir: "/headlamp/plugins"
  # enableHelm: false
  # watchPlugins: false
  # # tlsCertPath: "/headlamp-cert/headlamp-ca.crt"
  # # tlsKeyPath: "/headlamp-cert/headlamp-tls.key"
  # # Extra arguments that can be given to the container. See charts/headlamp/README.md for more information.
  # extraArgs: []

httproute:
  enabled: false

resources:
  requests: {memory: 64Mi}
  limits: {memory: 64Mi}

pluginsManager:
  enabled: false
  resources:
    requests: {memory: 512Mi}
    limits: {memory: 512Mi}
