---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authelia

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - {namespace: authelia, name: authelia-configuration, files: [configuration.yaml=assets/configuration.yaml]}

components:
  - ../../../../common/valkey

resources:
  - Namespace.yaml
  # - Secret.jwk.yaml
  - Certificates.yaml
  - ServiceAccount.yaml
  - Deployment.authelia.yaml
  - Service.yaml
  - SecurityPolicy.yaml
  - CiliumNetworkPolicy.yaml
