---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-ntfy
  namespace: monitoring
spec:
  encryptedData:
    token: AgCQ/qo5LIY++TbPnVb9vXM4gJxclLi09CyTINa+zXv73gydNFjHCyGa/l8x32cv+7IWaks3iXz6A4GSAhHS2UDsR3nOUp5v4n/2wZuGl7IzV5voGD01SbESQ/i3ZMy81DmlhCIv3THqh3IZZ0oWIP0OtYxOE7HszwC+lBPWuvFTdXOYzccuhwyzyhZFFMRXLFCyDdseATt8U1okOUk3Z0Z5jYVBNqfzUxURo/bsGRhyXG4qMU4juFbgDWBTu59MrtdjKdVLaHmcC3PVT33TXOkptwGGhlVRNFkCWxVgTjQ2y5Bw2zdTnEJ4KAHtWL8jUZbaCk1jByCA/iyFEdbVos0gz4BzAx5RTvVBaYGNcPXI7XTy6IspPOIhCQq6r68p4+Pok7WHpFsn2Z5TJGzAYBffMW6BHNK74bmLN7EJipbUycDvrkjY28LfYc+Ma4XCqU7WGEFzz6j1iLLaO9B95Ln1aHSWY8GofF/zenX+YMPMVjgElbi8wpxHu4TK//2n7P8lzCCgfc5t0tx/HL4Gv/ywrRBBjpFLtCn/ZbdoGkJoNT40nXmVxxyJb2QBAVslQVxheOeF6c8iz9vAhgC/UYYuEcu0SVPBgNUgYWhxjYqK54k7boAYiTvEtePqdCutBmJakun53BL+lEegf1JP3eoHO+6ZIkSNqbUhiSa7bcA6D1ZKFyCl2sOjOQSZRSf+jHPqVJl00hKLKCSMYyfYvZLKn+j6ModaPBvAedagiboF+g==
    url: AgA2g4K+Fs/HB9KtAhY7rOnvt5KEDH/ZAPaO/ArEFPUTgCetV7zUsc1IPJ2A3gHLG1wa4JJOpsEjoYS97zPMQC7V5tG/ORvHKLkI13qbVPRFHyw/5HkFNlKpetfHuFJaa6Yvy8lffVpqqZLavpgtk2lbR2wJ/LwdrOyDTtTjWFliQ0xMU4D2LBf17pYM98h5OLfqz+AWK4B6hS+ftG1P83fZZ9zy3IzAaQmghRK8F7lsU6xuuCpRzQmVE0VnPNCFgSkMcetAHMCyTj+a2w/RbJfftuFsv5zwfA+IZeXNeYnduaQjC40ujdtDehM71xv0DlZpEcINzIosexRkJ0UUxBPmcZGRvvNiqGN1wu9gbYwlCMcUgFRy4wc1J7P1WMUH0kKkn84cd4L8pyQPCbAiLIo4QDJgPe8Fns4vK6wvyYmuohd0nBUlmaeUCZkKQezt6WYpXHSB/tnUDIfllMaWpBzkXX4/ciBdyR10JdIXONBdGqmy16yt0s2Lr0WJm+Csp3t215I3jYqsH4EMkTDX6Gos4CjA+ILKSc1sHz8RQ3wb+F8eVLdoRY/6yQs6UgkBWtd2G8k1DoE6vS5uKvn0B4/rQ+6yidAbcfL8y9cNK6Z0cIzs+6kqu06rJ54K/YLLyJxKWu/3YUDGhXlImmFBE+gbdJvZo6w2LJisDLUWkdEHHA5OUN1NBVN+NFAaSI83lV3EgQf5p4iKxuZKAjCYpALo5LDGWc5PEtGD6orujV+z+Rw5ZAU2kEkWUJ/zOM2KyJkiIA==
  template:
    metadata:
      annotations:
        kustomize.config.k8s.io/behavior: replace
      name: alertmanager-ntfy
      namespace: monitoring
