# yaml-language-server: $schema=
# https://github.com/aquasecurity/trivy-operator/tree/main/deploy/helm
---

trivy:
  storageClassEnabled: false  # Use emptydir
  slow: true
  resources:
    requests: {cpu: 100m, memory: 1024Mi}
    limits: {cpu: 500m, memory: 1024Mi}
  # githubToken:
  server:
    resources:
      requests: {cpu: 200m, memory: 1024Mi}
      limits: {cpu: 1, memory: 1024Mi}

# resources:
#   requests: {memory: 256Mi}
#   limits: {memory: 256Mi}
