# yaml-language-server: $schema=
# https://github.com/aquasecurity/trivy-operator/tree/main/deploy/helm
---

trivy:
  storageClassEnabled: false  # Use emptydir
  slow: true
  resources:
    requests: {memory: 128Mi}
    limits: {memory: 128Mi}
  # githubToken:
  server:
    resources:
      requests: {memory: 1024Mi}
      limits: {memory: 1024Mi}

# resources:
#   requests: {memory: 256Mi}
#   limits: {memory: 256Mi}
