# https://github.com/thelounge/thelounge
# https://github.com/thelounge/thelounge-docker
# https://hub.docker.com/r/thelounge/thelounge/

# When using maxHistory = -1, SQLite will spill a temp sort to /tmp. 
# To avoid this, "USING INDEX network_channel_time" and adding a "(network, channel, time DESC)" composite index to the "messages" table is recommended.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thelounge
  namespace: thelounge
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  strategy: {type: Recreate}
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: thelounge
      app.kubernetes.io/version: stable
      app.kubernetes.io/component: irc-client
      app.kubernetes.io/part-of: thelounge
      # app.kubernetes.io/managed-by: kustomize
  template:
    metadata:
      namespace: thelounge
      labels:
        app.kubernetes.io/name: thelounge
        app.kubernetes.io/version: stable
        app.kubernetes.io/component: irc-client
        app.kubernetes.io/part-of: thelounge
        # app.kubernetes.io/managed-by: kustomize
    spec:
      serviceAccount: thelounge
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: {type: RuntimeDefault}
      containers:
        - name: thelounge
          # Dockerfile: https://github.com/thelounge/thelounge-docker/blob/master/Dockerfile
          image: ghcr.io/thelounge/thelounge:4.4.3
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: {drop: [ALL]}
          resources:
            requests: {memory: 64Mi}
            limits: {memory: 512Mi}
          ports:
            - {name: http, containerPort: 9000, protocol: TCP}
            - {name: identd-tcp, containerPort: 9001, protocol: TCP}
            # - {name: identd-udp, containerPort: 9001, protocol: UDP}
          startupProbe: {httpGet: {port: 9000, path: /}, initialDelaySeconds: 2, periodSeconds: 10, failureThreshold: 3}
          livenessProbe: {httpGet: {port: 9000, path: /}, initialDelaySeconds: 10, periodSeconds: 120}
          readinessProbe: {httpGet: {port: 9000, path: /}, initialDelaySeconds: 10, periodSeconds: 120}
          volumeMounts:
            - {name: tmp-volume, mountPath: /tmp}
            - {name: thelounge-data-volume, mountPath: /var/opt/thelounge, subPath: thelounge}
      volumes:
        - {name: tmp-volume, emptyDir: {}}
        - {name: thelounge-data-volume, persistentVolumeClaim: {claimName: thelounge-data-pvc}}
