---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: thelounge

resources:
  - Namespace.yaml
  - Deployment.yaml
  - Service.http.yaml
  - Service.identd.yaml
  - HTTPRoute.yaml
  - PersistentVolumeClaim.yaml
  - SealedSecret.oidc.yaml
  - SecurityPolicy.yaml
