---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oidc
  namespace: thelounge
spec:
  encryptedData:
    client-secret: AgButqJdkbIiA0usLh8+t7GENAQa/xiltZ8+C3k1q+nx0FMrftAuRWDWrOvwpQ/diQzMJp8GfkjCX2fBwQpL3lwjIA3OrRNKJxSw/9hUYF96g6mq44EaQqg2BJq875yMvGRB/tEEg+fHSdm3+33ljvZjgxjLWtpl856Zs8YlPpEHPVguopJEv46AUbNzKvDYtmlsjzc9C5xUeF9l4R0s7hp2PWMeEV3E1F7T2o/r9/De/4uT33leL6Bk+nVpUD1+KU1o8aZmmFfoeIBwvYZqY7zhfUNbw1HI7w7w2zuU0uay5drQ6wgOl57uSt+hDFHkgkIuD4myCUhUAhla6FCc/RmXJoKVeGfHCbB9l7xQmpkoWm0jG0ZUICpxMsLTVB46v8Jbj42md+sInn0tVjOEgoWhtbr7oQW/QqXCcoexG6E+h92FFA0sME2RogJ5hyevEpMmzh3It63GPGmQJuojAFT+SSXbUu+PJN3q1mL55MUTbONhc9RjEHoQJyOVEOr/5yrS3j8Kilz1aZMmu19aq4ULGt0ntE+hrsVmUF+L9wmjASae8k515+OnV3WXESq84QGsQahriFFJirnqOCyULGVc1D8AMR0ojGIYbl2eAKULI9jFiw5KHyhkagwmrcHRRWj16XdWLE93Dg0uySOR78vgYl1app/7FijnEHXuDlIeZVv9KkokeWReWFbTrMPba0ZbZkgfLWVYVAKXybXK9l0+vsiT+sTXD+j9Vh4jtiKAE1DDRsmvZ8Bqa0XimbEnLpoI37am4E58c9M275CqJ1XFgWo41w4DuYY=
  template:
    metadata:
      annotations:
        kustomize.config.k8s.io/behavior: replace
      name: oidc
      namespace: thelounge
    type: Opaque
