---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oidc
  namespace: thelounge
spec:
  encryptedData:
    client-id: AgCULwJY3OimOTu1YkFSrazcfwKE3QA6YDtBkjU5iCFvnOZZzgrRC6dOa2QnxDXJABPe5a25sRvILkOok5GzbHPHELsmAxFEvIADFXVRMa8pw+KJvkJoWx4Y+XOD6x+VtYZEiFTOhIaNiezqdXN/4tlYhxj7jpj7bfw6eKYQxDIQvo+5oacUEECz32ECAitreVWVfApBjidV8WVXFwfgOEPMz+dw83eEjlhVHdNuVRDhNvv7wuRD2uE4/7rBHbWFOaugoacyvtFDRYsaGBXpcxR8mPTzB2HftpfVrlFDneUDf7uSUWHWOVUeoGb1x04mnBLNaBzcNMA7Eay1BWf+yEzqcET1sN/AcR9kVOJyxLiquaRuPZVobbCQSbua9agux3zte11QIAcv3IdTyXihheaqhQEb3Z9tbrOZ50BmLhr6IOZUNJYJHrw4piU4ZDud8ht/qyA1f4DYZgtCmjyYpe7i3rC9J68kNWRdckfSwSHQK+6CAOzrnRA0j9n6dlxF0l+2aOLsavfBidDsMm04wd9zCJ9diuGOjjwx8+pssv2990bH/fiFYs68P7CYysJBDcL3F0rvlJVg2C4jibBnjgEwGfGch1dp1oJb79YEkgjjEhtRfC+LhC/lFy9u6ci1z4vL9LHGdu/LoejGUxgV9AcwxmSepMkV6XbCcbXz8tcNQ+mMlm3QMQiQWvLoBUwvjFUCHTryvB9AmpK3LrBV7biIbyI=
    client-secret: AgCT8z8st96a0tPQW/+2e+E3YFjRRnSnUr+fgLwFgDica0Qit8Ryst3XDZpatQOG2th8HKHeBafwwzRcTlzRM4GkJcx511lFgac9Yz15xOCqO0higVU5NNZOQZn1e7bN9WDEDGlv/SrvEU0pVTL7UQdZtfhSYCv3F8ZoOKpJGW/LNcq7rGs2/9FIl3iuj+K9b5+PCk/oGcxMk/FdSZ5LKq9P4GivU/Xd8fcZKQL4cnJJT+pdreJcZ9kLkxpvETkvotoQ8tuwDDMRHsvUMOOl3tCkl0pQGrCKSET04oKwPhZHbfXFJxTlZGXLoN4ivDJ51c7fxiAdToT0BHdSwOE1yYIi2lp4PAcOzjrLaO+ap9COtkV8ZsEof9da+Jz69T3JPk4D8fKGMlRBiLKE247Uj9abQrQVuUxh8kvRHHW8o8ZqqBryv2rPBC9vNRIOF4CytcW5asqg1PS/8g/CxEWg1P3lvgMhyx5uS81PgFLScUy1B3SFqOYui4FV5kopqSOgWiyc/Nk0owSUs5XNN0RuboIlpop7re0VDv/UIlFcD80aHQ9Yw2f0+Y9L3lsfOujYfF2THBoQT8m4zvLAdoJTsdurk8o2n1FHGphb5oZkdAgQYaCT52ulWbbb/ZkEWiCfpVj/WPIEKeJAuVwUKQUuCAElOscflwGDiUQ7KMuhKDOUpzNOus0qJzQ0TY7Z7LdIybNGrCbufyyOmnDYu+hVUoPgV4UyNEe1LaE3YGwUEA2qboLMXET7bxpxzS9ylGpXAVLRMVds4R3i7MxOv1AzqOnX
  template:
    metadata:
      annotations:
        kustomize.config.k8s.io/behavior: replace
      name: oidc
      namespace: thelounge
    type: Opaque
