---
apiVersion: v1
kind: Service
metadata:
  name: identd
  namespace: thelounge
  labels:
    arp.cilium.io/announce-service: default-arp-l2-announcement-policy
    arp.cilium.io/ip-pool: default-arp-ip-pool
  annotations:
    lbipam.cilium.io/ips: 192.168.2.11
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: identd-tcp
      protocol: TCP
      port: 113
      targetPort: identd-tcp

    - name: identd-udp
      protocol: UDP
      port: 113
      targetPort: identd-udp
