---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: thelounge
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: thelounge
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: identd
  namespace: thelounge
  labels:
    arp.cilium.io/announce-service: default-arp-l2-announcement-policy
    arp.cilium.io/ip-pool: default-arp-ip-pool
  annotations:
    lbipam.cilium.io/ips: 192.168.2.11
    service.cilium.io/forwarding-mode: snat
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: thelounge
  ports:
    - name: identd-tcp
      protocol: TCP
      port: 113
      targetPort: identd-tcp
