---
apiVersion: v1
kind: Service
metadata:
  name: thelounge-service
  namespace: thelounge
spec:
  type: ClusterIP
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 9000

    - name: identd
      protocol: TCP
      port: 113
      targetPort: 9001
