---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: utils
  namespace: argocd
spec:
  sourceRepos: [https://github.com/sebastka/homelab.git]
  destinations:
    - {namespace: fallback,                       name: talmox}
    - {namespace: argocd,                         name: talmox}
    - {namespace: deluge,                         name: talmox}
    - {namespace: element-admin,                  name: talmox}
    - {namespace: glance,                         name: talmox}
    - {namespace: matrix-authentication-service,  name: talmox}
    - {namespace: n8n,                            name: talmox}
    - {namespace: ntfy,                           name: talmox}
    - {namespace: paperless,                      name: talmox}
    - {namespace: searxng,                        name: talmox}
    - {namespace: thelounge,                      name: talmox}
  clusterResourceWhitelist:
    - {group: '', kind: Namespace}
    - {group: '', kind: PersistentVolume}  # Needed by Deluge
