# Env vars: https://www.authelia.com/configuration/methods/environment/
# Secrets: https://www.authelia.com/configuration/methods/secrets/
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authelia
  namespace: authelia
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  strategy: {type: Recreate}
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: authelia
      app.kubernetes.io/version: stable
      app.kubernetes.io/component: identity-provider
      app.kubernetes.io/part-of: authelia
      # app.kubernetes.io/managed-by: kustomize
  template:
    metadata:
      namespace: authelia
      labels:
        app.kubernetes.io/name: authelia
        app.kubernetes.io/version: stable
        app.kubernetes.io/component: identity-provider
        app.kubernetes.io/part-of: authelia
        # app.kubernetes.io/managed-by: kustomize
    spec:
      serviceAccountName: authelia
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: {type: RuntimeDefault}
      containers:
        - name: authelia
          # Dockerfile: https://github.com/authelia/authelia/blob/master/Dockerfile
          image: authelia/authelia:4.39.19
          command: [/app/authelia]
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: {drop: [ALL]}
          resources:
            requests: {memory: 128Mi}
            limits: {memory: 128Mi}
          env:
            - {name: TZ, value: Europe/Oslo}
            - {name: X_AUTHELIA_CONFIG_FILTERS, value: template}
            - {name: X_AUTHELIA_CONFIG, value: /config/configuration.yml}
          envFrom:
            - secretRef: {name: authelia-secrets}
          ports:
            - {name: http, protocol: TCP, containerPort: 9091}
          startupProbe: {httpGet: {port: 9091, path: /}, initialDelaySeconds: 2, periodSeconds: 10, failureThreshold: 3}
          livenessProbe: {httpGet: {port: 9091, path: /}, initialDelaySeconds: 10, periodSeconds: 120}
          readinessProbe: {httpGet: {port: 9091, path: /}, initialDelaySeconds: 10, periodSeconds: 120}
          volumeMounts:
            - {name: authelia-config-volume, mountPath: /config/configuration.yml, subPath: 'configuration.yaml', readOnly: true}
            - {name: jwk-rsa-volume, mountPath: /secrets/jwk-rsa/tls.key, subPath: tls.key, readOnly: true}
            - {name: jwk-rsa-volume, mountPath: /secrets/jwk-rsa/tls.crt, subPath: tls.crt, readOnly: true}
            - {name: jwk-ecdsa-volume, mountPath: /secrets/jwk-ecdsa/tls.key, subPath: tls.key, readOnly: true}
            - {name: jwk-ecdsa-volume, mountPath: /secrets/jwk-ecdsa/tls.crt, subPath: tls.crt, readOnly: true}
            - {name: client-secrets-volume, mountPath: /secrets/client-secrets, readOnly: true}
      volumes:
        - {name: authelia-config-volume, configMap: {name: authelia-configuration}}
        - {name: jwk-ecdsa-volume, secret: {secretName: jwk-ecdsa}}
        - {name: jwk-rsa-volume, secret: {secretName: jwk-rsa}}
        - {name: client-secrets-volume, secret: {secretName: client-secrets}}
