---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authelia

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - {namespace: authelia, name: authelia-configuration, files: [configuration.yaml=assets/configuration.yaml]}

components:
  - ../../../common/valkey

patches:
  - target: {kind: CiliumNetworkPolicy, name: allow-valkey-ingress}
    patch: |
      - op: replace
        path: /spec/ingress/0/fromEndpoints/0/matchLabels/app.kubernetes.io~1name
        value: authelia
      - op: replace
        path: /spec/ingress/0/fromEndpoints/0/matchLabels/k8s:io.kubernetes.pod.namespace
        value: authelia

resources:
  - Namespace.yaml
  # - Secret.jwk.yaml
  - Certificates.yaml
  - SealedSecret.authelia-secrets.yaml
  - SealedSecret.client-secrets.yaml
  - ServiceAccount.yaml
  - Deployment.authelia.yaml
  - Service.yaml
  - HTTPRoute.yaml
  - SecurityPolicy.yaml
