---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

helmCharts:
  - name: prometheus-operator-crds
    repo: oci://ghcr.io/prometheus-community/charts
    version: 29.0.0  # renovate: datasource=helm registryUrl=oci://ghcr.io/prometheus-community/charts depName=prometheus-operator-crds
    releaseName: prometheus-operator-crds
    namespace: monitoring
    includeCRDs: true
    valuesFile: values.yaml
