---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: karlsen-app-certificate
  namespace: gateway
spec:
  commonName: karlsen.app
  dnsNames:
    - karlsen.app
    - '*.karlsen.app'
  issuerRef:
    kind: Issuer
    name: cloudflare-dns01-issuer
  secretName: karlsen-app-certificate
