---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - Namespace.yaml
  - Certificate.karlsen-fr.yaml
  - Certificate.karlsen-org.yaml
  - Certificate.karlsen-app.yaml
  - Certificate.talmox-hera-home-karlsen-fr.yaml
  - Gateway.internal.yaml
  - Gateway.external.yaml
  - HTTPRoute.https-upgrade.yaml
