---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generators:
  - ./ksops.cloudflare-api-token-secret-generator.yaml

resources:
  - Namespace.yaml
  - ./Secret.cloudflare-api-token.enc.yaml
  # - Secret.karlsen-fr-certificate.yaml
  # - Secret.talmox-hera-home-karlsen-fr-certificate.yaml
  - Issuer.yaml
  - Certificate.karlsen-fr.yaml
  - Certificate.talmox-hera-home-karlsen-fr.yaml
  - GatewayClass.yaml
  - Gateway.yaml
  - HTTPRoute.https-upgrade.yaml
