#ENC[AES256_GCM,data:KPSZgxmwMXZpza2naF9ngINMOTeFRlYenlOKwh+O6miz+OLFqCWglklVGHtBPQYeGfVh86h8948GHnz/LI8OtWok264Zv5f6oJrdWdU6Gg/Ba2VSeOiIB5s=,iv:3IuDEG888JOMk8Peg6LvMoqRutqoEFyTMby636RaW2U=,tag:vlnDBohvWOlcKvijqzQjQQ==,type:comment]
#ENC[AES256_GCM,data:7M07ft968lL86WpYwq1W5nQYD0THubyVsSK1j7H29kwB8kQI2yBf8OdEUFnObBuceeMeJjag4TsgmyKbTQZUmGFKwAN/se2rGXIQOtyxOHBA91h8ItSSepw=,iv:RLGVHBx1jXP9ZYMy1+h+psvDBND1/JSvjYbQNuiw36M=,tag:AKWtlNEJQGobUrtoZKdkZg==,type:comment]
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: gateway
    annotations:
        kustomize.config.k8s.io/behavior: replace
type: Opaque
data:
    api-token: ENC[AES256_GCM,data:GDJM92WyYvx2Tp8maECNRzu40PZxk+qiZ4tzud+J4lwsI7N5yibm76qSbQtP5Z3LX1Fw8twYx3w=,iv:ZgNkNaJrzaIIg0NUX7iJXE1GtClAvv9RfAKekP5HEHU=,tag:4okc/+XD2bP61ctPQYTzEg==,type:str]
sops:
    age:
        - recipient: age1u8uutg4mpsn82nd9y828sj5agg7s89uswmp7frzpkrruhgw6xcuqr8hvf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBndG9XMWNpYytqWnpyeEp1
            b3VPZzB2c2lQUks5QXFVbmdmZFZWT0tKV0JFCnE3MXg4Rkt2TThPWjVBMnd1aDFU
            TExnT1hYMzl1N3FLQnVFZng4bDloQk0KLS0tIHdPdEZqWGRtMTBiRjI4anZBb2xG
            a25qTTgrVGNDalBlUHgzOVB2VytxYkEKqqha01Za2urOc2SqbnoReJDPhDkE05mw
            EAk8L++bV1vXrEI9znacUyMdAIqrgSbCoeSDauem1pkSXyy4pzoUrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T10:14:38Z"
    mac: ENC[AES256_GCM,data:M8LELRIOI9yl+6n8uYmU4ZnkBOg7xO/Gg3Dn7D6QCuyMDJQu9GzNrYYOEyL5j1KOVVY4Ef08NJAaDeRPgA0L8g/89ZAZrGbFi6yuBxnCLQbJH4n6uULRwpgNV1/+ACRqHGbENi/UngZumUoELJ2MsegOtQD778A1IaZ0wE7FLOI=,iv:CPFwFdKixTPrkNqKmU0tm6gHbxq1dQXA6ywT/nuREvw=,tag:xGMJSXpopcRBOzFVPwlWzQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
