---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: web
  namespace: forgejo
spec:
  parentRefs:
    - {namespace: gateway, name: internal, sectionName: https-wc-karlsen-fr}
    - {namespace: gateway, name: external, sectionName: https-wc-karlsen-fr}
  hostnames:
    - git.karlsen.fr
  rules:
    - matches: [path: {type: PathPrefix, value: /}]
      backendRefs: [{name: forgejo-http, kind: Service, port: 3000}]
      filters:
        - type: ResponseHeaderModifier
          responseHeaderModifier:
            add:
              # - {name: Access-Control-Allow-Origin, value: '*'}
              - {name: Content-Security-Policy, value: "default-src 'none'; script-src-elem 'self' 'unsafe-inline'; script-src-attr 'unsafe-hashes' 'sha256-Pkx60eNq3uRgXKeux8nGvnsB1ZrZmDLfK3mukOM9AuA='; style-src-elem 'self' 'unsafe-inline'; img-src 'self'; connect-src 'self'; worker-src 'self'; frame-ancestors 'none'; form-action 'none'; base-uri 'none';"}
              - {name: Strict-Transport-Security, value: 'max-age=31536000; includeSubDomains; preload'}
              - {name: X-Content-Type-Options, value: nosniff}
              # - {name: X-Frame-Options, value: DENY}
              # - {name: Cross-Origin-Resource-Policy, value: same-origin}
              # - {name: Cross-Origin-Embedder-Policy, value: require-corp}
              # - {name: Cross-Origin-Opener-Policy, value: same-origin}
              - {name: Referrer-Policy, value: no-referrer}
              - {name: Permissions-Policy, value: 'accelerometer=(), autoplay=(), camera=(), encrypted-media=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()'}
              # - {name: Integrity-Policy, value: 'blocked-destinations=(script style),sources=(inline)'}
              # - &RE {name: Reporting-Endpoints, value: ''}
