# https://artifacthub.io/packages/helm/forgejo/forgejo
# https://forgejo.io/docs/installation/helm/
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: forgejo

resources:
  - Namespace.yaml
  - SealedSecret.forgejo-appini.yaml
  - SealedSecret.forgejo-gpg.yaml
  - PersistentVolumeClaim.yaml
  - HTTPRoute.yaml
  - TCPRoute.yaml
  - SecurityPolicy.yaml

helmCharts:
  - name: forgejo
    repo: oci://code.forgejo.org/forgejo-helm
    version: 16.2.2
    releaseName: forgejo
    namespace: forgejo
    includeCRDs: true
    valuesFile: values.yaml
