---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forgejo-shared-storage-pvc
  namespace: forgejo
  labels:
    app.kubernetes.io/name: forgejo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn-static
  volumeName: forgejo-shared-storage-pv
