---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forgejo-data-pvc
  namespace: forgejo
  labels:
    app.kubernetes.io/name: forgejo
    recurring-job.longhorn.io/source: enabled
    recurring-job-group.longhorn.io/group1: enabled
spec:
  accessModes: [ReadWriteOncePod]
  resources: {requests: {storage: 10Gi}}
  storageClassName: longhorn-encrypted
  volumeName: forgejo-data-pv
