# Sealed Secrets:
# - kubeseal --controller-namespace sealed-secrets -o yaml -f Secret.forgejo-admin-secret.yaml >SealedSecret.forgejo-admin-secret.yaml
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-admin-secret
  namespace: forgejo
spec:
  encryptedData:
    password: AgBieFhf6qsYSQU86NIonqSxRuYlph9ti1aWk/VZx8AmLO13aRpXB+U5/dlvbFZjrLj8NArDjVbF2PaZhLBEjiHjhzW49wKZPNH1Yuc9Z+dUToo+GG6QuKQP3elS1keatyYWPruEtp+0k7nJmB7AIah+DA2TLRrRYUq7v+i3XmKa0CSvORIer6Gx+SikRAYVw7is+mF2QnWYUSmvsk/cQsh1vOO80t2KYg6FQ6aPrg+jXVuQQwJjBw6B+FGbJhAugEKwBnMlS4OSMoOlu0FDsidVnLCzX7kuMjfsm9w8FP5bGG41DcinWEd2AsRmiaRHphLLV9/6gusoo48xHVGS1ngjUV22JG1g8WV0X1cY8+qj9LJpHi8I9WhlSa3i3eKZabGutYeTIZTfpAkVXfSuDybicWbl2sfYkaCh14piD97DuiG4UnxjT82HwkqCucxiy3MxHSmhvPZo5BLcYvjve1PcVyt5qJnqP0uoqzO5ApJxBO0lp+xeDPCOsyZpqjEjbUWyvXUHt/eSY2sq/X7Qkhy/zI2VYgtNF5cosinJJb71Er6HXXvY483AjEu1XdPrQMqv6Jk3ocK60+lKmeWtWkhe2cmH97i0l7bhY18zz19TTLY+jA0mVKuTHEm4mw1axALndPwQXxD7rY6Yz9CVn5YXdDjaH6pI2JRgRkneTMthLUwrJ/aiJu/tJ29r2tV3efasp3jzE3dA5nK8FpxGKUrEqfWnMKQ84sybZCuhGnBLB4VfMC16DkmWFXEHxEa5ZPs=
    username: AgCJgj5oMzdFMJSiNkdPP8pV8x8SrHfzO9Fd22gj+H1TTDCbRojbY4JHVh5kNnlUBV6utc3ERpcdhqRZOZOqtDDnJoUkkqwVbdyRMlyC4Uflt8JGYUhtrdqekkrAcBf/zRu2toL3bmzGtpPiiRLf+qVpfR2LQUKB96LsaCLjyHAVgaqbeSv7EJMWSVJvzNeBwPxxV41nQkZ890JHpYMfnU2gkYWq5KW5TxavVMlyB70i5QKREq5EY8jxf0dLMzNazGKc1xmErGxIm3fwL1wCe4lUOzwCDw5euUCeWohHjiA3LRnCMg7XehDabhV3njfrSVUG+7kAn4GF31jnDCNnWPL8zlu2AmvyRWm2XgCM7DGhABEi6UAiixTdEl8J6hyqPpt0RKdMteoRSp7hINVPaX8+JRKaj8S9V5zMY2Gy0T70lbKwG+d0+weWWwtMmmUGQ51KBMWTv2QNxrx6zAsGDeOKA5svM7M23FTZenxvQFiUo3Dd9+mHh62IPYTdNHHzEtYIZA6gSKCN4y7vZkkEVXumSBywS/kFBnRVwgRvaDQr2GpTnO45uSorm3z/R9kjgb6sVe9fOX1LZ0tGQLnWe1+nUxHkXzv4TSZ1b/D02c0HMMPmWHSaMvXMu2ED7lcWzd8t0yInkB+Z7l6G9DChmrfvZSHFozuC6koTA6R3TfVHx5YDINM6vBDt0gYOXQNLOPiiGvHZsw==
  template:
    metadata:
      annotations:
        kustomize.config.k8s.io/behavior: replace
      name: forgejo-admin-secret
      namespace: forgejo
    type: Opaque
