---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authelia-secrets
  namespace: forgejo
spec:
  encryptedData:
    key: AgBDFfGKppBd8iobgqouMuzu8he6XNJjhAYADNtAsT/7aoY8YMkVvP3jqzCDPdHqPSfkRrCBvsCbNIsHMomSZAJjXthzska/giVEhoyBkGV/4bz7Sa8sIYGe5w06+k0Jtld5VGSmwyL56SXVn/UYnjkhBEAmmaArfpUb6ZuZZmW5yVMKjtO8qaZKabISLFQwtgJKhcwmWDjbfTpv+dZLzSFgp+nB3GHQ5YaR6o6woji5EUKtGqPqfKMXZv7u4qWZMqI24rakcNRi65d6Sq1zNQmBK95pt3/03b+WabEnoZkp7wyrLRPPauvxaiMAoXWISLlITddOZ0Pu65ncmbKmfy0EuGH/MP48CtgKH6uIatoTo7JgLI1j08q10xT8PdJosnTo/vi80oOz/GkoJysgJhYWMxXIsJt89Bn7k3FuLGV3O9a7TtiCEHS7XS0JmBszasKMh4qgPoHQaCDRximW1otk549btAXxcxER1PUtNa26Rrimyhrn1KxdYfSYlq91vKdG8dNnxS96RoIIvwkIm18dUvGAIuCuCYkFQGJIvOAmCEfZkOtABKI95dM73ICH6r3IkVWoy9ThxF7if7eGbt8IlXLqoS3C3uMzdsqirF00uZY10nB2nQNz82jlY88Afu0KxiRqmOwJwApiQC0xRSla8snx2ezOCkS5p6uI6AAlYTUT3gYSWTNsJ4djFZaf00M9/Sxo6SvQCK7ALQSGeVpfFX6TBt0SfeILG+7ko0d1UGzsFlMx8ryvpqTvHQcIg9x3nTIaB4xbMHeA8/9jpxfLzIZ/V8+c3bg=
  template:
    metadata:
      annotations:
        kustomize.config.k8s.io/behavior: replace
      name: authelia-secrets
      namespace: forgejo
    type: Opaque
