# yaml-language-server: $schema=
# https://artifacthub.io/packages/helm/forgejo-helm/forgejo?modal=values
# https://forgejo.org/docs/latest/admin/config-cheat-sheet
---

# Set up Valkey:
# - https://artifacthub.io/packages/helm/forgejo-helm/forgejo#session-cache-and-queue
# - https://artifacthub.io/packages/helm/forgejo-helm/forgejo#external-database

service:
  http:
    type: ClusterIP
    port: 3000
  ssh:
    type: ClusterIP
    port: 22

ingress:
  enabled: false

httproute:
  enabled: false
tcpRoute:
  enabled: false

resources:
  requests:
    # cpu: 100m
    memory: 128Mi
  limits:
    # cpu: 100m
    memory: 128Mi

persistence:
  enabled: true
  create: false
  claimName: forgejo-shared-storage-pvc

initContainers:
  resources:
    requests:
      # cpu: 100m
      memory: 128Mi
    limits:
      # cpu: 100m
      memory: 128Mi

signing:
  enabled: true
  existingSecret: forgejo-gpg

# https://forgejo.org/docs/latest/admin/config-cheat-sheet/
gitea:
  additionalConfigSources:
    - secret:
        secretName: forgejo-appini
  admin:
    username: forgejo
    password: changeme
    email: postmaster@karlsen.fr
    passwordMode: initialOnlyRequireReset
  metrics:
    enabled: true
    serviceMonitor:
      enabled: false
  # oauth: []
  config:
    # APP_NAME: 'Forgejo: Beyond coding. We forge.'
    # APP_SLOGAN
    RUN_MODE: prod
    repository:
      DEFAULT_BRANCH: master
      # ACCESS_CONTROL_ALLOW_ORIGIN
    cors:
      ENABLE: 'true'
      ALLOW_ORIGIN: 'git.karlsen.fr'
      X_FRAME_OPTIONS: DENY
    ui:
      EXPLORE_PAGING_NUM: 20
    server:
      PROTOCOL: https
      DOMAIN: git.karlsen.fr
      # ROOT_URL: https://git.karlsen.fr
      START_SSH_SERVER: 'true'
      SSH_CREATE_AUTHORIZED_KEYS_FILE: 'true'
      # https://github.com/go-gitea/gitea/issues/4196
      CERT_FILE: https/cert.pem
      CERT_KEY: https/key.pem
    database:
      DB_TYPE: mysql
      HOST: db01.hera.home.karlsen.fr
      NAME: forgejo
      USER: forgejo
    security:
      INSTALL_LOCK: 'true'
      GLOBAL_TWO_FACTOR_REQUIREMENT: all
      COOKIE_REMEMBER_NAME: __Host-forgejo_remember_token
      # COOKIE_REMEMBER_SAMESITE: strict  # Made up?
      # COOKIE_REMEMBER_SECURE: 'true'  # Made up?
      DISABLE_GIT_HOOKS: 'true'
      MIN_PASSWORD_LENGTH: 48
      PASSWORD_COMPLEXITY: lower,upper,digit
      PASSWORD_CHECK_PWN: 'true'
    service:
      REGISTER_EMAIL_CONFIRM: 'true'
      REGISTER_MANUAL_CONFIRM: 'true'
      DISABLE_REGISTRATION: 'true'
      ENABLE_NOTIFY_MAIL: 'true'
      ENABLE_INTERNAL_SIGNIN: 'true'
      DEFAULT_KEEP_EMAIL_PRIVATE: 'true'
    mailer:
      ENABLED: 'true'
    cache:
      ADAPTER: memory
    session:
      PROVIDER: db
      COOKIE_SECURE: 'true'
      COOKIE_NAME: __Host-forgejo_session
      # DOMAIN: git.karlsen.fr  # Do not use with __Host- prefix
      SAME_SITE: strict  # https://codeberg.org/forgejo/forgejo/issues/1205
