server {
    listen 8080;
    server_name vert.karlsen.app;
    client_max_body_size 128M;

    root /app;
    index index.html;

    location ~ /(\.ht|\.git|wp) {
        deny  all;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    error_page 404 /index.html;
    error_page 500 502 503 504 /50x.html;
        location = /50x.html {
        root   /usr/share/nginx/html;
    }
}

server {
    listen 8080 default_server;
    server_name _;
    deny all;
}
