---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: thanos

components:
  - ../../../common/images

patches:
  # Fix missing namespace in resources created by the helm chart
  - target:
      kind: (DaemonSet|Deployment|Service|ConfigMap|Secret|ServiceAccount|Job|PrometheusRule|ServiceMonitor)
    patch: |
      - {op: add, path: /metadata/namespace, value: thanos}

resources:
  - Namespace.yaml
  - CiliumNetworkPolicy.yaml

helmCharts:
  - name: thanos
    repo: oci://ghcr.io/thanos-community/helm-charts
    version: 0.18.0  # renovate: datasource=helm registryUrl=oci://ghcr.io/thanos-community/helm-charts depName=thanos
    releaseName: thanos
    namespace: thanos
    valuesFile: values.yaml
