---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: thanos

resources:
  - Namespace.yaml
  - CiliumNetworkPolicy.yaml

helmCharts:
  - name: thanos
    repo: oci://ghcr.io/thanos-community/helm-charts
    version: 0.11.0  # renovate: datasource=docker registryUrl=ghcr.io depName=thanos-community/helm-charts/thanos
    releaseName: thanos
    namespace: thanos
    valuesFile: values.yaml
