# yaml-language-server: $schema=https://raw.githubusercontent.com/thanos-community/helm-charts/refs/heads/master/charts/thanos/values.schema.json
# https://github.com/thanos-community/helm-charts/blob/master/charts/thanos/values.yaml
---

global:
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    seccompProfile: {type: RuntimeDefault}
  containerSecurityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    seccompProfile: {type: RuntimeDefault}
    capabilities: {drop: [ALL]}
  resources:
    requests: {memory: 128Mi}
    limits: {memory: 256Mi}

bucket: {enabled: false, bucketweb: {enabled: false}}
compactor:    {enabled: false}
queryFrontend: {enabled: false}
storegateway: {enabled: false}
receive:      {enabled: false}
ruler:        {enabled: false}
rustfs:       {enabled: false}
kube-prometheus-stack: {enabled: false}

query:
  replicaCount: 1
  replicaLabels: [prometheus_replica]
  endpoints:
    autogen: {enabled: false}
    static:
      - kube-prometheus-stack-thanos-discovery.monitoring.svc.cluster.local:10901
  serviceMonitor:
    enabled: true
