---
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: grafana
  labels:
    app.kubernetes.io/name: grafana
    app: grafana
spec:
  disableDefaultAdminSecret: true
  config:
    log:
      mode: console
    # auth:
    #   disable_login_form: "true"
    server:
      root_url: https://grafana.talmox.hera.home.karlsen.fr
    auth.generic_oauth:
      enabled: "true"
      name: Zitadel
      client_id: '358847975163817689'
      scopes: openid email profile picture
      use_pkce: "true"
      auth_url: https://karlsen-xzy0yv.zitadel.cloud/oauth/v2/authorize
      token_url: https://karlsen-xzy0yv.zitadel.cloud/oauth/v2/token
      api_url: https://karlsen-xzy0yv.zitadel.cloud/oidc/v1/userinfo
      signout_redirect_url: https://grafana.talmox.hera.home.karlsen.fr
      login_attribute_path: email
      name_attribute_path: name
      allow_assign_grafana_admin: "true"
      role_attribute_path: contains(roles[*], 'k8s_administrators') && 'Admin' || 'Viewer'
      # auto_login: "true"
  version: '12.3'
  deployment:
    spec:
      template:
        spec:
          containers:
            - name: grafana
              env:
                - name: GF_SECURITY_ADMIN_USER
                  valueFrom:
                    secretKeyRef: { key: username, name: admin-credentials }
                - name: GF_SECURITY_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef: { key: password, name: admin-credentials }
https://karlsen-xzy0yv.zitadel.cloud/oauth/v2/authorize?client_id=358847975163817689&code_challenge=IJ0fx2A51ztJWz-EPGGE_BDKnkzCJW-DWp4hpneiEaY&code_challenge_method=S256&redirect_uri=https%3A%2F%2Fgrafana.talmox.hera.home.karlsen.fr%2Flogin%2Fgeneric_oauth&response_type=code&scope=openid+email+profile&state=TQa5PR-E_KkmcGhjndHAvbf4E_HzkXQYCTv8ZidA5HY%3D