---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grafana

resources:
  - Namespace.yaml
  - HTTPRoute.yaml
  - SealedSecret.admin-credentials.yaml
  - Grafana.yaml
  - GrafanaDashboard.yaml
  - GrafanaDatasource.prometheus.yaml
  - GrafanaDatasource.alertmanager.yaml

helmCharts:
  - name: grafana-operator
    repo: oci://ghcr.io/grafana/helm-charts
    version: 5.22.2  # renovate: datasource=github-releases depName=grafana/grafana-operator
    releaseName: grafana-operator
    namespace: grafana
    includeCRDs: true
    valuesFile: values.yaml
