---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grafana

configMapGenerator:
  - {name: kubernetes-logs-dashboard, options: {disableNameSuffixHash: true}, files: [kubernetes-logs.json=assets/kubernetes-logs.json]}

resources:
  - HTTPRoute.yaml
  - SealedSecret.admin-credentials.yaml
  - SealedSecret.oidc.yaml
  - Grafana.yaml
  - GrafanaDashboard.yaml
  - GrafanaDatasource.yaml
  - CiliumNetworkPolicy.yaml
