---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oidc
  namespace: grafana
spec:
  encryptedData:
    client-secret: AgB/XfXxgTF26Le7C8IiD4SLfFZVeUR75cGLeazqrjtCm56WyT47gzTTkM/r8nbeNGHnZMG62ZxEsgw5r2thdeaEU7l0GUkgq1vEOBsa3QYJFegGftp1g2IIFEfcYd++bvT/lynPdd+4tlJHyxUTCBZiWWX7aD6v8MzLjHWbjayYzwZGPcpeGQLVx0RhsSTEhn30v4VCx3L5+yl/ybWEUhPqlTlAkdKjNJUASGxxcl3FiZJc5UVRFbN6j1qPjue1unbi+fd4goRtv3XBNY5Iiar5Aw78SLXBHz8UmGslIbxzGooiAnKE0Ir6JZbLp76WhGvQ5DBCmNeZq213kt3rUtTVtqi2a8s0CC3vLwpRaa39vKaJWkpMWlBZdsW2nPk6pDqGonRR3PB4LALqg8XYGXhb8VR4KmfTXIpMKatWvsHQlMcq74gB0Ihvz1BqypQLQUl/0TSBfI2aI91a2/WduhH8qmGNqffSGHNC5rb8CrsRGcviBdSQ6ZTceJa1I1xl0BlGJmCVX4bN26NJNq7hRyZT/hDVWoYAXDi/GbMfWT+efYlUL3xDaEgUx2mjfge77mCuvaxFE2d3okqGekJuVv1QMGPI7aPQXUDBP61KDX6tCqPXzE9xi/vdRWIriCH2YvPpZYrv7eTTae/y9oxO25HfXY5FsHKMzWlfJ7xbjwiyQjsZfSD11kUYQcKOn9OpKYDX/EuaY3PuEZffuV7K34XBCyP4XdqOuSBkfIDBTY/b99JCzCzS+KK6xfZEOvKI+p6KhjHPmVNkutxU/BI31u5KVEfddkH4ihQ=
  template:
    metadata:
      annotations:
        kustomize.config.k8s.io/behavior: replace
      name: oidc
      namespace: grafana
    type: Opaque
