# Ksops:
# - Encrypt: sops -e Secret.admin-credentials.yaml > Secret.admin-credentials.enc.yaml
# - Decrypt: sops -d Secret.admin-credentials.enc.yaml > Secret.admin-credentials.yaml
# Sealed Secrets:
# - kubeseal --controller-namespace sealed-secrets -o yaml -f Secret.admin-credentials.yaml > SealedSecret.admin-credentials.yaml
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: admin-credentials
  namespace: grafana
spec:
  template:
    type: Opaque
    metadata:
      name: admin-credentials
      namespace: grafana
      annotations:
        kustomize.config.k8s.io/behavior: replace
  encryptedData:
    password: AgDXRikz2omTopX4dR4NzALdzhijRfXzzNN36gkP/x7/jsAAvZE/NCdUJMCqXofu1/rFRrgZQYoiv/RciSmJuk7tC7r6Lr5VGF0k8d7zFVJr/8GR3JGsJFtOmIJ04G/Lu4W+c5K4fsJ0U3hTJLMMkpqc/5CzxQRL8hjlnVP08iudpyv7DteRT3oS8jScuwen74tFIcDg6o3SuoFBeAUEKmXFzQEnAS8EmJUJe6DmBPFLWG059afz4Dr9FccIp4wWYJdtGwnBHZbkW43Jkn/czW06mNJ2vU7fpg9eJgkRgsPlDbKZxV9WSk5iVkOsLL83E4xTgvcKPiwdjhx8Lr2QQ5+RAHtkSLTKIWAGj8WSTVwkMj2TPXc7u7JdKO3PkcyZaznSAZuzq7HU3/A84cYXH5mBvFPQzn5BQhafib1/tGHbrGkWoBc+uc40ZJp70VtQT4++asURRFr9JzO8CUf0xsMAFuja2BBSEiKKXJvkK70ZrL25HX2Jd/kMXcHmp7FONBb53TBMGGiH7g/hFnwQy8S4P8j7qTkn2uuDUGJ8g7Efr+GgEaj/kBgDbb9U7e2N8CGfV6oxPeAmqmywBnchGfRNgqPWmDuwbNRON+SK8VI7HnmSHabg6gA9TkNlWa0micuqTMlmEVH/3lILUkwUG13pjHpZNk9/oDyJKcaIX4TIBfklvaHQFHbtNMxpyn+FPvQdEvk7U0JVheRTDZRYCbafJ3w1lVpM4kLWCWKd2sx8YsT8rElnGXhBzegmhjF4G0o=
    username: AgCQyOXp2WCGunWUhLg1HKJG8k4MqeVxhnICwKJn3/rzS33e4bkWGsOJra7Y96ef7rvLjA64AZW7BkxRoBu1gUsWJqvh5u3ULd+jowS7rERqsz0WCsyqsoU1YhfQ2XCH7iwWj56tAi5zjZ/yA+0fFOMMlmQbcQzBDSYm7/JWLvck0MpRyN8S4UjwOnwFhEL495ykiQ42eqDhaKl4KR/4QwOify0cKvpMm9oAMtRnTjxj8iFtofsjJu83WpGPyA8xY6ko3eZ3N6Nimye7eB1ZLv1p1J3zJQtEXTKIVqP+Md6PA8n4JOoX4KLhHBiq0yqPybFzu4fMutEBwtPOixGDZHNvv9qsK3uB6lkMnUuu1GJ7GSRlG6OsQtSegQfrMoqnpiXC4v+4FFcVBFnZ/aE4KKspjFxbYCMdyWXbBgd37whVnqmi3RDdPT75+41rvM3lY4ylRgSQQsFtFWzdeig8LoSJshcnZyLuMJPe9s7gpP5FH6C2TWqO2HFq/KWNR99+udFcmJ5J+jWmoP3/lP9JLK4m186SG0Y7haQBble+rNgCnv7X6mSOV8miCh+NIEG6QGby53aQhIfSUt/Yiac8D4iBZXRaL5/15hRD2wvmoSfYc6vrtmRbLpQzcrXaysIeG7VrnuQgUjOAD0BU3A9fs+cLwd3FiDyaY2/l5cuItZtnJKSJUd3ksRav7kJDv5nBenupNb/ESg==
