#ENC[AES256_GCM,data:7jtwqAyyEDcq12ge+idB+1GDqBcTppKgJmLqyDhp3fw6YKUgtqcyTjutm9QGubhYIWxMvAq0lXbPyxty/f/pBxkV93FmQyksryvfp/n31l2boew=,iv:/6j9Qflr6LsROBHucdJDokUfPSay/i4UyOWI/0IdY/g=,tag:Dx07g+AS40yMaIQ3XFakKg==,type:comment]
#ENC[AES256_GCM,data:pQb8vrVNBVyCdbuTS2TrnMSd83XjoA60GwHcQln4nsgBClVoVw/HGJzVqzdf7OWPSJ/0LnI7OeOceMHbeApMXQw7qYD27ZHei/7I+TrQMKgePOY=,iv:mCbsKgDtD4fJPN7yQhYm7Yger43s4wHiBRpElkOEPdE=,tag:r7IdQX5tsMSS/ZcnrVI+dg==,type:comment]
apiVersion: v1
kind: Secret
metadata:
    name: admin-credentials
    namespace: grafana
    annotations:
        kustomize.config.k8s.io/behavior: replace
type: Opaque
StringData:
    username: ENC[AES256_GCM,data:ZvAYhWU=,iv:ge9Lm7pI39kVTs1gMmZU9dyNh671CEk1PD4ISfY+PJk=,tag:Wu0GtpQDIfBJki0Psh14Lw==,type:str]
    password: ENC[AES256_GCM,data:m6K4splKHPx4s/I1zfxBPRkv53X30xzMvHb87Azcrp58ZaLRLiV654kA/RpKNUIA,iv:4Xw74gBm5Rvn9nVmMqNB9XX66AW3M8chswkfg14DxBQ=,tag:CKg+9XAWQRzvyQCdjOHuXg==,type:str]
sops:
    age:
        - recipient: age1u8uutg4mpsn82nd9y828sj5agg7s89uswmp7frzpkrruhgw6xcuqr8hvf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIRWYrWUxRQUxGR2VhcjRx
            Szg3L0k4c0E2d1h0c3BoVXZUUi9BZWFBYkVjClZJVzJ5V3BxandIbCtxTHRmYUhX
            WXB3aW5HUy9lUkJhUm4vVCtOa0JVSzQKLS0tIHpsbWU1SVZUNVFONzY2YlNPczJU
            Mjk1ampxLzRiVnlTUTdscGRNeGNtcTQKIrZf+Os6o02cEuX4T4dQAhE5rJbbioXB
            z3sv/zur795Bi8we8YFISwlEVMQmDkONj9ajZS3KZT31wk/g+jKHbA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-06T14:07:26Z"
    mac: ENC[AES256_GCM,data:YWH/L/0Kx95uxClVBU/Rmc/21ZfH4B0+MeTbJ4K1OBi7GJCaGB8SkIBVuhk+2jv7KQXH4Wwt1kfLf1ZnzLtHPu8tOb7iio+z+JQZEC7Segmo+AY2uCOQ58649Gme2YqITsqkXTVnmhHGR/jIWGg62ZYPnfdXFuwi+tyGf5l9DnE=,iv:eoiuBhne00gjkINK0b6N5bYmnFrM26U6/s1ZUNahZPQ=,tag:FjyiQ6yjBkiMTxbJFg+eIw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
