# yaml-language-server: $schema=
# https://github.com/grafana/grafana-operator/blob/master/deploy/helm/grafana-operator/values.yaml
---

serviceMonitor:
  enabled: true

dashboard:
  enabled: true

resources:
  requests: {memory: 64Mi}
  limits: {memory: 64Mi, cpu: 1}
