# yaml-language-server: $schema=
# https://github.com/grafana/grafana-operator/blob/master/deploy/helm/grafana-operator/values.yaml
---

serviceMonitor:
  enabled: true

dashboard:
  enabled: true

resources:
  requests:
    # cpu: 100m
    memory: 64Mi
  limits:
    # cpu: 100m
    memory: 64Mi
