# Secret zone "e" -- name lives in secrets.sops.yaml, records are public.

resource "cloudflare_dns_record" "secret_e_caa" {
  name    = cloudflare_zone.secret_e.name
  proxied = false
  ttl     = 1
  type    = "CAA"
  zone_id = cloudflare_zone.secret_e.id
  data = {
    flags = 128
    tag   = "issue"
    value = "letsencrypt.org"
  }
}

resource "cloudflare_dns_record" "secret_e_a" {
  content = "185.134.245.113"
  name    = cloudflare_zone.secret_e.name
  proxied = false
  ttl     = 1
  type    = "A"
  zone_id = cloudflare_zone.secret_e.id
}

resource "cloudflare_dns_record" "secret_e_a_www" {
  content = "185.134.245.113"
  name    = "www"
  proxied = false
  ttl     = 1
  type    = "A"
  zone_id = cloudflare_zone.secret_e.id
}

resource "cloudflare_dns_record" "secret_e_cname_autoconfig" {
  content = var.domeneshop.autoconfig
  name    = "autoconfig"
  proxied = false
  ttl     = 1
  type    = "CNAME"
  zone_id = cloudflare_zone.secret_e.id
}

resource "cloudflare_dns_record" "secret_e_mx" {
  content  = var.domeneshop.mx
  name     = cloudflare_zone.secret_e.name
  priority = 10
  proxied  = false
  ttl      = 1
  type     = "MX"
  zone_id  = cloudflare_zone.secret_e.id
}

resource "cloudflare_dns_record" "secret_e_srv_autodiscover" {
  name     = "_autodiscover._tcp"
  priority = 0
  proxied  = false
  ttl      = 1
  type     = "SRV"
  zone_id  = cloudflare_zone.secret_e.id
  data = {
    priority = 0
    weight   = 0
    port     = 443
    target   = var.domeneshop.autoconfig
  }
}

resource "cloudflare_dns_record" "secret_e_srv_caldavs" {
  name     = "_caldavs._tcp"
  priority = 0
  proxied  = false
  ttl      = 1
  type     = "SRV"
  zone_id  = cloudflare_zone.secret_e.id
  data = {
    priority = 0
    weight   = 0
    port     = 443
    target   = var.domeneshop.caldav
  }
}

resource "cloudflare_dns_record" "secret_e_srv_carddavs" {
  name     = "_carddavs._tcp"
  priority = 0
  proxied  = false
  ttl      = 1
  type     = "SRV"
  zone_id  = cloudflare_zone.secret_e.id
  data = {
    priority = 0
    weight   = 0
    port     = 443
    target   = var.domeneshop.carddav
  }
}

resource "cloudflare_dns_record" "secret_e_txt_caldavs" {
  content = var.domeneshop.dav-path
  name    = "_caldavs._tcp"
  proxied = false
  ttl     = 1
  type    = "TXT"
  zone_id = cloudflare_zone.secret_e.id
}

resource "cloudflare_dns_record" "secret_e_txt_carddavs" {
  content = var.domeneshop.dav-path
  name    = "_carddavs._tcp"
  proxied = false
  ttl     = 1
  type    = "TXT"
  zone_id = cloudflare_zone.secret_e.id
}

resource "cloudflare_dns_record" "secret_e_txt_dmarc" {
  content = format(var.domeneshop.dmarc-rua, "mailto:${var.domeneshop.ds-rua},mailto:198308768a4741d989365a4536cb7909@dmarc-reports.cloudflare.net")
  name    = "_dmarc"
  proxied = false
  ttl     = 1
  type    = "TXT"
  zone_id = cloudflare_zone.secret_e.id
}

resource "cloudflare_dns_record" "secret_e_txt_spf" {
  content = var.domeneshop.spf-ds
  name    = cloudflare_zone.secret_e.name
  proxied = false
  ttl     = 1
  type    = "TXT"
  zone_id = cloudflare_zone.secret_e.id
}

# Generated by Domeneshop and served invisibly while they hosted the DNS -- it
# was in neither their API nor Cloudflare's import scan, so it had to be read
# out of the live zone before the delegation moved. Without it this zone would
# publish p=reject with nothing signing its mail.
resource "cloudflare_dns_record" "secret_e_txt_dkim" {
  content = "\"v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqOXj0kAh3G1SAmxTOUOpbmLfl3Z6unRPVnEUNseMsxMntE1UiE+HsuaIncbXT4vL6tsn8rIPOwMAhFS1bEhGORW8narJzLj4ObUVVl8R4ZkvW6w53fLML+70v1e6gRyDf7bUfEAepyarEX6gQi+FtkTkrMN+vQQ1qjac4U/zZvOELmgLAQU4tuFqSSwIjrW\" \"eZBGXnLEGMk9PN0sX0FJnSsW1+VzvHw2jizeghkwnLpRMMpPgiuED29xf0+Nb5Xz0HHre7j31SGq5SZp5vdR/M3gZTJjlhPmQ9VapjQBnBQRt1XONpk1W6tk29oS9DGyt/jtAapxaeYnbKPbwIxOIwwIDAQAB\""
  name    = "ds202601._domainkey"
  proxied = false
  ttl     = 1
  type    = "TXT"
  zone_id = cloudflare_zone.secret_e.id
}

# The apex record only covers the apex. Without this, a forged envelope sender
# at any subdomain gets an SPF result of "none" rather than "fail", and only
# DMARC stops it. No wildcard CNAME here to conflict with.
resource "cloudflare_dns_record" "secret_e_txt_spf_wc" {
  content = var.domeneshop.spf-ds
  name    = "*"
  proxied = false
  ttl     = 1
  type    = "TXT"
  zone_id = cloudflare_zone.secret_e.id
}
