{
  "id": "sebastian",
  "password": $ENV.LLDAP_SEBASTIAN_PASSWORD,
  "email": "sebastian@karlsen.fr",
  "displayName": "Sebastian Karlsen",
  "firstName": "Sebastian",
  "lastName": "Karlsen",
  "avatar_url": "https://www.karlsen.fr/me.jpg",
  "pictureUrl": "https://www.karlsen.fr/me.jpg",
  "groups": ["k8s_admins", "forgejo_admins"],
  "telephoneNumber": $ENV.LLDAP_SEBASTIAN_TELEPHONENUMBER,
  "streetAddress": $ENV.LLDAP_SEBASTIAN_STREETADDRESS,
  "localityName": "Trondheim",
  "stateOrProvinceName": "Norway",
  "postalCode":  $ENV.LLDAP_SEBASTIAN_POSTALCODE,
  "countryName": "NO",
  "uidNumber": 1000,
  "gidNumber": 1000,
  "timezone": "Europe/Oslo",
  "homeDirectory": "/home/sebastian",
  "loginShell": "/bin/bash",
  "sshPublicKey": ["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPez8beLkvaGA3EK61rE/EeihTlbiGJJTgPUwgBQ3wiB sebastian@boreas.local"],
  "pgpKey": ["-----BEGIN PGP PUBLIC KEY BLOCK-----\n\nmDMEaq1dgBYJKwYBBAHaRw8BAQdASA7cwfTLDThvAkjBQERRwz1NGPkvEzwHG1C6\nshzA19+0KFNlYmFzdGlhbiBLYXJsc2VuIDxzZWJhc3RpYW5Aa2FybHNlbi5mcj6I\nmQQTFgoAQRYhBAslsmxTe0C1sgjzpsdMAuZtDL7PBQJqrV2AAhsBBQkDwmcABQsJ\nCAcCAiICBhUKCQgLAgQWAgMBAh4HAheAAAoJEMdMAuZtDL7P5wwA/1vvlS1tXFI7\n2VSr6pAR2vKeenk4vbN1JMyS71I1YvXYAQC5KOeO4hRcqAdDAhfeiUtlz79VLuE8\nb3FavzloLXIxA7gzBGqtXfAWCSsGAQQB2kcPAQEHQPpwCIVNuhWrYkgMhh+H1LEO\nvSbVOBtJuDWbjpWC5XKoiPQEGBYKACYWIQQLJbJsU3tAtbII86bHTALmbQy+zwUC\naq1d8AIbAgUJAeEzgACBCRDHTALmbQy+z3YgBBkWCgAdFiEE70Q1MpVF2DHW6W+9\nNUlTFL5XHaMFAmqtXfAACgkQNUlTFL5XHaPeZAEAvWU5NUUjVLuUN0nAKDnmuWcJ\n3+UWUraq4aR9w3mM0gIA/RWGCWQjBTB1fockyEMh2WjOuadOeEwBGXQn2xkAoIwH\nRmYA/RzT5m0SdUWWCwHTHzaejJ69DTgJb5Uys9SNGS9fn4LZAPii4gmp7XWWGuJO\nt2XJkIqoL7GYEBHGO1A1lLk1d1kEuDgEaq1eABIKKwYBBAGXVQEFAQEHQNvEJiRs\nh8XAO68CAG/fY60fGCCVyr0wGOPr0nvedi4fAwEIB4h+BBgWCgAmFiEECyWybFN7\nQLWyCPOmx0wC5m0Mvs8FAmqtXgACGwwFCQHhM4AACgkQx0wC5m0Mvs+gwQEAoiRD\nov+MWhoeO+hW2tyGzJY+Xp1FvDMFW6mcPr/w6x8BANonTMayccloxq5nqfKVB3nR\neNVdVPwhknddolHSft8FuDMEaq1eChYJKwYBBAHaRw8BAQdACjE+rhyVKBbZKZim\n92VHsZYY4cX4Sjxk2SZ2/NrS2Z2IfgQYFgoAJhYhBAslsmxTe0C1sgjzpsdMAuZt\nDL7PBQJqrV4KAhsgBQkB4TOAAAoJEMdMAuZtDL7Pr94BAJT+GvkGUXN4RJoPdVfy\nUvpYRPnugzEfrxY35QXbZdtNAP94DLcIW8a15d0NFBRB+nSRhA3+krZXR5TEMFkc\nlLszCA==\n=kxJs\n-----END PGP PUBLIC KEY BLOCK-----\n"]
},
{
  "id": "sebastka",
  "password": $ENV.LLDAP_SEBASTKA_PASSWORD,
  "email": "sebastka@karlsen.fr",
  "displayName": "Sebastian Karlsen",
  "firstName": "Sebastian",
  "lastName": "Karlsen",
  "avatar_url": "https://www.karlsen.fr/me.jpg",
  "pictureUrl": "https://www.karlsen.fr/me.jpg",
  "groups": [],
  "telephoneNumber": null,
  "streetAddress": null,
  "localityName": null,
  "stateOrProvinceName": null,
  "postalCode": null,
  "countryName": null,
  "uidNumber": null,
  "gidNumber": null,
  "timezone": "Europe/Oslo",
  "homeDirectory": null,
  "loginShell": null,
  "sshPublicKey": [],
  "pgpKey": []
},
{
  "id": "melanie",
  "password": $ENV.LLDAP_MELANIE_PASSWORD,
  "email": "melanie@karlsen.fr",
  "displayName": "Mélanie Karlsen",
  "firstName": "Mélanie",
  "lastName": "Karlsen",
  "avatar_url": null,
  "pictureUrl": null,
  "groups": ["family"],
  "telephoneNumber": $ENV.LLDAP_MELANIE_TELEPHONENUMBER,
  "streetAddress": $ENV.LLDAP_MELANIE_STREETADDRESS,
  "localityName": null,
  "stateOrProvinceName": "FRANCE",
  "postalCode":  null,
  "countryName": "FR",
  "uidNumber": null,
  "gidNumber": null,
  "timezone": "Europe/Paris",
  "homeDirectory": null,
  "loginShell": null,
  "sshPublicKey": [],
  "pgpKey": []
},
{
  "id": "stork",
  "password": $ENV.LLDAP_STORK_PASSWORD,
  "email": "stork@karlsen.fr",
  "displayName": "Stork",
  "firstName": "Stork",
  "lastName": "Service",
  "avatar_url": null,
  "pictureUrl": null,
  "groups": ["lldap_strict_readonly"],
  "telephoneNumber": null,
  "streetAddress": null,
  "localityName": null,
  "stateOrProvinceName": null,
  "postalCode": null,
  "countryName": null,
  "uidNumber": null,
  "gidNumber": null,
  "timezone": null,
  "homeDirectory": null,
  "loginShell": null,
  "sshPublicKey": [],
  "pgpKey": []
},
{
  "id": "zabbix",
  "password": $ENV.LLDAP_ZABBIX_PASSWORD,
  "email": "zabbix@karlsen.fr",
  "displayName": "Zabbix",
  "firstName": "Zabbix",
  "lastName": "Service",
  "avatar_url": null,
  "pictureUrl": null,
  "groups": ["lldap_strict_readonly"],
  "telephoneNumber": null,
  "streetAddress": null,
  "localityName": null,
  "stateOrProvinceName": null,
  "postalCode": null,
  "countryName": null,
  "uidNumber": null,
  "gidNumber": null,
  "timezone": null,
  "homeDirectory": null,
  "loginShell": null,
  "sshPublicKey": [],
  "pgpKey": []
}
