---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: debian-debug

components:
  - ../../../common/default-networkpolicy

resources:
  - Namespace.yaml
  - ServiceAccount.yaml
  - Deployment.yaml
  # - PersistentVolumeClaim.yaml
  - CiliumNetworkPolicy.yaml
