---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: from-pvc
  namespace: debian-debug
spec:
  accessModes: [ReadWriteOncePod]
  resources: {requests: {storage: 1Gi}}
  storageClassName: longhorn-encrypted
  volumeMode: Filesystem
  volumeName: from-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: to-pvc
  namespace: debian-debug
spec:
  accessModes: [ReadWriteOncePod]
  resources: {requests: {storage: 1Gi}}
  storageClassName: longhorn-encrypted
  volumeMode: Filesystem
  # volumeName: to-pv  # Keep empty to automatically provision a volume
