---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-redis-secret-init-egress
  namespace: argocd
spec:
  endpointSelector: {matchLabels: {app.kubernetes.io/name: argocd-redis-secret-init}}
  egress:
    - {toEntities: [kube-apiserver]}
