---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-notifications-egress
  namespace: argocd
spec:
  endpointSelector: {matchLabels: {app.kubernetes.io/name: argocd-notifications-controller}}
  egress:
    - {toEndpoints: [{matchLabels: {k8s:io.kubernetes.pod.namespace: ntfy, app.kubernetes.io/name: ntfy}}], toPorts: [ports: [{port: '80', protocol: TCP}]]}
    - {toEntities: [kube-apiserver]}
