---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-applicationcontroller-ingress
  namespace: argocd
spec:
  endpointSelector: {matchLabels: {app.kubernetes.io/name: argocd-application-controller}}
  ingress:
    - {fromEntities: [host], toPorts: [ports: [{port: '8082', protocol: TCP}]]}  # Host probes
    - {fromEndpoints: [matchLabels: {k8s:io.kubernetes.pod.namespace: argocd, app.kubernetes.io/name: argocd-server}], toPorts: [ports: [{port: '8082', protocol: TCP}]]}
    - {fromEndpoints: [matchLabels: {k8s:io.kubernetes.pod.namespace: monitoring}], toPorts: [ports: [{port: '8082', protocol: TCP}]]}
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-applicationcontroller-egress
  namespace: argocd
spec:
  endpointSelector: {matchLabels: {app.kubernetes.io/name: argocd-application-controller}}
  egress:
    - {toEndpoints: [{matchLabels: {k8s:io.kubernetes.pod.namespace: argocd, app.kubernetes.io/name: argocd-redis}}], toPorts: [ports: [{port: '6379', protocol: TCP}]]}
    - {toEndpoints: [{matchLabels: {k8s:io.kubernetes.pod.namespace: argocd, app.kubernetes.io/name: argocd-repo-server}}], toPorts: [ports: [{port: '8081', protocol: TCP}]]}
    - {toEntities: [kube-apiserver]}
