# https://argo-cd.readthedocs.io/en/stable/getting_started/
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - Namespace.yaml
  - Service.yaml
  - GRPCRoute.yaml
  # - GrafanaDashboard.yaml
  # - service-monitors/argocd-application-controller.yaml
  # - service-monitors/argocd-applicationset-controller.yaml
  # - service-monitors/argocd-redis.yaml
  # - service-monitors/argocd-repo-server.yaml
  # - service-monitors/argocd-server.yaml
  - SealedSecret.oidc.yaml

# OIDC broken from 9.4.3?
helmCharts:
  - name: argo-cd
    repo: oci://ghcr.io/argoproj/argo-helm
    version: 9.4.10  # renovate: github-releases=argoproj/argo-helm
    releaseName: argocd
    namespace: argocd
    includeCRDs: true
    valuesFile: values.yaml
