# https://argo-cd.readthedocs.io/en/stable/getting_started/
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # - Application.yaml
  - Service.yaml
  - GRPCRoute.yaml

helmCharts:
  - name: argo-cd
    repo: oci://ghcr.io/argoproj/argo-helm/argo-cd
    version: 9.2.1
    releaseName: argocd
    namespace: argocd
    valuesFile: values.yaml
