---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oidc
  namespace: argocd
spec:
  encryptedData:
    authelia.clientSecret: AgBnoS4Ju3+fj0pDoAqzsCVNVT9MHIkhhcOgrZzccNVDHGm/ahf1J+xisOkFxkm2qNm7wXfuZBXlx7zWgRaJRvL3t2XffaPTuCrP8GOTFpxkZaEH0bvgBJ5Y1VxsqaivMrBXVbuRYClehZxBKuxhjei5yKnlU8MnKXelzZ9p+HzFDpLQpL+fMXdc5fApgkWlpFsC5QUfmFLCgSg1qNu6VO9/Vz8QJFzq0G0CkdzpTKvP5+IEhgwP+R7/E22EJyteJGKR9zjzpV7U4jjAiwtVoO900mEIc5G5El4PWM4Bh9aBixEqcu9W/nGl0Q2zgu2LHSrWF9V/8SN5xhUqYlJDWl/xfqHUYxeoazH7YWinjgViRJbv3cujmOTmTk6MDIRwKokZ0xQXMqG6hkXbHQLEQxOWo2ES8sCD3yxP55TAZsYWExwoB37oxPjhVr/cnAfVc9XeSMT1cBm6EKJma5vobNoDUZ+++yCDr1/tEVYs4fsvGxCRdaXosH4ygfgqjM06UcDKDj1lgKlsYZFZaV83o/x/oB3fx+Nlij2EeXAb8BtGoyI1OMRso5gMe6h102gXJLslXi9+AXvrv/InZ71UslDInRIvMUq4FnMxPFTP3Io0gmVkJ/tGgd3XR5PiY5Mmll56SO1O387INWDds1jNhtinXGweRDDpNA561mpwEdqg+/gnpHz3pfvSRaSOgNU3QXVkYU6jmp28J1VKUzpB1QsM8izaxsT7+ijV+rTDgQnBvEJaH7O+WrUWnAhTIixKj6CbWZy8Ba4M40JZqnWJpGpYuc73QBK6ZJU=
  template:
    metadata:
      annotations:
        kustomize.config.k8s.io/behavior: replace
      labels:
        app.kubernetes.io/part-of: argocd
      name: oidc
      namespace: argocd
