---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oidc
  namespace: argocd
spec:
  encryptedData:
    authelia.clientSecret: AgBeTYBt8sn4kdI0N5/xx5+8EI/sbU6J/kevcSnOnBOF2EtK6RSf4IuF4JODMMVMnDFGs1j4dG19tgs/nWcJ+RJryYgzej1fuD98n4EuwV9bXCwjxpGlJN1Fc6GrigVo1wpSjmQXT4i9dFp906WWQKaBN3HjaPK2NLj+HuXxTNYFb1JGNut8modosu/6+KIs/UYE/0+h3lAhUpBOZI3nkDpkuCvQPcY2XoWxYShj6KDlqZhYESjKimdbRKXv8lkZUe45T2NnxtST/J/DJQaPYF+z3g7VsVq1J2idjrxxmfmmKHY5DzmRtQEclj6GtAD4M0gscxGaqevwgoYvFecvB8Ot7FAOOlbE2iDx2JhAcZOW6ojtwRupgLoXhJKWvIN81j/4Ca1V/EzwkTVAxUHQK44iK2Mc3tQEHwvsHf9ZQkAIdnt2s+N+83J+7zl+rUCa+aL9pmKlnN0H4tpGOnnlXuep7QFSKH1iBlbbUVhD0Y8i5blNAivUNK7QjaV1TmGbhnljztqwzaYeBO8SGjE1cr6Wd9i01EICr5jLrV0SdBpSaDwnEfHGtn9G9SEhBvQxqnWuq1nie0KZYDPkeQMGvmpgrJ8Ad+rlvoG/iu3k8JYWRpJ8TeK97aDFgMDpBYcz1THdy5ruxX/gKLxAytqUQpo8M4tiHP4lNELtffixSHpuChOealkFsboJf9VlbXvcsXbZ5Zc+A42doaXoGiWHxizMYgw1vaUqO/uu9khUGxDPfKhfF25eHeq+dtqsLIFMYLPeET+RdMxe5u0txulDsxSsrNfwr2fkoPo=
  template:
    metadata:
      annotations:
        kustomize.config.k8s.io/behavior: replace
      name: oidc
      namespace: argocd
