---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oidc
  namespace: argocd
spec:
  encryptedData:
    authelia.clientSecret: AgAaTJtgtunBDLwS1Cnn3DP39GiS4p8IRnOcSyVOahmFRcU1o/de7Ap2kqvmkBNE/8KTIvNMDJouLtKHDKY3kx7B9oiQ+Mj2Hj0+ah3GnvM/m3AhKiMoh962G3SuKylWZI+rVCJmfdhTY2MHkXkV01Ygqw+QUUI2zXMxkLJtUwZHtprSYOIXWUn15R1gGbrm4eDodabDz5bVxjq0ZVt0i1ZDc3JAVmCPpGMmFm//EuNCIEBDtujGCK8rQOGZlTTM0zUhr8U7xhapaKUkWkAeg4Je+VA+8XgLhCWdtnv/CH5P6o5mEO6OhLkUcHxRehqXFJrJhKlWG29BjkomH6yqa82ZPXavaB3BmF5wY++roYFImC0kNwk4QuDX94RNb7W273mVWsZ8A3EStT8t8GbtvOuuFxExc41gb9EYFvh6atln/ReiSGCFo1CapYmleQs1En1+WNd77tOdTO+/G/GcoSna1wheQ4+Xa2S/r6ZZjxrfo6FL+01Uut+CuTDnWnwxWe4VPTgueRxlVCWyOuLbJrfDnO0ke8MR7gMW84mZ4c51WdRl07FCrt0oY//kni2Uq56JnOm0ypV6da61xLHZgzVV/aWgnltKfdY+6F77l31I/mKuEymQt1/EZJBOcken7+0uT01pG3d1IqASonEOpRlAMHxmBDSQ4+i14tZ8QNHHNljTmmkTg2mW96hpjWCJX1N3fAp2Qk4n9lr+55nxBUde5ReipWu8L5FJ2ZKyDQ/3eVAynDXabTSIKTn+6ZwmYlbkCG3EdXSbOYzIJA6kH38/ZfN/iMHO3nQ=
  template:
    metadata:
      annotations:
        kustomize.config.k8s.io/behavior: replace
      name: oidc
      namespace: argocd
