---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
spec:
  encryptedData:
    ntfy-token: AgBp9kuzoL3b+4ZOU0gGQJ/9CgjIUpLHbS96qjJelXfAzp+WPjjUDAsaC9Yj3J/DOZSNEjRb6UGE1BXFebWcMqs0TJ9suAUnStW8RlvJx4+r1SlybpOe2OYk8HH5Wz3ltFOx/WddG+D8JWQm7dYmYiQ2Hy64X1hGn4Smbj3QXAYv9UzRDgvFjdty/6uLyxOaySpxInTpMZsGAku9L3t6ROhdew7RdYQBezCRavB9ksb5HZdQJ6qSo5JlzsHI5KUsezxSdk5ZAkr63K2NY7JuMSjIzY+1KO63v4TICers8wgA2CWLmy/2Cb3o7cr/zoa/C7iDxy9YzC1tHMkn5A3vv8a/2asem6OUnNkG1jgLAv6Lv+tf6DeVxE1/sFoQlRVDbZ/Kdp+czWHQH9xzV3KNjWNNVXL4CzSasXD33+tcqpLXrfNzV7nIO0qgUT5frGUbcIH4hQd65SyC6O1UcfVoZ8ekK+IVZYT/HIWXXLQ/vQ9bvPCEd+ySUtWLu9aFPygw7+Tl/UTfm73yk3afY7Ry1H+McK4GggCRnRLHqAXRIeb4cmqKZelQjB0zLlpLgf6GuhexI3ua+ZVmVJ7aSSNPHYSliwbE+7y0/EQljAMz9O8np7+jDGFdFpz+vUK+dGVzUWS/B/dg7pwvb30EfVSW2wBbEB3pS2S4A+yF+uj200IY76oSTCmwhpRgog0FrHW5LjMIpBZN9LDY3xBYfiMe1keiZq3h+8JNnW6tFrnT8Txhzoh5TS28+B0=
  template:
    metadata:
      annotations:
        kustomize.config.k8s.io/behavior: replace
      labels:
        app.kubernetes.io/name: argocd-notifications-secret
        app.kubernetes.io/part-of: argocd
      name: argocd-notifications-secret
      namespace: argocd
