---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
  namespace: whoami
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: whoami
  template:
    metadata:
      namespace: whoami
      labels:
        app.kubernetes.io/name: whoami
        app.kubernetes.io/version: v1
    spec:
      serviceAccountName: whoami
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: {type: RuntimeDefault}
      containers:
        - name: whoami
          # Dockerfile: https://github.com/traefik/whoami/blob/master/Dockerfile
          image: ghcr.io/traefik/whoami:v1.11.0
          args: ['-port=8080']
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: {drop: [ALL]}
          resources:
            requests: {memory: 12Mi}
            limits: {memory: 12Mi}
          ports:
            - {name: http, containerPort: 8080}
