---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: harbor-db
  namespace: cnpg-database
spec:
  instances: 1
  postgresql: {parameters: {timezone: Europe/Oslo}}
  bootstrap:
    initdb:
      database: harbor-core
      owner: harbor
      secret: {name: harbor-db-credentials}
  managed: {services: {disabledDefaultServices: [ro, r]}}
  storage:
    size: 5Gi
    pvcTemplate:
      accessModes: [ReadWriteOncePod]
      storageClassName: longhorn-encrypted
      volumeMode: Filesystem
      volumeName: harbor-db-pv
