# https://artifacthub.io/packages/helm/harbor/harbor
# https://harbor.io/docs/installation/helm/
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: harbor

resources:
  - Namespace.yaml
  - SealedSecret.harbor-db-credentials.yaml
  - SealedSecret.harbor-secrets.yaml
  - Cluster.harbor-db.yaml
  - PersistentVolumeClaim.yaml
  - ServiceAccount.yaml
  - Deployment.valkey.yaml
  - Services.yaml
  - HTTPRoute.yaml

helmCharts:
  - name: harbor
    repo: https://helm.goharbor.io
    version: 1.18.3  # renovate: github-releases=goharbor/harbor-helm
    releaseName: harbor
    namespace: harbor
    includeCRDs: true
    valuesFile: values.yaml
