# https://artifacthub.io/packages/helm/harbor/harbor
# https://harbor.io/docs/installation/helm/
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: harbor

components:
  - ../../../common/valkey

patches:
  - target: {kind: CiliumNetworkPolicy, name: allow-valkey-ingress}
    patch: |
      - {op: replace, path: /spec/ingress/0/fromEndpoints/0/matchLabels/app.kubernetes.io~1name, value: harbor}
      - {op: replace, path: /spec/ingress/0/fromEndpoints/0/matchLabels/k8s:io.kubernetes.pod.namespace, value: harbor}

resources:
  - Namespace.yaml
  - SealedSecret.harbor-secrets.yaml
  - PersistentVolumeClaim.yaml
  - HTTPRoute.yaml

helmCharts:
  - name: harbor
    repo: https://helm.goharbor.io
    version: 1.19.0  # renovate: datasource=github-releases depName=goharbor/harbor-helm
    releaseName: harbor
    namespace: harbor
    includeCRDs: true
    valuesFile: values.yaml
