# https://artifacthub.io/packages/helm/harbor/harbor
# https://harbor.io/docs/installation/helm/
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: harbor

components:
  - ../../../common/images
  - ../../../common/valkey

resources:
  - Namespace.yaml
  - SealedSecret.harbor-secrets.yaml
  - PersistentVolumeClaim.yaml
  - HTTPRoute.yaml
  - CiliumNetworkPolicy.yaml

helmCharts:
  - name: harbor
    repo: https://helm.goharbor.io
    version: 1.19.1  # renovate: datasource=helm registryUrl=https://helm.goharbor.io depName=harbor
    releaseName: harbor
    namespace: harbor
    includeCRDs: true
    valuesFile: values.yaml
