# Seal secret:
# - kubeseal --controller-namespace sealed-secrets -o yaml -f Secret.harbor-db-credentials.yaml >SealedSecret.harbor-db-credentials.yaml
# - kubeseal --cert "$(dirname "$(readlink -f "$TALOSCONFIG")")/seal.crt" -o yaml -f Secret.harbor-db-credentials.yaml >SealedSecret.harbor-db-credentials.yaml
# Unseal secret
# - kubeseal --cert "$(dirname "$(readlink -f "$TALOSCONFIG")")/seal.crt" --recovery-unseal --recovery-private-key "$(dirname "$(readlink -f "$TALOSCONFIG")")/seal.key" -o yaml -f SealedSecret.harbor-db-credentials.yaml
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-db-credentials
  namespace: cnpg-database
spec:
  encryptedData:
    password: AgCtIoLOVnTCnWsM9vgsNkqHZ7Crow5p/0a0+YGdB4wRgaI21ytSeSDKcTrIv0RBSwzjnX1h1hGty5t5PYgw9Tc0d2kgTxUF4Ukxdh2ZmIqt1/uaiUeBWd/+KUJXKaRqgD50I150cVXSPMJyRB77w95NHTpdlqopR7Cx9bEqY9GzBhvgi8lMRACe7FxmttBSUbNC++pcAnsmO7whK99CsLWlDvcXYhNkw0Sn8I03no+yVnT0RIgq/sdZdqPfRPBC671Y6kOL1SW8ON4DlAD6s+x09KR4jIPm31YcrZWoFLSp3k9OQiZcUW+G8CSNIoAVqPLEGuV06inMaSHrTlclRgZ8hECSnQhFdDWXxWwvvWoo+dgxDYM11VZRsSrB8cb2tEn9L8fY7zPYmqTxxeP8sHkRiM/IlNIMfH/j8vy6nFng2c0zmwjZbjM90/o3mvgr+WaeO88rpvJbT/R7eY5IN6YV9MMm4vUmEz83lfF+gsW1mD3hdcq+RQhvho6IAvQNxgYAQS5aNme+V6vRbwigm/SrDW4qg8jeEjBEJX4Is5TcAIxyRg/NbJ+c+3kTiXHlNMY5pZxNDdtUC+GjarJbZ32Izgw+q5QUM4Rps47EhgBdvgzw+jgdl+P4twtu8SpFqTLYN6X6drBLXM6yq9DcKL3TLG2OO1DEdapmpwCmobC1YQMcL3x3Mfs99h9kWaHnal1TY2q4nSRl/46voCg2G0GWh1uXRmWLczDKsfswq1smoLcDixjwJ3a1YGTizjf8zvU=
    username: AgBt48sBx5BRWNV26WRl0YKVXONnkhycfViyBj5jsWTzQJTpAtSBxwrVHxJPO2PGzz/9cRb2DwIzHuWRFr18d4zl565WgNM1Iij9Ht78dNyfwF9RtUQmfIF9MXtqHn7w8F0dE6x3iztvk7U3ZsuOmdVjPDcG5CjzjkPQFKaTBpzVl8EBo5MAlPd1u49taVl+2IypNARwOHDnNeR6clmo5rUFbmx4XYzAfr3wQgkRs7CBbTUeIXLouJJ7CiLrvFWa3CVda+4F5VUhgIIW8649kHOTxEKzUnSWJMzi0cSLZyKEnmkbO97bloFoXVYOd3++zn5HEfY3LIuBTDp/4hnhpfrZkigSCbEf07Xso3E36wJJbH7DQxoiIOBSrDn+7F9ntdq+cIDaisopLMp+EfRnF+hC27NZl2UhN/LBs/j7rrbAgqge2pPEbio301pXo28FlQh51p+Shm+fciiwf5ju4QH/zw2VBCu2+YOihMB661jZi9OF4v2gTf22or3aJMEf6n2PfpyFK5pQqupouEdKIauY3PSHRT9VwrymYMO6+M+1OgfQEiLaaUhfrHr9FOuohJ7qcYCa6dfEPagjr6ppCfnEyWl0nqzTVLRafyRFHxzjqRWalfK7dwoMYIUjii+Sg9mjPIGkp5fjfWdPzPMFUtErFFcHrMOUxL/MC9M1Qazx/xMbjwNL4b5+hauXjQ44u464sKO1vCI=
  template:
    metadata:
      annotations:
        kustomize.config.k8s.io/behavior: replace
      name: harbor-db-credentials
      namespace: cnpg-database
    type: kubernetes.io/basic-auth
