---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vertd-secrets
  namespace: vert
spec:
  encryptedData:
    ADMIN_PASSWORD: AgBtkMPBc6PNFbTLdBnZlbTzcL0LUvwLTudItGNMfsW/ZzqdBPK08jCGyw9zw4ySW7gUGfgSZChL9s71a8r9nPJ0l2nWkdXHtemZpeaBcG81vD9dm4liFEsdD4/CUf7pLt4YlUSinNkJ6Ckj9hNHrme28tTnwLkxBXT7cD+gie1UIepWnsyUl5KaYmZPfTdYZ8GgQJjirbw718VGzXSZQ81TKtxQ/3xF4voOR+g+drDmX2AeR2zYk9fNf2NJTTU4UFW/r4iIA4tFtGEWl7ImujfgWUeOZIILEdNTJjFAKrgUAIkfom2Vs4qaQ5IdTIhG0BYnkGzrKFyJJCf2LoF3bNk6QCL9Wi6HLsm2UWXiC1X9ANnfmL/6jV1vr8Q0js0h+Cwp8h3YtxLOl8u2fnF+tkfuNBukCHhUS+6c+DVLzPf2vVwQIz3f/RMyqfEVlfGFPk7AaqM/2QfgXe8JZSYKw8y6VlLMJ3ARSeNh4AkAMS11d7OU/wSgeKYwd/WWu95TEJGbGO46dWDqf0RPqyCPNrxyIaKWtyEEMQCD5Nv4ai4dP6jNwvX2udq3aS6GVqb3CJiNR5b8kfVdYU8OSa6diVK4LTFPpEzSAgJZN9d6hUIRD2y5a8eXCsFmYipfh9H9YDFiYNyiLj7tK9Q/0my8EOL9Lp0v7uxNq0TZk4aSS9w9/4ZOdk5z268LG3Eamohinx2gGtpC+i6Q3ozHiL56Yn0ohSmr7wJlgC4DS8s7RvHQQEfklqPZiFG0wBP7Hoh005A=
  template:
    metadata:
      annotations:
        kustomize.config.k8s.io/behavior: replace
      name: vertd-secrets
      namespace: vert
    type: Opaque
