---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oidc
  namespace: vert
spec:
  encryptedData:
    client-secret: AgCDUzBujMmi1FhZEIXkb5X6HfSQDPvcrfnCtdzkvbsZmcM5rmMloTc7DLbA5tq6yYEnPr6J/3bvJrb8srfPPJmV+sC64IYOeGR76U2GMn2aybjrym1mOAAYZvi/Bs74TNdfcEF1d/STTSsUFhVmlJuaIeUjZqTyYlGB+qWAGX+muvywW2xlwpQNzs6JF6VGU93ZUPuRpLEk28XGuGaAiwRGpjjBG8rUlPmuvneccHTabsKbvmGraWIqBAY2KQKIBkkQQGSQer44sMGj3fB7ZszrkSxUM3BCf43KITcEMJ793GTW7VpCzl0JLPSI7kwLk6InIV0IzvBkV1dq+b6+adPsmUeN4ZoVvHqCvk9sbhRsqmSE1W5mtihAfPS08QSzbY0/0oId92+bj96IDyB/Nrh4PKcs/j9yHdD8+ssqLFfZRO79TKtlvCSIsx20mckrc+La8t8BYwJ+4jZxv/OC76KOgyeCfWpY2sCD4ZKIp4bjDKlx7vqDXjFCWlyoGW1sxMG9MYVndeR5/Hll/Pg+TTugAdg4hBYq391nxuTFT6hO6xFym5x3E+Rmzj12yDPiQp5FYhmj6QD/EI0sppRM7cdiF/mBQFCCcOJD/PZMz1VFp8PR0e/wObBbAiPzPE+8DPk/WJiUThju5A/H9/wuRKOOlhWUkDiyWzjAg6AO0YFelJ68vc3oEhcQc7mqDo1fLns1HCoAm2a+DWxQ1p25Q3wjOCSEI0DAUb41P3+Lb1IOf9s2wWJsAwihtS5xfvnOWIVDVtJqDao63dIOJ05s6MSEqNmk0WnYa0w=
  template:
    metadata:
      annotations:
        kustomize.config.k8s.io/behavior: replace
      name: oidc
      namespace: vert
    type: Opaque
