---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oidc
  namespace: vert
spec:
  encryptedData:
    client-id: AgCUAJEWIi+m/HH4BBgICtDs6JrLBeicz+iXInxYAF68uUHCP2lrBOWHOi5n6NyKiKt77/mlFQu8jIhK3P/L09+npDxAcZybPbS/rkXPhrFp92xJDOPtzu4YPSksiXDbkQqm45/phgKQ60IWtRJB2a6zJDqLNlFPtRY+HgkhT/NldKV0S3d41WyeGf8dvhom8GsFAD6+weob8/D15WxfN5E9nml/2R4SBWgZ4JmhGrVW02yf5x97nd7OK8fEiN1ewqvyG4sg238zX/aFwJOWGHzpv3QGPa2iwIn+MH7qV7lzT/043duCSMJMVkQwy/7oKCKIofDN0bmD0ZODKn6+ZCKp5DSd73UEsPOMtifQjIqAdo6sO1aZe+4FixLR7Yyy89bX8GmqunmmvYmLMnSxvhbVQTKuBNnZ5HdOWER9/qX9CpqHpEFK4LPXb14w4clwjzegiyMMg7cS4jo1R4NKHOeMIVbRui/VNg/paxhfyDSj5m5gslDsT3jfl/BmhZ6WWcg7g/dqLbJv1clUkdHTazZZkh5crVI9lVj9wdmAhew1xgGrBGOwO8n2drHcpSgrR8tb+XnbLdfIcLXz48WhKlRulFzLAMq14COWlw3o3U0xEmYE84f7AXFr2YLOaIsP3vqCM5SwFDcdZKFgjLVZ0ctns2ANaBcI77c+XAT0D0jI7RTY2Ce43euRw9u0Z8pirjvi3qnW6T+PkVM0MKrjW41D9SQ=
    client-secret: AgB6Kf2ZMREDbtinFojkao1qbjvGG3CnCm+Gs/ChqXDQDUGOyPs7bdBiUE1pepAe71kUpFzgTedt5WOvUnY3RORxP+Unv3YOVIAo5fMZaR+8PkG+W9BNjlWjYypNCtbSqRmHDMTPZU6Sy8VVMvxBcqxTNoa5qSWnbSxvx82gS0+YTotFBNyMBqQZDeXwCe9SAyxCzPHi+SAGbWDimLvgjHZEPBjFEBX1jGhYA6rRWwskAqoUfPXsWUH35Srfp/QAx8nRNJ0iHqllHlYoRw1TGU79z60f1DRT/ihl653r++1jKfKPHXnZjBxR3FVzD4MX4VGAon2FUSbu/2q4prSZiQXPf2aTyvTUZxfou04AnrufKgvsMAuGYq2YPJlX1SlelYa1anqAjysJGizCaID3m1oCnFc5AFQiXgP9gWD1rIWuQWvMNyC6awGeNZG4ICd1c4xApU6H13MzV7TgcUYGZApovahAFfVtFNkaC/ghbg4pjhAsMEsprXQBoY0jXcEAc0YwVtxL65eNu8S+UtVF7Oxl+pz68rxYedbPuFSDMIujyrCzr93VzhhejEXgyF/0WbwUHZa6+Ey1XdnlilAoFymoz64lg6zEiMFpL4GCj5xd7CGuWaeesZyFzTtcSpjUH7iF3dg/NHI8192nRvoZEsUM3zSZ78LZwKMY5Zi8wYzjPlV40NamGZKXibX+d4IxK/ENUcBstA3uQ1PdNHIGeAsbD/cVxkhzmRtmM560J+HWr0GPNuRRZcYzY6M2zCbVo4XHC/0Z+n7wFz2LpRUYiqBV
  template:
    metadata:
      annotations:
        kustomize.config.k8s.io/behavior: replace
      name: oidc
      namespace: vert
    type: Opaque
