# yaml-language-server: $schema=https://raw.githubusercontent.com/crowdsecurity/helm-charts/refs/heads/main/charts/crowdsec/values.schema.json
# https://github.com/crowdsecurity/helm-charts/blob/main/charts/crowdsec/values.yaml
# https://docs.crowdsec.net/u/getting_started/installation/kubernetes/
# https://docs.crowdsec.net/docs/next/configuration/values_parameters/
# https://docs.crowdsec.net/u/bouncers/envoy/
# https://docs.crowdsec.net/docs/next/appsec/quickstart/envoy-gateway
---

container_runtime: containerd

agent:
  hostVarLog: false
  lapiURL: http://crowdsec-service.crowdsec.svc.cluster.local:8080
  podSecurityContext:
  #   runAsNonRoot: true
  #   runAsUser: 1000
  #   runAsGroup: 1000
  #   fsGroup: 1000
  #   fsGroupChangePolicy: Always
    seccompProfile: {type: RuntimeDefault}
  securityContext:
    # allowPrivilegeEscalation: false
    # readOnlyRootFilesystem: true
    capabilities: {drop: [ALL]}
  wait_for_lapi:
    securityContext:
      capabilities: {drop: [ALL]}
  persistentVolume:
    config: {existingClaim: crowdsec-data-pvc, subPath: agent-config}
    resources:
      requests: {memory: 64Mi}
      limits: {memory: 256Mi}
  acquisition:
    - {namespace: envoy-gateway-system, podName: 'envoy-gateway-default-*', poll_without_inotify: true, program: envoy}
    # - {namespace: nextcloud, podName: 'nextcloud-*', program: nextcloud}
    - {namespace: forgejo, podName: 'forgejo-*', program: forgejo}
    - {namespace: authelia, podName: 'authelia-*', program: authelia}
    - {namespace: synapse, podName: 'synapse-*', program: synapse}
    - {namespace: matrix-authentication-service, podName: 'mas-*', program: http}
  metrics:
    enabled: true
    serviceMonitor: {enabled: true}
  env:
    - {name: COLLECTIONS, value: yanis-kouidri/envoy crowdsecurity/nextcloud}
    - {name: DEBUG, value: 'false'}

lapi:
  podSecurityContext:
    # runAsNonRoot: true
    # runAsUser: 1000
    # runAsGroup: 1000
    # fsGroup: 1000
    # fsGroupChangePolicy: Always
    seccompProfile: {type: RuntimeDefault}
  securityContext:
    allowPrivilegeEscalation: false
    # readOnlyRootFilesystem: true
    capabilities: {drop: [ALL], add: [DAC_OVERRIDE, SETGID, SETUID]}
  persistentVolume:
    data: {existingClaim: crowdsec-data-pvc, subPath: lapi-data}
    config: {existingClaim: crowdsec-data-pvc, subPath: lapi-config}
    resources:
      requests: {memory: 64Mi}
      limits: {memory: 256Mi}
  env:
    # - {name: ENROLL_KEY, valueFrom: {secretKeyRef: {name: crowdsec-secrets, key: ENROLL_KEY}}}  # Covered by envFrom below
    - {name: ENROLL_INSTANCE_NAME, value: talmox}
    - {name: ENROLL_TAGS, value: k8s talos homelab}
    # - {name: BOUNCER_KEY_envoy_XXX, valueFrom: {secretKeyRef: {name: crowdsec-secrets, key: BOUNCER_KEY_envoy_XXX}}}  # Covered by envFrom below
  metrics:
    enabled: true
    serviceMonitor: {enabled: true}
  envFrom:
    - secretRef: {name: crowdsec-secrets}

appsec:
  enabled: true
  podSecurityContext:
    # runAsNonRoot: true
    # runAsUser: 1000
    # runAsGroup: 1000
    # fsGroup: 1000
    # fsGroupChangePolicy: OnRootMismatch
    seccompProfile: {type: RuntimeDefault}
  securityContext:
    allowPrivilegeEscalation: false
    # readOnlyRootFilesystem: true
    capabilities: {drop: [ALL]}
  resources:
    requests: {memory: 64Mi}
    limits: {memory: 256Mi}
  acquisitions:
    - appsec_configs: [crowdsecurity/appsec-default]
      labels: {type: appsec}
      listen_addr: 0.0.0.0:7422
      path: /
      source: appsec
  metrics:
    enabled: true
    serviceMonitor: {enabled: true}
  env:
    - {name: COLLECTIONS, value: crowdsecurity/appsec-virtual-patching crowdsecurity/appsec-generic-rules}
    - {name: CUSTOM_HOSTNAME, value: talmox-appsec}

config:
  profiles.yaml: |
    name: default_ip_remediation
    filters:
      - Alert.Remediation == true && Alert.GetScope() == "Ip"
    decisions:
      - type: ban
        duration: 4h
    notifications:
      - http_default
    on_success: break
    ---
    name: default_range_remediation
    filters:
      - Alert.Remediation == true && Alert.GetScope() == "Range"
    decisions:
      - type: ban
        duration: 4h
    notifications:
      - http_default
    on_success: break

  notifications:
    http.yaml: |
      type: http
      name: http_default
      log_level: info
      format: >
        {{- range $Alert := . -}}
        {{- range .Decisions -}}
        {"metric":{"__name__":"cs_lapi_decision","instance":"talmox","country":"{{$Alert.Source.Cn}}","asname":"{{$Alert.Source.AsName}}","asnumber":"{{$Alert.Source.AsNumber}}","latitude":"{{$Alert.Source.Latitude}}","longitude":"{{$Alert.Source.Longitude}}","iprange":"{{$Alert.Source.Range}}","scenario":"{{.Scenario}}","type":"{{.Type}}","duration":"{{.Duration}}","scope":"{{.Scope}}","ip":"{{.Value}}"},"values":[1],"timestamps":[{{now|unixEpoch}}000]}
        {{- end }}
        {{- end -}}
      url: http://vmsingle-victoria-metrics-k8s-stack.monitoring.svc.cluster.local:8428/api/v1/import
      method: POST
      headers:
        Content-Type: application/json

  config.yaml.local: |
    api:
      client:
        unregister_on_exit: true
      server:
        auto_registration: # Activate if not using TLS for authentication
          enabled: true
          token: "${REGISTRATION_TOKEN}"  # Auto-generated and handled by the chart
          allowed_ranges: ['10.244.0.0/16']  # Pod CIDR

    # https://docs.crowdsec.net/docs/configuration/crowdsec_configuration/#configuration-directives
    db_config:
      type: postgresql
      user: crowdsec
      password: ${DB_PASSWORD}
      db_name: crowdsec
      host: db02.hera.home.karlsen.fr
      port: 5432
      sslmode: disable
      # max_open_conns
      flush: {bouncers_autodelete: {api_key: 6h}, agents_autodelete: {login_password: 6h, cert: 6h}}
