---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - CiliumLoadBalancerIPPool.yaml
  - SealedSecret.cilium-ca.yaml

helmCharts:
  - name: cilium
    repo: oci://quay.io/cilium/charts
    version: 1.19.4  # renovate: datasource=helm registryUrl=oci://quay.io/cilium/charts depName=cilium
    releaseName: cilium
    namespace: kube-system
    includeCRDs: true
    valuesFile: ../../base/values.yaml
    valuesInline:
      cluster: {id: 2, name: hyades}
      ipv4NativeRoutingCIDR: 10.245.0.0/16  # Pod CIDR
      encryption:
        strictMode:
          egress:
            cidr: 10.244.0.0/15  # Covers pod CIDR for both talmox and hyades
      clustermesh:
        apiserver:
          tls:
            server:
              extraIPs: [192.168.3.100]
          service:
            labels: {arp.cilium.io/ip-pool: default-arp-ip-pool, arp.cilium.io/announce-service: default-arp-l2-announcement-policy}
            annotations: {lbipam.cilium.io/ips: 192.168.3.100}
        ui:
          enabled: false
