---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - CiliumLoadBalancerIPPool.yaml
  # - SealedSecret.cilium-ca.yaml

patches:
  - target: {kind: Namespace, name: cilium-spire}
    patch: |
      apiVersion: v1
      kind: Namespace
      metadata:
        name: cilium-spire
        labels:
          pod-security.kubernetes.io/enforce: privileged
          pod-security.kubernetes.io/enforce-version: latest
          pod-security.kubernetes.io/audit: privileged
          pod-security.kubernetes.io/audit-version: latest
          pod-security.kubernetes.io/warn: privileged
          pod-security.kubernetes.io/warn-version: latest

helmCharts:
  - name: cilium
    repo: oci://quay.io/cilium/charts
    version: 1.19.4  # renovate: datasource=helm registryUrl=oci://quay.io/cilium/charts depName=cilium
    releaseName: cilium
    namespace: kube-system
    includeCRDs: true
    valuesFile: ../../base/values.yaml
    valuesInline:
      cluster: {id: 2, name: hyades}
      ipv4NativeRoutingCIDR: 10.245.0.0/16  # Pod CIDR
      encryption:
        strictMode:
          egress:
            cidr: 10.244.0.0/15  # Covers pod CIDR for both talmox and hyades
