---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deluge-web
  namespace: deluge
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  strategy: {type: Recreate}
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: deluge-web
      app.kubernetes.io/version: stable
      app.kubernetes.io/component: client
      app.kubernetes.io/part-of: deluge
      # app.kubernetes.io/managed-by: kustomize
  template:
    metadata:
      namespace: deluge
      labels:
        app.kubernetes.io/name: deluge-web
        app.kubernetes.io/version: stable
        app.kubernetes.io/component: client
        app.kubernetes.io/part-of: deluge
        # app.kubernetes.io/managed-by: kustomize
    spec:
      serviceAccountName: deluge-web
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: {type: RuntimeDefault}
      initContainers:
        - name: deluge-web-init
          # Dockerfile: https://github.com/home-operations/containers/blob/main/apps/deluge/Dockerfile
          image: ghcr.io/home-operations/deluge:2.2.0
          command: ['/bin/sh', '-c']
          args:
            - |
              set -eu

              # Clean up volumes
              for d in config; do [ ! -d "/$d" ] || { rm -rf "/$d"/* "/$d"/.[!.]*; }; done

              mkdir -p /config/plugins/.python-eggs

              # Generate web.conf for deluge-web interface configuration
              jq -n \
                --arg DELUGE_WEB_PASSWORD_SALT "$DELUGE_WEB_PASSWORD_SALT" \
                --arg DELUGE_WEB_PASSWORD_SHA1 "$DELUGE_WEB_PASSWORD_SHA1" \
                '{
                  file: 2,
                  format: 1
                }, {
                  base: "/",
                  https: false,
                  cert: "ssl/daemon.cert",
                  pkey: "ssl/daemon.pkey",
                  default_daemon: "",
                  enabled_plugins: [],
                  first_login: false,
                  interface: "0.0.0.0",
                  language: "",
                  port: 8112,
                  pwd_salt: $DELUGE_WEB_PASSWORD_SALT,
                  pwd_sha1: $DELUGE_WEB_PASSWORD_SHA1,
                  session_timeout: 3600,
                  sessions: {},
                  show_session_speed: true,
                  show_sidebar: true,
                  sidebar_multiple_filters: true,
                  sidebar_show_zero: true,
                  theme: "gray"
                }' \
                >/config/web.conf

              # Generate hostlist.conf for deluge-web to connect to deluged
              jq -n \
                --arg DELUGED_USERNAME "$DELUGED_USERNAME" \
                --arg DELUGED_PASSWORD "$DELUGED_PASSWORD" \
                '{
                  file: 3,
                  format: 1
                },{
                  hosts: [
                    [
                      "60fd37b1be6940388eae58b4628680c2",
                      "daemon",
                      58846,
                      $DELUGED_USERNAME,
                      $DELUGED_PASSWORD
                    ]
                  ]
                }' \
                >/config/hostlist.conf
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: {drop: [ALL]}
          resources:
            requests: {memory: 24Mi}
            limits: {memory: 24Mi}
          envFrom:
            - secretRef: {name: deluge-credentials}
          volumeMounts:
            - {name: deluge-web-config-volume, mountPath: /config}
      containers:
        - name: deluge-web
          # Dockerfile: https://github.com/home-operations/containers/blob/main/apps/deluge/Dockerfile
          image: ghcr.io/home-operations/deluge:2.2.0
          command:
            - /usr/bin/deluge-web
            - --config=/config
            - --loglevel=info
            - --pidfile=/tmp/deluge-web.pid
            - --do-not-daemonize
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: {drop: [ALL]}
          resources:
            requests: {memory: 128Mi}
            limits: {memory: 128Mi}
          ports:
            - {name: http, containerPort: 8112}
          startupProbe: {httpGet: {port: 8112, path: /}, initialDelaySeconds: 2, periodSeconds: 10, failureThreshold: 3}
          livenessProbe: {httpGet: {port: 8112, path: /}, initialDelaySeconds: 10, periodSeconds: 120}
          readinessProbe: {httpGet: {port: 8112, path: /}, initialDelaySeconds: 10, periodSeconds: 120}
          env:
            - {name: TZ, value: Europe/Oslo}
            # - {name: DELUGE_BIN, value: deluge-web}
          volumeMounts:
            - {name: deluge-web-config-volume, mountPath: /config}
            - {name: tmp-volume, mountPath: /tmp}
      volumes:
        - {name: deluge-web-config-volume, emptyDir: {}}
        - {name: tmp-volume, emptyDir: {}}
