---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deluge-web
  namespace: deluge
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: deluge-web
      app.kubernetes.io/version: '2.2.0'
      app.kubernetes.io/component: client
      app.kubernetes.io/part-of: deluge
      # app.kubernetes.io/managed-by: kustomize
  template:
    metadata:
      namespace: deluge
      labels:
        app.kubernetes.io/name: deluge-web
        app.kubernetes.io/version: '2.2.0'
        app.kubernetes.io/component: client
        app.kubernetes.io/part-of: deluge
        # app.kubernetes.io/managed-by: kustomize
    spec:
      serviceAccountName: deluge-web
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: {type: RuntimeDefault}
      initContainers:
        - name: deluge-web-init
          # Dockerfile: https://github.com/home-operations/containers/blob/main/apps/deluge/Dockerfile
          image: ghcr.io/home-operations/deluge:2.2.0
          imagePullPolicy: Always
          command: ['/bin/sh', '-c']
          args:
            - |
              set -eu
              jq -n "{ file: 3, format: 1 }, {hosts: [[ \"60fd37b1be6940388eae58b4628680c2\", \"daemon\", 58846, \"$DELUGE_USERNAME\", \"$DELUGE_PASSWORD\"]]}" \
                >/config/hostlist.conf
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: {drop: [ALL]}
          resources:
            requests: {memory: 24Mi}
            limits: {memory: 24Mi}
          envFrom:
            - secretRef: {name: deluge-credentials}
          volumeMounts:
            - {name: deluge-web-config-volume, mountPath: /config}
      containers:
        - name: deluge-web
          # Dockerfile: https://github.com/home-operations/containers/blob/main/apps/deluge/Dockerfile
          image: ghcr.io/home-operations/deluge:2.2.0
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: {drop: [ALL]}
          resources:
            requests: {memory: 128Mi}
            limits: {memory: 128Mi}
          ports:
            - {name: http, containerPort: 8112}
          env:
            - {name: TZ, value: Europe/Oslo}
            - {name: DELUGE_BIN, value: deluge-web}
          volumeMounts:
            - {name: deluge-web-config-volume, mountPath: /config}
            - {name: deluged-certs-volume, mountPath: /config/ssl/daemon.cert, subPath: daemon.cert, readOnly: true}
            - {name: deluged-certs-volume, mountPath: /config/ssl/daemon.pkey, subPath: daemon.pkey, readOnly: true}
      volumes:
        - {name: deluge-web-config-volume, emptyDir: {}}
        - {name: deluged-certs-volume, secret: {secretName: deluged-certs}}
