---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: deluge

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: deluge

resources:
  - Namespace.yaml
  - PersistentVolume.yaml
  - PersistentVolumeClaim.yaml
  - Deployment.yaml
  - Service.web.yaml
  - Service.torrent.yaml
  - HTTPRoute.yaml
  - SealedSecret.oidc.yaml
  - SecurityPolicy.yaml
