---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: deluge-downloads-pv
  namespace: deluge
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-static
  nfs:
    server: file01.hera.home.karlsen.fr
    path: /mnt/nfs/homelab/k8s/deluge/downloads
