---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deluged-config-pvc
  namespace: deluge
spec:
  accessModes: [ReadWriteOncePod]
  resources: {requests: {storage: 1Gi}}
  storageClassName: longhorn-encrypted
  volumeName: deluged-config-pv
  # volumeName: pvc-755a1707-6d1d-4068-88bc-89fac77d7e99
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deluge-downloads-pvc
  namespace: deluge
spec:
  accessModes: [ReadWriteOncePod]
  resources: {requests: {storage: 1Gi}}
  storageClassName: nfs-static
  volumeName: deluge-downloads-pv
