---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oidc
  namespace: deluge
spec:
  encryptedData:
    client-id: AgB+sSb84MHPDBhkeYi4LPnOl3P7UD1uIpCmrHaGF4x2gMQrMjSOetOxyCfZB6CW03qYhXWH5vhayuUOHsknIAO+ltu5rBN02J+P4xAHqKXhjbBYwz/DCEaWHO5OifTta4KHxpEoRXuQ3mZuNerJhP83A9ebUlAXvx4iIwIQ00WgPIU1uzh0eu5QcWIYyeTxtrzcGQmneA66zYUKHyVjWZdjDRkfWPX6jB9um2sGxWa9CSgILqsy04dK8S7vZKWNZfdDJMuVR3QEApLHoqWNmeEcbwjYyMcQOM3Xj8fBKQHaAp3wNIxMmIGzvVdF48VIQLoTXPh3z26gqSMWzXUvt+BThvssQYFoM6x7ylk6K6Qi9ITnyE3OjZyVR6BLwUO/+AeqRrgkbm0RZVoDomxNq5htB8+3j/TSOazdJjuLyKG1wayJ7NlvSnpRy2b7hWujwmb8cReb90hIH1lt/bUS9qgKi7VVLJd2tdDZIL8qewldNyjpfr2lzBqeWEar78PUEnDMnAUTTAwlc5uybhrtGQojWESPD2QYl6sUzgEz3Ow30Tt5Fp/vDBP8hfAOU8897DgHCnOVQXFplet0KBH+NVKeq5ancCeQPvk7IlWH+KVzO8SlTQd0d0byeeYvuhNKFvTq3fJUjK7tmaVyiKC6+TfrBsGFKU0p2bAp2JvTs/nmH+vPJ0GoDgbRfA56rdx4asMFzh/OKZ/NnU54aSyvTv+Wb64=
    client-secret: AgBeWjsobnMCLu5NPKOr9Wcs+RhJEuJLZ89Zk6Qf65XG8L31Ccv41Jlcox+PoZKYEweCgbB6r8xtVUXTGEMAd4ZkjL04qux4wTnEqfOhvsU89WTYfMIWWSk/hunU8UDosnwZSsIAYgDeYlvucb04CvSI/wL9YMmvf0V7ZIzS7FTiFZ+ocH1u0N6yiT+fmYXAJAhC0tyH4VwiV7tS4iTm0W5XWxptn3N2mzAh6sO2JcIuUc9k98Gh3f6WTHHYLGRZ7XEwqLwic31pB5bnrFfcDDf5RMaHsRyu8qVMj/eSmEhLb4Sk9gNv6FiyRbg02Ca3lV63dSh6dNuSUN0i0LNrQYFc4YHSI7EtBPn3s2XoW18VHRZrhCL6E8NDFYtbriA4pEXJRsCe3qZ/faYCTMtn7wRNeUfHm/A/lp4WtygxlzUxEuxyVgyXU8x7EN3hTO2vJi8ZB8YfNsSBV77jbLR00U2fMolsB54s2BzUyJFfEBRAjmViDAvHIDijgqIcxS2GyfiIlz29DhzJ1VA1BBm9mY7Xuk3dxEBNLojbKLv13ZF3+Jdi1enucAac4r9DchO9E5VHhIwI+B0V35NBUsilyIeUo0ijYFshKpuYOE6/4in0LcmIFi/3Tm8zVOUurGSE2shfI8WSqANbLikDIT03owdYy5kQawHFgaLwMcG/mFsPHRfcR8r+wU/Qm0xcXLYZAsTIlqRyT+A7EAdGj2a7TEtIQedR7mZ+EXW70FZoF5yDKQ+yoBjZzqWDPP8LibPSfvucwmgNjG/50crzbo4fg7JA
  template:
    metadata:
      annotations:
        kustomize.config.k8s.io/behavior: replace
      name: oidc
      namespace: deluge
    type: Opaque
