---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: deluge-credentials
  namespace: deluge
spec:
  encryptedData:
    DELUGE_PASSWORD: AgBBy1FCddassL+ryAdiy8MCE/ONMo96VTG1WA2a78nME61OWn6LidBikhvXJjT81q0S5fBwL36mILapV0NI2GowiA+vio7pVBJzOC5ix43r2Bpcm6XOtyIGUcLDc9+SEmB5x5Pizp2w0tLfWjiVU8CFPoc+8kgzft4WhSHcdhnyHPKlFHud1Q70n0/HwMhGDsiIjPX5PzeFLjFAlg2Ns6z4eHLriAXlquc7HNEXHquwUcvGJM6/hlJAVge7pmEnfPH/CgyVMOhGqMZWp5XcwtDJopC9AOtPqKgMOoI4gd/LgwzHkGdQfuv1XgJNsH3Wsidu7El75Z4KrPD2Qcrn/31DoiSdTXlKbh2I6tzUh03j7H7gOBMs3akS/2Gl/Si5G9gG/1AhiQXAA2sG44lUiJS/tL0u3V+oeblXXr0LFrtPWhXYKqeCPkxmmjDQ/86EmQE0KMtcZ+rDaJQG/G7d2XSPVbDcvfykLIdoQm15zfx/5FkTjIxBBDlZyn3a7FRa1gojcRmUpkUZHTMK4eqT4Rxwi8soJ3koVVQnCWoOKIFuUD64u+0EQohUzeRrLkkIUYCvgMpMdiCUi1zF6uTt2S7I3sIjpcXJLC5kaPbUpv3SF0V65AxXZaQXUbh2kkbvxmVPKvWOGVPAl2V+GStxr7dodbSR//+YFtAQLXLbAzcI1iiU4Shu9LiBSM7BEDu6wlxjWbRhmrYDnpmT8Hy18p482061Ms5qgRgQ258HI7s5fuunglXpfiMW1QoLGR1XbUc=
    DELUGE_USERNAME: AgCf8CoYC+NmQygxHwDNpsp3e4dYsdTsMjjcgLgUFwDssNEhWwqQT2uI5SvY0/bdZ69zfKMmBeXZZ2gNCE25vI/m6KR20FXvml8nMKS9QV+baRAtH+Z36qun5JtjNZSXh+IgySfbY3oPDFsaFBLTvvYfiZA6zIBc5taOAO44GDdlFGw6E3KFBsTRzMMvg+fP3gWMP09geNwTrMKgroyeOLcE8vUZkRZbFw+ESHKrsoS5xMZF/yuP3c/OoUrMp/7A/wQvg3Kp2ArkgMeUxi9qqpBYOLdGbw4BZkewrzkZCrTYASbsCGsDbP/e9Cjt9ub0aUuWUpxHhvYH2lj3Y3cqEBZiN6NVd3HOvQ1qe36QgTdyv3NfiZFE82CnFRbx7Ld2haUQgYhkHkuODdHbDKmDaEqDdhM9WbGbl2b85vXruXvjVJrGxtLpGlBtg4OD9pgzL1ljBCGKOY9AQTLYIDtOT21vZOEJ1XMB7MGFlMOoOYKY3hrVCPbmwLpg4acEQDwJ+wXjzB/aEhpeOAPLMf1QOHpyUXT+xLbZOte9r/OZ1WxlI0UpewmVUsELosE2SvQnxracLnuwSPGvTsHeRS1uVF1KBw1MITRt1xj1UhljedPQ/YtsJhE4Vo3k3wz44GfXAB7lLf4vAHFEmxl0YhALJ8nn03IScDJZPtmwtRTleB1QyJsFZU/SWXPHKewwLDIveZVRS9O9EaPgXgE=
  template:
    metadata:
      annotations:
        kustomize.config.k8s.io/behavior: replace
      name: deluge-credentials
      namespace: deluge
    type: Opaque
