---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deluged
  namespace: deluge
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deluge-web
  namespace: deluge
automountServiceAccountToken: false
