---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: UDPRoute
metadata:
  name: deluge-udproute
  namespace: deluge
spec:
  parentRefs:
    - kind: Gateway
      name: internal
      namespace: gateway
      sectionName: torrent-udp
  rules:
    - backendRefs:
        - name: deluge-service
          port: 6881
