---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: phpmyadmin
data:
  'nginx.custom.conf': |-
    worker_processes auto;
    error_log stderr notice;
    pid /tmp/nginx.pid;

    events {
      worker_connections  1024;
    }

    http {
      server_tokens off;
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;

      log_format main '$http_x_forwarded_for [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent"';
      access_log /dev/stdout main;

      client_body_temp_path /tmp/client_temp;
      proxy_temp_path       /tmp/proxy_temp_path;
      fastcgi_temp_path     /tmp/fastcgi_temp;
      uwsgi_temp_path       /tmp/uwsgi_temp;
      scgi_temp_path        /tmp/scgi_temp;

      sendfile on;
      # tcp_nopush on;
      keepalive_timeout 65;
      # gzip  on;

      include /etc/nginx/conf.d/site.conf;
    }

  'site.conf': |-
    server {
      listen 8080;
      server_name pma.karlsen.app;
      root   /pma/public;
      index  index.php;

      location ~ /(\.ht|\.git|wp) {
        deny  all;
      }

      location / {
        try_files $uri $uri/ /index.php?$args;
      }

      location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        try_files $fastcgi_script_name =404;
        set $path_info $fastcgi_path_info;
        fastcgi_param PATH_INFO $path_info;
        fastcgi_index index.php;
        include fastcgi.conf;

        fastcgi_pass 127.0.0.1:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
      }

      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
          root   /usr/share/nginx/html;
      }
    }

    server {
      listen 8080 default_server;
      server_name _;
      return 404;
    }
