---
apiVersion: v1
kind: ConfigMap
metadata:
  name: phpfpm-config
  namespace: phpmyadmin
data:
  'php-readonly.conf': |-
    ;; PHP configuration for php-fpm, read-only settings

  'phpfpm-readonly.conf': |-
    [global]
    pid = /tpm/php-fpm.pid
