---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: phpmyadmin
      app: phpmyadmin

resources:
  - Namespace.yaml

helmCharts:
  - name: phpmyadmin
    repo: oci://registry-1.docker.io/bitnamicharts
    version: 20.0.0 # renovate: github-releases=bitnami/charts
    releaseName: phpmyadmin
    namespace: phpmyadmin
    includeCRDs: true
    valuesFile: values.yaml
