---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - Namespace.yaml
  - HTTPRoute.yaml

helmCharts:
  - name: phpmyadmin
    repo: https://charts.bitnami.com/bitnami
    version: 20.0.0
    releaseName: phpmyadmin
    namespace: phpmyadmin
    valuesFile: values.yaml
