# Sealed Secrets:
# - kubeseal --controller-namespace sealed-secrets -o yaml -f Secret.pma-config.yaml >SealedSecret.pma-config.yaml
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pma-config
  namespace: phpmyadmin
spec:
  encryptedData:
    config.secret.inc.php: AgAj0WJCoFqxOE7X/8s5giVYWPrx5tyae0b0bJCMdwf6Ni2JhxfI4mOVEr7UvB92jU/5mrwaGUW88wWQWw4uZkhhOx4lW/TYijb/2dmc0wyui7tdzL71AWBf2PgDtTTEBsk9LifuG9G3O5zIa9H3X0KWeShw6lOrDTP8oEmW++A+jgGdQ/xWSBOKJoD2yj4IGqIxJwnozLT4e1QJQbF8k1MTSQlEtUfoSwZSq5AIycZ34chpQS43VZPFzmVoVNdE3hjCLHk1EavG40TslyFTcu3j3pyq12zHGeh8np/2WAuMoNNEQi9BHimobJI457xinVBEchgmzBoA/LyBrcnUJ6I0jkQ59s/+ZqiEQuOkWY+NWIhqSKDHrhlPN+FfhxShRNFynw618sGqd6X8oWFg7eexku7uI7MzbZWg3WWRkxFxAxYXvM77atEIhmlevl1VmLDgO1TX7Svo+lxP8L25glHX/M7UMzYArrcfwqxlWCcUffcqBsHqKhx7Lt3BoEpez1NaBMqUTam9ftPhEMFP16BrvLIoSPqc07zlD66+qB9AK5ROQLMgTGnRof8Q1TQuMPmlcN+0uRBBx8/Lx9UBhiR7IAPR5K2qP52k0PdQMBla62DfRhQbsf16Uiu80h+8k80U9ADbMYk4LCMeIzCirxk8exM4glhuTsE4S9PUKPvrpASLxn9jV8XV3mK8M4zCKTT/AgHhZiqASCktsuwL+K3YRV7c4hzbbkTrYsXeQ18+CYZGf4YIJOT0siCfWUrmS7G27HYfu7ftJx6JXfGsKJ9hhsvBXw==
    config.user.inc.php: AgAf/Z4Y3OVFh2OmBfHsKtz2AETaB3cGPEVNYX/F//QDgfS6wXilRZNkaAAMkVWttmAJHm/zc91sVFYL6tH8tbulaOcy68T+5KmF7GqnjmEL6Ae63WOvuhkJfEqeDgFXEEhY5hzKmwdrKZy3AeQQYq/WR65PYakUpJ15ahf5Fm5/3uVzDIPRcD7V1xVt/cj4NF/3jlcvP0ab8T5OCu9s8XgD6cOPs/M8LURPmNZbP3P+QziIPZDg9DZmxdi3RnBcREXAl9VJDdUrwGW8gjbdjsAhhtWllfSfezKTbB7/4z3g67XeI/5GXiuwuEXDw9Q8fSK6+xEhcU1IG2Rsye7Jpg9lDlzCerkMqRRbAWeYpdjwmluu1uYBkID7hpqV5WD33Cj4R2PH+FXNhBNnC6jElk4kabKsZb1wCt56suzzzX6/RmmhDy6udnUl3B77JQQ7+ngaROyH5VgwQmQ73J3r1f4jEtmpxCVU2/7U4FRd6bFGMUpeFSlt21DFCkkPavXXu+w0eSRqLEVvxSUkfdxwHNzepjMcGxkm24ItdfNRTM+uM4PYRtfURZe1J8Se+rY39S9QldgpRgPceftBMbJwIFvX6dtgoM62eMZPhld2fd7d29mc9mCqkELZO753zlNRS+pTRwCynfM/mhOV4FkOXc0shCIZhnHbZoyHNtQgwz61LPYBwVA/CKiU4jyeodrh4zsrLDBxN/mmOsIR1nuMZPga3NbegjAmp4LUjg5LxP3whzz6iv6AFjR3ipMq
  template:
    metadata:
      annotations:
        kustomize.config.k8s.io/behavior: replace
      name: pma-config
      namespace: phpmyadmin
