---
title: "Sync failed: {{ .app }}"
priority: high
tags: [rotating_light, argocd]
click: "{{ .url }}/applications/{{ .namespace }}/{{ .app }}"
markdown: true
message: |
  **{{ .app }}** failed to sync.

  **Message:** {{ .opMessage }}
  **Repo:** {{ .repo }}
