---
title: |
  {{ if eq .status "firing" }}🔥{{ else }}✅ Resolved:{{ end }} {{ .commonLabels.alertname }}
message: |
  {{ range .alerts -}}
  {{ with .annotations.summary }}{{ . }}

  {{ end -}}
  {{ with .annotations.description }}{{ . }}

  {{ end -}}
  **Severity**: {{ .labels.severity }}
  {{ with .labels.namespace }}**Namespace**: {{ . }}
  {{ end -}}
  {{ end -}}
