---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: opentogethertube
  namespace: opentogethertube
spec:
  strategy: {type: Recreate}
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: opentogethertube
  template:
    metadata:
      namespace: opentogethertube
      labels:
        app.kubernetes.io/name: opentogethertube
    spec:
      serviceAccountName: opentogethertube
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: {type: RuntimeDefault}
      initContainers:
        - name: migrate-db
          # Dockerfile: https://hub.docker.com/r/opentogethertube/opentogethertube/dockerfile
          image: index.docker.io/dyc3/opentogethertube:latest
          command: [yarn, workspace, ott-server, run, sequelize-cli, db:migrate]
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: {drop: [ALL]}
          resources:
            requests: {memory: 128Mi}
            limits: {memory: 128Mi}
          envFrom:
            - configMapRef: {name: opentogethertube-env}
            - secretRef: {name: opentogethertube-secrets}
          volumeMounts:
            - {name: tmp-volume, mountPath: /tmp}
            - {name: cache-volume, mountPath: /home/node/.cache}
            - {name: config-volume, mountPath: /app/env/base.toml, subPath: base.toml, readOnly: true}
      containers:
        - name: opentogethertube
          # Dockerfile: https://hub.docker.com/r/opentogethertube/opentogethertube/dockerfile
          image: index.docker.io/dyc3/opentogethertube:latest
          command: [yarn, run, start]
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: {drop: [ALL]}
          resources:
            requests: {memory: 512Mi}
            limits: {memory: 512Mi}
          envFrom:
            - configMapRef: {name: opentogethertube-env}
            - secretRef: {name: opentogethertube-secrets}
          ports:
            - {name: http, containerPort: 3000}
          volumeMounts:
            - {name: tmp-volume, mountPath: /tmp}
            - {name: cache-volume, mountPath: /home/node/.cache}
            - {name: config-volume, mountPath: /app/env/base.toml, subPath: base.toml, readOnly: true}
        - name: valkey
          # Dockerfile: https://github.com/valkey-io/valkey-container/blob/mainline/9.0/alpine/Dockerfile
          image: index.docker.io/valkey/valkey:9.0.3-alpine3.23
          args: [--save, ""]
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: {drop: [ALL]}
            runAsUser: 999
            runAsGroup: 1000
          resources:
            requests: {memory: 64Mi}
            limits: {memory: 64Mi}
          # env:
          #   - {name: VALKEY_EXTRA_FLAGS, value: '--save 60 1 --loglevel warning'}
      volumes:
        - {name: tmp-volume, emptyDir: {medium: Memory}}
        - {name: cache-volume, emptyDir: {medium: Memory}}
        - {name: config-volume, configMap: {name: opentogethertube-config}}
