---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opentogethertube

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - {name: opentogethertube-env, envs: [assets/opentogethertube.env]}
  - {name: opentogethertube-config, files: [base.toml=assets/base.toml]}

components:
  - ../../../common/valkey

images:
  - {name: docker.io/dyc3/opentogethertube, newTag: latest, digest: sha256:feec95f418e7d438b632bb05311bfa522d5e40f13d019e2146216a49e5b53d93}

resources:
  - Namespace.yaml
  - SealedSecret.opentogethertube-secrets.yaml
  - ServiceAccount.yaml
  - Deployment.ott.yaml
  - Service.yaml
  - HTTPRoute.yaml
  - SecurityPolicy.yaml
  - CiliumNetworkPolicy.yaml
