---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: cnpg-database
spec:
  encryptedData:
    password: AgBCShYB3QAq3HKzh3/fq5yvVvkS2AAaFZDnfTPBhnePBMC6ZnsRgPQHhYsXGxE0zEjZEFAAjI3c0Ggdpzj/1cd2kXN3QESEwaO16VwwyhKQHyqP4+1eu9cZB2Z7DhbL13eGsGcTcv0aIlppE8fgKsxm2HTEswpNQuv7+r2z8nPShVWA7k3fHRBGUeH9pErhvnuFUIEDwrO3kt/D+cw0XH2cfNUu+08HqtuO5b6XyZpVeJI5TkttK/gYiwSNQa2nrCFDVlxlZt1xJDj6ilrvapBGAUooHD8oiK94OiMdUJr7P+BK5Qrup1m2QbPdLeR/RspFHBmZPYrM07PEFHahWqwdNOj/rHRKM7W5+Nrth8Ad5/OLfiJVhwQejJLKTqjzDPD8xgGNggH9pELV38kDDfe6APBLswifdnYXWk1XRZ+UYvHXRPleEF3U+fvnYYd+4jUXtjrMmOk06acQfa0H8qHL42EqdiYjOduOm34t7nHY8DmyEAEFIErKFnvqbrQ1M3kBmGi6y8mf9QNC0mAewZW6vd0uHlINnYA9udWhnl4BUHV6qsRQWiWgVHclze1xdI2dak/7MPV8bHIKaZdgtd4B6DE85NB3iYKM09klML0iEUb6ckvY9mDYozi6N4SrdeWnoR8VSVnho8sdUoBGwo5Vt4h6iQ4WfkN5aV7YgS/zgKD9cL9ddJs6h4de7c7E5LxKgFkzypc/tTTFFw==
    username: AgCnEnx76q5Aj4A/dEfNRitlIUuTL1jWLBZfUHyrWC9eC3bC6RktElWmkMVb3zjR18MiLi8MU5qC0jMGipaLARfHxQrn44gN3fYk0j8xx7l6F/gmaSF2ORbxmqwOEIRu6qOVek1Odz72Y/m2xL6YVn+GF2sHh6SEXW6RvxW7UvLXv88aV237lPNnn0IFzyhElHFyaYHm+X+QD8n+Pd4oq3RJgwG4NHdTUJiof7Fb5gGSGBkGMrWeMahaS040kbdxuv1PBsYTNaXWN60mzw8iGIbIleWqtqSBui3OxyTPfT4bexrxZHFzuzH6KxxMc+CGY0g1LEmVuJl+gU//N9U1aXc3oJ3S5VVHg2h770ZCC7JSfQOomPsO2UdMmaZ5L8IeAeh/tiFKlUJX+KvCjCntcGTgh/dCESTBwQJygy+YRyB1/iMrx7WJgARgUFVBPv0Q4QQHkIP/+71kkXE8vWE6DqWYPa4Jnq9x8a2xGOE3yHk200TS6Qw1lDYQANzF7Sxpq98YFWEXuALNAwFZVTzo+RS5X7+IXFDB7F0yv3fG4GyHmXz0HOoUFBD+nc77vOjm0jT57Y7EXFhkbLPheCr3Z8pa1n539lHbw+KHlWz0RKGzPUH4aDgpXX8PR+OaY8H1mjurvOwrIEFHRlg9ELT21csuD6DDWlC7gYGsvrGHWy2jVY9u8pie912SrnLGn9qoBauQwzmi4c0VVA==
  template:
    metadata:
      annotations:
        kustomize.config.k8s.io/behavior: replace
      name: postgres-credentials
      namespace: cnpg-database
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: user-credentials
  namespace: cnpg-database
spec:
  encryptedData:
    password: AgBZrnkEHiYw77Vw9vaYcUXrsZtZUasv0knjGPdKR1ABbkR7dk+YiFIbrTMK5514Z+QW4ZrtvYcULVJZjsaA9KoElJW3i2yBcC02oEmvJF9ygzRR2yTnigf0/3bQheRanFwN22QIwN/BHkwkdfVndHa8Ze5mwZ+WSflpqwxSXQTDnAFi72YjM/hBDzIT6feYJeQKMJ+m8VTASSm8tduqGIudDFGdHlrmVOVn/59/HNoEZWz8DX3nD1uHzbZBJ6i+5UtStmenXIPlrcY/pi7J6my5z6eXpV2NjEpnwH3u7rxD9ghtNmy7Q3uaNPnupQC8CjORTkYWuRyOckrY/abRsbzf5waTJDh+ZsIFO/WhwowZytEOMZc/isNBNstIN5+J78ygwsBs0sKVIC7u3uykpcrp3lVglLBdSmNbrxDhoTd+wXDjFAFcPqMLiFSeWR5ojHB9t3wumwQYxCGl0/2snvSaP3t1P7LSqJtajbFOJ/gWaVw7vFpCH9ayx/SY4fJBYBOkHNb58rMjhjlzqBgzdLc5mZMVE/MqkVaVKBCPcGWg+hFSWcK4pRbKoiFe3tOxuN00Tp/jyW/90h0QGwbevE7BW4mdLOlXHYQ1E8+ON3Z/R1jCR/BNcWtYbm07XbyN39OdmCO7OKoyujVNQl4modmxCNk6fI95r3nZJ+VulshwjYMpZV3VTDPlL1EKyVaB00yVZ4UbDO8swos8gw==
    username: AgAqQ/+tUUdOrCZ6oLm0dA/l8j5TzPDdH47iBL0eKlNxsPupNzx2NokbHpC9cEMupx5WsFnBVWsE2p4nwMOpcet8nx8pwHogGFHD3wm5TRHEAvBGA7OUX5sII5VfFmosBi/17g9dtmCZRFarEb1CkuUshcsA81o1D0UNiFrY0ZA05EUvIKDsfBNj6/bc3a638WrEKZs1tl4dq/4VxShZ2GDiDsDzTKiXFXMauOU0Zfsj/9fmR78TvznLQqNoHYuZzNv/shPwTQwE5XxpHJHwl5dW0KcdGsKNAf6DS7donm115mVvpLOXQqb7Sv6VuPWyITVZNgwJOYDkD3/INwgEwsaFYV3iSdotnJj1/IUGQ8dI06mQcHZ+dPoeP9BW+3SImZjI4G+4DPUb+ZYU6o0yLxW7aPW/U5eGGMer5/MWqyhvWqP0Cz4FoDsXeH+0qwQpCjfaQpdZFuqXaN21Th3m8olbx+IyM1Ohq/cRU1ngSGzS/WPoZ95SENQzX6gYrPukh28cYigrbQEfyRAqQjD06aSsKVGkd4VCuSmu/aWNWGJx5jHZ+2uMnOky29ZxAL9g7fg5EzOA/rUOUdE2HaG/eN9imw0ZBqybLINXE7cQ6i+JYkTbCrFJYtwHWwY5aVOL4wM7rTf0dfLvvJ268B3LiPGxD+IiUOWYCubo+sKptnIZrr7SlGSOhR3nkLXoihJ187xGuvgCGsDWcQ==
  template:
    metadata:
      annotations:
        kustomize.config.k8s.io/behavior: replace
      name: user-credentials
      namespace: cnpg-database
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: read-credentials
  namespace: cnpg-database
spec:
  encryptedData:
    password: AgBId91XohjvPEZg9ZBwQALnQPBgKSI+J8Xne6SPzh2G+V8cp6WvC2iGrLjgpp/zblsjViJuacsIgoz6mRZ9aXcmnRs3q9xapOgikzjLd4eiJA0Digv4pRDFnxyob4jHfphGFoIKqqRhV7GLBwevQ6LZyyl0dz1UCA0hoo1JPInjj8I7c3YSXqgMyKCJZa9vMVWLR9/JIlGDwO+yMbyoIIBwwXqO3m4ZwgmC6vgFNJn2JtXDSaVP+JUz9EsDrd9HqtZiCe0wnHEoFS9gPnrYU0CGlxrWSLKEWYoUBo9Spt1VO3AdBWfxT792kZT6ICZIYPoIE1YWLwtQcjzKIFJI6fwk5M0SlTCG41kWo8qtQZtKLfmMaUD6SojURbv2rt+qa8IqfF4wJ8x7g4glL+flZZzyI4DPjtnG/DNEarJaLX765NeETwsJcvZPkodPIA7OVrYwWSDFsFKNWnkc4VcO6R7MkJBXV6xQLzmLh+rEMgzJW1qOwYF+/ksLAHKHo5Y1hBqhrORrMk4Gu6OEl45IXBtfE4vWuQHw42nEfMP8qf4euiFiL9kAXnYFLROM9SFA0Vy9ZHyxa2yBbRo/Tpzj6KmZ+yH2q2youBydOTZL3WkC00L+J1AfRfnPKncSKA29dt+lqibevqXQ4p2E34dsigE9m/oVoyqZ4KZZx2AGDI27IaQ9DALn7hJJaLJWiTzpypHP0lr9AwCIujXSFQ==
    username: AgBZH8dHL0byAURgwo/9mrtAA8FwWDNgRYS2kyZ7DZL4wiNB/1UvshyW6+G1gn8TbLTxXuQOSJHjmMcfezUdYthx0xbboFjTbnVj/ACsUJkdwg0uh4/A0g1RzZrz0ZWRbBcaxz2T0xyYIwoQMixryfg5lahKuAWyWrEuhIOO79r2q1eyPVEgMFbQpYR8K96p6gNGOclNgGrjuTmSs51BthX7t5aFugPPk50ZcdGG8FYcSnTQ49nHxNbrGQvoqGQDDE3ETwSCImGXpWo9DpNPHNw+XGi8IAwwSw2gslnZ06S2Z+LnsCBvDo+MstZJ0vIYF/63kavUcACXw/Wg/8sXGAJgJJ19XWqcj5CD9Js8nDLwAByd8hcYxAx8aLrt8XZVoPoJDrGmigVaKjchCXfofF/HuGqMCtC9Erlj86t/CBX5k8iARvI4JZYFHVfEgj/nPLqYoPOY4L26Ayv0kfoihBV8ciNCWZcHxe+pW/m5LxHCUzusRiagv6DtxjmsQ2EWz+nQ1CVu46DTjCb7XGg+dO7mAQgBpDFC1hBJE1CebXipvIPhspAfJgWqxh9Kk7IA78Vc2cEaQgIAsnLC6VNqJez7AqitNfRr8PiH0ptJOIjKA74BqKDjSeKjpEweNRbhOxpt08+C0FmSxSj0vPiL+X6mLZJTzb4os01Kh5W1zHsYOE7Gemj9cjOGm8PxFjHCGgqrnoNTGeeGag==
  template:
    metadata:
      annotations:
        kustomize.config.k8s.io/behavior: replace
      name: read-credentials
      namespace: cnpg-database
