---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oidc
  namespace: opentogethertube
spec:
  encryptedData:
    client-id: AgClx/MfkeklfwNT88uFS7JQQbi3vcTFw5qymfVnsOgkSsGAJiRA+gGXciLgNnplL/5jJUfHb5jLbX9rQi5WOYqnwzjx2398bVMoB8uHgKRMGHXfr5iLqRBcq2Y8oLZYh9KNQZ8j/YFAyynxmPZDc14ajSz58+WznWthL7c2Pz6djM8kd5QsTXomnvSAUMH+JEz+c2YbPAybadEtpRuEGUkN6X98orzWQxMd1fm73LBTpUtMhodlf2RF3fAsEQtag8nMNwOQtZ71CC9W+HwAT68PBxoXBbJsSuMPg9KpsedNSgpr4zfU0WdbcIiVAl399Ibw5XcMqOgUpaiTAYIr4FUZ74lRm0hhjJ57mhTJkVnyQx3+D8jHIwoZAyapot+XdKcWNMqiPq4Z4nXRSfKtHZ0ivYXRBAEW86TUNUaPLiYHfAtI96Jcy/YM5XyTWTKOIOFN5cR1zCWB4BofPjv/mzXC81OiKyn6oZtbXtVTlsq/xh05FM9HnLgAN1GVFkGRjkl32ecf607Ofz6Ya6ig7RATfP9FISAsMlOWLiq/nODI8ET4W5lkrmkdDmr8N1H66zodryjHjoQ5d6+NL9zZ6la5PT8J0cTwhPD58Z4OE7AG1yQdwVoRzOIL0XcXJrvYxsUsTAcl12+Ejo1CjuxEPnxnOamSfzPMNd7+i1oubPehoVtg1Ptxu70UswslU9Cc63rYAoP5pN670G/NHpQjB8HjACE=
    client-secret: AgBj7Ew1+OBqLe4NdjkoAf4gdzBO1WD5nCxdjfzo+nBDnh/BPjcEBN8PEpKrlJKIcc94UnwpDNMbp3J7OzbV725IzaAyYEkxw+zevnmtzT1O36bC/Wkag9mTykcwOf66pXMjzT+FCUHTgkqsRg82GpwcJjNz+lk/SwctWc34a717+5FG5nfAEiZ1FEGxdecmhjKlZ1o5L11fVkyLX7LYZVsXznPhxmu6V5/UuIuP+wFYprwiTnZTOalQbhLB0E33EzXvHEQFko7ExU2O5ZKRDQGl9IgpHNioluKaufPO3rZbTD5zmHzEbfhX/ZrFjpqbRpRa1gw17CvyGBXT1jiFTTFfDEkgJ7KkBECYeDMpaV6YvPMX+ndk9/zQFwOhBBGbFQQD6mNqDI6TtpTbrI0v+PVo6U3iV1AY78adkEfI9O/Hv40CgO6BLrZ4nNuKKqaZ5KSTUTXsGgIOHaeFpkMDVx11YzrsjVO9Y7uVYFZPy4nfJdmBCX7C+jq+a//GqWrIS3TLBgdJKvqnhLhpP12Avbm/fibdlQSjkqJ0DXGWmDxbjgLFrwZ049cWYzf9D8ubmKEisB7Jt8UT8HiWg6GVZlcnraljJyNPsGaMDAvoB3hxDwXpyUaSS+ma7o/oDxpdSXCwrUEE4bfGK8Io3BR3aBkQ1mFcBqXSDHY5fide3sPny1lk0SbOTCDAbuSZI9NLJKmX4h8nLD126edLQtVI0xJJ4mi8bqgOpkhjR9IN+OLZeR0xtB3IdVLTlZO4h+V7ruh5Btj6Yn0MBiz18wjZKLKq
  template:
    metadata:
      annotations:
        kustomize.config.k8s.io/behavior: replace
      name: oidc
      namespace: opentogethertube
    type: Opaque
