# Seal secret:
# - kubeseal --controller-namespace sealed-secrets -o yaml -f Secret.ott-db-credentials.yaml >SealedSecret.ott-db-credentials.yaml
# - kubeseal --cert "$(dirname "$(readlink -f "$TALOSCONFIG")")/seal.crt" -o yaml -f Secret.ott-db-credentials.yaml >SealedSecret.ott-db-credentials.yaml
# Unseal secret
# - kubeseal --cert "$(dirname "$(readlink -f "$TALOSCONFIG")")/seal.crt" --recovery-unseal --recovery-private-key "$(dirname "$(readlink -f "$TALOSCONFIG")")/seal.key" -o yaml -f SealedSecret.ott-db-credentials.yaml
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ott-db-credentials
  namespace: cnpg-database
spec:
  encryptedData:
    password: AgCed0bEB0IJfgpML2oePUm/gsrdKgd11At5FJ+W7XwF3FNQ11abITML+Equkk3vxw4zaAHgdvJfbBeGbdJeRG6SCnMjmOgvjPIea+krjmT12ihgrFeAWI7Pvbov2Y/uMauMmIlAuZduKWdzP8Ha+D7LgrUN3W7Y6XbCIXlIN8/A7SyolN8jFPNgOBTXcQpqxDW0MI2jQjVvjSPiNF+b7+tGINxe0gZ+Vu1Vlwyk0gYLzfA/kddmDiJCkwZmjuYYbCUiFkGcTX0dDpbV56uZFcqbgToybLQi+q5z0UaN5jlRmxzPl3pM7TIw/KnAQeHbWu4zvsrOHaj8P/zUo24zl3AZT0GrJ2Jp9kqqf/hwrqJl8fvHe3pOmnRIFkMqEfw3MfSMEk/ds7eiFsDzyhBZCOWqMQoh5FMJ6uEWtU+nOYg7f/vjyZYs421cGgUkERWTQlE3Gji6fxO1HGrwS7tDd3d4KR5lxzFye5pn2QUk3SHMJuqQb4Hpo+Vc1nsWSn3Ye8tdr0d/FK1AO3Vq1533vY/IGKdUHsvpGbE028PXrfWw5x9teH0t4pa52Vn4bhZ7rylE53pS2nrSSDzMoSnaiOWA9FDI20vr3DQz/myQ77dfbC+EujBqI7rbXgF23zvZsIu36vIPLbnUJuzpX8S99cpn1+GYUTSPhP7Z/br7J0z5G+U5ciSif+lSRuwRaRiWyx1YzLhaRVW4hliJVaEAbKzIf3NGj1Yho+LvP9EfFeL4JdP+dcx8ZvU3w2Fv7X5rwjE=
    username: AgBzNoMuvvGmVh20TSzCKlfaWCkespi0otDIE3w+Tbd0WBiJ6DcHXpgCNpU4PkEHIGbFdWpAYz5YMJ3prw1Z1bAgdAkCUzjvbB+FQcpI0TR5akiyJEHoZRqW4N1ogVI2dVvX8890HljQsxUE85CxEOJm0Gi4M2nYuoRM/CARBG9KYFrvRxWGZNgW3QaLnd2CVL7p/BRN+EAdmQajecy7PPH+EfjD9Ny96Az/Qu6Tzwihf6spdv+vKqBdBXhQ8rSVrkryHBBM0Y6L537Rdeg1OE8/WfHToG+THD1M0DT/Ygc84MwcNqkxjnLeliVfIbiRQgqyBRikhCJhR+ASzBwcBNVaWoQO7UTKR/4j+n1OeUbmyZOt/udFzPkihRR4oH0Z3oPN6edArZRDB1OjHwudKJoG154g8VORSJZ8zVOXsjXrrQp9pPDL05Buzy09dui/wPvKow/6AimBEcdauv51H7EgGjaKaeeAwr+3XZIC8LJJ5v/jbE19CeC6r66/UC+xMexyFg3w0vmQ4oJ3oPbTrPpEgMFI81Hqv+K6Kx+s6ih/uIFs2fmF0+uVOB4aURD06J+uhelc9Yst/FEQSfHg5mY+ZI4MjBNnhuy8nVYPtKin0HvKcYPlBhEQaxIIiNVq70+pqYf2o+1ErRnIRZ2fk5qVtuN++65mLCCPRrALiiRPvetNynboBax0Jy1RhxIM4p2ImYo=
  template:
    metadata:
      annotations:
        kustomize.config.k8s.io/behavior: replace
      name: ott-db-credentials
      namespace: cnpg-database
    type: kubernetes.io/basic-auth
