---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: opentogethertube
  namespace: opentogethertube
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: valkey
  namespace: opentogethertube
