---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: opentogethertube
  namespace: opentogethertube
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: valkey
  namespace: opentogethertube
automountServiceAccountToken: false
