# Create: kubectl create secret --dry-run=client generic -n databases-backups postgres-secrets -o yaml --from-literal=postgres-db-csv=XX
# Encrypt: sops -e Secret.postgres-secrets.yaml > Secret.postgres-secrets.enc.yaml
# Decrypt: sops -d Secret.postgres-secrets.enc.yaml > Secret.postgres-secrets.yaml
---
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: postgres-secrets-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - Secret.postgres-secrets.enc.yaml
