# Create: kubectl create secret --dry-run=client generic -n databases-backups mariadb-secrets -o yaml --from-literal=mariadb-db-csv=XX
# Encrypt: sops -e Secret.mariadb-secrets.yaml > Secret.mariadb-secrets.enc.yaml
# Decrypt: sops -d Secret.mariadb-secrets.enc.yaml > Secret.mariadb-secrets.yaml
---
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: mariadb-secrets-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - Secret.mariadb-secrets.enc.yaml
