# https://medium.com/@Vishwa22/mastering-kubernetes-cronjobs-the-complete-guide-for-periodic-task-automation-2d2c0961eff4
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generators:
  - ./ksops.mariadb-secrets-generator.yaml
  - ./ksops.postgres-secrets-generator.yaml

resources:
  - Namespace.yaml
  - Secret.mariadb-secrets.enc.yaml
  - CronJob.MariaDB.yaml
  - Secret.postgres-secrets.enc.yaml
  - CronJob.Postgres.yaml
