# Sealed Secrets:
# - kubeseal --controller-namespace sealed-secrets -o yaml -f Secret.postgres-secrets.yaml >SealedSecret.postgres-secrets.yaml
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secrets
  namespace: databases-backup
spec:
  encryptedData:
    postgres-db-csv: AgBe5rTBUqLWjelmi/8o/zmp30/srBoVsei7kpPI2XxxgSkTqR5XwfmkEad2WvetU1uDpFG99pwGxZSAOAEKTwwVauEHcHJB43UDqNnMe0sossd4XWZs0K3dhCEEklfpLcF8E+3k6v9RpujkFLfdgNVf4iofzRHdlbkrgZSmyskQBHhO16MlsYTQ123yf9IKHdbGsgvf3bh9WR4RNqG+ZxAeyDHJCjEsJRKZw7JNKnCs9DF8w5JCASgEkxECFfyCOsP2hvsIyOOZ4F5D/CDRon+8Ml/WOes8gj4AAOo5ccrB1ydNzRlD5wjx2k4vyaI8DOVZtE/wmA44NfMBlX9bHl6iwdoQ2ve6cV+PJ5vPsAp43/MzjK9CuaFfLdYX4+F5O44YxksB8sqDNVsF0qKMfsD7T/qzZ2p/u64wb4fTxJOYyi4FvdML8Awu9bla48dfj3suvY5m57CZVH7roZSl1TPqQ48ZuuiW9DkhfxIt18ey/cVH8BgQ504zjEPzxCE67EUdixEsAug7F0RQIlSBajwcs/h5roJ0vfVw/bwaHVAsJwbPceyEETnCHmSuOqOZZsaCnzf9ZTadNDSmhP+tbEh+BkeVNIVAXXbmie/JqhkubioNF8/+XDbVF+j4g8CTZxY6bbk4K6DynNRvJKaUON2M1p7FLS5gmzQAGQX9Iykx70uIs3yu2QiUIkN1yWIF6j7N0sadqoX+hCZYakE8qlgoJc6PePGE4y+YdDrdDQ+5oTbxi4ybAEx7tjaaI2tuk0ahSIMY3GNrFtfFO9mEz66C46gfcpUekAiNUOShdRItJ8rHu9bMg+DzN/LD1NlTg17TY/b1a54Yt4a5LISNuQEAEpdg+v1YmROQGPRf0c4FiqmCGN9PewIHO8E4Rr5ehaKPf7xCUvs3ohv82FKuKTo7MvKorwuR4kA5/DRvQmiKXjVMKbA+a4liAbACnmjRJ1dKq5YUlJRj/uXhqRUlzzqOk8T09w3teTF/Uo76CFKpceVw8vXCfP/+lDVKsoPrkM7gaGHndY0yVmk1pdcnRmaRfvf1IiwKUwSAm95NZfvHHAyhPEbP11A3ZXGCvct45ibLerrwiReoP8aNLGpj8LdLHqQGjVcPz9BzFYpUClkr+XX5mZVAcKzOgOuKTXnTonJAfSRpuUCyATqiuiOcVce4GRKe8a6t3N1Z5AR/r30NOec7pqVMB+MSGmd0+a0O+I4kde+WF6Md4L5hJZBHko/E9m3s7+QoJv7wrnL393ZEtxELEDMoIAnJd4X+bdw5aEax2YPls2jY4X9lTSUAsu2xasL3OeIoqeb13IMXR+JXixobJ+lXE1jvWoS+hOjqETlYLyLo+q3wFpA76in7eAXoTI8kIbRIpNC4gz9WAtWq9/IdILgppDdV9wG9HNS2quV4IcSog9XlVzSYYr8+nWaqzk2q34d9TVfF2uFMTcBnKOeYDZYZBe455kcN5ybyH4kuEVmpq7+tjAmupk/k8Fbu5NLMoXUzrS7vRbShI9Tr/yqpfqO47exyrA==
  template:
    metadata:
      annotations:
        kustomize.config.k8s.io/behavior: replace
      name: postgres-secrets
      namespace: databases-backup
