# Create: kubectl create secret --dry-run=client generic -n databases-backups postgres-secrets -o yaml --from-literal=postgres-db-csv=XX
# Ksops:
# - Encrypt: sops -e Secret.postgres-secrets.yaml > Secret.postgres-secrets.enc.yaml
# - Decrypt: sops -d Secret.postgres-secrets.enc.yaml > Secret.postgres-secrets.yaml
# Sealed Secrets:
# - kubeseal --controller-namespace sealed-secrets -o yaml -f Secret.postgres-secrets.yaml >SealedSecret.postgres-secrets.yaml
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secrets
  namespace: databases-backup
spec:
  template:
    metadata:
      name: postgres-secrets
      namespace: databases-backup
      annotations:
        kustomize.config.k8s.io/behavior: replace
  encryptedData:
    postgres-db-csv: AgB1JTNNwHH0Ejpg9iOuMOyFbPly8EIdB4jwhyCPMPeMjdIN8+rNRLMxJ4/9ybVtE/LMvIUWTHOK2EAs5dKGjdH49V7TztoV1dFfiNiys/D4RG0LRvf7qeTTVKE/jEJ5dcK0kcyLYeWlCfu0VTJxtpWFU421fi8B/T6D6vDTkA2z2vXfLw1geEhGZYjmdGoluwPhQw3jd3cThqnLM6SD+LUMohmwttL10ShhfXNZIwTCDExTFrRpICBar9fEfgUU3v6l8QZRFSRJJW6/yVwXsBdFFrNRQ6vvj/vJNGmslilJMWb6s+6svfGWPrJgJvsdFssiG+Ywt+fYnWX12SUs5cObgiTvz+GBH8YTqC1jge08n63BMaEyGsahqDoNXY55Kr1P2vKFuPb46w6VWIcnBM1KS77AVkoe2noomSZBbRVIZ9Kb29GBMJIWdY0vO3dz4khusNivjW3fi+BbHwstnSVYUJg5hcPijimfDtc9Cvb9dCZQUjswosx6irH6J/cFsNVgmKzgCLT3NynwZWJ0cy5GJJ41Yjhl4MwEREIvEV+YqEhF6YhJdHetM/Xijfy3OhE/P4b7C4S/v6mml3/yqh3r433qU3wEjEHO0du/JSGubPRvC4ZUUJnPvS3L0Bsy9wLivRKK/jlens3Lm3mbW5QJ4Okn3p0U84Q63CfMHBXFnvIhMOOqYK2YowtciByV7HpLriKovTI1eosBSaQfuX4KgxjGr1Qvz9pbNdReyMB7YP31PcOD4q8rC63uc2AgAly80tgqfz6bYtBnyq6zwjtvcW3jCPIgqnhWl+WsdweqAGXQLSk1Oznm725/dT43VC64nAa095N47bcB8/MWIPtxqrSLuwxunRC3ob9NHkmT5C6cS0oWXPStpusaFfGkxZtCY2Wzv7R9Nrgc7NOkAkThB5B3pPYoWIyBbe662a32TrbYbOQmKXTEfocFOCgzXgj9fQIvmcWLfwaRNFjJZYm5GaQ2chCIUMMf5AGXySEA79qzFh3q3wsnxg9rG0EGQNnIwYwCnKf+2Ljb6FH2K3WY79t4iX4DUPHYqdwDIdFQAvmCuSZ80i13f1s2VqiqDTLXW/5gT2Yha0zGjCYgMWBrxo8gpjRbkZlLJjaEyVDlOQ2WDA==
