# Create: kubectl create secret --dry-run=client generic -n databases-backups mariadb-secrets -o yaml --from-literal=mariadb-db-csv=XX
# Ksops:
# - Encrypt: sops -e Secret.mariadb-secrets.yaml > Secret.mariadb-secrets.enc.yaml
# - Decrypt: sops -d Secret.mariadb-secrets.enc.yaml > Secret.mariadb-secrets.yaml
# Sealed Secrets:
# - kubeseal --controller-namespace sealed-secrets -o yaml -f Secret.mariadb-secrets.yaml >SealedSecret.mariadb-secrets.yaml
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mariadb-secrets
  namespace: databases-backup
spec:
  template:
    metadata:
      name: mariadb-secrets
      namespace: databases-backup
      annotations:
        kustomize.config.k8s.io/behavior: replace
  encryptedData:
    mariadb-db-csv: AgBf96lgzCGdRPozUjQ0+5ePKw+f7x0WjIdMXS9l4iNU6u1Z+390tOJrEKFj6PPDAyuix183zWvm+furvijpq1oggy3u/nI7V7Obo7ecs9/64+ODtDxyPAW0X6S0Ll7MLR24wXGUhsGlEteLcIXA4Cb6leGk6TSO9JU36YnEJPaCMc+GVguNe45RFtfFBHZEmDnl/KjwwSnnh+fTsS792NJso19NCDoKQmxA2yLPCyjGHuOuhGrM44mQA/xoHZIm2x7u606vzXhFup+D8ye/hCcwyRlY1YPSLZ+a9H7fhpjhogqFrFzFefVBHj9FxPV50yVeVEAvDJxnKSgcaJRgNm2PO25g3ebHW5b5CGn9cDjhR1i33FwOe1NNOqjUCWo1AqSHLwLCtqecCOnPf0qdusBzEfphpH9zvwLykiyDwdJQD3Ks/PQNDOiEcVgqBtEyKFhwquxiRAxjvD10ehbHw6+aC7PWK2L2DEvPbW1GZoFn7yWjgD4n1HGlpGsr3YlM5sH8X1fDcMIOGNuyUQgf9TiQ5yR5rzmMU0OgCux4JoOFX3Nc1TFLefPv5FYgcuYvmmH6qm4cCnBXLwPUa44XFG9zUDRgD3HBtuh1bn1OGiPtMNNpHB/Usk6qKOPq6d8xWxCYrpTVjMcIAHmsOl5advVVbazcZHLttk7sUyTz6ir+h2SeoTvOMSD51HdwZij+YF2wQ4/aESZLqm4MPU3OtQjcO2SLLrMTWpI2utsDskwbXhvBA8Q1NehfQykpQ7PNBRL2ipOXXelCxFWGBqRy1RrfBvmMxUoH560mIrhwYnbWoPAPG9uEfABMaY/E1AgauGfwDLxzM0ML8ZaoO3mw4ZNQXZU1Nu6pb3fin6VWRyppzVkHmRJO1edbWw==
