---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mariadb-secrets
  namespace: databases-backup
spec:
  encryptedData:
    MARIADB_DB_CSV: AgCDLY7cq8WVE22nxeqezRLoShMqG4MRoiCCjEo5ivSs/vHgAGKD14fVBnNSrUmA5/elBFOZcTdxeYU2kOGCUrDdXwR4rC0u6NGUlJjM4iG3fNs3PLB3/xK49o9riFHrjnPS7PkrC6HPzw/KgXJ8u4mlldGxg/5pUEBE0W0KQLlx9FTkwqVYkyeBtKvgN8ioWebXJKSOuS7BBpuf4wXIac/wETDQXz+bzrCqO/qTbUBdOWEcW8Ws3GK7iPAS3FAjb+VUorcoCG7eo3iX303fkZU8bsNd12CVOwks/+6nhX84C38Al+0BHDlPTPp3JktT06AbuHL25SQ4jFEmZZuh67tZOTGaASm9bzY4qYs3v/wivAskiYkGkOMIt+PnfwUiNUNXZiJKJ7PcHJ8MBIrVwceqMBsWRqAn/IdNALYV38kWw1B4vkkSC+YKkZ0/M2HY+dOxLiXY3yyDh8jxsonejgcaRkGgUA62KCR2tFw/nKk7C+7jYd+ZNLh6XuXy3Sm2g8Khx9FCFXOqQtEx1ly4hbv9MrXkc99H2kNuoxxLWcQDgKubo0szlSO5hUNxbXcdDtM4oVZ+P2qxbjZpwhe1Hw83dE7zCkrXS8BjG7PnDEtR4Ck+tXv6JyTakG5rYs+cz9nln0tj8SBUXCHtyvbEYKVJdGR/7PNiTd2JawOWrzerUl0Qc39BhqFdpgnccGd++SmDNarSHRMgSMAm/oJJ/HZ15D1IdusaiQXYCBNcOaH/rBMn2eTGji8/uT+Lh+ne6QirT+f1Xwyv76+nRIhKQPuePl89lCtf3WRqe1tcpoUi8dS4x+lWVNP5wLDDPXrnCNZ5AYjP6SQ975nG9pYZzl72CqcjCLGNEFP9ZXl7Z1RXNpdS6aAJyjAuU1uoIIvAPHwiHLsImkTToQvXJjehgYtOBHn0/aCyBF7EGBMhogDFQvZC76kUxZVM7BVSV0wwOL4xY+l8MmLzRcW4DFFvaeqZJzZwcKwjZu9fS9+yrfEg+1KhyQ9MOXdtfvc/rzIwFypiDSpcV/qbSno418WKAJrntP8IvASn/w4pV4vnR+gdwyFtenZ3N8qvE3nJXTb9Zbkor0biPyl5gvAdgLHGsZDkdTz+dTa/eGV7bnPHktjSdv4JLZfEhw==
  template:
    metadata:
      annotations:
        kustomize.config.k8s.io/behavior: replace
      name: mariadb-secrets
      namespace: databases-backup
