#ENC[AES256_GCM,data:P9+jL7syke2uMlk++gt8QAm9DzCsZ78HlncEPP0kDX1z6NBwpqjapSfPbTbiAy1ettXy6pLXGx8bL5vk/dQgP7hFvm3r2OXEPwb6RC2c+NfkLHiQmrcTeBGkts91xc++P9avS3iXCb1lGAy5kAbehuTmm3YcxkWdpuwNWkdMmGExudJlmF4z,iv:h9rjeytKUFTM0uzbHfJaY6LkPw5TxeKwIjhETFh0r9c=,tag:q0zKwIM143SUNb2n1Hsedg==,type:comment]
#ENC[AES256_GCM,data:tF3diP/O2S9dLslHuPK7q+sb8UWwbFZIC36u1HoGpP/DMM0OecZcpxz6N2y/X/FcngpVGO4x//HpQcHGZTgOyj0gKTaqpVVAZ4a8AzR6rfd4,iv:0zGymHe5PiTBjTXRdKaEfO0i/7bRC47tWO5uTidc9+E=,tag:MV9hXXyTHlqCg+UJ6wQzlQ==,type:comment]
#ENC[AES256_GCM,data:v9GVQKbkMtLDcEVGBHwfauGvo54LYnCOBKCh4RIrrwh1EBPHF7toCcq+nd//nthFIBowHuR0oZJUTFD1ZkfVFca94H2sr7BKZTkFNSqEVowg,iv:B9f8CBhfkteUajXOHRFP30yuqr7II6PMekr7uaKdRh0=,tag:5dD31TjAycVeTBW9JX9mNw==,type:comment]
apiVersion: v1
kind: Secret
metadata:
    name: postgres-secrets
    namespace: databases-backup
    annotations:
        kustomize.config.k8s.io/behavior: replace
stringData:
    postgres-db-csv: ENC[AES256_GCM,data:Hwy+J6K2GRawhhfRv+VrBTkruAzgsCPVIPd6/1r1Q3YmTc/8ZYnY6MQXx21giT9MwhnMIu2tHZHlu/oRIooRZ9cYMNldmn3YMv6Bn/Pa0E7ZNodq6mkP1pMuDSO+Ho6OARkjTC7tu5sRqR9DZ1ePV/hdGLDXuiZTUJQzHMX9fy8P1BmA4tRTH3LB5GnNNR1+s5OGNWjAoocHGivQGuWkocfPt7h6tj9Hbna6nbY3tyX/8U8jlq244OerAYZ30iGYZ4yRt/8D3vHrRIm8wj0eQeYGzIJ41OCUJ4h0USeHQZ3dZ55fMhb40ai5dxklrAGv/qtosiPaDPY/NxYa89Nmdv2vSgnquSv3x3VRWPBr+b8VuOt1OFqTdXcV9xHN7+33iaPixaTLZ8uD3yXw64S0OjnpDUie7Z8TiS+FGtBFRbaLSyM=,iv:JwjjyWF9Z1YqgvirU7LE8ysKB39Qida/ATnsQCW4LR8=,tag:jePJ24qjmHaSUZ3F2DiRoA==,type:str]
sops:
    age:
        - recipient: age1u8uutg4mpsn82nd9y828sj5agg7s89uswmp7frzpkrruhgw6xcuqr8hvf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4NlRWMk1wYjhiSGRGRXZp
            aktSYWpEcGFGakxMaGJuMFNLS29mWXpFQkJBCldkeU9idEFFN1lJRTJ0MFl4VDh1
            cjF3a3RxZkpMT1BXRDEwQUZtL2tFME0KLS0tIHFnSDluYVM1MDNUUDk4T2xLb01V
            S3dUR29lMTdxa09qWWg2Q0I4Rk5RcXcKd9MPQVsokOAUVxpei9f7V7xdpum9MorS
            EcSJNWimyAwsYK241yZJT6xSotYEv0mXFO4rZU/ubbUbrWhLuC21QQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-05T23:28:55Z"
    mac: ENC[AES256_GCM,data:wgYH6W8asL4RyoHAkfxLAaiF/z+Nm4QQgmvEvK3P1EM3NXueRI2uvrWB430bTeY3nsIKkTs0HvukenW6ZfDfO/wcJYwnMdf1qqfspIxmxFSgUbYvL1TU8UFbtic3C5yjsrFfLMisoH/2jTJb+3qS1poGNiewkFggN3OoRssFszg=,iv:VU3SiActLy0HLHX7WVOBBrlxg/VbCvC/inIUI4i5S5I=,tag:RDGM1sIDB3xT2vgJ7uIwJQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
