---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-falco-ingress
  namespace: falco
spec:
  endpointSelector: {matchLabels: {app.kubernetes.io/name: falco}}
  ingress:
    - {fromEntities: [host], toPorts: [ports: [{port: '8081', protocol: TCP}]]}  # Host probes
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-falco-egress
  namespace: falco
spec:
  endpointSelector: {matchLabels: {app.kubernetes.io/name: falco}}
  egress:
    - {toEntities: [kube-apiserver]}
    - {toEndpoints: [{matchLabels: {app.kubernetes.io/name: falcosidekick, k8s:io.kubernetes.pod.namespace: falco}}], toPorts: [ports: [{port: '2801', protocol: TCP}]]}  # Events to Falcosidekick
    - {toEntities: [world], toPorts: [ports: [{port: '443', protocol: TCP}]]}  # falcoctl rule updates
