---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-falcosidekick-ui-ingress
  namespace: falco
spec:
  endpointSelector: {matchLabels: {app.kubernetes.io/name: falcosidekick, app.kubernetes.io/component: ui}}
  ingress:
    - {fromEntities: [host], toPorts: [ports: [{port: '2802', protocol: TCP}]]}  # Host probes
    - {fromEndpoints: [matchLabels: {k8s:io.kubernetes.pod.namespace: envoy-gateway-system}], toPorts: [ports: [{port: '2802', protocol: TCP}]]}  # Envoy Gateway
# ---
# apiVersion: cilium.io/v2
# kind: CiliumNetworkPolicy
# metadata:
#   name: allow-falcosidekick-ui-egress
#   namespace: falco
# spec:
#   endpointSelector: {matchLabels: {app.kubernetes.io/name: falcosidekick, app.kubernetes.io/component: ui}}
#   egress:
#     # - {toEntities: [world], toPorts: [ports: [{port: '443', protocol: TCP}]]}
