---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-falcosidekick-ingress
  namespace: falco
spec:
  endpointSelector: {matchLabels: {app.kubernetes.io/name: falcosidekick}}
  ingress:
    - {fromEndpoints: [{matchLabels: {app.kubernetes.io/name: falco, k8s:io.kubernetes.pod.namespace: falco}}], toPorts: [ports: [{port: '2801', protocol: TCP}]]}  # Events from Falco
    - {fromEntities: [host], toPorts: [ports: [{port: '2801', protocol: TCP}]]}  # Host probes
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-falcosidekick-egress
  namespace: falco
spec:
  endpointSelector: {matchLabels: {app.kubernetes.io/name: falcosidekick}}
  egress:
    - {toEndpoints: [{matchLabels: {k8s:io.kubernetes.pod.namespace: ntfy, app.kubernetes.io/name: ntfy}}], toPorts: [ports: [{port: '80', protocol: TCP}]]}
    - {toEndpoints: [{matchLabels: {app.kubernetes.io/name: falcosidekick, app.kubernetes.io/component: ui-redis, k8s:io.kubernetes.pod.namespace: falco}}], toPorts: [ports: [{port: '6379', protocol: TCP}]]}  # Redis storage
    - {toEndpoints: [{matchLabels: {app.kubernetes.io/name: falcosidekick, k8s:io.kubernetes.pod.namespace: falco}}], toPorts: [ports: [{port: '2801', protocol: TCP}]]}  # Test connection
    - {toEndpoints: [{matchLabels: {app.kubernetes.io/name: loki, app.kubernetes.io/component: single-binary, k8s:io.kubernetes.pod.namespace: loki}}], toPorts: [ports: [{port: '3100', protocol: TCP}]]}  # Loki output
