---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: falco

images:
  - {name: appropriate/curl, newName: docker.io/alpine/curl, newTag: 8.19.0, digest: sha256:23b60dc412cd453aba2841da0ee8bc6ad8da32263c557fcc9eccd52840f4ca43}

resources:
  - Namespace.yaml
  - SealedSecret.falco-ntfy.yaml
  - HTTPRoute.yaml
  - CiliumNetworkPolicy.yaml
  - GrafanaDashboard.falcosidekick-loki.yaml
  - GrafanaDashboard.falco-events.yaml

helmCharts:
  - name: falco
    repo: oci://ghcr.io/falcosecurity/charts
    version: 8.0.5  # renovate: datasource=helm registryUrl=oci://ghcr.io/falcosecurity/charts depName=falco
    releaseName: falco
    namespace: falco
    includeCRDs: true
    valuesFile: values.yaml
