---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: falco-ntfy
  namespace: falco
spec:
  encryptedData:
    NTFY_AUTH_TOKEN_FALCO: AgCXRx4BihPpfmoqO5cgvvNg9IFMrg3mOCFvgvZwMSq/0XSkl9WDpCIOyOEVN13I8z5s/v/huGDykLbfzsi9h/pRlrQjXK/1vrX8eAd0S+9eKLr9h+H4zpvoAd6sjsA/Y1+rO9fdVf9QNl6+GqwgLohwpMKBARtVlTNerox1uuSTrfWm1DAeRv8eumpIsgQNwdyJ5LPl3WaGyTG4imer7ZMl7PwBDpD8Ac2Y2KnDKbuIAciKQ3BCwbMnKumPpOT7EpO6dU/qZ2U9xh/ROoc1yTUFMaUPz4Nq+G5tUhvRwHHRT7Q1DsN8hGgf620wZM4aCDvUMkACmAnpyKmtb14q8H6n9kuhAW/5c59E4FEdzqppbvArif9nhgRO0FDjrwclIJTvdFdpqXpnr6uopgVn40AzSPyR4Y8DA9xyTRRBUGLM0DFcSp4yAbMv24Al+tadleDfZc9BriduXNfhUArPCX3G3Di8jkpiXmlU60Lb2b0K1H74MQMmCdO2XA8yLq8FsVTiJvZAITeDxrItsuDdwDG1IwFFSZqjZx6zGf/RAIw4OE5WQca6neWAPMrsHoYvZz4FzQD5vsG1v589rDdXB8EvLx3YQJyeXY/e6DmGCfMlZd1JkD5wtd8WnFUZtNj9uxe9Ou3mk40/AG38BuEG+34iojae1a0Im035cXpYcc+Kko/DMghiDHTNOzOYAt3QuVssdUAaR4D1SHaoolpDr2/O6sHzdYkcK+RltfIzvIvRug==
  template:
    metadata:
      annotations:
        kustomize.config.k8s.io/behavior: replace
      name: falco-ntfy
      namespace: falco
