---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: falco-ntfy
  namespace: falco
spec:
  encryptedData:
    NTFY_AUTH_TOKEN_FALCO: AgA3p2nHoTYE+PzzrNXk+prMj4Bw+RCIWy++Nhce1hlEyKQKO93GRhNI5NKLF8767lakCelPyLwyh2KdhTTxCFrC/L53+M5XRpXL08D3nnzx5hU27226AmXdarXH4lwhgbHH12jeUQcVY3Ri9e/X6IW7JgGpFV2Mns79t/uj1yH7GZavv5NuSOQOpVX0bygkqeU3a5R5sgHHRXspVD3T0guNtT9U4VkQzaK+bzTZgzSUl8qwn+zgIz5sgBMEItku+H7P2wMg2YODJ5EIdfjcIsk+2oJ67J0GrSt2TqsPgwhYl8JcGM8Gc6fWK0B7bi9s/fsKAyWlQVuoI9fGFoXhdBTc3uE4x00yIfJSjhFc2d9MnyUSxy8xAHbk6vjPpj42oDaw3boVWt3my/WxGWAYRdnUWY//rker4CCmj+QRK1hnLU93C3vVjGgEDXAo5Y0l0dn5a/XIAD1BKsG+1BQdY8MjevJsG6ontiwV5w4PNi2YS93rlggzHqfq+BzZDrzINl7gg6Obj9AgMA6rTrAO3/Zt0tLpQZ70GoNKhqO46nQ3Dp09SkIe5kq7r4+XwzEEW2yw9OumnHC0pcwubQRk+NbgL6XKIOSwqrxnyE1eljD0tidstJm7FrJia48GBbqYT0u1jx9tssULIaKTVL9lxTZYPX4KDrj1jcvHF3ycFnR3lpSwN+KrqKcO/4ybERpdLpwf2Ji5gW2rUeCJl8y0eyIGNpTPjKzXhWPYJiqpYURvEQ==
    NTFY_TOPIC: AgCsYuHJgQ5I8t0r7pctf08v4QKqbTcox8pscxWPYWXP2/qV02rUPtw/gaJNJGBPoT/fEQ8pUeoeqtRMz/5kuwmI3j3W696jlfhoOkXNs3/qnwlxVM7QPnjFOv6KlR+g11XyNE7nhT6elfQJ3/uG5P2ttNC7PLQVOWDQDrFLfJljexUndy8QkVKWOKBanUFzZXEJ4Zm+SC8xyzL8u9nKYYrsBoPSzZ4mtVmOmKRhK34dVKbGFiZgPgiiMAL1HSw3SKdYChifAhhWJ4NtsMEIku67qgf1MUNr077/JDCtLLPnVxj37sGqKv2CNA+73AKwCPnMFHXfRKOvs/bj7MxZ2z0RyNZHhrZTOmzUOd+wshXGPWvP+bf/jO2QgHlZN/EYeR4IheD+CGk6TGuD1in9Xw1osy1qJFJaUrNIujnhr3QdCtfqY+uAzMDbsvPFafFuyYC2VoY27Uou8a7BjUkYhUtUzfBO0F0o9TO4xddHvQ6Izca0PdghdJ7BiYN4Uzdpm2QDRYNsH8yD+wzaoXxy30tHkB6YHJkckEXIF6KKbHYRKxDrNz152GNefgL4bRYuKQmAc+ZQYNVaal1P4ROWts806kjaYkd6ltTmbvfMeOKTPaqgG4qmJvpMmX0eLRmwPqlSf1jgThyNJ2Cl8+LpH7Pz9LVfGoUnVIqX2PtmT90jW+wwxzNOsZnnS+JmL9N7ncHBvP8kVEXsdIKk9mUmt7hG
  template:
    metadata:
      annotations:
        kustomize.config.k8s.io/behavior: replace
      name: falco-ntfy
      namespace: falco
