---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stork
  namespace: stork
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  strategy: {type: Recreate}
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: stork
      app.kubernetes.io/version: stable
      app.kubernetes.io/component: server
      app.kubernetes.io/part-of: stork
    # app.kubernetes.io/managed-by: kustomize
  template:
    metadata:
      namespace: stork
      labels:
        app.kubernetes.io/name: stork
        app.kubernetes.io/version: stable
        app.kubernetes.io/component: server
        app.kubernetes.io/part-of: stork
      # app.kubernetes.io/managed-by: kustomize
    spec:
      serviceAccountName: stork
      securityContext:
        runAsNonRoot: true
        runAsUser: 100
        runAsGroup: 101
        fsGroup: 101
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: {type: RuntimeDefault}
      containers:
        - name: stork
          image: ghcr.io/sebastka/stork:2.4.1@sha256:b956942816f6cc5f8c073f8886a63f36d06beaa4dee9e32829f53739f3af283f
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: {drop: [ALL]}
          resources:
            requests: {memory: 128Mi}
            limits: {memory: 128Mi}
          env:
            - {name: SSL_CERT_FILE, value: /mnt/ca/cluster-root-ca.crt}
          envFrom:
            - configMapRef: {name: stork-env}
            - secretRef: {name: stork-secrets}
          ports:
            - {name: http, protocol: TCP, containerPort: 8080}
          startupProbe: {httpGet: {port: 8080, path: /}, initialDelaySeconds: 2, periodSeconds: 10, failureThreshold: 3}
          livenessProbe: {httpGet: {port: 8080, path: /}, initialDelaySeconds: 10, periodSeconds: 120}
          readinessProbe: {httpGet: {port: 8080, path: /}, initialDelaySeconds: 10, periodSeconds: 120}
          volumeMounts:
            - {name: ca-bundle-volume, mountPath: /mnt/ca, readOnly: true}
      volumes:
        - {name: ca-bundle-volume, configMap: {name: cluster-ca-bundle}}
