---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: network
  namespace: argocd
spec:
  sourceRepos: [https://github.com/sebastka/homelab.git]
  destinations:
    - {namespace: argocd, server: 'https://kubernetes.default.svc'}
    - {namespace: kube-system, server: 'https://kubernetes.default.svc'}
    - {namespace: cilium-secrets, server: 'https://kubernetes.default.svc'}
    - {namespace: envoy-gateway-system, server: 'https://kubernetes.default.svc'}
    - {namespace: gateway, server: 'https://kubernetes.default.svc'}
    - {namespace: tailscale, server: 'https://kubernetes.default.svc'}
  clusterResourceWhitelist:
    - {group: '*', kind: '*'}
