# https://hub.docker.com/hardened-images/catalog/dhi/nginx/images/nginx%2Fdebian-13%2Fmainline/sha256-12e286038641ad2919be50aec641eb6eabfc7f68d1ad8a8991cf6b8a922b2bf2/specifications
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  namespace: lldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lldap
  template:
    metadata:
      namespace: lldap
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: {type: RuntimeDefault}
      containers:
        - name: lldap
          # Dockerfile: https://github.com/lldap/lldap/blob/main/Dockerfile
          image: docker.io/lldap/lldap:2026-02-27-alpine-rootless  # renovate: docker=ghcr.io/lldap/lldap
          # command:
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: {drop: [ALL]}
          resources:
            requests:
              # cpu: 10m
              memory: 128Mi
            limits:
              # cpu: 100m
              memory: 128Mi
          ports:
            - {name: ldap, containerPort: 3890}
            - {name: ldaps, containerPort: 6360}
            - {name: http, containerPort: 17170}
          envFrom:
            - configMapRef: {name: deployment-env}
            - secretRef: {name: lldap-env}
          volumeMounts:
            # - {name: tmp-volume, mountPath: /tmp}
            - {name: lldap-config, mountPath: /data/lldap_config.toml, subPath: lldap_config.toml, readOnly: true}
            - {name: cert-volume, mountPath: /key.ldap-karlsen-fr.pem, subPath: tls.key, readOnly: true}
            - {name: cert-volume, mountPath: /cert.ldap-karlsen-fr.pem, subPath: tls.crt, readOnly: true}
      volumes:
        # - {name: tmp-volume, emptyDir: {}}
        - {name: lldap-config, configMap: {name: lldap-config}}
        - {name: cert-volume, secret: {secretName: ldap-karlsen-fr-certificate}}
