---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - {name: lldap-config, namespace: lldap, files: [lldap_config.toml=assets/lldap_config.toml]}
  - {name: deployment-env, namespace: lldap, envs: [assets/Deployment.env]}
  - {name: bootstrap-env, namespace: lldap, envs: [assets/bootstrap.env]}

resources:
  - Namespace.yaml
  - SealedSecret.lldap-env.yaml
  - SealedSecret.bootstrap-schemas.yaml
  - Configmap.avatar-sebastian.yaml
  # - Secret.ldap-karlsen-fr-certificate.yaml
  - Certificate.ldap-karlsen-fr.yaml
  - Job.bootstrap.yaml
  - Deployment.yaml
  - Service.web.yaml
  - Service.ldap.yaml
  - HTTPRoute.yaml
  - TCPRoute.yaml
  - TLSRoute.yaml
