---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: lldap-db-credentials
  namespace: cnpg-database
spec:
  encryptedData:
    password: AgBqzc5HoVU9FM0EMoBxfRUCvmI44W5PhpccnPIRW6HSGoYEV/rhKbo+GuoMwIhSnJNl257eUjmw3Cd1SfBhFSFbdE9fUPLGvLgZ75qhMCRqiaxMrOh/kBs1jIMjDEICG6Dpd+9cQphITUQWApJf66ns668ObwRHOu6bQDY3sAEi9sLjOcjrJLKDL7SLlAl75STiQzTIoWuK4/pzGf2FHGgyCwAuiN/M/uQuNuj818vqLg0ITeQksq0dMIpX9EGRcf1cqxTLaJUdjL4eb7j7ReEbNFVhf32+t+CPN0mwplVfgNdu5fuPdwMIgb1J1Cjw7ZmuzN4hwmxB5yWk9YalMyFZhBe5zB+65kIKfPteM6eKCtWVNIhhFgAXFnkfMAJFHIb+4DqaCaw8QXRt6r80Wmg1W2g3e+j8OigUIF1EZyu7yldjlnskTjVKaC6KxwuVgHeCZf4IDXwMvGoiKLXx8tStdvtpAlsdLuzdHJXt2AAjwQ7B7JrFPDDHc/0P0vIrvlZVjf4HKIktVKd5KPR4Nj1UcS/ajEWQQ1/c6r1f2rWnt31ygsTksYExXzBGdIBqdKfmFK/7a6xvMAmFsRAlu9h1JoaNWfnt2RA5PRzf1FM8Z+6m4xhMzVUFEzm03YCwcRDVH0Ys3uqyuEq5DJvhVlKL6H2UMP3npI/TdPlq8s+b2X7wOkycpFrGbF0jCIuRo5kZa0+2nLntRc79oAUiIngw5ypzzGcZX1celWPfP3TeX6AcHR8fv9tRywefe2YTCBs=
    username: AgAb2h5prTKHhj3ZRyVEnXbbQSB3H0v/QCjkfSz3a0ulTdDM6jR3EzapNz1L2IimZ/T/XphU7FvN6gd8AhL+xbVyzE/b66/QrR4ZfzklsSAOkWX/8ZNo4ZqszfAMstj/nAfbrb8rAS8zfPWmAA8z+AHET4SYkyb5QFIprEulRmfgKO7CODoeWjTuPy1PadUqvhLMxrptzrbiLxVB7HWX+lTS1qXroT91pxKQ0+dEtG3tW/frU0hglgb3mqTvpFkyNrFEH3DPPxFNvdLiDQCkLFyh5T8Hk1ZtCmQo1ucTUwFgk6Tl8oQrLzuP1tSgKaf/tZi0TWnBkwNzbQ+j9wviWTuvTQqlRrP5R0KXdWfDwWo8Bo9CHVLgeeFSHXsEFpEORemwFPehzk+q8R5rnTcwovlwlYN2TCzMJLqd8dK5+bywVep7O+Epr691UIeIPN/HRs3uBxI4PK3CE8VofjLp2VHXW8vWLlC9s90jdRoB1ZGBepuia57+xJZmbXTXiE+C5YHaHRMiHfnFDEbUmiXtIa2XCz55qlSoi8bzsaanEFbtIBasCy/x54hCipD3BFHy3m3L4mAzAhoiSV3lobN4OsJgMI56GP7oP3fbQrDh8+VvfBPjwYA60j8gqco3XdsU2OxhXZ2cocC+Nt1CEjn2HnEQAZCC51tY6lhCjVpHrYKdyRUpWtCGo46SsMWi8CDQqILMxYYLf0X75EV/sAI=
  template:
    metadata:
      annotations:
        kustomize.config.k8s.io/behavior: replace
      name: lldap-db-credentials
      namespace: cnpg-database
    type: kubernetes.io/basic-auth
