---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: lldap-db-credentials
  namespace: cnpg-database
spec:
  encryptedData:
    password: AgCWwgex0GJ626iXpgS+VWcGpfAgzhrTl0czCqCEt5DmZANPWLtqWba1Cx1nhdEj9gN6ApRVzllJir/kls6d/O3qnwP2k5cBVmZjHiz7ddDDulxyk4/B6nEebCzBsaQ/yRR7BGcPErWaAjh5dvNz0uRTjz6jca5kKoXhLJf00lVLfPn+rXqKNH+T+urQHkAmoE4rCVgq1GnTW5tYNDlUBWo1BMZamKNfcpsWojedSUsLd0z1GOlnqZSJI1Uw/HtAxENKBOI35od4hFhf09G1FOSpqTfXwPklTar5Z02XSojgIBAevTARekyev2e62bIBulsXN4mFqD2EoXI0Q/C6ROlY8YStV9V3QzaiJeCpvDKyXGpAMFl4iI2f2+wZC/OARz3ih5YSR1J0kpT1uqqfuwdrTpNJSAylx+KhNPY/t1otOddL1aJAPk5g6xR79dYjWpwpjpSDnWmg8SBv5VMUlfW2bMzmnD0qUll3rmr0Da4Sjb2xtc6QkWT6UzFamJdnWBYyo1Wi/CGE1DICUkRebzew8/alKoGeEpEvBeKVX6ffR649LtKfavYJ7PoxApkKkpw1XhIJVWrJ79Y3LdnRaI7uXRWNUgvHkPEdr8ZQ3M01iTrUHK/sIq58g8EBoj4ZacWVa71PO93FDnTUmk/daDoIz+4YRnFdsTTtzvtlmdOJljjLrzThRamRRY5gnaw0OOUxED/YbwXRWa9WOVe4KoCUdCeEkBv+qYs+zJPXnEseLbtiSZq1y/m/zS+ycwMlo4A=
    username: AgBUAVTNcxOPDlCmBsJkrjLkEcDsJXyu/zdwDwHTrq0xwQQiEkyE16BlnJ7SeEZuXXJ1n4Ze41ElCpGrUK4NqjJ93j5rvd49GWkC/PYEHq21S//tE/B3g4GSVHHzb4wzsn8EwzAmuSGZ+PaGGBujhcjqqwONxchsybkm1AocE5Ef7FU4iMMOHwF4b6MWJVc40sVlcorVgec+gmKtn4t6iBgjnNmRQH036/FGpo5Eo5LJLsfll2VWZu8fHCBi1xfeE3j3emo509y7kdt6EuiW39MJ8xSbXYVpphXLsaNN863YrnbrdjrF1fgmDZcb58mGA3nUXMihpShxJtu9gj2OJpSwNSX6VsF74etKvd6Psvry7N3jmUhnRVzYn0CrsVC33Qqkav4z4wGsMj0XpbUkBE2R7pPuWOaAKtoq20MS+p+UVcSsCHN1fuF4C4+r7GuqCbAVepolxO+Updi4PfU2oQQ0OcQ4IHhr9ciIDiAneKk6icvYTPCIL0BHdabjIzRz1BOZJb1lF/bXV0huKv8latCNOB51IbBO6umQ+dUUGBmzvegxvJhWyueKZzvSF9Jp9Wg4TfK8ophJ8Ne3UTslMFw1AcS4YqdiqzDsE1B7VLAixPcdhmQ9oqYdlyysN8DzdX4N9zWPCY3Woo6zTf8MoT2hBOn9gwHmQY0kJou4gOZQYdbmlBvnu5kCVN3SoPMtcPKM9EBRUg==
  template:
    metadata:
      annotations:
        kustomize.config.k8s.io/behavior: replace
      name: lldap-db-credentials
      namespace: cnpg-database
    type: kubernetes.io/basic-auth
