---
apiVersion: v1
kind: Service
metadata:
  name: ldap
  namespace: lldap
spec:
  type: ClusterIP
  ports:
    - name: ldap
      port: 389
      targetPort: ldap

    - name: ldaps
      port: 636
      targetPort: ldaps
