---
apiVersion: v1
kind: Service
metadata:
  name: lldap
  namespace: lldap
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 17170  # http

    - name: ldap
      protocol: TCP
      port: 389
      targetPort: 3890  # ldap

    - name: ldaps
      protocol: TCP
      port: 636
      targetPort: 6360  # ldaps

