---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hetzner-s3
  namespace: velero
spec:
  encryptedData:
    cloud: AgBSZjpg1mbSaxmXNgjlRjUV5qz7kQeTMKeU8D3a8/APgsVcvuEef+ZY5OnEV2L8VmJTAxkR6S2MV05F+vGdC9OdFeaGRw+oVyLoylx08ov1v5lDoyee06AzdMtt7h0j6Nalsdf/poc/tZB2Dr/nlbI/OKDdaf1ZPMaUkJF4p/sMTqSBHKf45zq1exLGJejcQ8FqEM5KHuqzARxr4SoPXJRGK3rrCVdSgtIX8PaFmJ9urVcq44Z+6kDzm9peKa1m57ToI01zqDTb0qyOc7m8ZpSIJlR5Tw89090ngvP2kgV8LCeR6M2BPHhSKyPZs/q4GjaAEo2xyHf5PhTs6aoho58dmOfGew7wNdR6baOi3G66YVj/p7cvw4BDAT5abQk6VXqPwKlqu673BRhiqs8R9aP71WqEDyoH/aQLjoXV5eikjW5z7QP2Ob+xe5AM4tpKrT0bPyTiLXRoQgjaDNiHqzXgsTAxgZS0BCc2mMkthW5ywkXN15k6gNXtjM3BQltXpMwGQ2JtKqr7+4ixZHP9rOYVOt7+cBIwCHx4b7SnFFv6ExGcxCOGQD5SDE9dxuTdBuU+Mbzfp5qIx3X0zZAudUW29RIPZODen1Ia4BQ02fiVxYCw/t07SMBf8RJsM1sXnldSCYqEkSOW8pUigE03Kt6PUXI4clrbngJQgoqzSaJ0Fh1lzWKElqsK9nYUM8qa63FQEu+G8xWK8sbOHHze2UHUDYtWJAEa1LnrxO/+NtrIJ86mTWoHW1UDrGL2g400Hf7AXgapofUgTePZkbo9wEdkF6RcL0G+lIp4fOORgCFy3NEO44AnhGQ51yRg+6EKH/JMpDTDXf1GbeBli5h4GdE9
  template:
    metadata:
      annotations:
        kustomize.config.k8s.io/behavior: replace
      name: hetzner-s3
      namespace: velero
