---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-mariadb-backup-egress
  namespace: databases-backup
spec:
  endpointSelector: {matchLabels: {app.kubernetes.io/name: mariadb-backup}}
  egress:
    - {toFQDNs: [matchPattern: db01.hera.home.karlsen.fr], toPorts: [ports: [{port: '3306', protocol: TCP}]]}
