# https://medium.com/@Vishwa22/mastering-kubernetes-cronjobs-the-complete-guide-for-periodic-task-automation-2d2c0961eff4
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: databases-backup

resources:
  - Namespace.yaml
  - ServiceAccount.yaml
  - PersistentVolume.yaml
  - PersistentVolumeClaim.yaml
  - SealedSecret.mariadb-secrets.yaml
  - SealedSecret.postgres-secrets.yaml
  - CronJob.MariaDB.yaml
  - CronJob.Postgres.yaml
  - CiliumNetworkPolicy.mariadb.yaml
  - CiliumNetworkPolicy.postgres.yaml
