# https://hub.docker.com/hardened-images/catalog/dhi/nginx/images/nginx%2Fdebian-13%2Fmainline/sha256-12e286038641ad2919be50aec641eb6eabfc7f68d1ad8a8991cf6b8a922b2bf2/specifications
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stork
  namespace: stork
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: stork
  template:
    metadata:
      namespace: stork
      labels:
        app.kubernetes.io/name: stork
    spec:
      securityContext:
        # runAsNonRoot: true
        # runAsUser: 100
        # runAsGroup: 101
        # fsGroup: 101
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: {type: RuntimeDefault}
      containers:
        - name: stork
          image: index.docker.io/library/alpine:3.23.3
          command: ['/bin/sh', '-c']
          args:
            - |
              set -eux
              wget -O /etc/apk/keys/stork@isc-6914F776A579B428.rsa.pub https://dl.cloudsmith.io/public/isc/stork/rsa.6914F776A579B428.key
              printf -- 'https://dl.cloudsmith.io/public/isc/stork/alpine/v3.23/main\n' >>/etc/apk/repositories
              apk add --no-cache isc-stork-server isc-stork-server-hook-ldap
              env | grep '^STORK_' >/etc/stork/server.env
              stork server --config /etc/stork/server.env
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities: {drop: [ALL]}
          resources:
            requests: {memory: 128Mi}
            limits: {memory: 128Mi}
          ports:
            - {name: http, containerPort: 8080}
          envFrom:
            - configMapRef: {name: stork-env}
            - secretRef: {name: stork-secrets}
