# Encrypt: sops -e Secret.stork-env.yaml > Secret.stork-env.enc.yaml
# Decrypt: sops -d Secret.stork-env.enc.yaml > Secret.stork-env.yaml
---
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: stork-env-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - Secret.stork-env.enc.yaml
