# Encrypt: sops -e Secret.cloudflare-api-token.yaml > Secret.cloudflare-api-token.enc.yaml
# Decrypt: sops -d Secret.cloudflare-api-token.enc.yaml > Secret.cloudflare-api-token.yaml
---
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: dhi-io-registry-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - Secret.dhi-io-registry.enc.yaml
