# Seal secret:
# - kubeseal --controller-namespace sealed-secrets -o yaml -f Secret.stork-db-credentials.yaml >SealedSecret.stork-db-credentials.yaml
# - kubeseal --cert "$(dirname "$(readlink -f "$TALOSCONFIG")")/seal.crt" -o yaml -f Secret.stork-db-credentials.yaml >SealedSecret.stork-db-credentials.yaml
# Unseal secret
# - kubeseal --cert "$(dirname "$(readlink -f "$TALOSCONFIG")")/seal.crt" --recovery-unseal --recovery-private-key "$(dirname "$(readlink -f "$TALOSCONFIG")")/seal.key" -o yaml -f SealedSecret.stork-db-credentials.yaml
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: stork-db-credentials
  namespace: cnpg-database
spec:
  encryptedData:
    password: AgBG7iB8U0C1ROV8BqxjHoU7+XAIg51Ddm67JVP/IgDwdhqyAHiDrYRdivEa5AUTM62RMB+f6kwqPi5WHCsKtSz+DH4rM0PkKuzLuXoUe0hZmfBuOsbQojFDzwgbop45HouMW0P7MeXwOgn/P+Ie/0h0AbLY7mCDVhSz3oLEv0t+sMoVyyHDK8vtYMXjo7SC774gLPF11MAMFLSj9WPfNq6VTNeWBe4YMWbgkKBgVBeG+li9BTbbAMPnsk8uD9Qqg5AMKvlm/jHdpBcoo0stvGkL6P5vs47HjSMAH2AdDvbR2Da6VFwPvJ6Z3ft/sySIFgYTD+WSqnJRqu6pJt5WNcd+vMN6oCvfNqze5WUlblZAq5VsEDUynBtc+bdPAWqPeqoyp3JdiGhfv4z5XpHSO4hOkYeD7iK/p1lbiR8OGvzw+REKjAFgPkgqy+G9m2lXlbeoYHrpiGJ9AlwPQntQaUUPOOrrVtU31RRPZTcmtEEBGSzZhPUL3RmSK/CbZeMF32Pyv73NM0jgu9vNBbd/Oow3zEbaE2p0N571AedVuuwOQHQkGBSkTb/tVXpPsrPTOtImmbg3VSOyG72Cs6KM5xLl4jbpgudiCArpSmGpWQhBCMBbYhdl6L1iR7YwrCQqFhHgU3B0Bw0ERptLIk3A6EJayDTW4Gb1MSr7E2n0yCvA4bilSTPJGRtNypjJNIxmwXVFZ1oN+xhMQGQFVv18MnM4mMcZ66Iy5AZqbBGXhIv7Gw4Cqvd5ftP7mQ3wJYSHQUI=
    username: AgChfgoHZ8M6/2xDjWtk3Eya97c5rR9DspA7lmyPUU6F0f7svsaDPlHwb8QeXAqqQzKMqUy1neNq5TJ9wlPK82YOfEGOdMtzOHhD1oPUTboEh0hcVuFp+hxlyXtGtyOMNd+UG+UhWkOi284YTAsury7f1eo3lhG+Hucyuz9O51+ekOx8TPZnPRd6dmZzTHh9VsJNDNj6fmTUv+oTjVvbvQ86pGywhZGli9YYfQDUz88xu9J2830XGKUHRLAGeAG6QikTpxeqrIwXW+969lqQzfhWO3hknJOka0UUDUWJR2O1sN9VXoQq81nVHSFFy8svz10VeXYc3sM9Z8UES+RnpuUuKGc+bwD1fuBe1VPm8jKz9sk1qqeqibHUboBocVV7/FkYNkQV7or9tk+YV8g3rPAwcqOEJY7tawhk97JY5+WAV65ytrI2W++jKa+JimGLoN33wnUnsnyb9TWtdmSjAn5MhJT2mJOKF5LRgdESqYYWYmqrp2wPHd8oizwYgC+zeF4CA7f2xIp+2T6/fto5RxwtTgLyWHXw7dZtdx4hjj2A5dWKtFMnOXmykN6ShyF9GrOuA1jnmAWUE3hOkgDa3lxbxrcIyvQ/2rpB6DdbsYcFb70Wv4H5YDCyAc3PAIruHLRyjBbYrAD2yG8Bt+Ske/5H+fzl65Lnp6YBQVcGEjc4x0kF56y2AUHw91tjGFPl7u3up3XDJN4TnJHp/MQ=
  template:
    metadata:
      annotations:
        kustomize.config.k8s.io/behavior: replace
      name: stork-db-credentials
      namespace: cnpg-database
    type: kubernetes.io/basic-auth
