---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: stork-secrets
  namespace: stork
spec:
  encryptedData:
    STORK_DATABASE_PASSWORD: AgB/AT0b2mwFc6lOdFywe6VRqO00xIrQzwk1HBvpeUQXX2y5yfdD9NE4NPCa4oaoFF/6byFjKrajH4/KhPUPYC3JO8youFDy+RdnpBYx8GMWgC7TA/oLT52Yw9FvvMbk0CJH1g00P7m/xFYmNoWtFdvVBrkBdWp8oybOan4BsguRUkwz3vT/6tm2eq83TcereIAZh2vYQWc2uh7O2fQwhyxHp7jpKs87nsuOEEYVxEIR3XAQWnSn14bk841749glgMb5aBJryjXQwQEq1KFUmVS4PTaEXuy6rZ5Tq4y24dsPxvJqFadC7DWiA4OWSSYlqZmCWewFgcASsca5AFFj4vkwwwommBjz2uJDQ0MRZBHW+FhlbpQctd20bncxZn0M+N99CaYvEktKBCh57wDRJzgnFmagvxxlIhNAUkeVK8lALZK6XNuR9ZMXPscRB9AYzYoHIkYTakVdKZu2lkhlK4HZpLPjYM849r66F/0fDj9kgagmEYs1MMUkr6A8R1lCyFQFg5/Vjix/q8++L2rm7bfpNZyjiI1oMHSCoGDYTvrKgJ3ljaeRZ35rEJ4yu0VPzlYxoZrQ3ebzmlMhniz+hDc4kryiBb7JUSrXrWkmhbOnTsq7JwNI7dcTCt67Tr3rKyJo+EZmyAf9KBIdIGc11pMY9/OyP3GnZA+559LV43woYN4EyVeH55Z4NXWR26ZKhP02CoLb7Env/KQIXWqv+pYJZlysqjBbfFCGMXEWVap/FX5rsaNlC0IY6cas/c70/yE=
  template:
    metadata:
      annotations:
        kustomize.config.k8s.io/behavior: replace
      name: stork-secrets
      namespace: stork
    type: Opaque
