#ENC[AES256_GCM,data:uBWYwEPy6sX+esKQrwSGKN8D7pbf7LpLO7AJMchFGM/xKVkt23x8EF8a4wo4RVHIgHHAlb+9f08jnN5SWb7esPx8cg==,iv:0OqkpscXKvPrJFmBmYJpEXTZix9QhgIvpHM5lMFOY88=,tag:irHdOhg0PlXG6Y8eMH4WGQ==,type:comment]
#ENC[AES256_GCM,data:CyDv+08R8adf0ojm28yuw6vRvZvK4pmyml8A7co9Z3OcBmueSt8zEt010bnXreuVn4Z5eAtZ7U3S4Rs6sOLTBwuWgA==,iv:AKjnLMbVOE0H4DpZZAUZtaKCXuLr/2Lbv+ojtH5RRu0=,tag:jdLDslsBHm+tIzjB8ewPtQ==,type:comment]
apiVersion: v1
kind: Secret
metadata:
    name: stork-env
    namespace: stork
    annotations:
        kustomize.config.k8s.io/behavior: replace
type: Opaque
stringData:
    server-env: ENC[AES256_GCM,data:DKplVDArAgiK0sTUzfkYbLs80G0jasiWU+BK0ht96G6UoiBQZ1RbKjKY6HTlIIsHPijBhNEBS+10t4nIZDatH7TXt+pSzg9OcI4SIDxh4mYmQY16sfh+3dNBl4d348cbSmaKGI4v/qyP66zTP/KP0vfJkbjYbv8b8IAZ4qpVnmftCO5lMhLKrvBpWhfiTJz+TekzpI3FSWmQWJHlf0kQf8vPK6qsKooYvd5x9FD8utNFM0OfdhlCrIZAXkkHQ3WLb/fhlIkC9WZ5PAFrCx1LjKUQ+PHbysQPNga/44aVKmtYpku/W/iOuq/hgZ0odmDra7wO+uG1Q6iDFnO/8WXtM6Tp6lkC,iv:LZf7v+riwFlvMs3aHGI96kkfZtLpTMvPQo8pL+vjl5M=,tag:r6+gNs5W6DqvL+v2ieGRWA==,type:str]
sops:
    age:
        - recipient: age1u8uutg4mpsn82nd9y828sj5agg7s89uswmp7frzpkrruhgw6xcuqr8hvf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJRktHS3Y3Ym5weFRIY3c5
            UkYxaFNWdUUyRDBlbEdLcmkzSXl3NG52cWtnCmZvR0tocTBhZEl0YktYUVZSODJS
            MnlyejJCUkpIZWkyQlhLaWRrbU4yL0kKLS0tIGJ0MDVuTEd4aERydVBJcGtydFpF
            eURyM2xmL2JjWFZKRnI5cytIL3JpS0EKvT4pPn9kFTIWK6G6z2exEMNRIXoixp9t
            5yBiG7f+aJn/z/oflIGIoCzodTLEzF/wIZu/gNR1RnMQwHrG9vrZBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-10T16:21:01Z"
    mac: ENC[AES256_GCM,data:+TjMHodktAA2Sd6Bd52QLgMA0K69cjvp83mdPlBwwU1S9Yt1JLYwoFBPUYiBvI4R4UWNjh/c0IkzIEuBJ0IiXBUbTp7660tQxZrbf8Aiz5JTXNtyZBPSZIl7B97kR9UTkp9Diwja0bLJM1GJB7Y3ASrpty05IyyztddWmeqeoAU=,iv:Dofyijb7Z+m8emmJlLJORJv24dmFI4arSox17GX0SaE=,tag:c0T1eBHDlnh94o8bF4XKBw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
