#ENC[AES256_GCM,data:C33Hwn622eeh+Fj6ofMxvRzZAJPzwWkocwmJOAHuIN6DELjCMg+HQwdTTydqHGD4brDrbDdeu71O+ltB8BmOv45WiTJeAhXis2YJI/99Bw==,iv:o5yNjAV3y7Hq2pDkZ70DixPuFn7dc4cbWmqGfMM2P0o=,tag:puNhzdB3A+87gaMja5AUxQ==,type:comment]
#ENC[AES256_GCM,data:G0CttYBj4p3T8MCc9tbHp2901NpPQUdqMLQ2JMM08tDn0ky7PcPZ5kz6oF89AR2i3wWcxZo3hf96QtBbN31V17VTFdQNLqxUchbwYmIcpw==,iv:C5OUcxL1Cv9oRB6jDcxYuLAMU57wjTKD4B2J3Bs9TjI=,tag:ZlV/7D7KfrUe8pCmrK3VVA==,type:comment]
apiVersion: v1
kind: Secret
metadata:
    name: dhi-io-registry
    namespace: stork
    annotations:
        kustomize.config.k8s.io/behavior: replace
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:ew8XzbP42xSc1RGSlq/OGVwyEcDRCJEtag51SRtgH6MdhlPV6Y5npGqfWEYxMyM4r9Wt72wkRxJxycoFq0gCJVb2ZZVHsKQkHb4CsO6wG7sUOPNG7h71hH5FZElykft4T4oFPzhpOv3xkrmoToxzxWJ3f8+/0okD+Dkgh08vT0jXtZ9D4DTigZ1KQ/EWYYHSgLPWfF36NNem2XAt5bGLBfXtIjLi+ZAVWXMxbXtug3eu7GV9amnxrpy/Vn6RRKr0ltIRrdqnVWrI/4a2zWG23eE4kxAFoqnKZjRR1UNV9vi6LGTDBLtAJYznwUhehjcAaxCjHoIEyEmmTbp1mv9XvUYQuz4=,iv:VwLp5OMpsPUhnIr0WZJAdWtvWXCEDnmWzsaH7kBPcuo=,tag:QF9bu4fxctpaD5taHL3zNA==,type:str]
sops:
    age:
        - recipient: age1u8uutg4mpsn82nd9y828sj5agg7s89uswmp7frzpkrruhgw6xcuqr8hvf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpNGVRR1haY2gwOTlIUDdn
            VTljaVdNUzhvc0hGZlRWaERSL3ZHVTNBWm5NCjZRR0FIV0FSam85dTk5T2xVeldV
            Mjh4a2Z5elVxOFVSaEhaaUFGV3lVdTgKLS0tIGFWdkRTWjVBelRTbWt2RmZLT2xS
            VWtDMHlBVnpZWUJqSisrWVA1Z2h5U2cKWwo5V7d8Psrm2F209hEJvVstMdDRBcmF
            Iz4QT4UNfkzjB0vUahtDzC5zN2CaCTwdoKcAqKOPsSpYMdEDjy2G1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-10T14:34:09Z"
    mac: ENC[AES256_GCM,data:wtaaBng/kbqfnFoz3PdYFpCK3hs0OhsIl3ZMvxmImjHHNhJHbxJMvqDJSX0Q0Rs1lo8wWaM2XkYYrXSbr+LS8p6cQCT29pv3tEddQAxZ4cIJ50sXylNlTlDBYl3njm3chDarIQl9K6iPRNslcfES3rXITLe4XuhsdfinE8tfUU0=,iv:7CErpFTgbon9QBdOd7abg8adwJ+QuYcQRB1GJIbWb70=,tag:mPjR7UAfElRXzlM2WLCf3Q==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
