# yaml-language-server: $schema=https://raw.githubusercontent.com/authelia/authelia/refs/heads/master/docs/static/schemas/latest/json-schema/configuration.json
# https://github.com/authelia/authelia/blob/master/config.template.yml
---

# Miscellaneous:
# - https://www.authelia.com/configuration/miscellaneous/introduction/#default_2fa_method
# certificates_directory: '/config/certificates/'
theme: 'light'
default_2fa_method: totp

# https://www.authelia.com/configuration/miscellaneous/server/
server:
  disable_healthcheck: true  # Required for readonly root fs
  address: tcp4://0.0.0.0:9091/

# https://www.authelia.com/configuration/miscellaneous/logging/
log:
  level: info

# https://www.authelia.com/configuration/telemetry/introduction/
telemetry:
  metrics:
    enabled: true
    address: tcp4://:9959/metrics

# https://www.authelia.com/configuration/definitions/introduction/
# definitions: {}

# https://www.authelia.com/configuration/identity-validation/introduction/
identity_validation:
  reset_password:
    jwt_algorithm: HS512
    # jwt_secret: AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET

# https://www.authelia.com/configuration/second-factor/time-based-one-time-password/
# totp: {}

# https://www.authelia.com/configuration/second-factor/webauthn/
webauthn:
  disable: true

# https://www.authelia.com/configuration/miscellaneous/ntp/
# ntp: {}

# https://www.authelia.com/configuration/second-factor/duo/
duo_api:
  disable: true

# https://www.authelia.com/configuration/first-factor/ldap/
authentication_backend:
  # password_change: {disable: true}
  # password_reset: {disable: true}
  ldap:
    address: ldap://light-ldap.light-ldap.svc.cluster.local
    implementation: lldap
    base_dn: DC=karlsen,DC=fr
    user: UID=lldap-admin,OU=people,dc=karlsen,dc=fr
    # password: AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD
    attributes:
      extra:
        grafana: {multi_valued: true, value_type: string}
        sshpubkey: {multi_valued: true, value_type: string}

# https://www.authelia.com/configuration/security/password-policy/
# password_policy: {}

access_control:
  default_policy: deny
  rules:
    - domain_regex: '^.*\.karlsen\.(fr|app)$'
      policy: two_factor
    - domain_regex: '^.*\.talmox\.hera\.home\.karlsen\.fr$'
      policy: two_factor

session:
  # secret: AUTHELIA_SESSION_SECRET
  cookies:
    - domain: karlsen.fr
      authelia_url: https://auth.karlsen.fr
      default_redirection_url: https://www.karlsen.fr
      # name: __Host-authelia_session
      same_site: lax
    - domain: karlsen.org
      authelia_url: https://auth.karlsen.org
      default_redirection_url: https://www.karlsen.org
      # name: __Host-authelia_session
      same_site: lax
    - domain: karlsen.app
      authelia_url: https://auth.karlsen.app
      default_redirection_url: https://www.karlsen.app
      # name: __Host-authelia_session
      same_site: lax
  # name: __Host-authelia-session
  same_site: lax
  redis: {host: valkey}

# https://www.authelia.com/configuration/security/regulation/
# regulation: {}

storage:
  # encryption_key: AUTHELIA_STORAGE_ENCRYPTION_KEY
  mysql:
    address: tcp://db01.hera.home.karlsen.fr:3306
    database: authelia
    username: authelia
    # password: AUTHELIA_STORAGE_MYSQL_PASSWORD

# https://www.authelia.com/configuration/notifications/introduction/
notifier:
  # disable_startup_check: true
  smtp:
    address: submissions://smtp.domeneshop.no:465
    # username: AUTHELIA_NOTIFIER_SMTP_USERNAME
    # password: AUTHELIA_NOTIFIER_SMTP_PASSWORD
    sender: Authelia <noreply@karlsen.fr>
    identifier: smtp.domeneshop.no
    disable_html_emails: true

# https://www.authelia.com/configuration/identity-providers/introduction/
identity_providers:
  oidc:
    # hmac_secret: AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET
    jwks:
      - key_id: default
        algorithm: RS256
        use: sig
        key: {{ secret "/secrets/jwk-rsa/tls.key" | mindent 10 "|" | msquote }}
        certificate_chain: {{ secret "/secrets/jwk-rsa/tls.crt" | mindent 10 "|" | msquote }}
      - key_id: ecdsa256
        algorithm: ES256
        use: sig
        key: {{ secret "/secrets/jwk-ecdsa/tls.key" | mindent 10 "|" | msquote }}
        certificate_chain: {{ secret "/secrets/jwk-ecdsa/tls.crt" | mindent 10 "|" | msquote }}
    cors:
      allowed_origins_from_client_redirect_uris: true
      endpoints: [userinfo, authorization, token, revocation, introspection]
    claims_policies:
      argocd: {id_token: [email, preferred_username, groups]}
      forgejo: {custom_claims: {forgejo: {attribute: sshpubkey}}}
      headlamp_policy: {id_token: [email, preferred_username, groups]}
      grafana: {custom_claims: {grafana: {attribute: grafana}}}
      legacy: {id_token: [email, email_verified, alt_emails, name, preferred_username, groups]}  # https://www.authelia.com/integration/openid-connect/openid-connect-1.0-claims/#restore-functionality-prior-to-claims-parameter
      username_email: {id_token: [email, email_verified, alt_emails, name, preferred_username]}
    scopes:
      forgejo: {claims: [forgejo]}
      grafana: {claims: [grafana]}
    clients:
      - client_id: argocd
        client_name: Argo CD
        client_secret: {{ secret "/secrets/client-secrets/argocd" }}
        public: false
        authorization_policy: two_factor
        claims_policy: argocd
        require_pkce: true
        pkce_challenge_method: S256
        redirect_uris: [https://argocd.talmox.hera.home.karlsen.fr/auth/callback]
        scopes: [openid, groups, email, profile]
        response_types: [code]
        grant_types: [authorization_code]
        access_token_signed_response_alg: none
        userinfo_signed_response_alg: none
        id_token_signed_response_alg: ES256
        token_endpoint_auth_method: client_secret_basic

      - client_id: argocd-cli
        client_name: Argo CD (CLI)
        public: true
        authorization_policy: two_factor
        pre_configured_consent_duration: 3 months
        require_pkce: true
        pkce_challenge_method: S256
        redirect_uris: [http://localhost:8085/auth/callback]
        scopes: [openid, offline_access, groups, email]
        response_types: [code]
        grant_types: [authorization_code, refresh_token]
        access_token_signed_response_alg: none
        userinfo_signed_response_alg: none
        id_token_signed_response_alg: ES256
        token_endpoint_auth_method: none

      - client_id: forgejo
        client_name: Forgejo
        client_secret: {{ secret "/secrets/client-secrets/forgejo" }}
        public: false
        authorization_policy: two_factor
        claims_policy: forgejo
        require_pkce: true
        pkce_challenge_method: S256
        redirect_uris: [https://git.karlsen.fr/user/oauth2/authelia/callback]
        scopes: [openid, email, profile, groups, forgejo]
        response_types: [code]
        grant_types: [authorization_code]
        access_token_signed_response_alg: RS256
        userinfo_signed_response_alg: none
        token_endpoint_auth_method: client_secret_basic

      # - client_id: harbor
      #   client_name: Harbor
      #   client_secret: {{ secret "/secrets/client-secrets/harbor" }}
      #   public: false
      #   authorization_policy: two_factor
      #   require_pkce: false
      #   redirect_uris: [https://harbor.karlsen.app/c/oidc/callback]
      #   scopes: [openid, offline_access, email, profile, groups]
      #   response_types: [code]
      #   grant_types: [authorization_code, refresh_token]
      #   access_token_signed_response_alg: none
      #   userinfo_signed_response_alg: none
      #   token_endpoint_auth_method: client_secret_basic

      - client_id: headlamp
        client_name: Headlamp
        client_secret: {{ secret "/secrets/client-secrets/headlamp" }}
        public: false
        authorization_policy: two_factor
        claims_policy: headlamp_policy
        require_pkce: false
        redirect_uris: [https://headlamp.talmox.hera.home.karlsen.fr/oidc-callback]
        scopes: [openid, email, profile, groups]
        response_types: [code]
        grant_types: [authorization_code]
        access_token_signed_response_alg: none
        userinfo_signed_response_alg: none
        token_endpoint_auth_method: client_secret_post

      - client_id: mas
        # https://element-hq.github.io/matrix-authentication-service/setup/sso.html#general-configuration
        client_secret: {{ secret "/secrets/client-secrets/mas" }}
        client_name: Matrix Authentication Service
        public: false
        authorization_policy: two_factor
        pre_configured_consent_duration: 3 months
        redirect_uris: [https://mas.karlsen.fr/upstream/callback/01KPNSVGCRHBYC9MY7A9P40ZPQ]
        # logout_uris: https://mas.karlsen.fr/upstream/backchannel-logout/01KPNSVGCRHBYC9MY7A9P40ZPQ
        response_types: [code]
        scopes: [openid, email, profile, groups]
        grant_types: [authorization_code]
        token_endpoint_auth_method: client_secret_post
        userinfo_signed_response_alg: none
        id_token_signed_response_alg: RS256
        access_token_signed_response_alg: RS256

      - client_id: portainer
        client_name: Portainer
        client_secret: {{ secret "/secrets/client-secrets/portainer" }}
        public: false
        authorization_policy: two_factor
        require_pkce: false
        pkce_challenge_method: ''
        redirect_uris: [https://portainer.talmox.hera.home.karlsen.fr]
        scopes: [openid, email, profile, groups]
        response_types: [code]
        grant_types: [authorization_code]
        access_token_signed_response_alg: none
        userinfo_signed_response_alg: none
        token_endpoint_auth_method: client_secret_post

# https://www.authelia.com/configuration/miscellaneous/privacy-policy/
# privacy_policy: {}
