# https://docs.cilium.io/en/stable/network/lb-ipam/
# https://blog.stonegarden.dev/articles/2026/02/cilium-dsr/
---
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: default-arp-l2-announcement-policy
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  namespace: kube-system
spec:
  externalIPs: true
  loadBalancerIPs: true
  serviceSelector:
    matchLabels:
      arp.cilium.io/announce-service: default-arp-l2-announcement-policy
