---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../../common/images

resources:
  - Namespace.yaml
  - CiliumL2AnnouncementPolicy.yaml
  - CiliumClusterwideNetworkPolicy.mtls.yaml
  - CiliumClusterwideNetworkPolicy.default-deny.yaml
