---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: loki

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - {name: loki-rules, files: [log-errors.yaml=assets/log-errors.yaml]}

resources:
  - Namespace.yaml
  - HTTPRoute.yaml
  - CiliumNetworkPolicy.yaml
  - GrafanaDashboard.yaml

helmCharts:
  - name: loki
    repo: oci://ghcr.io/grafana-community/helm-charts
    version: 14.2.0  # renovate: datasource=helm registryUrl=https://grafana.github.io/helm-charts depName=loki
    releaseName: loki
    namespace: loki
    valuesFile: values.yaml
