# https://github.com/sebastka/mailwatch
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mailwatch

configMapGenerator:
  - name: mailwatch-env
    envs:
      - assets/mailwatch.alerts.env
      - assets/mailwatch.checks.env
      - assets/mailwatch.db.env
      - assets/mailwatch.domains.env
      - assets/mailwatch.http.env
      - assets/mailwatch.mailboxes.env
      - assets/mailwatch.oidc.env
      - assets/mailwatch.recipients.env
      - assets/mailwatch.schedules.env

resources:
  - Namespace.yaml
  - ServiceAccount.yaml
  - SealedSecret.mailwatch.yaml
  - Deployment.yaml
  - Service.yaml
  - HTTPRoute.yaml
  - SecurityPolicy.yaml
  - CiliumNetworkPolicy.yaml
