# https://github.com/sebastka/mailwatch
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mailwatch

configMapGenerator:
  - name: mailwatch-env
    envs:
      - assets/alerts.env
      - assets/checks.env
      - assets/db.env
      - assets/domains.env
      - assets/http.env
      - assets/mailboxes.env
      - assets/oidc.env
      - assets/recipients.env
      - assets/schedules.env

resources:
  - Namespace.yaml
  - ServiceAccount.yaml
  - SealedSecret.mailwatch.yaml
  - Deployment.yaml
  - Service.yaml
  - HTTPRoute.yaml
  - SecurityPolicy.yaml
  - CiliumNetworkPolicy.yaml
