# https://artifacthub.io/packages/helm/cert-manager/cert-manager
# https://cert-manager.io/docs/installation/helm/
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager

resources:
  - Namespace.yaml
  - SealedSecret.cloudflare-api-token.yaml
  - ClusterIssuer.le.yaml
  - cluster-ca.yaml
  - Bundle.cluster-ca-bundle.yaml
  - CiliumNetworkPolicy.yaml
  - GrafanaDashboard.yaml

configMapGenerator:
  - {name: trust-manager-dashboard, options: {disableNameSuffixHash: true}, files: [trust-manager.json=assets/trust-manager.json]}
    
helmCharts:
  - name: cert-manager
    repo: oci://quay.io/jetstack/charts
    version: v1.20.2  # renovate: datasource=helm registryUrl=oci://quay.io/jetstack/charts depName=cert-manager
    releaseName: cert-manager
    namespace: cert-manager
    includeCRDs: true
    valuesFile: values.cert-manager.yaml

  - name: trust-manager
    repo: oci://quay.io/jetstack/charts
    version: v0.22.1  # renovate: datasource=helm registryUrl=oci://quay.io/jetstack/charts depName=trust-manager
    releaseName: trust-manager
    namespace: cert-manager
    includeCRDs: true
    valuesFile: values.trust-manager.yaml
