# https://artifacthub.io/packages/helm/cert-manager/cert-manager
# https://cert-manager.io/docs/installation/helm/
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generators:
  - ./ksops.cloudflare-api-token-secret-generator.yaml

resources:
  - Application.yaml
  - Secret.cloudflare-api-token.enc.yaml
  # - Secret.cloudflare-api-token.yaml
  - ClusterIssuer.yaml
