# Sealed Secrets:
# - kubeseal --controller-namespace sealed-secrets -o yaml -f Secret.cloudflare-api-token.yaml >SealedSecret.cloudflare-api-token.yaml
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCYYYcadehvnOr1xvURVGsadlplGmwgP6/nIAq4sXinC1NSAK4/JA82NE0XLM7w4D4ffNxvrEXctmrhLz7Jam8aiPsjmkGIE+Si/3FonoluPR8RchS7z0+mBKlMF8dZDTLOUt8v/XlZixXEDiWl3saof8MM9FPl1vGdiAOYiPg/EPhoYIgfPziE3Es4e/2W7dZ+IRd8A7yRDPl/3jycVi1ERhzpY6G5rRK7OtPXnEgU+R7cOFjsaoDp4gU38mH90heijLiKHU6uzOvHvTJ5JieZOJTsf8RC1dvlV1IF4CsDG5rC/gnXvkia1knEqvT0HqBU6+Cv5CphdBXO0xezaaIJycpP4pAGE1lUT+DzRASOEgvNLf58kLL1cLupFOmZ0Niow9zn3uv2Kie5dGlwFJJAvasnQl8XuMVVXtxIEa9biRWCnMcpdXnD0StVR75PMKTUuch0Lf3yTNrxjwDuAPdjwC9GFuTGqevDzBoQoljZcLXyeghcSIYjfCV1Gepr3QtF3hYqbRhNxEwKyiU8uGooS0gRwGjWuq7IfEhdeEEeTZ1W8YBZXiLQO3uhSsdIpgxaduEhQseoEyGRboSzWGZfFFFlHO2dnlakZQNbd28HlyvJnNxxLft+ryW042b2ur/ykBoP0nx8tdJ41cqFBYWdzlXKp5ydNaGLHagq7tHSfxa01EX44Q/w2S1JR/knochDDKcBKqbT8YMSeSbwwWQVJxxr+vdYsy6zVsDsNiX9wGgbngaMdpat
  template:
    metadata:
      annotations:
        kustomize.config.k8s.io/behavior: replace
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
