#ENC[AES256_GCM,data:Fb8cNxHCJkEXkvtxQmbG46002RAVULcIzQiBohZCOVt9NUM0QawczipKHij6fWTEeJ8rcChzS/VKtEdzc+c3tN6wxgcGb1HZdHNU9PESPwijZXwRyro+lok=,iv:aUJudoEUz3ADG9AdFKJeelCuus8eDpq9qJ34O6BULi8=,tag:luJZFaqD45wlPbQU8Fn7RQ==,type:comment]
#ENC[AES256_GCM,data:+FqbMi4STxl5uwo5QgJ0e4aaKEXR9nKyaZaUFw+KV+UIkVhRZkqd93/x0tiZErPlBIzaUs3UWCXk6wFKHA9g8TdrwPL/7SSf546VquW1NHVo7ChaBT8ChKM=,iv:qqT2yWvcDraTxwXbhqmDPKST34bOHSY3syLXoEIcEiQ=,tag:P4KdbMqAixyDFzyVbQJHHg==,type:comment]
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
    annotations:
        kustomize.config.k8s.io/behavior: replace
type: Opaque
data:
    api-token: ENC[AES256_GCM,data:DVnC1vzvUSUisxz5fkqami66ShjBGTYD0MeUOBy+wPZc4pHN+TvIMZ/GXeJtNMwQEgrwGgJCpHw=,iv:cOcUmMt1vWJWeUwRI2nkwEkIT3UWXtwxr85PW+Key9E=,tag:jcYaYhfLvKqhmJDHIY+mjw==,type:str]
sops:
    age:
        - recipient: age1u8uutg4mpsn82nd9y828sj5agg7s89uswmp7frzpkrruhgw6xcuqr8hvf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzTnpjZXk2dkZndG1xWDFQ
            YW1hSFdrUlBnN3dTNWlOWTVBL1pOZ2Zna0VRCjRRbU5LQVNUZzl6UnFPWlVWK2VM
            cVdDaDdqSzhLVkFUZ01pU3FnYnNMZWsKLS0tIEFFN3pudGVkeTJkRWFDcWlFR2xy
            WWVvUDVXeEtqRnJyVzhzT0JWTExwQ00K5gnT2Ze1FRn+47MLNhaOkHKGo8/0/jb5
            O8lZ4ufhmcTbAkzqc3PJ+fh39yHYcCKQj/qkFoejO1uS0qXj16NliQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-27T11:25:02Z"
    mac: ENC[AES256_GCM,data:HPh9XeQwYEethjVDKDaNycKANZzEPFzg7hxrYcRfUc5jlFwO5MjP0d2vzTxvPyUYhxPYH6vNE8/x1whEWz/5fmKh5tr5W5vNnroHFqcnXk+qbsIDle4cxpYBGBDgyPqvRDxbqPcoPJCsbeKmgVLV462X1So6NJg3pvHURI2bZfg=,iv:XCblFzCScPrYVOiTaILisQZ8u1AnpZyvN7vGf/YKoKE=,tag:EUjsMg/YiqsoXRFddl5vBA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
