# yaml-language-server: $schema=https://raw.githubusercontent.com/cert-manager/cert-manager/refs/heads/master/deploy/charts/cert-manager/values.schema.json
# https://artifacthub.io/packages/helm/cert-manager/cert-manager?modal=values
---

crds:
  enabled: true
  keep: false

config:
  enableGatewayAPI: true

extraArgs:
  - --dns01-recursive-nameservers=8.8.8.8:53,8.8.4.4:53

# disableAutoApproval: true
# approveSignerNames:
#   - clusterissuers.cert-manager.io/cloudflare-dns01-issuer

resources:
  requests: {memory: 64Mi}
  limits: {memory: 64Mi}
webhook:
  resources:
    requests: {memory: 64Mi}
    limits: {memory: 64Mi}
cainjector:
  resources:
    requests: {memory: 128Mi}
    limits: {memory: 128Mi}

prometheus:
  enabled: true
  servicemonitor:
    enabled: true
