# yaml-language-server: $schema=https://raw.githubusercontent.com/cert-manager/trust-manager/refs/heads/main/deploy/charts/trust-manager/values.schema.json
# https://artifacthub.io/packages/helm/cert-manager/trust-manager?modal=values
---

crds:
  enabled: true
  keep: true

app:
  trust:
    namespace: cert-manager
  metrics:
    service:
      enabled: true
      servicemonitor: {enabled: true}

defaultPackage:
  enabled: true

resources:
  requests: {memory: 64Mi}
  limits: {memory: 64Mi}
