---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperless
  namespace: paperless
spec:
  replicas: 1
  strategy: {type: Recreate}
  selector:
    matchLabels:
      app.kubernetes.io/name: paperless
      app.kubernetes.io/version: stable
      app.kubernetes.io/component: document-management
      app.kubernetes.io/part-of: paperless
      # app.kubernetes.io/managed-by: kustomize
  template:
    metadata:
      namespace: paperless
      labels:
        app.kubernetes.io/name: paperless
        app.kubernetes.io/version: stable
        app.kubernetes.io/component: document-management
        app.kubernetes.io/part-of: paperless
        # app.kubernetes.io/managed-by: kustomize
    spec:
      serviceAccountName: paperless
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: {type: RuntimeDefault}
      initContainers:
        - name: fetch-tesseract-data
          image: ghcr.io/paperless-ngx/paperless-ngx:2.20.15
          command: ['/bin/sh', '-c']
          args:
            - |
              set -eux

              # Clean up volumes
              for d in customizations; do [ ! -d "/$d" ] || { rm -rf "/$d"/* "/$d"/.[!.]*; }; done

              # Fetch trained data for Tesseract OCR
              # Use the existing PAPERLESS_OCR_LANGUAGES var
              for lang in $PAPERLESS_OCR_LANGUAGES; do
                curl -sLO --output-dir /customizations "https://raw.githubusercontent.com/tesseract-ocr/tessdata/refs/heads/main/${lang}.traineddata"
              done

              # Force cookies to use samesite, httponly and secure
              if [ "$PAPERLESS_CUSTOM_ENABLE" = "true" ]; then
                cat /usr/src/paperless/src/paperless/settings.py /scripts/extra_settings.py \
                  >/customizations/settings.py
              fi
          envFrom:
            - configMapRef: {name: paperless-env}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: {drop: [ALL]}
          resources:
            requests: {memory: 64Mi}
            limits: {memory: 64Mi}
          volumeMounts:
            - {name: scripts-volume, mountPath: /scripts/extra_settings.py, subPath: extra_settings.py, readOnly: true}
            - {name: customizations-volume, mountPath: /customizations}
        - name: migrate
          image: ghcr.io/paperless-ngx/paperless-ngx:2.20.15
          command: [python3, manage.py, migrate, --noinput]
          envFrom:
            - configMapRef: {name: paperless-env}
            - secretRef: {name: paperless-secrets}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: {drop: [ALL]}
          resources:
            requests: {memory: 256Mi}
            limits: {memory: 256Mi}
          volumeMounts:
            - {name: migrate-tmp-volume, mountPath: /tmp}
      containers:
        - name: consumer
          # Dockerfile: https://github.com/paperless-ngx/paperless-ngx/blob/dev/Dockerfile
          image: ghcr.io/paperless-ngx/paperless-ngx:2.20.15
          command: [python3, "manage.py", "document_consumer"]
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: {drop: [ALL]}
          resources:
            requests: {memory: 256Mi}
            limits: {memory: 256Mi}
          envFrom:
            - configMapRef: {name: paperless-env}
            - secretRef: {name: paperless-secrets}
          volumeMounts:
            - {name: consumer-tmp-volume, mountPath: /tmp}
            - {name: consumer-cache-volume, mountPath: /var/cache}
            - {name: scripts-volume, mountPath: /scripts/post-consumption.sh, subPath: post-consumption.sh, readOnly: true}
            - {name: customizations-volume, mountPath: /usr/share/tesseract-ocr/5/tessdata/nor.traineddata, subPath: nor.traineddata, readOnly: true}
            # - {name: customizations-volume, mountPath: /usr/src/paperless/src/paperless/settings.py, subPath: settings.py, readOnly: true}
            - {name: paperless-consume-volume, mountPath: /usr/src/paperless/consume}
            - {name: paperless-export-volume, mountPath: /usr/src/paperless/export}
            - {name: paperless-data-volume, mountPath: /usr/src/paperless/data, subPath: paperless-data}
            - {name: paperless-data-volume, mountPath: /usr/src/paperless/media, subPath: paperless-media}
        - name: scheduler
          # Dockerfile: https://github.com/paperless-ngx/paperless-ngx/blob/dev/Dockerfile
          image: ghcr.io/paperless-ngx/paperless-ngx:2.20.15
          command: [celery, "--app", "paperless", "beat", "--loglevel", "INFO"]
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: {drop: [ALL]}
          resources:
            requests: {memory: 256Mi}
            limits: {memory: 256Mi}
          envFrom:
            - configMapRef: {name: paperless-env}
            - secretRef: {name: paperless-secrets}
          volumeMounts:
            - {name: scheduler-tmp-volume, mountPath: /tmp}
            - {name: scheduler-cache-volume, mountPath: /var/cache}
            # - {name: scripts-volume, mountPath: /scripts/post-consumption.sh, subPath: post-consumption.sh, readOnly: true}
            # - {name: customizations-volume, mountPath: /usr/share/tesseract-ocr/5/tessdata/nor.traineddata, subPath: nor.traineddata, readOnly: true}
            # - {name: customizations-volume, mountPath: /usr/src/paperless/src/paperless/settings.py, subPath: settings.py, readOnly: true}
            # - {name: paperless-consume-volume, mountPath: /usr/src/paperless/consume}
            # - {name: paperless-export-volume, mountPath: /usr/src/paperless/export}
            - {name: paperless-data-volume, mountPath: /usr/src/paperless/data, subPath: paperless-data}
            - {name: paperless-data-volume, mountPath: /usr/src/paperless/media, subPath: paperless-media}
        - name: worker
          # Dockerfile: https://github.com/paperless-ngx/paperless-ngx/blob/dev/Dockerfile
          image: ghcr.io/paperless-ngx/paperless-ngx:2.20.15
          command: [celery, "--app", "paperless", "worker", "--loglevel", "INFO"]
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: {drop: [ALL]}
          resources:
            requests: {memory: 512Mi}
            limits: {memory: 512Mi}
          envFrom:
            - configMapRef: {name: paperless-env}
            - secretRef: {name: paperless-secrets}
          volumeMounts:
            - {name: worker-tmp-volume, mountPath: /tmp}
            - {name: worker-cache-volume, mountPath: /var/cache}
            - {name: scripts-volume, mountPath: /scripts/post-consumption.sh, subPath: post-consumption.sh, readOnly: true}
            - {name: customizations-volume, mountPath: /usr/share/tesseract-ocr/5/tessdata/nor.traineddata, subPath: nor.traineddata, readOnly: true}
            # - {name: customizations-volume, mountPath: /usr/src/paperless/src/paperless/settings.py, subPath: settings.py, readOnly: true}
            - {name: paperless-consume-volume, mountPath: /usr/src/paperless/consume}
            - {name: paperless-export-volume, mountPath: /usr/src/paperless/export}
            - {name: paperless-data-volume, mountPath: /usr/src/paperless/data, subPath: paperless-data}
            - {name: paperless-data-volume, mountPath: /usr/src/paperless/media, subPath: paperless-media}
        - name: webserver
          # Dockerfile: https://github.com/paperless-ngx/paperless-ngx/blob/dev/Dockerfile
          image: ghcr.io/paperless-ngx/paperless-ngx:2.20.15
          command: [granian, "--interface", "asginl", "--ws", "paperless.asgi:application"]
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: {drop: [ALL]}
          resources:
            requests: {memory: 512Mi}
            limits: {memory: 512Mi}
          envFrom:
            - configMapRef: {name: paperless-env}
            - secretRef: {name: paperless-secrets}
          ports:
            - {name: http, protocol: TCP, containerPort: 8000}
          startupProbe: {httpGet: {port: 8000, path: /}, initialDelaySeconds: 2, periodSeconds: 10, failureThreshold: 12}
          livenessProbe: {httpGet: {port: 8000, path: /}, periodSeconds: 30}
          readinessProbe: {httpGet: {port: 8000, path: /}, periodSeconds: 30}
          volumeMounts:
            - {name: webserver-tmp-volume, mountPath: /tmp}
            - {name: webserver-cache-volume, mountPath: /var/cache}
            # - {name: scripts-volume, mountPath: /scripts/post-consumption.sh, subPath: post-consumption.sh, readOnly: true}
            # - {name: customizations-volume, mountPath: /usr/share/tesseract-ocr/5/tessdata/nor.traineddata, subPath: nor.traineddata, readOnly: true}
            # - {name: customizations-volume, mountPath: /usr/src/paperless/src/paperless/settings.py, subPath: settings.py, readOnly: true}
            - {name: paperless-consume-volume, mountPath: /usr/src/paperless/consume}
            - {name: paperless-export-volume, mountPath: /usr/src/paperless/export}
            - {name: paperless-data-volume, mountPath: /usr/src/paperless/data, subPath: paperless-data}
            - {name: paperless-data-volume, mountPath: /usr/src/paperless/media, subPath: paperless-media}
      volumes:
        - {name: migrate-tmp-volume, emptyDir: {}}
        - {name: consumer-tmp-volume, emptyDir: {}}
        - {name: scheduler-tmp-volume, emptyDir: {}}
        - {name: worker-tmp-volume, emptyDir: {}}
        - {name: webserver-tmp-volume, emptyDir: {}}
        - {name: consumer-cache-volume, emptyDir: {}}
        - {name: scheduler-cache-volume, emptyDir: {}}
        - {name: worker-cache-volume, emptyDir: {}}
        - {name: webserver-cache-volume, emptyDir: {}}
        - {name: customizations-volume, emptyDir: {}}
        - {name: scripts-volume, configMap: {name: paperless-scripts}}
        - {name: paperless-consume-volume, emptyDir: {}}
        - {name: paperless-export-volume, emptyDir: {}}
        - {name: paperless-data-volume, persistentVolumeClaim: {claimName: paperless-data-pvc}}
