---
apiVersion: batch/v1
kind: Job
metadata:
  name: tessdata-sync
  namespace: paperless
  labels:
    app.kubernetes.io/name: tessdata-sync
    app.kubernetes.io/version: stable
    app.kubernetes.io/component: data-sync
    app.kubernetes.io/part-of: paperless
    # app.kubernetes.io/managed-by: kustomize
  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  ttlSecondsAfterFinished: 604800
  template:
    metadata:
      namespace: paperless
      labels:
        app.kubernetes.io/name: tessdata-sync
        app.kubernetes.io/version: stable
        app.kubernetes.io/component: data-sync
        app.kubernetes.io/part-of: paperless
        # app.kubernetes.io/managed-by: kustomize
    spec:
      restartPolicy: OnFailure
      serviceAccountName: tessdata-sync
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: {type: RuntimeDefault}
      containers:
        - name: git-sync
          image: registry.k8s.io/git-sync/git-sync:v4.7.1  # renovate: datasource=docker depName=registry.k8s.io/git-sync/git-sync
          args:
            - --repo=https://github.com/tesseract-ocr/tessdata.git
            - --root=/mnt/tessdata
            - --link=tessdata.git
            - --one-time
            - --sync-timeout=1800s
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: {drop: [ALL]}
          resources:
            requests: {memory: 512Mi}
            limits: {memory: 512Mi}
          volumeMounts:
            - {name: tessdata-volume, mountPath: /mnt/tessdata}
            - {name: tmp-volume, mountPath: /tmp}
      volumes:
        - {name: tessdata-volume, persistentVolumeClaim: {claimName: paperless-tessdata-pvc}}
        - {name: tmp-volume, emptyDir: {}}
