---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: paperless

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: paperless

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - {namespace: paperless, name: paperless-env, envs: [assets/paperless.env]}
  - {namespace: paperless, name: paperless-scripts, files: [post-consumption.sh=assets/post-consumption.sh, extra_settings.py=assets/extra_settings.py]}

resources:
  - Namespace.yaml
  - SealedSecret.paperless-secrets.yaml
  - PersistentVolumeClaim.yaml
  - Deployment.yaml
  - Service.yaml
  - HTTPRoute.yaml
