---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace: paperless

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - {namespace: paperless, name: paperless-env, envs: [assets/paperless.env]}
  - {namespace: paperless, name: paperless-scripts, files: [post-consumption.sh=assets/post-consumption.sh, extra_settings.py=assets/extra_settings.py]}

resources:
  - Namespace.yaml
  - SealedSecret.paperless-secrets.yaml
  - SealedSecret.paperless-db-credentials.yaml
  - PersistentVolumeClaim.yaml
  - Cluster.paperless-db.yaml
  - ServiceAccounts.yaml
  - Deployment.paperless.yaml
  - Deployment.gotenberg.yaml
  - Deployment.tika.yaml
  - Deployment.valkey.yaml
  - Services.yaml
  - HTTPRoute.yaml
