---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace: paperless

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - {namespace: paperless, name: paperless-env, envs: [assets/paperless.env]}
  - {namespace: paperless, name: paperless-settings, files: [webserver.py=assets/settings/webserver.py]}
  - namespace: paperless
    name: paperless-scripts
    files:
      - post-consumption.sh=assets/scripts/post-consumption.sh
      - consumer-health.py=assets/scripts/consumer-health.py
      - scheduler-health.sh=assets/scripts/scheduler-health.sh
      - worker-health.sh=assets/scripts/worker-health.sh

resources:
  - Namespace.yaml
  - SealedSecret.paperless-secrets.yaml
  - PersistentVolumeClaim.yaml
  - ServiceAccounts.yaml
  - Deployment.paperless.yaml
  - Job.tessdata-sync.yaml
  - Deployment.gotenberg.yaml
  - Deployment.tika.yaml
  - Deployment.valkey.yaml
  - Services.yaml
  - HTTPRoute.yaml
  - BackendTrafficPolicy.yaml
  - SecurityPolicy.yaml
  - CiliumNetworkPolicy.main.yaml
  - CiliumNetworkPolicy.paperless.yaml
  - CiliumNetworkPolicy.tika.yaml
  - CiliumNetworkPolicy.valkey.yaml
  - CiliumNetworkPolicy.gotenberg.yaml
  - CiliumNetworkPolicy.tessdata-sync.yaml
