# https://juliushinze.de/posts/paperless-on-k8s/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-data-pvc
  namespace: paperless
  labels:
    app.kubernetes.io/name: paperless
    recurring-job.longhorn.io/source: enabled
    recurring-job-group.longhorn.io/group1: enabled
    backup.velero.io/nightly-hetzner: enabled
spec:
  accessModes: [ReadWriteOncePod]
  resources: {requests: {storage: 20Gi}}
  storageClassName: longhorn-encrypted
  volumeName: paperless-data-pv
