# Seal secret:
# - kubeseal --controller-namespace sealed-secrets -o yaml -f Secret.paperless-db-credentials.yaml >SealedSecret.paperless-db-credentials.yaml
# - kubeseal --cert "$(dirname "$(readlink -f "$TALOSCONFIG")")/seal.crt" -o yaml -f Secret.paperless-db-credentials.yaml >SealedSecret.paperless-db-credentials.yaml
# Unseal secret
# - kubeseal --cert "$(dirname "$(readlink -f "$TALOSCONFIG")")/seal.crt" --recovery-unseal --recovery-private-key "$(dirname "$(readlink -f "$TALOSCONFIG")")/seal.key" -o yaml -f SealedSecret.paperless-db-credentials.yaml
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: paperless-db-credentials
  namespace: cnpg-database
spec:
  encryptedData:
    password: AgB+Z+di53kV8Rj9XhAZ9rdyHAgv/mCZamfy6oMPSGILvFi+EG+BTQieGrl3zJjvQzgfvlJoWwqpe4ROncBLkBs2KqJ4WvO8E4j7XmBjpJSKnzJBgime7mYkZd2k5TVDGrP/i6KJBfBQt+Wil6AMSXsCwOXuA1mob2ttInFHrlNQfFAFt6cuF3M0UgaGInDNM4cm/+ojOJVWbvYIE57LMzPNqq3SQOaUZPddltTyXPVSiVgpeGyOzvzUFfUtR4tMu0RHvN0dX+vvYewK1V5HGVon+vp89Vix+/i86tZK7xKl35GGlSNMRST9VDdxEIdUQ9G9v+mhAHvdsYdE4U9P2AMe1EOs/z0Ws0SNwknCIcpVjxbUU/ZTdCntyEPQ5+bQP840ll2C/nWzI9Jo+djgHUOk1oinri6l0tsYFcb+byX025und4RCWwFF1TsWE2YxCQUPUPldTB2ROy6HoGvYQGM3K0hoLaIlC2iK/ULw7C1/RzCVwNFC7UEdp/XbXxViPNrfxnxBE8r5/OsEL3Nk1foFhdNutKGZOFc/+7PgLiXSPemmBrElevKVPFWVcaaIgV9vMuIZ6UKro/Wjne458h3i5mt0Rjz+IWaZZ/ZXjhoVhWT1qlUbXCYyUhMQw827Ksle9qPzuS4OiqQZEvmaan/ipvs2h/qj54VzLLqYblr/VH4IwFbIx0K+PLM1lNJ23bpwbxyrWrKW39I6OyNAVeL0oD7v49I6KE/h+/aaY4nlDvJz/i9BPYMkLs24vpHpiG8=
    username: AgBC4C0QYFC2Vyplsm3k4xjCIpDlQ2W83BvSP8l/zqyW3kcNMZGP+0cqPM6Cuaau8xhMqpqHADHZ8nxXlBGEf4kJo6XE7eU4lrYQmXfun8iExWrvkfAtAndDBJBBTFFtEYzfCxYNRYLSmgXQD2bMtz2BXXzUsDs/14mtwN3x473Oq5ISokVILCgVfHmQEOPX5JkVZR0u/dCCTtNXWXavr7vSPPbsZ0WYcGjmdrkSGlWpNwV2jN7fPVLbynzqZxtnf9B45gS6bGhTF191UzyYc2PsR8286RY1UGx+cCdAPNKEbhR9ZZlfui3GjTQrBmTZFqFYWwx40kIPhjr0ryBTN8mozuyl6V9j/c3FmSgTeFD2Ib/aGqEaUxMPwsbj1D4sxcYOLzYYgX4oPYRY0Fse/c65i1YozumkTuyjNwGSa04S0A8TFBilBztT1IEzJaqzEew5rONbGVJpSOM0Ynkp8wIrU9HIQGvqDfs6wg5mHCwDWSfJtiqDxrJpd5lZPeBZySlV9/3sk99kFq9xPJ5w8W4kTZvsmj60dLtDDtDTqnyx9nV9JXchyHFhY1DyBX5A0XYcY/R3YlZNyujveC1jJUYV4+sRk3Un/3FoSSVPACb8scgRtk9vPgRhUZTprS6QO7IKPdnnM/k8FeMmtrHD/A7G7zIHLP1JcC4cXI75FuNjcGmZXZq3Vz2GTMFjqEbBeSHayB5YsgGnlYI=
  template:
    metadata:
      annotations:
        kustomize.config.k8s.io/behavior: replace
      name: paperless-db-credentials
      namespace: cnpg-database
    type: kubernetes.io/basic-auth
