---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oidc
  namespace: paperless
spec:
  encryptedData:
    client-id: AgAcyAyfSP42s8c9KQV6cJwcx8hTpZbczzWV4EHdhdp6FwmWp0M8sHolLePNdHqGtS0Zb0IsyN+bTLda4bM/NVLHmXJTRYGeRsgOpQwa9nlGrkUJ+VJxM4mvwVMKo8OeAjVL9ZchIwmM+maUWGQD+EK4dEilvE/tOBQi5r+qJtRXyjHlMmzAHtcV3AzDlwO/qtXLMt666VyuOMUqm0ixlNNJ/DHmhAmDS0GNU2BCUQFJR+TREJfODyYvundEsK545B+5E9pBQ4xmwdGBonLhh24q6aX+VF33I2LaZ3Kagza2u8RG1thbUUJo6I2DWr0OOwrE05X0biad0Ly+55m9SK3YigA/SZo5GqtLPtk7iUtUB39F4wlf9qBD7WFDhxHZ0CoRYMh3Gx8bGDTESbOqKJBEeGSZOSFLL08AU6jHzvQTPBr4jacW8d3BSwENGa3Q6c7Ibw+uX6g/T6bgpTurTlcHI93ha3IKBW7kyMGkKp16tpBYg1eVSmyOcpPnedK5RvAyfw6pwhwuEQ7YnH6RUONcESbDFSstPCh2hQL8Hv1TS7C7QxmsZftnsxSglI5PJPEn8wBWYFy4qBQMjls++ApalFJhCWrWJOLw5V6Bhg/BZAWCtQpSP8lsehZluv5fEhJq+tLL742R0Eufv9aHVQzDd38OsCWc8rzz5auwkWBpThumDhxovhJi3fNrsTb5BmFTmnvGV5l+n6is+G2ipggK+/A=
    client-secret: AgAxQ8Gf/50+T88p/6+kmWC6JdaWSaz92FCxun/OSKNSZ7AEHIEhyDa+/X8rD4R0bqb5zoCZgzWemaYxhIutbgzdB7+BS4+uVHTgQODXoDFBO9nClBh8vPFEc5WjET1Ri8Jx84ZiL6Gz9jtXBRUUuJj9ggL9BxYuHy+hzmqi6VPmmENbtGir5zk7SPKEI/KQRaw2sxQGaKKorT8Nw3HYAJ8VkNsNT6/RIkcqqVFT5cUrmGLrkPGx6OPjscnF70FDyjv25D8IAbGmY6kDf0JIFl4YLDLPeo+4PqkwyLw8Rzj+r7OdhyTChrCtxo5LLTtzQR/u/7TCPpo9IqMvjRi6SrmxotK59Zfv5+HzA8tJBzJE5qPzoXQa3lTqT4zBx2o+rn1DgoZveBeuzVQfj8kW8f5Pah/1IzHoPCA8IU0nvKtuzsrbDqtt3mmQp3Y1OTg81jgxLc3PBjBXpk/U+VD/nSZ2MswEj9Ywnhdxh4OI4i9WhN7gWscvRWmg7/jcXjleiNND8D4q7pt9vQI522ZzCKfUWxCSpY7Fu/ndjc4gnXwULRpJAom9ig/p7zjzgPiUg2raO6QAIwD2HOQd52E1d7n9HFk1U+rKy4Pxl8wHj5sXAb4UIhpUPbRvV7n/IIWDco0uq2jHrttitAzXuEwzFIfwBWmdyOYS/ZVho1h0oxvYWAy238w0+moFw8iGP0Q8TV6Nq3PxroWlrxNtuGFDX9W6SwvU/ceIbEgALvrR23PU6gSjNiBjI3odKUbL/0+C2Kh6WBHs3gj0Jiy2TOhDtPdF
  template:
    metadata:
      annotations:
        kustomize.config.k8s.io/behavior: replace
      name: oidc
      namespace: paperless
    type: Opaque
