#ENC[AES256_GCM,data:JIBPYbBeyyTNSpABLkS9O5FQHd9R57RVRIm6l1s7Iyw8seS7c4PLTp+NzUR/rejqSyRd81B2ZkdPg3DZucpnryVbcVAPYWct4460McWOSS0D0UzqNvoiZPu5Nc0yRCx+kzTSgjcgNLf0xyrg1Ff4pMW/k9BQuq09nI2Asg/OoTXin9xuL7RipGCV6s5N3Bm0EtNq0ES9JGKKGcAD05nbsyrEMK3bVBmoLEr2z5XYZ0hfCO8b9vVS5bprmr3ILjQwpW/yz7aLQpMtwlvxr1Xlun0iRZQrq+I53H4t/OAgLK62OY0E+zVO4A7UrOkyUTmp20gVajg=,iv:X/gSdr69PTESBVjWxcDz+ceE0zAb0oJpOjYGXnZeDM4=,tag:bNpagqTif1aYz56Dxwb29Q==,type:comment]
#ENC[AES256_GCM,data:suG4AUAZ0iBC8J7PeHtdqEA1CLhDK0ROAaMzOd9ypIQcydDq0GIO+cfdrJ0Dp+rD+186aMpzE+mx1TBtohDw7yCF2riubf2FRWtgKW/+J7JodRk=,iv:YIsnbIDRd9wTp3s5v1Re9wGkb63LY4It9h9Hx99ii5I=,tag:I3g9TT7KLJVDs++zdQxm5A==,type:comment]
#ENC[AES256_GCM,data:Rf31jMLvifrdJkxQn74Yw0mxTGNrbKR7LYRqY0Ric5JQxseWupCcR2XCtGW5elMlyA4aJ8Bdng+QK4S5FZxluMPhhTIdo1mMToK99CJwNRHnKaw=,iv:jQ7FYC/x5s4uCjMKMpRzB8Hg0tgvaO4xhEy/8LWn32A=,tag:DQGV8vq2bpfHLDtqndn3LQ==,type:comment]
apiVersion: v1
kind: Secret
metadata:
    name: paperless-secrets
    namespace: paperless
    annotations:
        kustomize.config.k8s.io/behavior: replace
stringData:
    paperless-admin-password: ENC[AES256_GCM,data:y8Nvnu2bdTqqoCADmauAZWCs4oL9cg6gyNIEfGPYGsA=,iv:PRcTkCdHLUlzrQ10lPgUzesAh9tA7ddvFn944yL1htM=,tag:sCNayzRUWVu+Lr1pkB98WA==,type:str]
    paperless-dbpass: ENC[AES256_GCM,data:HNp4wBBbd2ROpQycX7kI2I4UWV0WGX6zF/Va9jQ8/CnkXmZ33D3xpBVp0vwaEH98,iv:nhecdXnoYHgnS6RF4fL3GojnPJSUhpQNub1lm2roKwc=,tag:yQKlWZlwN1vN1FL380JBjQ==,type:str]
    paperless-redis: ENC[AES256_GCM,data:PKcZF/KGo0Hn8rW/kQTXJPrS6UN/X5s6s1C6jXhOgT6WaXWH3YbvpMYy+CHYytDj8wdDLBz/wHKKLWP/tfbUS7SwXab3/Kplsco1HOlvxM1dgO3M8im9uZQdaj0iqwBWG/WW8A==,iv:CmvBlYVt7bEKIBb/1jymLTdKtGOuKdRVlmH02qqXjEY=,tag:LbTrR3cnQNqmn91FyHN9/A==,type:str]
    paperless-secret-key: ENC[AES256_GCM,data:E3XaafpZIKHDn5KT6ixhlMv6ZKvskpxMoolbsLCbMEDFNClVxDdYLS1Gic/AUw62,iv:ZOndTsG/yUUtLPkQT0y0cDQ2nSNPYi4GBrvz4F2fmsU=,tag:y+59Xg/ufUKUu9HhEWHb8g==,type:str]
sops:
    age:
        - recipient: age1u8uutg4mpsn82nd9y828sj5agg7s89uswmp7frzpkrruhgw6xcuqr8hvf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0SmY1MWdXYjk3MzgyODFQ
            Z2krL21UZndKR2dERktoNWg0SncwT2x2QUVrCjNCRTNJRHhxM2o0bUlncTc2UXpw
            aTVqbmtXL29ma0VQYjkreXF0ZUI0NG8KLS0tIHFybUlxa0Zjcm1uZlBudHV1K3Yz
            SmRJQWFqZGpuNjBPb01MTDBmcWtWS2MKsfknJXU98kPONlylwija4H5G617zLkzP
            DL5OmhSw6bAo5eHw8W/F5b/lQ9UdbONXp/OIFXeV4TQq3iaTitNjtw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-09T14:03:34Z"
    mac: ENC[AES256_GCM,data:cBxMc8OFGgjX+8ENYvh2ZxlEBvsoWEWzijAE1sGQnzAeNevJPrIe1843pjJnPxmhDcjDVwd+o4pk9HyIcAkhYJwA9bNuVWfmk+46s9h96COAEHWQyJLZfJ2C17qxDUYapWkF0PXrrwgEuZnf2QlFwpNYvUqtjrm6qVkj4oQ7Hu0=,iv:GzOsNymEAF3tdXHCQnNeaeJT5qeAUAKLIGZ1wKIzwcY=,tag:0egm449HTEBOOcPlT+piXg==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
