#ENC[AES256_GCM,data:VrP+E/WomRD397UTMUZ9EajpMB1GOjN+dc1cmIwduR3hAFdmN2/9lFqDRZnGqKWSm9SNzLwWcpHwnqKODErtoVGLUo2lmq8FAPnvJQtUziPfwgIu9CljPO46ypp3umzUD/ON38OP0OTFsbYGGoPTgp+ulOCsf83c+QS+O7G1a9mYIq9WHKzqAArNRD/cO83DMyUwo1TSZHIWy1IKjqy1KUx13txos22qVQQt6x4s5NH/h94YLdKuA6yOsw9Nu/qqGncz93NNJsNlFAVHCwT5hxtKSh28kzQ6b87Mq2hY0rCVww+4TrqLXTyaklXLAX+Kb7EAoro=,iv:dyBLqsKTYc+nQ0ZIG0VdgwyfUMFMY+UZWY04XpvkFOo=,tag:7k5W/legkATfHR6oymFpug==,type:comment]
#ENC[AES256_GCM,data:XHI9JX4rGjxK9g1wT2q9MNp7abFY+OE6qVaGGaLEwveuB2X5opq47YDTHg/qJuUHJPOUfy6EL1OjAneqrX20RSlIxq+YeAlV7hY6ki02C8aOjwQ=,iv:68XSSbdCVV08IaHfhJFjTMM5A5DI5LcyEZGbFIfNt68=,tag:sJ+PFJU+KT5QwGWnNUrd2w==,type:comment]
#ENC[AES256_GCM,data:GH6s3xFrPjN5R35Ap8TNU4xZI2Ch7Irqel8ETtIlji2vKqIOkbokV8u7lY9DXFh+KVNsa+8vZMJZI2UvTRLhPtPQvcvnAtlvReskxAF8Bm3bC1o=,iv:o1oEjxMorALhvkTMC+TtWsv9HvbIbOP8SW/cF3ksvoI=,tag:eQ1Z4IZ37Byy1H6a/71y6g==,type:comment]
apiVersion: v1
kind: Secret
metadata:
    name: paperless-secrets
    namespace: paperless
    annotations:
        kustomize.config.k8s.io/behavior: replace
data:
    paperless-admin-password: ENC[AES256_GCM,data:ayCpGs07D9xgCz18PrQU8QNWNxZYkAlUwioy3/4HvtLZg0sxvTtH21XQo5s=,iv:NR7+t2bodf5M3zRnPhN12qVfCP+2JNfqHDsixIqGJ+A=,tag:Vncd2lxYKWD+qWNGu3BpGQ==,type:str]
    paperless-dbpass: ENC[AES256_GCM,data:GhjyDc5wOhtJ5/+34TmgjpAY9gp4ZM4VPr9ZJcw+HD109HpRJKzQ0+5eIa0XXiZuvh+AuSDuMbNuWk93Qb/qiQ==,iv:2a5F/XwDyx69m7I4mqPUYF+3RiwRqXFKr5CFdnVnqFc=,tag:Z4f/6cQN+MXk3k68YCrN7w==,type:str]
    paperless-redis: ENC[AES256_GCM,data:jnc8tAaOXB278akpbvosrqF9yC5Ki9XFRlOl08bk6pWeXC+gaWFK/vrUkXcPdG8/z5ZpCIOuyXv1PSBpR+yuVxlm5B1vnm6ce1kRCpLCxZegt3SkQKALSdpalk3V31jmyvqphGPZ55qbC76rZLg5CA==,iv:wbOpwmeEwoeOWd1nfUC41n6eec2lqy/AUoLJuYEhzMQ=,tag:DZTUzHk+SrJuO8kellEUgw==,type:str]
    paperless-secret-key: ENC[AES256_GCM,data:p2JiWHJ0umrESSD1iTOacB7uFHhI0wC4ekRFMnJpGgFI8o9E1yqbcRpGHFg84YW40kbRl34cMku9GeQ2tqHXvA==,iv:Tm0IhhR/KpVAQNL4z0amzVnVPCHiKm/tcq4IpY7v15s=,tag:7u9EGYBoTGB4jBakR1fLvQ==,type:str]
sops:
    age:
        - recipient: age1u8uutg4mpsn82nd9y828sj5agg7s89uswmp7frzpkrruhgw6xcuqr8hvf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaemh4anBCNEpxeGtMdVhS
            Z0ZlVi8ySUk5UHZncTU0eUMySWdqaVc3aXlJCndPZUFqVlRjMkZsWEZHVjRJZmN0
            bE1zaXF6c2ZBOVlmcm05OXpFc09oc2cKLS0tIHZYaUo1Y3JheTBCT1QxY1I3T0Vl
            RXFOUExmRlJvU3ZQL2pIcEszRGN3b1kKlGvNqHLM+Ss69kUPat1exnqBt+1tNpks
            8YEV10dNwrxKLNtVVi2QMj5JGIImErtiOLi2IMhw47udw/fHgejuUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-04T23:09:10Z"
    mac: ENC[AES256_GCM,data:7G0HjLuISTybTFTriojgsGp/T9FCiSPBAdErdVI7lXithXXTIFh/0YtUVQU5UQx0J9rx6tmxJJOL7cvW7BJ965Nk/hcrvtMudcNGBitakuPKaa2FGXngPEMJNlM0BmkI2LiwR2rX9EUtbwtRD7ATGUdHUhIMtmjoBZ4k8zwpw4M=,iv:WxbY2N282jQvdj7YhBVtpCF228IXRSLQXLvWvVrzUx8=,tag:lmUF3JNJq7Dh/Ij5LT6jwQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
