#ENC[AES256_GCM,data:7F2AHqYakIu867bnE7u8DWJtMI0MWLifmkAezBx68BH5Ey1wwUaf8ZNoHeSGllmS8yI7yh31jweHHj76bdsoI/W/L4qzXnsTgDrv72oKNGT1V848S3v8lIuNT1gPEHAxXw8c+8OU+y3BY3b+ZAHyWbnIOGUX8h4nAu+5IOWlYfBG+sj0YATOHNPIcSJoYKPK9tyVQLoc5d3xN9NaPKimkjOObeF+X6bAirHTeVXbkVwxuMk30vwnnkTvxsZLBg3MvCakxKibT/dxsDyjz1i6Q1Q2op1k7aWiRmHQ0NDJrLo4tGaklJ4RT5duZADtqj9tMUDTV6g=,iv:Z94fHAOdZl/SaqZJcATQPtC8pKGyT1TGoVVIDwkpEgU=,tag:bWMEp2cVUaHfK9w/uKRiUg==,type:comment]
#ENC[AES256_GCM,data:FqvDyzu9OpQ/SbP3GNnekxu28oi1GAEtSbID15OtlD28Ly7mzAqnvNOTa9xsKvguJKh7nS9u7RI+HGDnIH1E2BA2by/w/elhz8LmK9Pyt8KB8Jg=,iv:CIn9xb2nM7gooocCn6LzsRXtJo1bmy0q+527GO8EKFY=,tag:jTMDcy5UROURdNFFcZ3k1A==,type:comment]
#ENC[AES256_GCM,data:M7HG0W5IlLdkGO6WQSUUQRg21pKYIIVIIQmrbxBDz/x9YfyQvBxMKiuum89jhz9kwP325gvjtNHdotOrS2xh4pkhcHkyhF5r3IBNJk47Ce6Og6M=,iv:s0Ia+Mj75Vp8bhtqB/UHkTwbLRbdqeHDKBs57ECCLR0=,tag:ALMS+vqzgWzTERtt9s5rOQ==,type:comment]
apiVersion: v1
kind: Secret
metadata:
    name: paperless-secrets
    namespace: paperless
    annotations:
        kustomize.config.k8s.io/behavior: replace
data:
    paperless-admin-password: ENC[AES256_GCM,data:CCZh1gUxP8XoWmwrqhiT4E06wEvuunvmtGQlb5O+OOHPK7OFC08jMbx1txI=,iv:BwPOSVSNUuILf8fVtf1Try+CxMePx9WX+QArGPixIhE=,tag:XZpoD/IxeM15kr135BCx4A==,type:str]
    paperless-dbpass: ENC[AES256_GCM,data:Q/X9M6U6+2ySel/WaEqQQCEtXEXMr2sfF1gEpBAhBVbylBkG25gZcZtRi/Q4kn8R8LFMTBh5tZYCvNCZO0K6nw==,iv:dwohL9nkuy7/wQFCLC7klSBcDKAiKjXx4ej559+fGdI=,tag:ZUisROWUUzFEKUKDY84aQw==,type:str]
    paperless-redis: ENC[AES256_GCM,data:XQZZngNPkVSy3qf1wUoI5yHEf0MV9+0Sa6LZevTFAVI0288nss6dRzXL3lSa8v5G0qW5UtVBk5b5RS4xOD3n07rVK/vjDcVTnDWO4ucaHREljntjIR/M4w/y+gP5dfyG4m1Q399/f8PdpCAEMcXy9g==,iv:gVFjoqt0rAA8Hb2c2l3hcOwYcNPijFCL5dcfthiWzr4=,tag:a4aOnQb+tqnHwXRpFmwahA==,type:str]
    paperless-secret-key: ENC[AES256_GCM,data:zZsLF75Zph233fp8Ojg7edA9L0G9feOkYGbHET1v48VjOAcj+TT/zHwJbkKKu0wOgtRb1E0TB8S6uTKffMNZ1A==,iv:cSleVIbexLQoJYhPoN4tl3fTfa3vZ6jb6l8oQ2vVBXY=,tag:7F5QwGHcgF3w5qK7n2rFGQ==,type:str]
sops:
    age:
        - recipient: age1gxk3ylhwfwe0nkhfu8pr08j5axz5y6qm50ntp0ncu0l6cx20fdrqw36n8a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsSXJWTW9EZVZraVRrektZ
            WmJNczgvc0VyZFV3MTd2V3hxUVp6clFBNkdvClJ5anRtT1BSeW9RRmFEVHBBYzNG
            M2FwZ21PYmw2VUkxY2dOdS94Syt5UEUKLS0tIG5jN3NsMU01K0VRV1F3T0MxODdX
            Y3U3Q2RqK1M5SjkvUTc5Znl2Q2FIL3cKBcQyGmasbxlwQfALzl0U/oirN7ak7KGS
            cbjeJlGLteU0RK9t9xU1/EyApdXYpHyA7FDNUH+Ca1JvAeipTavILg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T13:01:19Z"
    mac: ENC[AES256_GCM,data:tcXs2AGyk3dReIbpIgArrs4BS+a/AmpVDDMJzHjvkGjkcMQrvNzG8BlX9L2j4pv6BF2LhEojEhx2Jf4VR2DpJ8qP51VmFzLTmpnRUy9DOwANXAZtIG0Hg3obXaeDYp1ww+AhGlaS5FG16bE3NiUWey9G4vkZvKpOFaaiMLJ/GjI=,iv:1KP4RnpFmC27zrmafxgThEfsW+oJGeIUDcp692OyAug=,tag:DteVBxPEkd9pcoG0uDta/g==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
