---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: paperless
  namespace: paperless
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gotenberg
  namespace: paperless
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tika
  namespace: paperless
automountServiceAccountToken: false
