---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - CiliumLoadBalancerIPPool.yaml
  - SealedSecret.cilium-ca.yaml
  - GrafanaDashboard.yaml

helmCharts:
  - name: cilium
    repo: oci://quay.io/cilium/charts
    version: 1.20.1  # renovate: datasource=helm registryUrl=oci://quay.io/cilium/charts depName=cilium
    releaseName: cilium
    namespace: kube-system
    includeCRDs: true
    valuesFile: ../../base/values.yaml
    valuesInline:
      cluster: {id: 1, name: talmox}
      ipv4NativeRoutingCIDR: 10.244.0.0/16  # Pod CIDR
      encryption:
        strictMode:
          egress:
            cidr: 10.244.0.0/16  # Should cover all Pod CIDRs in the cluster
      # clustermesh: {}
      hubble:
        ui:
          enabled: true
        tls:
          caBundle:
            enabled: true
            name: cilium-ca
            key: ca.crt
            useSecret: true
