---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wc-karlsen-app-certificate
  namespace: gateway
spec:
  # isCA: false
  secretName: wc-karlsen-app-certificate
  # commonName:
  dnsNames: ['*.karlsen.app']
  # subject: {}
  # privateKey: {}
  issuerRef: {group: cert-manager.io, kind: ClusterIssuer, name: cloudflare-dns01-issuer}
  usages: [digital signature, key encipherment]
  # duration:
  # renewBefore:
