---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/kubernetes-sigs/node-feature-discovery/deployment/overlays/default?ref=v0.18.3
  - https://github.com/intel/intel-device-plugins-for-kubernetes/deployments/nfd/overlays/node-feature-rules?ref=v0.34.1  # NFD rules for Intel HW

patches:
  - patch: |-
      apiVersion: v1
      kind: Namespace
      metadata:
        name: node-feature-discovery
        labels:
          pod-security.kubernetes.io/enforce: privileged
    target:
      kind: Namespace
      name: node-feature-discovery
