# yaml-language-server: $schema=https://raw.githubusercontent.com/kubernetes-sigs/node-feature-discovery/refs/heads/master/deployment/helm/node-feature-discovery/values.schema.json
# https://artifacthub.io/packages/helm/node-feature-discovery/node-feature-discovery?modal=values
---

master:
  resources:
    requests: {memory: 128Mi}
    limits: {memory: 128Mi}

worker:
  config:
    core:
      sleepInterval: 60s
  resources:
    requests: {memory: 128Mi}
    limits: {memory: 128Mi}

topologyUpdater:
  resources:
    requests: {memory: 64Mi}
    limits: {memory: 64Mi}

gc:
  resources:
    requests: {memory: 64Mi}
    limits: {memory: 64Mi}
