# The Ansible inventory for every host managed here, written on apply and committed with the
# state, so Ansible needs neither tofu nor the state passphrase to read it.
#
# Each host carries its data under a `tofu` hostvar, and joins one group per Proxmox tag. A few
# tags are pluralised on the way, to match the group_vars directories on the Ansible side.
locals {
  hosts = merge(
    module.virtual_machines_hera.host_data,
  )

  ansible_group_names = {
    database   = "databases"
    fileserver = "fileservers"
    mariadb    = "mariadbs"
    postgresql = "postgresqls"
  }

  ansible_host_groups = {
    for fqdn, host in local.hosts : fqdn => [for tag in host.tags : lookup(local.ansible_group_names, tag, tag)]
  }

  ansible_inventory = {
    all = {
      hosts = {
        for fqdn, host in local.hosts : fqdn => {
          tofu = { for key, value in host : key => value if key != "tags" }
        }
      }
      children = {
        for group in sort(distinct(flatten(values(local.ansible_host_groups)))) : group => {
          hosts = { for fqdn, groups in local.ansible_host_groups : fqdn => null if contains(groups, group) }
        }
      }
    }
  }
}

resource "local_file" "ansible_inventory" {
  filename        = "${path.module}/../ansible/inventories/tofu.yaml"
  file_permission = "0644"
  content         = "---\n# Generated by tofu/ansible.tf on apply: do not edit.\n\n${yamlencode(local.ansible_inventory)}"
}
