---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-n8n-main-ingress
  namespace: n8n
spec:
  endpointSelector: {matchLabels: {app.kubernetes.io/name: n8n, app.kubernetes.io/component: main}}
  ingress:
    - {fromEntities: [host], toPorts: [ports: [{port: '5678', protocol: TCP}]]}  # Host probes
    - {fromEndpoints: [matchLabels: {k8s:io.kubernetes.pod.namespace: envoy-gateway-system}], toPorts: [ports: [{port: '5678', protocol: TCP}]]}  # Envoy Gateway
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-n8n-main-egress
  namespace: n8n
spec:
  endpointSelector: {matchLabels: {app.kubernetes.io/name: n8n, app.kubernetes.io/component: main}}
  egress:
    - {toEndpoints: [matchLabels: {k8s:io.kubernetes.pod.namespace: n8n, app.kubernetes.io/name: valkey}], toPorts: [ports: [{port: '6379', protocol: TCP}]]}
    - {toFQDNs: [matchName: db02.hera.home.karlsen.fr], toPorts: [ports: [{port: '5432', protocol: TCP}]]}
