---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: n8n

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - {namespace: n8n, name: n8n-env, envs: [assets/n8n.env]}

components:
  - ../../../common/valkey

resources:
  - Namespace.yaml
  - SealedSecret.oidc.yaml
  - SealedSecret.n8n-secrets.yaml
  - HTTPRoute.yaml
  - SecurityPolicy.yaml
  - CiliumNetworkPolicy.yaml

helmCharts:
  - name: n8n
    repo: oci://ghcr.io/n8n-io/n8n-helm-chart
    version: 1.11.0
    releaseName: n8n
    namespace: n8n
    includeCRDs: true
    valuesFile: values.yaml
