---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oidc
  namespace: n8n
spec:
  encryptedData:
    client-secret: AgBuz73r9CG9Vi0JT8ffEvf8jfM3z4c2066dP0nxTav2zHEMKCTWgxIiw4ehRTGQG0UyyMZSaBzOUrQrIQ5hBnt0z49p6WvjK3/lblLtMDIwzDOhw35Rrn0jQwqtPDkHAQslqWXRXQhfj3euOPg3q6tg00P1PwZqLt0YsMtEc2HpJ+V0v5vBe/Tv6yPvcFSObjjJsSCaNnES5p+ZUa57pVVuN8RXsVVTpmtCnJC7jjlGELDM2YAC9Blt44Djfqh0Y3mRGRFoIsZyjXfs/oPQNRCs2TRl9SQjfBXzClFvXXgWSnYCWkovBIUMPUC8GkylkDIxw6Ofq4xmNjYaIqOZIboZ+B6upyxiicN/gkwpLCtQEPRAOA06YE0wRuUtNSNFLavAuaegNysiaIkWxc0H49Brb/nzC7YMQbTSc/b8lIWYKSvhCRMdpXnKeWT50WAOpIZ1lr8Xakt/3+e4O8NlSKLyELQciIVVv3NEEtFmixJQm1XcLeRiPwul/GahDVcYRNYjfwfGoIbbxjPUmWIv7o+EVkgvRaCCzQz+Nizv9T8wndFhOVzA8tQvE+qsvVE2FMCeb96Jy6XmE21ib7Sqbcp7pUFEP5JvITnT/3TgZVYHDVQERm3B8o8fYG8V1Xrk44X5wK5DZODZUWhEx6qHAYZOSFJLOqLIOSbWhfb0jwNyE6Bbul1/COKATFO+ibA/jIg8iPe/gVcu50S7R/zkpcmfPawCx6+iEngJpDiLvbkZEyPCEkhMcPNpFlZm0/19uD973rZD5qVUJ39NMDZ8iHRlCTeY93kezBw=
  template:
    metadata:
      annotations:
        kustomize.config.k8s.io/behavior: replace
      name: oidc
      namespace: n8n
    type: Opaque
