---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-db-credentials
  namespace: cnpg-database
spec:
  encryptedData:
    password: AgAtFrj5HhBn3cHP72l962g7i7D6icazaIksYAVpq01OkoYyGes2ktuqiLnjOL1XbqLDW/AMOE16H0CxmJ1GSH2uN0jnX2dEiu5BS71ggWtZr1sUMVzBsQSGjAelgYaFLMu/Q8+53d/p/3vpmteD98OcHCfqW9C4mQwnmmPwgqt73SVm7F8EmNRbLejhjXifBVo/zWYzG24mJUYnVl+DGJE+NE5zPCH+ZKBrVNYJUpMs7Sh4youvy2xL3K5TpwpsKLcLKzJNV0QBFWMhn212qAbbAeOet9FbVwiu1Mb7M20sdSzw0F7oH0GIsJg1ExNBnk0EKmsO/5dw3T/v9Ja2eFYkCCULlxkDTxmCwd4XoRrHeFZA5YBsPcH+SgYNWSjhjdDGlYklMbrR1RrMmmgxmLxIz4lONh8cPQko69qAUd+G7ExobiRYvF24osRHvjiqxnaNDIGlWmHaNoT1BDP2b8OSv6CsnIhXWKpvDmQNjeuXEfKXQ/LKEj8QPZCgFcryYvaK18DAgCWuz1krA9fyoYC8bKO8jswd+GhEBdzRRLzCqGfZljGuF4t2uHnvJ6GKe2HcfADq+B55C1RJZjIZg7/FSSkosE3Kl1RlT51tjA6ritnktQWbMFJmgX9qpUCLZBoST5BwClTsf1qXntEoIXZwetWSQ0d0iV6h4kQoy2U6ir1J6Ow0CyOAaQi8MBHIGn79T/XMzStkTDjtmbdAPPyY1sTNkvIm6m9nvFzPUtj0c6C9x1BhntAIk4MjTWct71M=
    username: AgAZqJQvtmxNFj/pu6a8HDFIYXH5tXTysBriJQM131AvE+vwEIEnDHQ1+dXhnhm1Tlz0QIqFXh+uFgJd0q1mQqRjv1FZF+0JRcy6r3W33+SsYYbcrXrlE/Vo6u7/ujbxVF2gNF0tPE9QIUzbzYzVTl2T/bHdJs7w+shiOP9DiSDFl19BffCcxIbUf5r3Ildwe3H3U5WFI2ATsHfgIsS3ma8wadY2f9ImEHDhxDWHSJxrPuxBTkkC8bSYW1QnB+i9DJG7JW+dQiAog06GQig36D0z01fwlzoTfzSDpagJ6pTDzT+lhnanu+hK/P8/pT2zQK20jFXQDjVewvhOIoh88ExP0XRXP++dt+VJke4mBecXAY6Snf+MNY38nPwviA2BqH9nYZxn0W5of15fOmzcTDcX7oDK1v5DlC7LFjuutpPQYLf4zUyIviyCsAE3hpckiFgLusEOstTBckiWu+J+Yop8ff1I8fASdUe7YdkJ+/jZhyZIDI8X1IWMcD0YDbSOXwG5KmeGFZXTX4qYZwgrTrRuBuO+ucEjL4aOW1jwQDf1HzuMMg7vz6z6pVQ5knbh/RZmrGS8y7G6RnjMudLcu534vegeUpKeoyl/Kfs0RQT9phlBCy3GSPxWZRQkofkxjhzv7ZtR6L6Y3zimK/og7nQc7FJ3fJawEtO1JB1XHmEmzdA7opbSWBJNhPVDU0OCu6/+db4=
  template:
    metadata:
      annotations:
        kustomize.config.k8s.io/behavior: replace
      name: n8n-db-credentials
      namespace: cnpg-database
    type: kubernetes.io/basic-auth
