---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oidc
  namespace: n8n
spec:
  encryptedData:
    client-id: AgAj5pHKOy8HWvqZMPyzEHfnxj2tG2ASLnn/Z6GzWcKXLZaatTNTwXMos39b1ln1FivA/EeAbGGEUlOcPMp4rHh30cUnYMonITQW9rHpSnRv5Ivqnmg+3CBqJFYVBS9Hi0b7mQkSZa56Nn5hUxrLgIuc8Wrb+p0WKwspjnHTWgXu260Ue+J9TkTwCuQk/owzwZbpzVDeX5B0a8dG3vf6UM6i6sygZak3RPUxzKBr1Hb+OgOlzak/FKnXO6gb3gBgousQ53w4KxJ1kS7/zfS/26Wp1ovhXjIJwVkL7tw/C2V/tBLmrFt5sK7DB7VuTs7ol4fxcKbhXB0LdKDCc5swR0UwPtNaFZlaT5gqU/0+SsLjYSXwS4iOGTuQxYlV8/1cO4QXavVqA/kUxj/ZqHsRYTaA8KgtiNj/jS2lUYK2aAfOksvz37TH/LD/l++3L4uztflnTuYUVQAL/XabQKfiAdpTN2iVQ5neMPck+4G45GPRzqtOTpjanmocRgNg5FgvA/1OG9VAs+Uj+SUUuq0vuBwmJWflhHiJk4MRTjxwnjNrKYgdHUMVFVr6T95kXLR1zrx+3LWgynA5lKuUi7p5SpGrA64iYtdo0CUed8JJF9ERSDzgtm/GwFQjmVvIiBJkvcstAuBpN6HLcaXZdd2/umoxvceEHgmHoMAcywfko7x8rXe+oZEfCg88kmXzn+rgxufzt7C46fh9vJwVqPX1j0f0nXk=
    client-secret: AgBZ11+mR4QIs2xeanlHTA8QWN65wde7mv54therQ0wbhnyWrszpAtm6QkbEhC85Qd7nx4nW+QcdZCPgAL4S6AtzX1q/y4dV/s7NCM2jcOgD0Ssu/6OlByobCvRcZmTEFpnm1x5lpMCh1RJqQjyc1R+l6a3tbzjc9BdD6DbiSrAWgysVWRIrpfXmF9435Gt7Qz+6Lf65aJ73CGvDh2aUcT72AH0mCwvy4bedF1eThxzQt4NgKzV+G8CnfspkNC6CAQ68iNJVBorU5lLuu1P28gxFUbFMVarX5C+Wkv0bIwC4dxPF5+OJjxZlMSwzljH6JDzXfjcxo1Fm2BZ8MIi2EosEPrRUTeVaLlCHmnCHj/LCn1OCX0NampffhSNzYoqr/RTLPPEbJK0Q+4uphGWgDBWfSFZjYXgDhVU7TFgxaIN6e/i55Mw4VxOLCnuSe3sO0NYo9IG+/8D1KizlNWYgmn5w4U+O1Tfu27rTq7f+BJg12FJVp/KaWpPYW+IL01oF8FUUiloYMKc6SWDakj5W3oHKHyTsCJVncvti+1W60M5yZqd+n1b0gYq7SJK6IX7EF3gZyZ22cvASoVtybtdpQPBWJXaZ4jmEjxkllpBXBtA2Le0CeEMaaZwNMiKGRC6fDJaFcVH7YBpfBp2g+hRSMN1/g/wctsgv7lZatFEBBsVShRSN9JY0kvMkIyNM4ZHil6Vw2XLXwdrHoqa5Os0MFGLZvG4G2qkyOQ3dl3cw1ux+uAoWBzGrA7njRDGXpT+TPhedFF4eVLEAZXQ9WV6pjRyM
  template:
    metadata:
      annotations:
        kustomize.config.k8s.io/behavior: replace
      name: oidc
      namespace: n8n
    type: Opaque
