---
apiVersion: v1
kind: ConfigMap
metadata:
  name: synapse-common-env
  namespace: synapse
data:
  SYNAPSE_CONFIG_DIR: /config
  SYNAPSE_CONFIG_PATH: /homeserver.yaml
  # UID: '991'
  # GID: '991'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: synapse-run-env
  namespace: synapse
data:
  SYNAPSE_WORKER: synapse.app.homeserver
  TZ: Europe/Oslo
  # SYNAPSE_HTTP_PROXY:
  # SYNAPSE_HTTPS_PROXY:
  # SYNAPSE_NO_PROXY:
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: synapse-generate-env
  namespace: synapse
data:
  SYNAPSE_SERVER_NAME: karlsen.fr
  SYNAPSE_REPORT_STATS: 'yes'
  SYNAPSE_HTTP_PORT: '8008'
  SYNAPSE_DATA_DIR: /data
  SYNAPSE_LOG_LEVEL: INFO
  # SYNAPSE_LOG_SENSITIVE: 'yes'
  # SYNAPSE_LOG_TESTING: 'yes'
  SYNAPSE_ENABLE_METRICS: '1'
