---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: synapse-db-credentials
  namespace: cnpg-database
spec:
  encryptedData:
    password: AgCqTtL+tyxoB9rHJXJSeIrRhV2aA1nSaHRKhUkiXmDHnbh/QXih/SyUMXtw3kIKM8kuH29TBwrRVHa50XoTZx/1SW7BUHm4i5BmE7nMM1i4T54GTQVyxSniP8L+eFn32yHOxVeiL+UHFQkrW9dJ+yM3vSEGrb0NKqqf/EgzQXy90R2dPERc2bzoCpNkfiVjnuRkjhBUu5SIjG92xa5CLT+MxMLVoeWe465v8/QVpax9PL5GSY6ysQyoAtzcVUs0Kg9F8r+P82flJAfZtSRN5lxQJY9nZZ6AKrsi/IZtxadOG26E/IiNZpQGooqLvgvu9VgMfkyi4t1yswbPHoe94em2rvLsuwcwBf8TIpyk6StQ2aW0+ICjeom0LvDFrqlnDU8QKeDGk6e2l7wgPxrscRs/u1/F/Coe0+LJAfDFidMMjGsIsKKSUIDFCDSI45m9rgsfX7ics9WAUwDqP7e5fPzYbrbH18Ay3LJM06yYSmjCqkSTBzMA3ZAQyWfbGyXWvHZDBsWkgURSGZq8a2qSOMNV2NzkTyDZ203Ej+SSkWgZzfJ/migjiFLkNt0nkuAE1ugE6bLCFyeGtqT+7TXGY4KHCSLy/U8rAeA9AWPKOTtpSTgI8GJ2z3w0/9IjE6Tmqu+gNdut3gOwB2lC0Qmy5QN9rT7vHMJ/jXtigt3hm5c35hM3i64nFwHAu580YZeQBSD9ZjRgM/N0s+YzHF+xH8z3EGA9/Z6PZ9Hajrneo5yWjthEMKficxZI3E4pmgP4Z6E=
    username: AgBAX+2jHAT2+WyvC3TwTFrE1KowZXLHFSUjyAY3lPdhnJpd+wu5mlA3CNjcLs5Wlt4PFDTWjAsPwFu1QSgonXfuk26zd8esq25Giiy4OsMMH0n8KuHZHeJzI6qyIU5TshjHBS0ZUuH9jw3vyek7sZftMHK8YMJ8NfVzkbWB7G+WVOroGa78rOaVEzGlCLJxKmtFxtseP0X1IMoKbpkiKrPTXlFeWW0vGW1TAuwCEepD/obvFpqKOxj40Vw0szeDMVcmD28ba3Cei27tQ0f99JzFpr/qfjVV2JI8pRZAPWtc/glQavSRcdxOhC/w0JqMBj85uC5JNXQSoe1UGlYL88OnkgF/Ql9Kc5HNjn38r2j6qS+5AerMR9fcmaJhn4L9TyInpj+aGAGDtwNMh/UWBz5sqKUoja3n9cGpwtHYgqZ0e5Hj6SRPtKhFGABGNBMEIA4szmjhNVuiLDkYsG0Z2QY3zuwdbUWQWyXCaxlV/ibNYueTnLD+Kx1IBNhrAx8CA/fTYrmbsKyqSN9OiRlYuX0E+ExWABd2bFzC3wsxVBVYZQzHUFaoUxk34+1gS7ADLorZSh33CXN7YDRTl5Yh3wvlm+ECV29peVB05WcP1wlJqXUOZ8vnBymx6NDWOVyBqbVKQcZNqtMww/6LTm2c1J/sBkN1apMeVINNkLl143EKbXKe8QE4tnK6iwBZAda4oy21RirIp8RK
  template:
    metadata:
      annotations:
        kustomize.config.k8s.io/behavior: replace
      name: synapse-db-credentials
      namespace: cnpg-database
    type: kubernetes.io/basic-auth
