---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: policyreporter-trivydb-pvc
  namespace: policy-reporter
spec:
  accessModes: [ReadWriteOncePod]
  storageClassName: longhorn
  resources: {requests: {storage: 2Gi}}
