# yaml-language-server: $schema=
# https://github.com/kyverno/policy-reporter/blob/main/charts/policy-reporter/values.yaml
---

resources:
  requests: {memory: 64Mi}
  limits: {memory: 128Mi}

ui:
  enabled: true
  resources:
    requests: {memory: 32Mi}
    limits: {memory: 64Mi}

plugin:
  kyverno:
    enabled: true
    resources:
      requests: {memory: 32Mi}
      limits: {memory: 64Mi}
  trivy:
    enabled: true
    updateStrategy: {type: Recreate}
    rbac: true
    podSecurityContext:
      runAsNonRoot: true
      seccompProfile: {type: RuntimeDefault}
      fsGroup: 1234
    resources:
      requests: {memory: 32Mi}
      limits: {memory: 512Mi}  # Needs some memory to decompress the Trivy database
    dbVolume:
      persistentVolumeClaim: {claimName: policyreporter-trivydb-pvc}

target:
  loki:
    host: http://loki.loki:3100
    skipExistingOnStartup: true

monitoring:
  enabled: true
