---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: light-ldap

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - {name: lldap-config, files: [lldap_config.toml=assets/lldap_config.toml]}
  - {name: lldap-env, envs: [assets/lldap.env]}
  - {name: bootstrap-env, envs: [assets/bootstrap.env]}
  - name: bootstrap-schemas
    files:
      - group-schemas.json=assets/group-schemas.json
      - groups.json=assets/groups.json
      - user-schemas.json=assets/user-schemas.json
      - users.jq=assets/users.jq

resources:
  - Namespace.yaml
  - ServiceAccount.yaml
  - Job.bootstrap.yaml
  - Certificate.yaml
  - Deployment.yaml
  - Service.yaml
  - CiliumNetworkPolicy.yaml
