# https://kite.zzde.me/guide
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kite-system

resources:
  - Namespace.yaml
  - SealedSecret.kite-secrets.yaml
  - HTTPRoute.yaml

helmCharts:
  - name: kite
    repo: https://kite-org.github.io/kite/
    version: 0.10.0  # renovate: github-releases=kite-org/kite
    releaseName: kite
    namespace: kite-system
    includeCRDs: true
    valuesFile: values.yaml
