# https://kite.zzde.me/guide
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kite-system

resources:
  - Namespace.yaml
  - SealedSecret.kite-secrets.yaml
  - HTTPRoute.yaml

helmCharts:
  - name: kite
    repo: oci://ghcr.io/kite-org/charts
    version: 0.12.1  # renovate: datasource=github-releases depName=kite-org/kite
    releaseName: kite
    namespace: kite-system
    includeCRDs: true
    valuesFile: values.yaml
