---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: &x-project database
  namespace: argocd
  labels:
    fr.karlsen: *x-project
spec:
  generators:
    - git:
        repoURL: https://github.com/sebastka/homelab.git
        revision: HEAD
        directories:
          - path: k8s/infrastructure/database/*
          - {path: k8s/infrastructure/database/cloudnative-pg, exclude: true}
  template:
    metadata:
      name: '{{ path.basename }}'
      labels:
        fr.karlsen: *x-project
    spec:
      project: *x-project
      sources:
        - {repoURL: https://github.com/sebastka/homelab.git, targetRevision: HEAD, path: '{{ path }}'}
      destination: {name: in-cluster, namespace: argocd}
      syncPolicy:
        syncOptions:
          # - ApplyOutOfSyncOnly
          - ServerSideApply=true
        automated:
          prune: true
          selfHeal: true
          enabled: true
