---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - {namespace: kube-system, name: coredns, files: [Corefile=assets/Corefile]}
