---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: searxng

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - {namespace: searxng, name: searxng-config, files: [settings.yaml=assets/settings.yaml, limiter.toml=assets/limiter.toml]}

resources:
  - Namespace.yaml
  - SealedSecret.searxng-secrets.yaml
  - ServiceAccount.yaml
  - Deployment.yaml
  - Service.yaml
  - HTTPRoute.yaml
  - SealedSecret.oidc.yaml
  - SecurityPolicy.yaml
