---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: searxng-secrets
  namespace: searxng
spec:
  encryptedData:
    SEARXNG_SECRET: AgA+gk/vekVWoePrdOrl+Vy92l86JfIkG9xreI3oXe1fxh7q3KqjoE25emVjsnRd+tKk5ZPck1Lt+JA4wcrn8yH0/sC00EEwqo2DmmypywHvNWtZy5SUB+s+josQMW4YY59fzlfgcdUalZ/RcxjyyMTPDET2DbBy23DMZ3z/AzxdtL7s0SA/NHSO/pXyF5MPtsubl7ipiytyBFPEkR9jEkPTN+qFUb0MX+9Df8k4PORBD4q7f/6JFCWXmCedSIzY4xE5xrB2TXf+8BH7pDMBScVLc9Sx8QK4NFYUvoDmXxeafGXoZNvLo9y1y6pkpWyDvT/CJ+w3cZL3EsQVvOk5Us+WhT2AjeUG4owcMgU2NYULA0pNqaVPlQUMa5tydY15t9qGVP6gzaX02+0qcxrL8ilTINcc3TyAU/RZwlSQ7YdrwgIfgmXWzwZ3vWj1IHedmgzIuRrED+xoBCHMZN0Z24zi/672506DwjXhB1vFVsCrI8cBpLRW81BYnPdhc0UBTs0OIJfjUeBPZ7CNcS03u78qJs26PFzwgv1C+u9iNkEEWbPD8qezUcmPsg1ZDDqAYKG3FuKfYE4rMZJUY4nnuCktdOFV0EHeGwnNzQJA1E2PuRc2kwzNcqad7j82fN/zSCpNLCh/dg3YUgNXKjPwBA+qNVfoY49s94xJ/gNoOPcH/FNUgbtTjwMRrPKWK2fD/kcOloCJl+ajz8wvWCn7lAsgO5z1L5eU52qw9B6Chp/ETOdjMKJhlh42L/6ijEtvUHk=
  template:
    metadata:
      annotations:
        kustomize.config.k8s.io/behavior: replace
      name: searxng-secrets
      namespace: searxng
