---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oidc
  namespace: searxng
spec:
  encryptedData:
    client-secret: AgBtv2z+Sh53FYFKwOBIAttWEu/ZYpJffu7p1B/uPjhCrNSd8cT5lqVygFqzz2TMp/zslkZH/HtzOG+WPoIrzLRtOrF7cKdt+3IJHNbLV1AAGk0TTRMMcR/f+5HofYCPCEi6UGYBtDzsYxg4Zb5VHW/C4viC46hRhKT5+1AZf5VFblXy1rYu6OGkQLp6BwstpAh9t0h5kmdcLQDNXZP8aT8qNzPezmHzf6HOzVQ5hsVv1WLx8IteDCsD3mx4O2sudJAS/oT2yu9RFRXCW/BCX1IAIg4fnrwViRaWNkJflyO8U0EGFgVXSejFegBKa7a5GBPhZSDXYWpZG6JaKjpcf5NKfxJi6jI6Ye6w6Rg1npilTyYW8WKgX6KUKYQv1MOZpMnubbEIerYQTcUX+1hDKBHFIHyj7aPGp2D4PQ4sIYt38kAaft9dqWIGInyS8T0z960kGAp71wfKmQB4wkkeWOZ5q/XWoxV7QCgd903OAopY1Ilrlju2zLZ/y6ksL5Q3pMps1kxYgO43VEtUJYh0I7Isg9DXekIeC7ftjtQJ0R4NBpOuFbhYz0kECVb3tiEGNTgpPAK+qbF8o5pCU3LtTGJm52xeqVkQz5Bp+ADsttDIlhmsLOTgIu0uTPRSwsC7Od2/WAHxaHDKfFX0chOZ03E17rhEkJcj5T/sfy3FBi1OB56XrG+VzD0GZkgl4vPjISoYFEzhNsq7TCePUnoorRlD070xhB4vTiBKTVQzm7kcv+A4wYKhqXrqr0KLIg5ys+t09YbtAyHo0zwvu/D/VgBExqd6mPwXx9A=
  template:
    metadata:
      annotations:
        kustomize.config.k8s.io/behavior: replace
      name: oidc
      namespace: searxng
    type: Opaque
