---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: searxng-secrets
  namespace: searxng
spec:
  encryptedData:
    SEARXNG_REDIS_URL: AgCp5BZYQ1/lK3T+VjP5HsDtvi08EXbaJmMNIo7UVJrZtYFnA48twa3gk6WAf/dlZVFRKqpp0mvqPv58sdjKr1J11PeB0AVDVa1526g+FlKykZhWhqJE0UNivnCeLws0Y3ayv4YLWk3RPmK+rx7bKa1jLCIuZj7sexy6zd9HUckXclpf1feZToe94F+o8QDm5qGKksYWWstze4Z/Jnw7yzGD3rJh5t5NHaqRR8GTtE/lUnWk/wcv+WNZJxwVQHufLT/JSGl+NVeEVRvgRcBx0wdDWT8mK+9FHZxQtzcUwvWG1bAXGVAG+NKZ+ijThZAhrYO5XLknUH9QiCknmvNCgPEGBu9tOVA8Dol+wQtBI/aMThjQjzVd3INBmKGXp14ATmKxg8dk1W2tROrQNcPnaMHtzBzNA8Rd09/r3HxmRa3u5wYvGI4CAUsP50w/84k7tZYjBA59ws/DHbImft6Tqywg6WkgOEreTqvjf5txaM871VcwHMA589vV8qtdli4EaY8a21DcelFpDtV989UGN45pspPgmdcwz/xFIH9ORBN2Wx6M3GHhjS2JCDkwhq56M65qwaXVyAjQv4gWqiddwB/MJacJ1nNUHfhvmkPMqZJbd5JtXaU5DgolU4LudkGO+x5U0GEJStBk56/lUAoXmxJgZ/NqrMb/XU4pszV5ICZad9I5nddop+bR61+A7LSL0YrwDXM61BHqBKsrZfhOhMqvvpqZ7qLdfHCEZoTlXaCB/O43pnD86sdZvvpsDOaJjb4wwmMLUtNjv8hBAWohFvgJXZG1dW+wMkFze9mZfDixLu7QvvYwdOIO/2rZ4mwaQs3TsdL4
    SEARXNG_SECRET: AgAp0FqYqG3JZSP+u7LqHLEmZ2XDO0+AG8KGyEWaYN9pQX8/ez8y0uHxOpLOL11UMHO3Q8uIbpINDujpreI/Ic3i2UMTYGsl4xpkSXqox1l0Gu7RobgcgmOLAV0OxSX4y9fG3aYgZKbBvJtKsJLbxMolao3AcXZyK72ytG/f4mwDMnTOGWco9/EOPoDzWM91wUP7CAF1WHbb26WREUWHirjVTt4/oROAq1Uxw4xUdo9fTQJhRSeaustRQMrQSXhgKTEMnhsQrfLhOfQ8e/akTBMdRFrnbg1wYSK4+U4ChKKo0TwbtVBtWGIq53fPDr0TbGw/NGJyeC/mOWtIsoi2K2UMbcEi6HcjIKws+pDCIqbJmBLIwBOHa3aaXuFmDGGxnbJboVvDYLurVbk9N5Bq/lAnTt9dTkkEk6G+HjeCD1WO2ViG/sse1ehgYxrn2d2Rq18fNYHSsVwxDhetDyNxyKl9bGxM5dSHB4mln1HDmUUn1vfvoL7avre2/qe8gAkVDBal/0OoLABZ24P8lY5djq0pYIY1czaFUcCtotsWsx5MlhznsUvB+690kyiilVW2undsZT2bY4YnpT1H25aXbFBZgeHSIfm86k/NUFjE7JaoD14qr489fmMUNI0wx2UMlyJI7wjwk/yKHoDOjcU/Vlv5iuirfCaGDU0IvpccJanYpYVLlGAWH3HkKTubeUn/zVaBWLzrZXx7LgS7gIiA9G8a05hohgRq5lGXlcUhoxr3YbKhYdoWwgAIf+uKkUOtuKg=
  template:
    metadata:
      annotations:
        kustomize.config.k8s.io/behavior: replace
      name: searxng-secrets
      namespace: searxng
