---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: searxng-secrets
  namespace: searxng
spec:
  encryptedData:
    SEARXNG_REDIS_URL: AgCAabPYDh0wtGpirps5noX9qcEafsS5ISl8rmZE6xrS98CzRBjyoz4b54YbeR+7gMZ1djizfatb8BINJwApXaNkvdwND4P8Uh1iSAMedJU55oaNmJrhAHTfZSXSdVtfGgmO1ZXQcmtsLKhfiGl6xvQ1GSiJTYlviDnySpmg9JUQATcxy9rPGriZHQ7n7W+WciCPnXn0e+hLsSada0ZeXu2kM4HK3TAWpTU8g8xKyK5iKWcqiuMTtJfnwqru7Hv7yKi0kkxD8uiz6qSZlARGBtcTfalL99RiwCWVwfA/nXBCKreYEzYV7btHQNNVdqjV5dtPfLaDi+yqw/1dPRTbz5Pf8Ye01FVkkxlFbJh62ULK28duA85hmEAwKIDq0h+9ngGBTHiMa2RYjZ3LRHsicVfnS6xDSlsXhBWm8GMErKUsHZVbnKfti6ED4DhAYyR0y256gVabdasx+p+hCccRVn35qDr+Dj2SfsXOxnMu3ryswb7UJtYuib8UYibRk2H/hA570hjonRzjRD67hHbElBGduYyLAFB0k44QAXa2l2232xqFON88Zr531KUhXgmVeCJnRQnYtW68nfTiO91xdrReuXOmSfZr34wL/ns8W8ph015149Xl4XAup/yeS+3B6tiWtst7lyRLKxCxmg9LBW++FP/OwG5V79diwTac2hN1vRKelKkWoTuIVdbqq4zu9CaUwvj9PRW1eI3r0xvC/walypV/MsTHsV17Mhcdur+QUbCXFUXaGOI0uZ99RksHoKX3eczvCmlLYELW2LCzzsOToqqpUYegeKtM7ZtSg2jCnmcQRowF1ZHg70r3N6dpCa/6jPXz
    SEARXNG_SECRET: AgCEyk7JTxLaLEQKk0Et8bsia7XR7F/h6fBIeWFDZXzSogjz3+3SsuTFYdV+bVofFv0tly7OmNbBIhXghrgnqeBdfyyovc/a42H1wKKWO3xhZphen6NkYB4FzAFBw6udgA2OSY3doBvwlaR7ZUQIpMRvXO57qlHH7o8tR9iGGinlWukr4/xImwUvw3QvsJXUmdaPnGUOx8xw8bSnogpNQGi1SQAr1QqqcBZEVu7A1xd6ejAWvC5mPJlqPsPPKUiP1ng/kNfeoZTSKh4xMMp/aU2inCe2sGGvTH6jNk7EuZ89LCriqPDZvGlHbuJPM4JqKJYV72kQq/nXRxtaR+FmDWCHIDiFXWCWAH4gb+k2tOCvPcdDYK1msWggI/0VYwTFJ5OHMaY3hIUlDfSDs5d1GGr+BHMipn3dA21a2fOGUY2u9Sv8NeFBDcwLqAEMW1BQT6RNmMRoqcLLWPVb6rNkHokjU+AQ7FhK7gm4kyNk/PdQkfsA3lLEveQr22YsU4asz/N7uRF1PL8dnPXu0SfjCEg979kMUqfe84RsMNck6G7Jad11R/3MMSBYQQKAFsZsVVGvFyCtDSeZvK+9N2lxT7fg+8hhSYSJG+byKM0vyoQznjS3t2U8tMYFcGKYuN9rqBd8Cg7WPPzEmOd9GrA/DB9qCxkS5TRE2FA7P8KqEu50XQTnzt9PWobIeR4Q30prS69/Ml4F419iP8cUvAihQ7IqCmM2kjOSe4kRSgQ0q5+ltPyJhHp8M+PBn7HjrlAAMpE=
  template:
    metadata:
      annotations:
        kustomize.config.k8s.io/behavior: replace
      name: searxng-secrets
      namespace: searxng
