---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-default-site
  namespace: homepage
data:
  'default.conf': |-
    server {
      listen 8080;
      server_name www.karlsen.fr;

      access_log stdout main;
      error_log stderr warn;

      location ~ /\.(ht|git|wp) {
        deny  all;
      }

      location / {
          root   /tmp/sebastka;
          index  index.html;
      }

      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
          root   /usr/share/nginx/html;
      }
    }

    server {
      listen 8080 default_server;
      server_name _;
      access_log stdout main;
      error_log stderr warn;
      return 404;
    }
