# https://hub.docker.com/hardened-images/catalog/dhi/nginx/images/nginx%2Fdebian-13%2Fmainline/sha256-12e286038641ad2919be50aec641eb6eabfc7f68d1ad8a8991cf6b8a922b2bf2/specifications
# Set up redirections in html because of HTST preload requirements on headers
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  namespace: homepage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      namespace: homepage
      labels:
        app.kubernetes.io/name: homepage
        app: homepage
    spec:
      imagePullSecrets:
        - name: dhi-io-registry
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
        fsGroup: 65532
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
      initContainers:
        - name: git-cloner
          image: alpine/git:latest
          command: ['/bin/sh', '-c']
          args:
            - |
              set -eux
              # Clean up volumes
              for d in karlsenfr other openpgpkey; do [ ! -d "/$d" ] || { rm -rf "/$d"/* "/$d"/.[!.]*; }; done
              # Homepage: www.karlsen.fr
              git -C /karlsenfr clone --depth 1 --branch master --single-branch https://github.com/sebastka/sebastka.github.io.git .
              rm -rf /karlsenfr/.git /karlsenfr/.nojekyll /karlsenfr/README.md
              # Other tlds (org|app) and karlsen.fr:
              printf -- '<!DOCTYPE html><html lang="en"><head><title>Karlsen.fr</title><meta http-equiv="refresh" content="0; URL=https://www.karlsen.fr"></head></html>' >/other/index.html
              # WKD: openpgpkey.karlsen.fr
              mkdir -p /openpgpkey/.well-known/openpgpkey/karlsen.fr/hu/
              cp /other/index.html /openpgpkey/index.html
              cp /karlsenfr/.well-known/openpgpkey/hu/* /openpgpkey/.well-known/openpgpkey/karlsen.fr/hu/
              touch /openpgpkey/.well-known/openpgpkey/karlsen.fr/policy
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          resources:
            requests:
              # cpu: 10m
              memory: 24Mi
            limits:
              # cpu: 100m
              memory: 24Mi
          volumeMounts:
            - {name: karlsenfr-volume, mountPath: /karlsenfr}
            - {name: other-volume, mountPath: /other}
            - {name: openpgpkey-volume, mountPath: /openpgpkey}
      containers:
        - name: nginx
          # Dockerfile: https://hub.docker.com/hardened-images/catalog/dhi/nginx/images/nginx%2Falpine-3.23%2Fmainline/sha256-838bfb5a32b0d803389b6ee72ed411c066b3b49301ecdd8e0d7469bca06c2f77/specifications
          image: dhi.io/nginx:1-alpine3.23
          command: [nginx]
          args: ['-c', '/etc/nginx/nginx.custom.conf', '-g', 'daemon off;']
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          resources:
            requests:
              # cpu: 10m
              memory: 12Mi
            limits:
              # cpu: 100m
              memory: 12Mi
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - {name: tmp-volume, mountPath: /tmp}
            - {name: karlsenfr-volume, mountPath: /karlsenfr, readOnly: true}
            - {name: other-volume, mountPath: /other}
            - {name: openpgpkey-volume, mountPath: /openpgpkey, readOnly: true}
            - {name: nginx-config-volume, mountPath: /etc/nginx/nginx.custom.conf, subPath: 'nginx.custom.conf', readOnly: true}
            - {name: nginx-config-volume, mountPath: /etc/nginx/conf.d/sites.conf, subPath: 'sites.conf', readOnly: true}
      volumes:
        - {name: karlsenfr-volume, emptyDir: {}}
        - {name: other-volume, emptyDir: {}}
        - {name: openpgpkey-volume, emptyDir: {}}
        - {name: tmp-volume, emptyDir: {}}
        - {name: nginx-config-volume, configMap: {name: nginx-config}}
