---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: www-karlsen-fr
  namespace: homepage
  labels:
    security-policy: httproute-allow-all
spec:
  parentRefs:
    - {namespace: gateway, name: internal, sectionName: https-karlsen-fr}
    - {namespace: gateway, name: internal, sectionName: https-wc-karlsen-fr}
    - {namespace: gateway, name: internal, sectionName: https-karlsen-org}
    - {namespace: gateway, name: internal, sectionName: https-wc-karlsen-org}
    - {namespace: gateway, name: internal, sectionName: https-karlsen-app}
    - {namespace: gateway, name: internal, sectionName: https-wc-karlsen-app}
    - {namespace: gateway, name: external, sectionName: https-karlsen-fr}
    - {namespace: gateway, name: external, sectionName: https-wc-karlsen-fr}
    - {namespace: gateway, name: external, sectionName: https-karlsen-org}
    - {namespace: gateway, name: external, sectionName: https-wc-karlsen-org}
    - {namespace: gateway, name: external, sectionName: https-karlsen-app}
    - {namespace: gateway, name: external, sectionName: https-wc-karlsen-app}
  hostnames:
    - karlsen.fr
    - www.karlsen.fr
    - karlsen.org
    - www.karlsen.org
    - karlsen.app
    - www.karlsen.app
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: ResponseHeaderModifier
          responseHeaderModifier:
            add:
              - name: Content-Security-Policy
                value: default-src 'none'; style-src-elem 'self'; script-src-elem 'self'; img-src 'self'; connect-src 'self'; frame-ancestors 'none'; form-action 'none'; base-uri 'none';
              - &HSTS
                name: Strict-Transport-Security
                value: max-age=31536000; includeSubDomains; preload
              - &CTO
                name: X-Content-Type-Options
                value: nosniff
              - &XFO
                name: X-Frame-Options
                value: DENY
              - &CORP
                name: Cross-Origin-Resource-Policy
                value: same-origin
              - &COEP
                name: Cross-Origin-Embedder-Policy
                value: require-corp
              - &COOP
                name: Cross-Origin-Opener-Policy
                value: same-origin
              - &RP
                name: Referrer-Policy
                value: no-referrer
              - &PP
                name: Permissions-Policy
                value: accelerometer=(), autoplay=(), camera=(), encrypted-media=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()
              # - name: Reporting-Endpoints
              #   value:
              - name: Integrity-Policy
                value: blocked-destinations=(script style),sources=(inline)
      backendRefs: &default-backendrefs
        - name: homepage-service
          port: 80

    - matches:
        - path:
            type: PathPrefix
            value: /.well-known
      filters:
        - type: ResponseHeaderModifier
          responseHeaderModifier:
            add:
              - *HSTS
              - *CTO
              - *XFO
              - *CORP
              - *COEP
              - *COOP
              - *RP
              - *PP
              - name: Content-Security-Policy
                value: default-src 'none';
              - name: Access-Control-Allow-Origin
                value: '*'
      backendRefs: *default-backendrefs
