---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: homepage
      app: homepage

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: lldap-config
    namespace: lldap
    files:
      - nginx.custom.conf=assets/nginx.custom.conf
      - sites.conf=assets/sites.conf

resources:
  - Namespace.yaml
  - SealedSecret.dhi-io-registry.yaml
  - ConfigMap.nginx-config.yaml
  - Deployment.yaml
  - Service.yaml
  - HTTPRoute.yaml
  # - SecurityPolicy.yaml
