---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homepage

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: homepage

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: nginx-config
    namespace: homepage
    files:
      - nginx.custom.conf=assets/nginx.custom.conf
      - sites.conf=assets/sites.conf

resources:
  - Namespace.yaml
  - SealedSecret.dhi-io-registry.yaml
  - Deployment.yaml
  - Service.yaml
  - HTTPRoute.yaml
  - ReferenceGrant.yaml
