# Ksops:
# - Encrypt: sops -e Secret.dhi-io-registry.yaml > Secret.dhi-io-registry.enc.yaml
# - Decrypt: sops -d Secret.dhi-io-registry.enc.yaml > Secret.dhi-io-registry.yaml
# Sealed Secrets:
# - kubeseal --controller-namespace sealed-secrets -o yaml -f Secret.dhi-io-registry.yaml > SealedSecret.dhi-io-registry.yaml
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dhi-io-registry
  namespace: homepage
spec:
  encryptedData:
    .dockerconfigjson: AgBGoh8y6Uv5gFPFVChV9H4meJt3HQp2FbcS+HhRGAmjE0HQIwHcrFMEfnzOaQ6QZQ9y1TuidUlffM9bBz8AhQta2Y2EYwwOu5lUG/BsRairDq1y+MI9rqePmEzxR3ERW8Sw2gKATlZEHfqmbIHOXvEYw/kpYRTojMlwTWhtXMMpzF729fpmKpqZtvaqrHRTIJGssTFb9YXveIR9LsX1TCqpJ7CNkvKUEqb+p7CblFiQ0wiIyNoI7/B+nxNFJbFLgdhdreTVZLn/lV4Ev+b8jfDRIUf8iPhgA99QuSBABKvc3tFyGlRHqctLkjhKmBL4Tvvh30/CNEN7oyXLIzwfHGDV+qLcQAdX80mR5f508rfAdUGYzDcxCaCZfktPJiRa5AUYgvvJ87NbJKLEKj6T4wqFWuOE6TsJP1d5HCC3pEglzxvq9YgiTIPxWGPTeyLamIb+04hykDfw4/QosZJxGo/4gQkXWrfhbHl8BnegFSmaxtWL33e8ICLdiwrBdatTrsXMSPGHpx4MbauPwYYlpt3CIQvmLvdHdyP2OpQzKHMuOXKl9MTE7wi9BHAVThlx/WsjfEbU3TJBOKfDal80niKh69m1yJbDmG7ysqBj4U3DbQda+CQcbnUKknTWHhaQEUjLbioimi5dBcZe5ExXFqmTxAkL4z/ZmN587rlKoM7FCo2Pkzx5Kk6FP06hm48L36TFxHDqXjZ9QOEkV6NmAsAMO1tf3izHybAO/7AvEA+juGjqA2UezQmqO6zDXlMjCnTu7xsURfwHqkX5rWUfv4XPJZlo2EnnSN3cZqRHjp4kNFazqe1rCQNg35ZovMso85CTm2N8JZnVbmSxNDcX/1jIMyDeHR9RoaXxfnIQvP82D8tN5Ler5kAgaMopgC4t+ljFjqGHlvpwDjC9PtEgDn1et840oNULZmRo4VOeqXLScCwI4p3SCpIGW/mWOKXYp4pF6Gc=
  template:
    metadata:
      annotations:
        kustomize.config.k8s.io/behavior: replace
      name: dhi-io-registry
      namespace: homepage
    type: kubernetes.io/dockerconfigjson
