#ENC[AES256_GCM,data:254bxIrknys6Onroyh9uDDr4W/oYYrdvocZD7mWCv1NTl6UZP8D4/QH1akUFPsQ/dUr07ryEQJXYoSNQbHi8sR/6KLFP3WcyCbH9A3ZWbg==,iv:+CjVVbpOGfgzfg/a7QqVmcEHnMGUrRuojOLUrJb2+B4=,tag:FUsEHc8qcuakmIk264ZfNQ==,type:comment]
#ENC[AES256_GCM,data:FjseQLq0/9Ft+DGXUxPCwY8Pf+PIlQC3H+VhkeDUssKo3nJLqZf+XPwcHCxZCb6yLkuejhzeM2/5gpfgoQDz+zNRQJI07QhnIH9HfvhpHg==,iv:2Elqcnm/oRXeyAVimtbwNBai6dueLhrBsvfzIWxa7N0=,tag:qYLNtfNnJ6mMvmxjK6j4SQ==,type:comment]
apiVersion: v1
kind: Secret
metadata:
    name: dhi-io-registry
    namespace: homepage
    annotations:
        kustomize.config.k8s.io/behavior: replace
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:uWEWO1XPklxN44yBFYeBeDudvdF5zAFlhur+fly84zuAUXcCW68zK45uOS7hIKH36pxM0SXjCjv3SaHFzhNgmQvuSg/To22ycJilVddleoVni+fvOM5e8DspnoZqvc+y25cnjXf7Gw8oiCDQolMd1BqN7u8L+DUbedGnHnyVdQeieuG83bUj7Ov78/NOrEhFktM6Tmzqawp7nhSrTinfBSf2OxGb2++C0Skj3FB0T5YQ4/kP2Aa1vmhYnwQEWikQyKl4ayzfid1qFXB2MVK0qezgZofIvcq3HnAwJb6Luo94r2Vq6IN+GJs3TQzyt99urwykVBRk8xp0y4IOjiEOBj0AEos=,iv:rIyLowX4zJV8YlxnQ+vQXl8nhyiNjaG7cLPXVq4KEks=,tag:3nNIsBefXQei/EWlZdmcLg==,type:str]
sops:
    age:
        - recipient: age1u8uutg4mpsn82nd9y828sj5agg7s89uswmp7frzpkrruhgw6xcuqr8hvf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaRjllcjJWYzhBNXdwV2xW
            MEZrVXBOS1J6RGNRVEprU0ZlaEhPMzF6dHdZCkkzY1Y3NnlpZmpuMmxkN21NYlIy
            bnBGN1I0VDdsTkwrVThuYU1kUVJrWW8KLS0tIEpUNWgzNDkrNHZpamU4WjhEcHAr
            S1o2Tm9IU2ZjeWdQaXR4U041bG9WUjQK4wXeR57U+gztdAfrL9BgIRLQX52fegK8
            A2E8KxSXbtAMFeDjOA5DG6HdaLSHVVJN1Qpr0xKnZFl1LfctOds2Dw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-09T15:18:31Z"
    mac: ENC[AES256_GCM,data:cEVIcESH8fjkMT8e/cGm0eWK51GnpASvLTZXqbidmmQTM6qIL4antaMNQhKna/4vQRt3n/4YQzu2MRhWeMIt2qDn2OHttwVKVjLB3EFhz4qKSUk3FUWIbX1wE7Uu0+i8hdEjyGmE+7pa6QcCtJhZQdu8pc41Yr0klEURIhBre18=,iv:nMCeMy0Gqwc/SXv335YTV2+31MeC/teIHTibebl7c48=,tag:1avoh1npGl1htovGB6bbCA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
