#ENC[AES256_GCM,data:ZgfxpmtrjoN2hnafJz/5eLutJxqG4GnyqVeyyqrDlnNo3iFS3bVUsGY52LQ277HYi94QgZCPOPwW2vI2c+N5id/j2onF0f3KYkQVfsArTw==,iv:EmoZBso9Re7feE/omEO4HnB7LSzB3yX/848bKysrSBs=,tag:mSQb/w5atH3MYoNB7pzRgg==,type:comment]
#ENC[AES256_GCM,data:Qu+xp/ax3pCs0/Nx4kt5MMo12tLpK0gIp3RQmO3FY2MCyhoqURUd7SYdUYemhz1LkMtbpzsgATxquOQ36KRgouic1TLKTNFYlfW21MZ0Hw==,iv:ptby4eKMjygPmtbh49VktkhhqfutKDEEXzrjjpN3eMI=,tag:jtn7qGjgb+EzideoJk3rlA==,type:comment]
apiVersion: v1
kind: Secret
metadata:
    name: dhi-io-registry
    namespace: homepage
    annotations:
        kustomize.config.k8s.io/behavior: replace
type: Opaque
stringData:
    docker-server: ENC[AES256_GCM,data:4Qk0n6Zi,iv:YgBtphzU4PK1tECOdz4Nie0qsqNlnruF98YHvt7h/4k=,tag:TCIpG2M3ytsrvp7bJwwvTw==,type:str]
    docker-username: ENC[AES256_GCM,data:b8Li72IoO5A=,iv:/ygy6/WGZp+AqyZztOoaH5Wj2kdpEoXP+CxGD7oxYbI=,tag:hgn1LhaLCSVMRlGewt7atw==,type:str]
    docker-password: ENC[AES256_GCM,data:xsLtOyQ51WWuEU9L0gNn6Hg5qncUmBEghNFd7WHMNlruSUBM,iv:dWuiy3RvroV9QH0KyBplONSNdmYs1zUcZaWD1tyT1pU=,tag:LgvmSLpob94IYG4JAroDBg==,type:str]
    docker-email: ENC[AES256_GCM,data:+EKpqlOZIZT6Q3rYSQI1tAwZy1Q=,iv:2u+WKLwRhfAZ5r4ReWO9+LQkANi0pZAsoLNMwJySb9I=,tag:vavRLdkoBq0/jo3Bk5+CXQ==,type:str]
sops:
    age:
        - recipient: age1u8uutg4mpsn82nd9y828sj5agg7s89uswmp7frzpkrruhgw6xcuqr8hvf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYWDlFdll0K0Z4RGNBYjMx
            eTdsb3JZL2JUZVprWCtYNUVaSy84bjRXQzJrCmIya2YyMXBjQkpFVUt5TjhKTHR1
            b25xR1Q5N0IwWGpSU2VHSzlXZERyVzQKLS0tIDR3dVdvQ0dXRWZQQ1gzMVA1OWFM
            aW5VV1VZUVBkdkMxY2ZxaVZaQUo4cmsK5Kx00NDy3vnFsc/xroPXbFd6O6vi7K20
            ufIKRnCRmVC5lyR+bBQ9H4T0aoaqh44GqLlNoMzxnQzkrlenUuHLEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-09T14:50:51Z"
    mac: ENC[AES256_GCM,data:Guhb4DjCEmzX4ygcm2DNJ6agEWWukJX8eRNzhLi4Q1uaSJvlIVFS2GbefX20BccYZTB6oUvUwr4PB62A1J3M9zZPmmKknbA/fcOxJXjk1vm+stTLWtb5iwQLJM1aGSR+WrlQnXFckPCszIFpAwPNTBawQ78XU8oNpThmmIfJsa0=,iv:JUeqobzOQCKRPehkvVuT7FaT5dc46YlETP5jj/MOuHY=,tag:dF4F5+2djUtV4TybW3Y2lQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
