---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: security-policy-httproute-allow-all
  namespace: homepage
spec:
  targetSelectors:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      matchLabels:
        security-policy: httproute-allow-all
  authorization:
    defaultAction: Allow
