# https://gateway.envoyproxy.io/docs/tasks/security/restrict-ip-access/
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: homepage-allow-all
  namespace: homepage
spec:
  targetSelectors:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      matchLabels:
        httproute-allow: all
  authorization:
    defaultAction: Allow
