---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: reloader

components:
  - ../../../common/default-networkpolicy

resources:
  - Namespace.yaml
  - CiliumNetworkPolicy.yaml

helmCharts:
  - name: reloader
    repo: oci://ghcr.io/stakater/charts
    version: 2.2.11  # renovate: datasource=github-releases depName=stakater/reloader
    releaseName: reloader
    namespace: reloader
    includeCRDs: true
    valuesFile: values.yaml
