---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: webadmin
  namespace: coturn
spec:
  parentRefs:
    - {namespace: gateway, name: internal, sectionName: tls-wc-karlsen-fr}
  hostnames:
    - turn.karlsen.fr
  rules:
    - backendRefs:
        - name: webadmin
          port: 80
