---
apiVersion: v1
kind: Config
clusters:
  - cluster:
      certificate-authority-data: ${CA_DATA_BASE64}
      server: https://${CONTROL_PLANE_IP}:6443
    name: ${CLUSTER_NAME}
contexts:
  - context:
      cluster: ${CLUSTER_NAME}
      namespace: default
      user: oidc
    name: oidc@${CLUSTER_NAME}
current-context: oidc@${CLUSTER_NAME}
