#!/bin/sh
set -eux

main()
{
    # v1 "$1"
    v2 "$1"
}

v1()
{
    NAMESPACE="$1"
    (
        kubectl proxy &
        kubectl get namespace $NAMESPACE -o json | jq '.spec = {"finalizers":[]}' >temp.json
        curl -k -H "Content-Type: application/json" -X PUT --data-binary @temp.json 127.0.0.1:8001/api/v1/namespaces/$NAMESPACE/finalize
    )

    killall -9 kubectl
}

v2()
{
    NAMESPACE="$1"

    kubectl get namespace "$NAMESPACE" -o json \
        | tr -d "\n" \
        | sed "s/\"finalizers\": \[[^]]\+\]/\"finalizers\": []/" \
        | kubectl replace --raw /api/v1/namespaces/$NAMESPACE/finalize -f -
}

main "$@"
