---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - CiliumLoadBalancerIPPool.yaml
  - CiliumL2AnnouncementPolicy.yaml
  # - GrafanaDashboard.cilium.yaml
  # - GrafanaDashboard.cilium-operator.yaml

patches:
  - target:
      kind: Namespace
      name: cilium-spire
    patch: |
      apiVersion: v1
      kind: Namespace
      metadata:
        name: cilium-spire
        labels:
          pod-security.kubernetes.io/enforce: privileged
          pod-security.kubernetes.io/enforce-version: latest
          pod-security.kubernetes.io/audit: privileged
          pod-security.kubernetes.io/audit-version: latest
          pod-security.kubernetes.io/warn: privileged
          pod-security.kubernetes.io/warn-version: latest

helmCharts:
  - name: cilium
    repo: oci://quay.io/cilium/charts
    version: 1.19.4  # renovate: datasource=github-releases depName=cilium/cilium
    releaseName: cilium
    namespace: kube-system
    includeCRDs: true
    valuesFile: values.yaml
