---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# helmCharts:
#   - name: cilium
#     repo: https://helm.cilium.io
#     version: 1.19.0
#     releaseName: cilium
#     namespace: kube-system
#     includeCRDs: true
#     valuesFile: values.yaml

resources:
  - Application.yaml
  - CiliumLoadBalancerIPPool.yaml
  - CiliumL2AnnouncementPolicy.yaml
  - GrafanaDashboard.cilium.yaml
  - GrafanaDashboard.cilium-operator.yaml
