# https://docs.cilium.io/en/latest/installation/k8s-install-helm/
# https://artifacthub.io/packages/helm/cilium/cilium?modal=values
---

cluster:
  name: talmox
  id: 1

kubeProxyReplacement: true

# Talos specific
k8sServiceHost: localhost
k8sServicePort: 7445
securityContext:
  capabilities:
    ciliumAgent: [CHOWN, KILL, NET_ADMIN, NET_RAW, IPC_LOCK, SYS_ADMIN, SYS_RESOURCE, DAC_OVERRIDE, FOWNER, SETGID, SETUID]
    cleanCiliumState: [NET_ADMIN, SYS_ADMIN, SYS_RESOURCE]
cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup

l2announcements:
  enabled: true

ipam:
  mode: kubernetes

operator:
  rollOutPods: true
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi

gatewayAPI:
  enabled: true
  enableAlpn: true
  enableAppProtocol: true
  gatewayClass:
    create: "true"
#   hostNetwork:
#     enabled: true

# -- Roll out cilium agent pods automatically when configmap is updated.
rollOutCiliumPods: true

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi

k8sClientRateLimit:
  qps: 20
  burst: 100

# https://docs.cilium.io/en/stable/operations/performance/tuning/#ebpf-host-routing
# bpf:
#   masquerade: true
#   lbModeAnnotation: true

loadBalancer:
  # https://cilium.io/blog/2022/04/12/cilium-standalone-L4LB-XDP/
  # https://cilium.io/blog/2021/05/20/cilium-110/#standalonelb
  standalone: true
  # https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/#maglev-consistent-hashing
  algorithm: maglev
  mode: dsr
  # dsrDispatch: opt  # Use with native routing
  dsrDispatch: geneve  # Use with tunnelling
  l7:
    backend: envoy

# The default tunnel protocol "vxlan" is incompatible with loadBalancer.mode: "dsr"
routingMode: tunnel
tunnelProtocol: geneve

envoy:
  securityContext:
    capabilities:
      keepCapNetBindService: true
      envoy: [NET_ADMIN, PERFMON, BPF]

hubble:
  enabled: false
  # relay:
  #   enabled: true
  #   rollOutPods: true
  # ui:
  #   enabled: true
  #   rollOutPods: true

# -- Grafana dashboards for cilium-agent
dashboards:
  enabled: false
