# yaml-language-server: $schema=https://raw.githubusercontent.com/cilium/cilium/v1.19.1/install/kubernetes/cilium/values.schema.json
# https://artifacthub.io/packages/helm/cilium/cilium?modal=values
# https://github.com/cilium/cilium/tree/main/install/kubernetes/cilium
---
cluster:
  name: talmox
  id: 1

# Talos specific
kubeProxyReplacement: false
# k8sServiceHost: localhost  # When kubeProxyReplacement=true
# k8sServicePort: 7445  # When kubeProxyReplacement=true
ipam:
  mode: kubernetes  # https://docs.cilium.io/en/stable/network/concepts/ipam/
  multiPoolPreAllocation: ""
securityContext:
  capabilities:
    ciliumAgent: [CHOWN, KILL, NET_ADMIN, NET_RAW, IPC_LOCK, SYS_ADMIN, SYS_RESOURCE, DAC_OVERRIDE, FOWNER, SETGID, SETUID]
    cleanCiliumState: [NET_ADMIN, SYS_ADMIN, SYS_RESOURCE]
cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup

operator:
  rollOutPods: true
  prometheus:
    metricsService: true
    enabled: true
    port: 9963
    serviceMonitor:
      enabled: true
  dashboards:
    enabled: true
  resources:
    requests:
      # cpu: 50m
      memory: 256Mi
    limits:
      # cpu: 500m
      memory: 256Mi

# Roll out cilium agent pods automatically when ConfigMap is updated.
rollOutCiliumPods: true
resources:
  requests:
    # cpu: 200m
    memory: 512Mi
  limits:
    # cpu: 1000m
    memory: 512Mi

# debug:
#  enabled: true

# https://docs.cilium.io/en/latest/network/bgp-control-plane/bgp-control-plane-v2/
# bgpControlPlane:
#   enabled: true
#   secretsNamespace:
#     name: cilium-secrets

# https://docs.cilium.io/en/latest/network/l2-announcements/#ip-types
# Deprecated? https://github.com/cilium/cilium/commit/6f33115b861a30c8e21fc99d604afe899772488c
externalIPs:
  enabled: true

l2announcements:
  enabled: true

# https://docs.cilium.io/en/stable/operations/performance/tuning/#ebpf-host-routing
bpf:
  masquerade: true
  lbModeAnnotation: true
  # tproxy: true

# ipMasqAgent:
#   enabled: true

loadBalancer:
  # https://cilium.io/blog/2022/04/12/cilium-standalone-L4LB-XDP/
  # https://cilium.io/blog/2021/05/20/cilium-110/#standalonelb
  standalone: true
  # https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/#maglev-consistent-hashing
  algorithm: maglev
  mode: snat
  dsrDispatch: opt
  # acceleration: native
  # l7:
  #   backend: envoy

cni:
  exclusive: false
  resources:
    requests:
      # cpu: 100m
      memory: 64Mi
    limits:
      # cpu: 100m
      memory: 64Mi

# https://docs.cilium.io/en/stable/network/concepts/routing/
routingMode: native
ipv4NativeRoutingCIDR: 10.244.0.0/16
autoDirectNodeRoutes: true

gatewayAPI:
  enabled: false
  # enableAlpn: true
  # enableAppProtocol: true
  # gatewayClass:
  #   create: "true"

envoy:
  enabled: false
  prometheus:
    enabled: true
    port: "9964"
    serviceMonitor:
      enabled: true
  securityContext:
    capabilities:
      keepCapNetBindService: true
      envoy: [NET_ADMIN, PERFMON, BPF]
  resources:
    requests:
      # cpu: 100m
      memory: 256Mi
    limits:
      # cpu: 500m
      memory: 256Mi

hubble:
  enabled: true
  metrics:
    enabled:
      - dns
      - drop
      - tcp
      - flow
      - port-distribution
      - icmp
      - "httpV2:exemplars=true;labelsContext=source_ip,source_namespace,source_workload,destination_ip,destination_namespace,destination_workload,traffic_direction;sourceContext=workload-name|reserved-identity;destinationContext=workload-name|reserved-identity"
    enableOpenMetrics: true
    port: 9965
    serviceMonitor:
      enabled: true
    dashboards:
      enabled: true
  relay:
    enabled: true
    rollOutPods: true
    resources:
      requests:
        # cpu: 50m
        memory: 256Mi
      limits:
        # cpu: 500m
        memory: 256Mi
    prometheus:
      enabled: true
      port: 9966
      serviceMonitor:
        enabled: true
  ui:
    enabled: true
    rollOutPods: true
    backend:
      resources:
        requests:
          # cpu: 50m
          memory: 256Mi
        limits:
          # cpu: 500m
          memory: 256Mi
    frontend:
      resources:
        requests:
          # cpu: 50m
          memory: 256Mi
        limits:
          # cpu: 500m
          memory: 256Mi

ingressController:
  enabled: false

# clustermesh:
#   apiserver:
#     metrics:
#       enabled: true
#       port: 9962
#       serviceMonitor:
#         enabled: true
#     resources:
#       requests:
#         # cpu: 50m
#         memory: 256Mi
#       limits:
#         # cpu: 500m
#         memory: 256Mi
#     etcd:
#       resources:
#         requests:
#           # cpu: 50m
#           memory: 256Mi
#         limits:
#           # cpu: 500m
#           memory: 256Mi
#     kvstoremesh:
#       resources:
#         requests:
#           # cpu: 50m
#           memory: 256Mi
#         limits:
#           # cpu: 500m
#           memory: 256Mi

cgroup:
  autoMount:
    resources:
      requests:
        # cpu: 100m
        memory: 128Mi
      limits:
        # cpu: 100m
        memory: 128Mi

# mTLS
authentication:
  enabled: false
  mutual:
    spire:
      enabled: false
      install:
        server:
          dataStorage:
            storageClass: cilium-spire-sc
          resources:
            requests:
              # cpu: 50m
              memory: 256Mi
            limits:
              # cpu: 500m
              memory: 256Mi
        agent:
          resources:
            requests:
              # cpu: 50m
              memory: 256Mi
            limits:
              # cpu: 500m
              memory: 256Mi

prometheus:
  metricsService: true
  enabled: true
  port: 9962
  serviceMonitor:
    enabled: true
    trustCRDsExist: true

dashboards:
  enabled: true
