---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mariadb-secrets
  namespace: databases-backup
spec:
  encryptedData:
    MARIADB_DB_CSV: AgAjp7sfY0tSs8APqm+Uc2NRTDuosrKjd57CpXuSIbxyrhOzuLsdnQQULZUVLMNdwXIPXWc60GtyvcofqNGljS2ve137H04xcELeLVJZer/iPitD2jyhaJGpDL938erIjVY4ngcdbibvMnKhDx2rI0BU3G7y6imT9F/1IqgBGgPe+OybtLhmlNnBei2KJX7VSk8/4V+TywzeKvhH8BrRahU818Bmpl3cnwtsn0HI/VEaQhyZjbRwCNzrXoLZEcWyp4U+JeKd8dmqOEqggCfVgIKGNyXsG/MxjO4USDVEAzO7s0qK7rnkKnYpwDAYr1dgleS6Ds4rrE2uvzlCgLgg11VsGDO53EzOQ5TWhzJHxR9DR+CIstn4y8f+FnvnMQZPDScy7jzN/ftRYjJ6iElMCh8xAbQyWKDlU/r/CEzqTkDvRJLsyIMWp+JyTtJEleyT6s+gM9Rn6JEuZmMyj6vZOYtPY+Ec2VvsawghY9GJUiFZHejD/cKvGySQ4/v2BVKxLw1x8uTHCf9JmvfPwGeCebtXcDEbYCOSjJpxMW11YIRFGsbj8lOCI/zwq20M8BC9MxdP9GePUmbZFOOBp4/+91c60ivSoNdf5Zz+5gSkGKoaKzh+itSuebbEko0UvcQUkjAIZJwKrqe5/lSF/gV89dzxzuppjkyX/TRw3pq94sJOPvJ77+qDftB2J0QUv86UrumqGyt6zmjY2XIgRP+OaeEhFhMLxeQOVD7PkAGzaNoFNICoNBWetSV9dj0RLY0xNx1l29rxI5SlS+3NXcfGpff2Ha0lYDGcisYUiJxdNsnQebwMJ2GbYkH+FnWZHoIlLlqF67rskb6Z6B/JtUrslxQn/6rfSkJTS1pF/hQ17TnXZaXlFQvf8naTm878mHBwHemUR9k5aYclialpZAkMHOIE/wekiDqdsSsV4uphYBx/0GYUo0ZCkDsD9udaNaDzp31jOT78iuSz5vPOYNms4DYrReyBuB8VRpm6r7eox8wZd9Y842+McPRcYK0xbYaCpzYxIhGjph6aGPqxdjeUsuBfOKraNOlTwisNEFLdVIT/i8X1da4leu3+ag9Cmkp33gqK1Y+xCwqRvTDa0/B96B0Tn0yJop0L6vWjOfQU5adf5CHvpp3zlyYn4zBhXdp/cO6Q8aNGyHs5H4578rLSubaKLJaDWZPGKj003lhIy6Eb+Lwe9D01MDe3hhmNg8bXzsnP+I2nxjO8BeYeSSosRXQJVftUHGKDVDDQ1kyhuwrECRHywgM9zBl127Q9
  template:
    metadata:
      annotations:
        kustomize.config.k8s.io/behavior: replace
      name: mariadb-secrets
      namespace: databases-backup
