---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: velero

resources:
  - Namespace.yaml
  - SealedSecret.hetzner-s3.yaml
  - CiliumNetworkPolicy.yaml

helmCharts:
  - name: velero
    repo: https://vmware-tanzu.github.io/helm-charts
    version: 12.0.2  # renovate: datasource=helm registryUrl=https://vmware-tanzu.github.io/helm-charts depName=velero
    releaseName: velero
    namespace: velero
    includeCRDs: true
    valuesFile: values.yaml
