---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oidc
  namespace: carat
spec:
  encryptedData:
    client-secret: AgAs8JDQOK8h7aGp2Cq0GcUSbiGi2TqNDDOwV6cAfxQACcpus7VtWk0Ax5xxCz9OFYInDyBbeomjt4bE8t9bFrwhHzLWjfHiBWpmeHCD/De4hfdMyH4kN1iRNqr/ff6uiCR4Z1jC7iHQapzCwbY9vJjVb1ziPkF3lAui8hw6Wt71UnUdUQn4PyDLtFnaDwNdF6b7zrqQTpzZgwMZkBbrl5sSJvrjU2FQHAnZ2Y9/ljNHi5spPN/WP1Kyzk6i07UHzjI1gxCPANmX8whgUU09iA+S7ARX+WXaZ1NkGDr1elya5C3dkvQ/u5RxY7F2lN6OWJ31IvdkWRPQzJ+tWnZ6WbfYT5s42lqOIbAq9M9IxLs2DZUpbtcMzWF/u/QSwhLhQHG5Za0GHXp6khVr+9JHdY0aprlvb7sBHcrSS0Q2EznpTFQfSoD40zCLZNAQlvPyWwlrQxRzmTevckmc1CM2ryerCsLc8OQyc9qFgxVu2mQq63gCou7Ffza68Q/oxll/ud7bKkCPiZfaU2F25uFJrKQDoqfrQHp4QQvQ8xdxf2qJ3lb8FLd59bbABhFJOrw0pgJGz3P4GocLTirfiiotOpbK7lo8T6EjhEYV0jrQVVNPPN0lSluyoUHnHMq30cUqi7NRMhtxVInQlU73zYpvA2gBk51Njiosf7jJqPJgLYYXw03jIAhI6R/DcRI49xWNI/l1BnM9a0PD42PFx97T+QtO4sESHzWZu9q22Gkd+XVCi2ybgT0yQ5E0bFJU7LPJ+VdHOB0P3v42/URQoTaIwnIAg14Zwoh534s=
  template:
    metadata:
      annotations:
        kustomize.config.k8s.io/behavior: replace
      name: oidc
      namespace: carat
    type: Opaque
