---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: auth
  namespace: argocd
spec:
  sourceRepos: [https://github.com/sebastka/homelab.git]
  destinations:
    - {namespace: argocd, server: 'https://kubernetes.default.svc'}
    - {namespace: light-ldap, server: 'https://kubernetes.default.svc'}
    - {namespace: authelia, server: 'https://kubernetes.default.svc'}
  clusterResourceWhitelist:
    - {group: '', kind: Namespace}
    - {group: rbac.authorization.k8s.io, kind: ClusterRole}  # Needed by users
    - {group: rbac.authorization.k8s.io, kind: ClusterRoleBinding}  # Needed by users
