---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: auth
  namespace: argocd
spec:
  sourceRepos: [https://github.com/sebastka/homelab.git]
  destinations:
    - {namespace: fallback,   name: talmox}
    - {namespace: argocd,     name: talmox}
    - {namespace: light-ldap, name: talmox}
    - {namespace: authelia,   name: talmox}
  clusterResourceWhitelist:
    - {group: '', kind: Namespace}
    - {group: rbac.authorization.k8s.io, kind: ClusterRole}         # Needed by users
    - {group: rbac.authorization.k8s.io, kind: ClusterRoleBinding}  # Needed by users
