# https://gateway.envoyproxy.io/docs/troubleshooting/admin-console/#accessing-the-admin-console
# Admin Console:
# - egctl x dashboard eg
# - kubectl port-forward -n envoy-gateway-system deployment/envoy-gateway 19000:19000
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: envoy-gateway-system

components:
  - ../../../../common/valkey

patches:
  # Fix missing namespace in resources created by the helm chart
  - target: {kind: (DaemonSet|Deployment|Service|ConfigMap|Secret|ServiceAccount|Job|HTTPRoute|ReferenceGrant), name: envoy-proxy-bouncer.*}
    patch: |
      - {op: add, path: /metadata/namespace, value: envoy-gateway-system}

resources:
  - Namespace.yaml
  - EnvoyProxy.yaml
  - GatewayClass.yaml
  - SealedSecret.crowdsec-secrets.yaml
  - GrafanaDashboard.crowdsec.yaml

helmCharts:
  - name: gateway-helm
    repo: oci://docker.io/envoyproxy
    version: 1.8.0  # renovate: datasource=helm registryUrl=oci://docker.io/envoyproxy depName=gateway-helm
    releaseName: envoy-gateway
    namespace: envoy-gateway-system
    includeCRDs: true
    valuesFile: values.yaml

  - name: envoy-proxy-bouncer
    repo: oci://ghcr.io/kdwils/charts
    version: 0.6.1  # renovate: datasource=helm registryUrl=oci://ghcr.io/kdwils/charts depName=envoy-proxy-bouncer
    releaseName: envoy-proxy-bouncer-karlsenfr
    namespace: envoy-gateway-system
    includeCRDs: true
    valuesFile: values.crowdsec-envoy-bouncer-karlsenfr.yaml

  - name: envoy-proxy-bouncer
    repo: oci://ghcr.io/kdwils/charts
    version: 0.6.1  # renovate: datasource=helm registryUrl=oci://ghcr.io/kdwils/charts depName=envoy-proxy-bouncer
    releaseName: envoy-proxy-bouncer-karlsenapp
    namespace: envoy-gateway-system
    includeCRDs: true
    valuesFile: values.crowdsec-envoy-bouncer-karlsenapp.yaml
