# yaml-language-server: $schema=
# https://artifacthub.io/packages/helm/metrics-server/metrics-server?modal=values
---

args:
  - --kubelet-insecure-tls

resources:
  requests: {memory: 128Mi}
  limits: {memory: 128Mi, cpu: 1}
