---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: element-admin

resources:
  - Namespace.yaml
  - ServiceAccounts.yaml
  - Deployment.yaml
  - Services.yaml
  - HTTPRoute.yaml
  - CiliumNetworkPolicy.yaml
