#ENC[AES256_GCM,data:HSYHMop9iKgidAoboNgKhLm1F0Bth+WrYSsYpb0FtEkiEYYdzWi2DwM5UUX+h6npz2NBtG56sNVCTq9W4g7sNFFC0gw2JDK/UVgmnakCO+2jiZD6tQbWfCjBFutl5DqOMQz2mTTtMPvrvV+g48DR6DjcKfKUsottiCjwNzIOl0wvo3j8Tb7uuVDlx7x4CPN6ztz+n/0=,iv:qQ0T1l4gu4g76fRIB/l0xo9tJOhhRDXUe6B7jmLgZCs=,tag:b0AevQ+q6ZGRfrpcH2zVkw==,type:comment]
#ENC[AES256_GCM,data:i2naKNQ3cvyLUbuq66DMgiuzHAsu0rxqK02G7vybnAbSRpV5dVw0M1pcbGacOhfzKQH7Tv5J9iP6j8mBrLkGpu6m0Y6UE4kzf8pxttU=,iv:9hybrhmm6sEJfj7HiTEUIOqTglYheuExZEMQMycjQqw=,tag:n+r8DMPZSB6LU4fXrV7xyw==,type:comment]
#ENC[AES256_GCM,data:igrgnD8+Tej3jZ9j+/Rr0Xyv11VuOfq8Tm+rOmnx6VdZZD0Ofhf89qs++0zzBbNisiLe4L310H/pFnRoLIf/3pjgwhZdJH4sz+S0UKI=,iv:HNQaKZswWf71jdhUgaDMaDmw0Xp42FKjP/m8UUT2AjU=,tag:rLw2oA4XI3fqf9dhLSvJAQ==,type:comment]
apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
    annotations:
        kustomize.config.k8s.io/behavior: replace
data:
    clientId: ENC[AES256_GCM,data:EK7IhgiYOchAn9s7e6swV82jjOFOUblO,iv:ocoEb0PF+nCJGolzKlPLDZ6ZKF81IrHZd+6sDR0ingo=,tag:cw7xAvQA82aDGy2PYoB9Tg==,type:str]
    clientSecret: ENC[AES256_GCM,data:bO8hGgNb+ZGKqhYfhkHgzddBAcqmnP2ykx9cbGqFSvn5DOlSTJWziSxPtI1swVCGcPM7jNOlDNoNikd+EDYSuas2Qw4kmZeZk+fdNZi3SCFkNXlM6xrfbg==,iv:YwWLN7x7ai36q5Wjo6RWZVgKfFSTfM9c1hpo0zj8gKE=,tag:DLxi6iyFB9vpHhyxKeaN0A==,type:str]
sops:
    age:
        - recipient: age1gxk3ylhwfwe0nkhfu8pr08j5axz5y6qm50ntp0ncu0l6cx20fdrqw36n8a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZRGJ2ejRGL2ZIMEV4NWRp
            T0drRlZWcEVRVFh2WWZtL3lEYmo4alkvRkNnCmRnd0E4UG1YRnFSYlNGT1lITGVZ
            L3BMaEM2YVRWVTg2d1MzY0Qzclp0RzgKLS0tIHcrMkl4SXU1SzRkWkNmMTdSSkFE
            dFR1dFk2eDdhV2x1N2ZHWG9JLzVjNFUKqvpGOoyPq7rpRxL/JDUjM3zJeWh1amQg
            PXWktSMLrtHQFRP6iXfZWQAIoAhL/NFEwQHttJBXu4hHvbHSKxovCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-02T12:31:14Z"
    mac: ENC[AES256_GCM,data:9XFTJHl5VUHCkLr4MN075sAnTghyIRaypUyh9iTENR7Vouni/E4SzbXBJo2acA1VBNy5cPUe6WDq41/bqRY2oWwk1BzQBfxdxLL3NQd4l5F464qAp21LV7ru6T9v7fR+Y/MYoSnRBSOogF6Z3AcenSIybtC/c4vqqfvj4C5KTuA=,iv:91SOmrq/PsqLb2TREKurjbD/FO8DENymGeuZZPTheT0=,tag:MXLwikCA8WqRQuzdOn+e2Q==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
