#ENC[AES256_GCM,data:D1OYFoOdqu3+Qui6mbnF4GVT5dvHRmqQMQ==,iv:Iy1TdvFhmp+N4zfaxernj8EuYlpIjx/g0w75hW4Iw+8=,tag:+0A56Kz/THd39/D3pVCSWQ==,type:comment]
#ENC[AES256_GCM,data:D/58cf7t/KaIKN4D+PMUd4+ggWGERAtxXe6Lo3Th6MnFFxDQLg==,iv:Ys4wgTvMtAfyYuiKjuSJzp01HjtMfzWhUmus/WOwdcs=,tag:S15HDIqcCiXQOgt/+koCcw==,type:comment]
apiVersion: v1
kind: Secret
metadata:
    name: tailscale-auth
    namespace: tailscale
stringData:
    TS_AUTHKEY: ENC[AES256_GCM,data:d2CVjw+MoTx3U22rmBPz7+egywYCX3ZTJW7M9UymcKhyYlzGQ9Ds4P1f1g0gJVIWIcY1sgb2Jr/Q1qL0ig0=,iv:F+VGqojtROzgZkTOAPyQYlqmbMhiphn3t9ZANriwrlA=,tag:aJfz7/nqr0u2Ccud264bHg==,type:str]
sops:
    age:
        - recipient: age1gxk3ylhwfwe0nkhfu8pr08j5axz5y6qm50ntp0ncu0l6cx20fdrqw36n8a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3cHI2NWlXZkVyYk12eDk2
            aXlLUHgxQVk0RzI4dnRPVXdQUzZ0ZEVUUUZBCnJFNGdnelZ1RDlSenF3eHBQSEs2
            ZHliMmsrKzJ4Q2dSaThhWk9rVkJvOEkKLS0tIHhPVm9jQ2dvL2s1SVNZUTZlN0hG
            QzFBN1dRMmNNWU5rakROMnBaY1RsbXcKzfKIG1R3Qi1jWrbKdSATd2YBtBCJcqCy
            m1MiWioQf/cega0YhUxlbYAGg5rwxtiMg99BM2sVXhb17BIQIaNvOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T19:34:41Z"
    mac: ENC[AES256_GCM,data:/2V0s+qAH1zPx96XcGMdIrExXjfPW8for8syblXMXYgdCFAv+khkfF3F0v8U0l48PkX3O6hqCEFlEhvMZ+DTFTzJP/ZlzBgBETAHh6Y7ivT4iFSP94SFfPrv2exXcbkeUc7L6S+R3CB8gAmtV3bU5syY4pfl+C3QSyBWF7DPtcI=,iv:Odcds4uUwe3PzDdpP/KNzKumwNyWTqMJ08NFDplFh2k=,tag:T2q3XqYtfztO5br6Afdmew==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
