---
# Copyright (c) Tailscale Inc & AUTHORS
# SPDX-License-Identifier: BSD-3-Clause
apiVersion: v1
kind: Pod
metadata:
  name: subnet-router
  namespace: tailscale
spec:
  serviceAccountName: "tailscale"
  containers:
    - name: tailscale
      imagePullPolicy: Always
      image: "ghcr.io/tailscale/tailscale:latest"
      env:
        # Store the state in a k8s secret
        - name: TS_KUBE_SECRET
          value: "tailscale-auth"
        - name: TS_USERSPACE
          value: "false"
        - name: TS_DEBUG_FIREWALL_MODE
          value: auto
        - name: TS_AUTHKEY
          valueFrom:
            secretKeyRef:
              name: tailscale-auth
              key: TS_AUTHKEY
              optional: true
        - name: TS_ROUTES
          value: "10.244.0.0/16,10.96.0.0/12,192.168.2.0/24,192.168.3.0/24,192.168.4.0/24,192.168.5.0/24,192.168.6.0/24"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
      securityContext:
        privileged: true
