# https://artifacthub.io/packages/helm/tailscale/tailscale-operator?modal=values
# https://tailscale.com/kb/1236/kubernetes-operator/?q=operator#setting-up-the-kubernetes-operator
---

oauth:
  clientId: kQFW8AHqyG11CNTRL
  clientSecret: tskey-client-kQFW8AHqyG11CNTRL-EcgXkzm34raMp4JxnL1yqayWe8Hiccw11

ingressClass:
  enabled: false
