# yaml-language-server: $schema=https://raw.githubusercontent.com/siderolabs/talos/refs/heads/release-1.12/website/content/v1.12/schemas/config.schema.json
# Disable userspace OOM killer
# https://github.com/siderolabs/talos/issues/12526#issuecomment-3707193227
---
apiVersion: v1alpha1
kind: OOMConfig
triggerExpression: "false"
cgroupRankingExpression: "0.0"
sampleInterval: "5s"
