---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources:
  - ../../base
  - VMStaticScrape.etcd.yaml

helmCharts:
  - name: victoria-metrics-k8s-stack
    repo: oci://ghcr.io/victoriametrics/helm-charts
    version: 0.91.2
    releaseName: victoria-metrics-k8s-stack
    namespace: monitoring
    includeCRDs: false
    valuesFile: ../../base/values.yaml
