---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mariadb-backup
  namespace: databases-backup
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-backup
  namespace: databases-backup
automountServiceAccountToken: false
