---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# labels:
#   - includeSelectors: true
#     includeTemplates: true
#     pairs:
#       app.kubernetes.io/name: kube-prometheus-stack
#       app: kube-prometheus-stack

resources:
  - Namespace.yaml
  - HTTPRoute.prometheus.yaml
  - HTTPRoute.alertmanager.yaml

helmCharts:
  - name: kube-prometheus-stack
    repo: oci://ghcr.io/prometheus-community/charts
    version: 82.4.3 # renovate: github-releases=prometheus-community/helm-charts
    releaseName: kube-prometheus-stack
    namespace: kube-prometheus-stack
    includeCRDs: true
    valuesFile: values.yaml
