---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

components:
  - ../../../common/images

patches:
  - target: {group: monitoring.coreos.com, version: v1, kind: Prometheus, name: kube-prometheus-stack-prometheus}
    patch: |-
      - {op: add, path: /spec/externalLabels, value: {cluster: talmox}}

resources:
  - Namespace.yaml
  - HTTPRoute.yaml
  - CiliumNetworkPolicy.yaml
  - PrometheusRule.etcd.yaml
  - PrometheusRule.oom.yaml

helmCharts:
  - name: kube-prometheus-stack
    repo: oci://ghcr.io/prometheus-community/charts
    version: 86.3.2  # renovate: datasource=helm registryUrl=oci://ghcr.io/prometheus-community/charts depName=kube-prometheus-stack
    releaseName: kube-prometheus-stack
    namespace: monitoring
    includeCRDs: false
    valuesFile: values.yaml
