# Make sure this matches the volumeClaimTemplate in values.yaml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data-pvc
  namespace: kube-prometheus-stack
  labels:
    app.kubernetes.io/name: kube-prometheus-stack
    recurring-job.longhorn.io/source: enabled
    recurring-job-group.longhorn.io/group1: enabled
spec:
  accessModes: [ReadWriteOncePod]
  resources: {requests: {storage: 20Gi}}
  storageClassName: longhorn-encrypted
  volumeName: prometheus-data-pv
