---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-ntfy
  namespace: monitoring
spec:
  encryptedData:
    token: AgAsnHZ5i5S1P8ZKiO1TuAMij6pfHv5WlWe2KxIVb/ddaSDsQ9iQy7UZPY3jwKTLOjd3aw5Hj47jiIlAG0ySBjTyNXDwa4DKPmajX2+NG3KGUKGC0PGAPqzeiK7itCh1NwT9rhEBvGlE3SD9HVXdIAHiNwu2adTAUcbhnJEFsdUA34MyWFbRA+2BmEN5XH+qsoUyeNjvRjnpgNp4cySYlGp+LzOcQhGETa6tHWDtttyUJ9ug9InyHwm+fno5Ys9d/dVGY4TFzrBIgaPYvYYB8/xoLi43uw5RWeWBwrNb6oPYl0l8smtAoWFzolg6D+t6/acaCSYD7iJBHqR6ehH8C7E7gtSQgorngzaGJffbwUpl0VuK9IcMHPAui2q6Vskb1vzfAxOvlTpUkwZnTDa42GrSLdh+60s2M8exJiY8fmJTTo79KCPUb68yYHu+wNeN7R0R7uKUWHlHJL+eU0coM6DHeYkHDwpBJF8ZxnOwRWJViLsuSZIV90haNwwYswXJSz8/jCjwdngxB+Jxqayxjsta28uUKrgu7Dq7tSTSYns17BS06vVmmw4zKa8v2YidDwEzpgOy4B0hYGcjltqP2OhjOrB2jQ2WCbXqXSzmGTRyycOiKO2L/3nGtX30Ljy5iZz6KIA3pNM86x4znQ0/qkAYua1SF4ljRyfdMRQdnRDD3nQMkxHcFSK1f3d/A7hU+5QI7rJ67zCs09Oum9bmNAoynNA0Kgc1+XhbKRwKBoBiRA==
    url: AgCYd1OMbPm8ikPPap5qKMeSnx2JOoJLUUGsieyRA8YBrOiTDGj1mfsCS5YpL3wxdu6/5ORdneB7T9YZIpfxOZz/5h4a7MqD0iswNWwnaM+IxH26RoyjgJTgG0n4exGP0H8vQsCEMTrLWWUTnrq1CEmMR/DdBZMSEWOskfj+yl5yd5tB+PBwz8b2QG0zbLV/A03udhvok8QFtRZZP1GOCpZ4l4zM7qxOsZRG+vOyYKYenmVqI8nsNP02zfm485fzALTCzIylXb7Qt0pmfdawN/ixKZdu3eRQhydoEqBMy3ji27PqycS6zw9UmCEHoXcl7k7MllOOW+m/nOLSIvqznMTl53rzb5Zx4TucshipKM75U8pRgSaJgBWx7FcmxP8hU2YXXIG9LTyVE7oOeh8D/ZhC+Svi8zSS+SsTpH6ffG/yprJVRwSUfP1I06QtkEETNewTY1z6/UoOHsVLKv1UtwnBFDvs3fOEu3bjr9yg87k2ZXUrHOeL65VlDQ0LB8IJXoMlEg/46eRdD6VnfOZTXdYqVW9FoJXeq8PyWGRSpYcO2IiqZWivvf+JRvS2Hdf/sg7QF5RK5A3VPYw8l99M2VseokHZ2lNOCqm0rqY9LEFTJ5KSWzWdyjlVGua0+ssHfA4szmmx60J+lILHyW5ysS7xgJ1Ccgx7IR8vH3i6942C1mKxQCHtMF5RKDhPCQKTnrMJ96u1UMtrgpNYGEH9epW2N0GoB1EvFAOTCdtIU/6V5oNg98tPhR05RvPwa0ehI7K4A4YZ7SG9S+Ced6p7jq3CrKX/7UnC
  template:
    metadata:
      annotations:
        kustomize.config.k8s.io/behavior: replace
      name: alertmanager-ntfy
      namespace: monitoring
