# yaml-language-server: $schema=
# https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack?modal=values
# https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
---

crds:
  resources:
    requests: {memory: 512Mi}
    limits: {memory: 512Mi}

prometheus:
  prometheusSpec:
    podMonitorNamespaceSelector: {}
    podMonitorSelectorNilUsesHelmValues: false
    podMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    resources:
      requests: {memory: 2048Mi}
      limits: {memory: 2048Mi}
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn-encrypted
          volumeName: prometheus-data-pv
          accessModes: [ReadWriteMany]
          resources: {requests: {storage: 20Gi}}

prometheusOperator:
  resources:
    requests: {memory: 64Mi}
    limits: {memory: 64Mi}
  admissionWebhooks:
    deployment:
      resources:
        requests: {memory: 64Mi}
        limits: {memory: 64Mi}
    patch:
      resources:
        requests: {memory: 64Mi}
        limits: {memory: 64Mi}
  prometheusConfigReloader:
    resources:
      requests: {memory: 64Mi}
      limits: {memory: 64Mi}

# https://github.com/siderolabs/talos/discussions/7214
kubeControllerManager:
  enabled: true
  serviceMonitor:
    relabelings:
      - sourceLabels: [__meta_kubernetes_pod_node_name]
        separator: ;
        regex: ^(.*)$
        targetLabel: nodename
        replacement: $1
        action: replace
    metricRelabelings:
      - action: labeldrop
        regex: pod

kubeEtcd:
  enabled: true
  service:
    selector:
      # etcd doesn't run as a container,
      # but most probably runs on the same nodes that host a controller
      k8s-app: kube-controller-manager
  serviceMonitor:
    relabelings:
      - sourceLabels: [__meta_kubernetes_pod_node_name]
        separator: ;
        regex: ^(.*)$
        targetLabel: nodename
        replacement: $1
        action: replace
    metricRelabelings:
      - action: labeldrop
        regex: pod

kubeProxy:
  # Cilium replaces Kube Proxy
  enabled: false

kubeScheduler:
  enabled: true
  serviceMonitor:
    relabelings:
      - sourceLabels: [__meta_kubernetes_pod_node_name]
        separator: ;
        regex: ^(.*)$
        targetLabel: nodename
        replacement: $1
        action: replace
    metricRelabelings:
      - action: labeldrop
        regex: pod

nodeExporter:
  enabled: true

grafana:
  enabled: false
  forceDeployDatasources: false
  forceDeployDashboards: true
  defaultDashboardsEnabled: true
  defaultDashboardsTimezone: Europe/Oslo
  operator:
    dashboardsConfigMapRefEnabled: true
    matchLabels:
      app: grafana
    folder: Kubernetes

alertmanager:
  alertmanagerSpec:
    resources:
      requests: {memory: 64Mi}
      limits: {memory: 64Mi}

thanosRuler:
  thanosRulerSpec:
    resources:
      requests: {memory: 64Mi}
      limits: {memory: 64Mi}
