---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: monitoring
  namespace: argocd
spec:
  sourceRepos:
    - https://github.com/sebastka/homelab.git
  destinations:
    - namespace: argocd
      server: '*'
    - namespace: metrics-servrer
      server: '*'
    - namespace: portainer
      server: '*'
    - namespace: headlamp
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
