---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metube-persistent-pvc
  namespace: metube
  labels:
    recurring-job-group.longhorn.io/group1: enabled
spec:
  accessModes: [ReadWriteOncePod]
  resources: {requests: {storage: 10Gi}}
  storageClassName: longhorn-encrypted
  volumeMode: Filesystem
  volumeName: metube-persistent-pv
