---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oidc
  namespace: metube
spec:
  encryptedData:
    client-id: AgA4Wfryql08UB0SSfmgpQbEsiouLCo3RyUwt5bZO+fAicKQu6TH6ezT3Ki1tGBUdHxpBsM52dtQB4a4MQ4ZE9rlQYT3hhsd95j7rXtHeJ1tMzCwBOU1T7K0J2rWz+WmFDQp8P61xL7kJv3feMKnr653KGkxSZc5iN5hLPNFioDxzWaK/pdZ742xrfP5kfp5984VK9t/gv/DkyDup8wd75Cb2mf/iXoY9K6EPvMemvMw06IBKKjC2x5LeNVp2ZNmKiKtTM42h/Ym1wC7/GkfPnm9h4th/QwdBdZI+8ystXk+jxSvY0N/pPy14WMXNX3ATlZmNgVUUw2rcujD8EXYbsiOM0LQsfhOfp/nREs2DOSsYb4YCBJofoHFGXRscQ4t5qoJJwHiAIOM4ROJhMoCUEbMx+dTFmeCzVGsBFX9nLVHg4uuA/H2t9R899hgtKA8SEz2jt+LylTwJRwlX1nY0bZ3s191OKu40W4uPAhn1ucoi64UqxxQXfGLTkgCAVP6eqXeB3VClD38Dvoo2pOich0EPCghjPG49OA58otoq5SO9COkFJ0s3c/NqyAN7gpesZnjSCE/TLFMxPMyD87moU2UHCJHsdITDjLaeI/NFWce8c/F83pAADxMKj+BEt+WaNaVtEy6hGcdeayr0VKKoIpTG6aTOkLy42BZPa2D9WWVAxYHkcs8n37YxSZDoMFLeuJ5dbOSbDJZIcmhej7XYruuhdU=
    client-secret: AgAYSZAwlYPTHjnJlSsshy5SfgNXSJaPlrH+hTtlz9YPa5oBTlT1Ye2948G8II5K5Ci62cIvwTWqydcGw5YlGcC5w4xuFgjZJuojbi4GdJ2WUiAcA/NryMuK1N/Tck9qtkvTl3vQFgQkmJsjtVYPU9znuA6hInbL6fDMMJ2EEP49it7mvI6a5H1tsuzjCSSXYVHCyBoGDelUkYmk13LXyZI1iNyPAzaY86s8PLuKSud5N/eSodOTsPB/zY9LE4T7HXGulDmsjZN0hmJG+s6DTE6U6Rep2+PhWWo/Zm1EknIXG/OeEgj+hU/20+WcEbmaSzkiH6Kj1h7ETcAQ+ymzDprAk7kP1XG+/ouFqAwd+rTUhCjGNt3OOtkgGSehyvLa/fLuLe4J8iRCCPzrFjACNO1KwuyHrGGI3+2RKnp0b+EcVvYfnfBPSAldyOxkwekaHPoAdBkHfKl3CXkIWQnytXPFdBKhBHo1xUE2tzvI/PegIxjYe4iXaDhT+/bA3l2qiB+ETiBP72T8qn0KrlVHcd/mh8paNI/GFMPVwsBBb3RRY5t062LXtLWaDGzZWTuL3FQx7+Fh7ifp0G1jTiQwQxQR17EDHC/SaM7Ro1M/6C54VA/pW3i34DQdurFjxZQKzm3TNTZfabpVIts2EyXyUWpwbbohNK0tF2EIVJSMNgCxWpSLblfj+o/gvRHOtdzCSM3bOqKjhCPomzgozkcnyFziqH4TVL6ha5NnK6RDOTeBor3kOZQTqWrWaUg9A6HhUA6ijrcTQylDI94Kx+IW6PiC
  template:
    metadata:
      annotations:
        kustomize.config.k8s.io/behavior: replace
      name: oidc
      namespace: metube
    type: Opaque
