---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oidc
  namespace: metube
spec:
  encryptedData:
    client-secret: AgAYvmXwDqZk+rZnkLFlx+dcPtFFae6g40Yvyv84V4JvWGuB/+cZJur+oB2H3VwcNxZiefZZbCxb5fi5357qAV98/gXo1S86RnFeu1VcJzibqkAJ8GB5sNZL2D19xxEjNWwGE8/TQRGMKslv8h0YeIpV67TXa7QE+sNX8n9Ej6fy83TC1S6eWAVi1AkFoeIIl0C3CYOWvUP1ajCJ7GQ/O3WY9uj8GvHs1gxkFAEipFFEXvz/ZeMwVoFICogxiCgqGe1wFATL78jfCfGSOBACreHa9jOjlxbjnVf2f6EkRE1BqtjIsZm24ZCdc2QZN8r7eU2u/PMuDi+if2DUngbyyCZfkWf3lvPl4pf/RI5J/AonVxbMmmDXVa+QIqg8IuAnit4Ye1yej6q1EMgDXF3HSB0BFwae0v3N4MnuLxApZ+iwdJeezMD/DORuIE0HAn9aj1ZkMrqadolxt/CEvrkxEeI0cUxgYMwHzIMtu3MKYYcgTsz/QRccupcdFT8+agKcuUl4I812OFKeVnaLiirpLCVX/RZXzafQCJoMK3u01gm+I3f3rKB3bzEsMMuwWasuhBqXc2G392pyLmHv0R2cfqd/3b5UTv7OPcNN6fw0MVOcts4FHrmcHl6Q77BQBAJ2+eVHrjH7NT7xT+83Rx6SnGOlf6BJuoVBcnLjRtgO3VjWsP/oLpuqt29ZtTVcB1WSpbyrpvFwH4GQmMNqaQFaXf4jbefgL67vPwUFChn2iyloxkEQQj7jAIMqlXLjZm3zmpOXU9vnsS5ma2hkXfHsf6u2rTc3UrnG7MI=
  template:
    metadata:
      annotations:
        kustomize.config.k8s.io/behavior: replace
      name: oidc
      namespace: metube
    type: Opaque
