---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metube
  namespace: metube
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bgutils-pot
  namespace: metube
automountServiceAccountToken: false
