---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: torrent
  namespace: torrent
  labels:
    app: torrent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: torrent
  strategy:
    type: Recreate
  template:
    metadata:
      namespace: torrent
      labels:
        app: torrent
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 2501
        runAsGroup: 2501
        fsGroup: 2501
        fsGroupChangePolicy: Always
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: torrent
          image: ghcr.io/home-operations/qbittorrent:5.1.4
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          ports:
            - name: http
              containerPort: 8080
            - name: torrent-tcp
              containerPort: 6881
              protocol: TCP
            # - name: torrent-udp
            #   containerPort: 6881
            #   protocol: UDP
          envFrom:
            - configMapRef:
                name: common-env
                optional: true
          resources:
            requests:
              cpu: 100m
              memory: 1.5Gi
            limits:
              cpu: 2000m
              memory: 8Gi
          volumeMounts:
            - name: torrent-config
              mountPath: /config
            - name: data
              mountPath: /app/data
      volumes:
        - name: torrent-config
          persistentVolumeClaim:
            claimName: longhorn-torrent-config-pvc
        - name: data
          emptyDir: {}
          # nfs:
          #   server: 192.168.1.117
          #   path: /mnt/pool-0/data
