---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-torrent-config-pvc
  namespace: torrent
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn-static
  volumeName: longhorn-torrent-config-pv
