---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: trivy

patches:
  - target: {kind: StatefulSet, name: trivy-server}
    patch: |
      - {op: add, path: /metadata/annotations/argocd.argoproj.io~1sync-options, value: Replace=true}

resources:
  - Namespace.yaml
  - CiliumNetworkPolicy.operator.yaml
  - CiliumNetworkPolicy.server.yaml
  - CiliumNetworkPolicy.scanjob.yaml

helmCharts:
  - name: trivy-operator
    repo: oci://ghcr.io/aquasecurity/helm-charts
    version: 0.32.1  # renovate: datasource=helm depName=trivy-operator registryUrl=oci://ghcr.io/aquasecurity/helm-charts
    releaseName: trivy-operator
    namespace: trivy
    includeCRDs: true
    valuesFile: values.yaml
