# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/refs/heads/master/pkg/config/schemas/talconfig.json
# https://budimanjojo.github.io/talhelper/latest/getting-started/
# https://budimanjojo.github.io/talhelper/latest/reference/configuration/
# https://github.com/budimanjojo/talhelper/blob/master/example/talconfig.yaml
# https://docs.siderolabs.com/talos/v1.12/reference/configuration/v1alpha1/config
---
clusterName: ${CLUSTER_NAME}
talosVersion: v${TALOS_VERSION}
kubernetesVersion: v${K8S_VERSION}
endpoint: https://${CONTROL_PLANE_IP}:6443
# domain: home.karlsen.fr
allowSchedulingOnMasters: true
allowSchedulingOnControlPlanes: true
# additionalApiServerCertSans:
clusterPodNets: [10.244.0.0/16]
clusterSvcNets: [10.96.0.0/12]
# cniConfig:  # Use patch instead
#   name: none

patches:
  - '@./patches/cilium.yaml'
  - '@./patches/longhorn.yaml'
  - '@./patches/metrics.yaml'
  - '@./patches/oidc.yaml'
  - '@./patches/resources.yaml'
  - '@./patches/tpm-disk-encryption.yaml'

inlineManifests:
  - name: sealed-secrets
    contents: |
      apiVersion: v1
      kind: Namespace
      metadata:
        name: sealed-secrets
      ---
      apiVersion: v1
      kind: Secret
      type: kubernetes.io/tls
      metadata:
        name: sealed-secrets-key
        namespace: sealed-secrets
        labels:
          sealedsecrets.bitnami.com/sealed-secrets-key: active
      data:
        tls.crt: ${SEALED_SECRETS_CRT}
        tls.key: ${SEALED_SECRETS_KEY}

nodes:
  - hostname: t01.${CLUSTER_DOMAIN}
    ipAddress: 192.168.1.201
    installDisk: &x-installDisk /dev/sda
    # installDiskSelector: &x-installDiskSelector 'size < 40 GiB'  # Make sure Talos is installed on the smaller OS disk and not on the extra data disk
    controlPlane: &x-controlPlane true
    ignoreHostname: &x-ignoreHostname true
    networkInterfaces: &x-networkInterfaces
      - interface: eth0
        dhcp: true
        vip:
          ip: ${TALOS_VIP}  # https://docs.siderolabs.com/talos/v1.12/networking/advanced/vip
    machineSpec: &x-machineSpec
      mode: nocloud
      arch: amd64
      secureboot: true
      useUKI: true
      bootMethod: disk-image
    nodeLabels:
      topology.kubernetes.io/region: &x-label-topology-region ${CLUSTER_NAME}
      topology.kubernetes.io/zone: t01
    schematic: &x-schematic
      customization:
        bootloader: sd-boot
        extraKernelArgs:
          - -lockdown
          - -lockdown=integrity
        systemExtensions:
          officialExtensions:
            - siderolabs/iscsi-tools
            - siderolabs/qemu-guest-agent
            - siderolabs/util-linux-tools
            # - siderolabs/xe
            # - siderolabs/i915
            # - siderolabs/cloudflared

  - hostname: t02.${CLUSTER_DOMAIN}
    ipAddress: 192.168.1.202
    installDisk: *x-installDisk
    # installDiskSelector: *x-installDiskSelector
    controlPlane: *x-controlPlane
    ignoreHostname: *x-ignoreHostname
    networkInterfaces: *x-networkInterfaces
    machineSpec: *x-machineSpec
    nodeLabels:
      topology.kubernetes.io/region: *x-label-topology-region
      topology.kubernetes.io/zone: t02
    schematic: *x-schematic

  - hostname: t03.${CLUSTER_DOMAIN}
    ipAddress: 192.168.1.203
    installDisk: *x-installDisk
    # installDiskSelector: *x-installDiskSelector
    controlPlane: *x-controlPlane
    ignoreHostname: *x-ignoreHostname
    networkInterfaces: *x-networkInterfaces
    machineSpec: *x-machineSpec
    nodeLabels:
      topology.kubernetes.io/region: *x-label-topology-region
      topology.kubernetes.io/zone: t03
    schematic:
      customization:
        bootloader: sd-boot
        extraKernelArgs:
          - -lockdown
          - -lockdown=integrity
        systemExtensions:
          officialExtensions:
            - siderolabs/iscsi-tools
            - siderolabs/qemu-guest-agent
            - siderolabs/util-linux-tools
            # - siderolabs/xe
            - siderolabs/i915
            # - siderolabs/cloudflared
