---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: element

configMapGenerator:
  - {name: element-config, files: [config.json=assets/config.json]}

components:
  - ../../../common/default-networkpolicy

resources:
  - Namespace.yaml
  - ServiceAccounts.yaml
  - Deployment.yaml
  - Services.yaml
  - HTTPRoute.yaml
  - SecurityPolicy.yaml
