---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: element

configMapGenerator:
  - {name: element-config, files: [config.json=assets/config.json, config.element.karlsen.app.json=assets/config.element.karlsen.app.json]}
  - {name: element-nginx, files: [real_ip.conf=assets/real_ip.conf]}

resources:
  - Namespace.yaml
  - ServiceAccounts.yaml
  - Deployment.yaml
  - Services.yaml
  - HTTPRoute.yaml
  - SecurityPolicy.yaml
  - CiliumNetworkPolicy.yaml
