---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  strategy: {type: Recreate}
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: jellyfin
  template:
    metadata:
      namespace: jellyfin
      labels:
        app.kubernetes.io/name: jellyfin
    spec:
      nodeSelector:
        topology.kubernetes.io/zone: t03
      serviceAccountName: jellyfin
      securityContext:
        runAsNonRoot: true
        runAsUser: 2501
        runAsGroup: 2501
        fsGroup: 2501
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: {type: RuntimeDefault}
        supplementalGroups: [44, 104]
      containers:
        - name: jellyfin
          # Dockerfile: https://hub.docker.com/r/jellyfin/jellyfin/dockerfile
          image: ghcr.io/jellyfin/jellyfin:10
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: {drop: [ALL]}
          resources:
            requests: {memory: 12Gi}  # gpu.intel.com/i915: 1000m  # "xe" supported?
            limits: {memory: 12Gi}  # gpu.intel.com/i915: 1000m  # "xe" supported?
          envFrom:
            - configMapRef: {name: jellyfin-env}
          ports:
            - {name: http, containerPort: 8096}
            # - {name: client-discovery, containerPort: 7359, protocol: UDP}
          volumeMounts:
            - {name: tmp-volume, mountPath: /tmp}
            - {name: cache-volume, mountPath: /cache}
            - {name: config-volume, mountPath: /config}
            - {name: media-volume, mountPath: /mnt/media, readOnly: true}
      volumes:
        - {name: tmp-volume, emptyDir: {medium: Memory}}
        - {name: cache-volume, emptyDir: {medium: Memory}}
        - {name: config-volume, persistentVolumeClaim: {claimName: jellyfin-config-pvc}}
        - {name: media-volume, persistentVolumeClaim: {claimName: jellyfin-media-pvc}}
