---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config-pvc
  namespace: jellyfin
  labels:
    app.kubernetes.io/name: jellyfin
    recurring-job.longhorn.io/source: enabled
    recurring-job-group.longhorn.io/group1: enabled
spec:
  accessModes: [ReadWriteOncePod]
  resources: {requests: {storage: 5Gi}}
  storageClassName: longhorn-encrypted
  volumeName: jellyfin-config-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media-pvc
  namespace: jellyfin
  labels:
    app.kubernetes.io/name: jellyfin
spec:
  accessModes: [ReadOnlyMany]
  resources: {requests: {storage: 1Gi}}
  storageClassName: nfs-static
  volumeName: jellyfin-media-pv
