---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin-service
  namespace: jellyfin
spec:
  type: ClusterIP
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: http

    # - name: client-discovery
    #   protocol: UDP
    #   port: 7359
    #   targetPort: client-discovery
