---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: storage
  namespace: argocd
spec:
  sourceRepos: [https://github.com/sebastka/homelab.git]
  destinations:
    - {namespace: fallback,         name: talmox}
    - {namespace: argocd,           name: talmox}
    - {namespace: kube-system,      name: talmox}
    - {namespace: longhorn-system,  name: talmox}
    - {namespace: velero,           name: talmox}
  clusterResourceWhitelist:
    - {group: '*', kind: '*'}
