---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: public
  namespace: argocd
spec:
  sourceRepos: [https://github.com/sebastka/homelab.git]
  destinations:
    - {namespace: argocd, server: 'https://kubernetes.default.svc'}
    - {namespace: homepage, server: 'https://kubernetes.default.svc'}
    - {namespace: slink, server: 'https://kubernetes.default.svc'}
    - {namespace: synapse, server: 'https://kubernetes.default.svc'}
  clusterResourceWhitelist:
    - {group: '', kind: Namespace}
