---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: controllers
  namespace: argocd
spec:
  sourceRepos: [https://github.com/sebastka/homelab.git]
  destinations:
    - {namespace: argocd, server: 'https://kubernetes.default.svc'}
    - {namespace: kube-system, server: 'https://kubernetes.default.svc'}
    - {namespace: cert-manager, server: 'https://kubernetes.default.svc'}
    - {namespace: falco, server: 'https://kubernetes.default.svc'}
    - {namespace: intel-device-plugins, server: 'https://kubernetes.default.svc'}
    - {namespace: kyverno, server: 'https://kubernetes.default.svc'}
    - {namespace: nfd, server: 'https://kubernetes.default.svc'}
    - {namespace: reloader, server: 'https://kubernetes.default.svc'}
    - {namespace: sealed-secrets, server: 'https://kubernetes.default.svc'}
    - {namespace: trivy, server: 'https://kubernetes.default.svc'}
  clusterResourceWhitelist:
    - {group: '*', kind: '*'}
