# https://hub.docker.com/_/mongo-express
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express-deployment
  namespace: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      namespace: mongo-express
      labels:
        app.kubernetes.io/name: mongo-express
        app: mongo-express
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
      # resources:
      #   requests:
      #     cpu: 10m
      #     memory: 12Mi
      #   limits:
      #     cpu: 100m
      #     memory: 24Mi
      containers:
        - name: mongo-express
          image: mongo-express:latest
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          # resources:
          #   requests:
          #     cpu: 10m
          #     memory: 12Mi
          #   limits:
          #     cpu: 100m
          #     memory: 24Mi
          env:
            # - name: ME_CONFIG_BASICAUTH_USERNAME     # | ''              | mongo-express web username
            # - name: ME_CONFIG_BASICAUTH_PASSWORD     # | ''              | mongo-express web password
            # - name: ME_CONFIG_MONGODB_ENABLE_ADMIN   # | 'true'          | Enable admin access to all databases. Send strings: `"true"` or `"false"`
            # - name: ME_CONFIG_MONGODB_ADMINUSERNAME  # | ''              | MongoDB admin username
            # - name: ME_CONFIG_MONGODB_ADMINPASSWORD  # | ''              | MongoDB admin password
            # - name: ME_CONFIG_MONGODB_PORT           # | 27017           | MongoDB port
            # - name: ME_CONFIG_MONGODB_SERVER         # | 'mongo'         | MongoDB container name. Use comma delimited list of host names for replica sets.
            - name: ME_CONFIG_MONGODB_URL
              value: mongodb://192.168.6.13:27017/
            # - name: ME_CONFIG_OPTIONS_EDITORTHEME    # | 'default'       | mongo-express editor color theme, [more here](http://codemirror.net/demo/theme.html)
            # - name: ME_CONFIG_REQUEST_SIZE           # | '100kb'         | Maximum payload size. CRUD operations above this size will fail in [body-parser](https://www.npmjs.com/package/body-parser).
            # - name: ME_CONFIG_SITE_BASEURL           # | '/'             | Set the baseUrl to ease mounting at a subdirectory. Remember to include a leading and trailing slash.
            # - name: ME_CONFIG_SITE_COOKIESECRET      # | 'cookiesecret'  | String used by [cookie-parser middleware](https://www.npmjs.com/package/cookie-parser) to sign cookies.
            # - name: ME_CONFIG_SITE_SESSIONSECRET     # | 'sessionsecret' | String used to sign the session ID cookie by [express-session middleware](https://www.npmjs.com/package/express-session).
            # - name: ME_CONFIG_SITE_SSL_ENABLED       # | 'false'         | Enable SSL.
            # - name: ME_CONFIG_SITE_SSL_CRT_PATH      # | ''              | SSL certificate file.
            # - name: ME_CONFIG_SITE_SSL_KEY_PATH      # | ''              | SSL key file.
          ports:
            - name: http
              containerPort: 8081
