---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: intel-device-plugins

patches:
  - target:
      group: admissionregistration.k8s.io
      version: v1
      kind: MutatingWebhookConfiguration
      name: inteldeviceplugins-mutating-webhook-configuration
    patch: |-
      - op: replace
        path: /webhooks
        value:
          - name: mgpudeviceplugin.kb.io
            admissionReviewVersions: ["v1"]
            clientConfig: {service: {namespace: intel-device-plugins, name: inteldeviceplugins-webhook-service, path: /mutate-deviceplugin-intel-com-v1-gpudeviceplugin, port: 443}}
            failurePolicy: Fail
            matchPolicy: Equivalent
            reinvocationPolicy: Never
            rules:
              - {apiGroups: [deviceplugin.intel.com], apiVersions: [v1], operations: [CREATE, UPDATE], resources: [gpudeviceplugins], scope: '*'}
            sideEffects: None
            timeoutSeconds: 10

resources:
  - Namespace.yaml
  - CiliumNetworkPolicy.operator.yaml
  - CiliumNetworkPolicy.gpu.yaml

helmCharts:
  - name: intel-device-plugins-operator
    repo: oci://ghcr.io/intel/helm-charts
    version: 0.35.0  # renovate: datasource=github-releases depName=intel/helm-charts
    namespace: intel-device-plugins
    releaseName: intel-device-plugins-operator
    includeCRDs: true
    valuesFile: values.operator.yaml

  - name: intel-device-plugins-gpu
    repo: oci://ghcr.io/intel/helm-charts
    version: 0.35.0  # renovate: datasource=github-releases depName=intel/helm-charts
    namespace: intel-device-plugins
    releaseName: intel-device-plugins-gpu
    includeCRDs: true
    valuesFile: values.gpu.yaml
