---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-dockur-windows-pvc
  namespace: dockur-windows
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 24Gi
  storageClassName: longhorn-static
  volumeName: longhorn-dockur-windows-pv
