server {
    listen 8080;
    server_name www.karlsen.fr;

    location ~ /(\.ht|\.git|wp) {
        deny  all;
    }

    location / {
        root   /karlsenfr;
        index  index.html;
    }

    error_page 500 502 503 504 /50x.html;
        location = /50x.html {
        root   /usr/share/nginx/html;
    }
}

server {
    listen 8080;
    server_name openpgpkey.karlsen.fr;

    location ~ /(\.ht|\.git|wp) {
        deny  all;
    }

    location / {
        root   /openpgpkey;
        index  index.html;
    }

    error_page 500 502 503 504 /50x.html;
        location = /50x.html {
        root   /usr/share/nginx/html;
    }
}

server {
    listen 8080;
    server_name mta-sts.karlsen.fr;

    location ~ /(\.ht|\.git|wp) {
        deny  all;
    }

    location / {
        root   /mta-sts;
        index  index.html;
    }

    error_page 500 502 503 504 /50x.html;
        location = /50x.html {
        root   /usr/share/nginx/html;
    }
}

server {
    listen 8080 default_server;
    server_name karlsen.fr
                karlsen.org www.karlsen.org
                karlsen.app www.karlsen.app
                _;

    location ~ /(\.ht|\.git|wp) {
        deny  all;
    }

    location / {
        root   /other;
        index  index.html;
    }

    error_page 500 502 503 504 /50x.html;
        location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
